package omsb.vehpc.equivalency.web.constants;

public class AppealConstants {
	public static final String CMD_ASSIGN_TO_ME = "assignToMe";
	public static final String CMD_COMPLETE_WORKFLOW = "completeWorkflow";
	public static final String PL_EQ_LEVEL = "PL_Equivalency_Level";
	public static final String PL_EQ_APPEAL_STATUS = "PL_Equivalency_Status";
	public static final String PL_EQ_APPEAL_STATUS_ITEM_EQUATED = "equated";
	public static final String PL_EQ_APPEAL_STATUS_ITEM_INSUFFICIENT = "insufficient";
	public static final String PL_EQ_APPEAL_STATUS_ITEM_COMPLETED = "completed";
	public static final String PL_EQ_APPEAL_STATUS_ITEM_RAISED = "raised";
	public static final String PL_EQ_APPEAL_STATUS_ITEM_INITIATED = "initiated";
	public static final String PL_EQ_APPEAL_STATUS_ITEM_REJECTED = "rejected";
	public static final String PL_EQ_APPEAL_STATUS_ITEM_CREATED = "created";
	public static final String PL_EQ_APPEAL_STATUS_ITEM_CREATED_EMPLOYER_DRAFT = "employerDraft";
	public static final String UTF_8 = "UTF-8";
	public static final String EMPLOYEE_VIEW = "/appeal/equivalency-decision-list-employee";
	public static final String EMPLOYEE_VIEW_JSP = "/jsps/appeal/equivalency-decision-list-employee.jsp";
	public static final String EMPLOYER_VIEW = "/appeal/equivalency-decision-list-employer";
	public static final String EMPLOYER_VIEW_JSP = "/jsps/appeal/equivalency-decision-list-employer.jsp";
	public static final String NEW_APPEAL_SAVE = "/appeal/new-appeal";
	public static final String NEW_APPEAL_SAVE_JSP = "/jsps/appeal/new-appeal.jsp";
	public static final String ADD_APPEAL_DECISIONS_JSP = "/jsps/appeal/edit-appeal/add-appeal-decisions.jsp";
	public static final String ADD_APPEAL_DECISIONS_RENDER = "/appeal/add-appeal-decisions-render";
	public static final String VIEW_APPEAL_ALL = "/view-appeal/view-appeal";
	public static final String VIEW_APPEAL_ALL_JSP = "/jsps/appeal/view-appeal/view-appeal.jsp";
	public static final String EDIT_APPEAL_COMMITTE_LIST = "/edit-appeal/equivalency-appeals-list-vehpc-committee";
	public static final String EDIT_APPEAL_COMMITTE_LIST_JSP = "/jsps/edit-appeal/equivalency-appeals-list-vehpc-committee.jsp";
	public static final String SEARCH_COMMITTE_LIST = "/edit-appeal/equivalency-appeals-list-vehpc-committee";
	public static final String APPEAL_ADMIN_LIST = "/appeal/equivalency-appeals-list-admin";
	public static final String APPEAL_ADMIN_LIST_JSP = "/jsps/appeal/equivalency-appeals-list-admin.jsp";
	public static final String APPEAL_PRESIDENT_LIST = "/appeal/equivalency-appeals-list-president";
	public static final String APPEAL_PRESIDENT_LIST_JSP = "/jsps/appeal/equivalency-appeals-list-president.jsp";
	public static final String VIEW_APPEAL = "/jsps/view-appeal/view-appeal.jsp";
	public static final String SAVE_APPEAL = "saveAppeal";
	public static final String ADD_APPEAL_DECISIONS_ACTION = "appeal/add-appeal-decisions-action";
	public static final String VIEW_APPEAL_EMPLOYEE_LIST = "/jsps/equivalency-decision-list-employee.jsp";
	public static final String FILTER_BY_FILE_NAME = "filter=dFFileName";
	public static final String EQUALS = " eq ";
	public static final String EQUIVALENCY_DECISION_LIST_EMPLOYEE = "/appeal/equivalency-decision-list-employee";
	public static final String EQUIVALENCY_DECISION_LIST_EMPLOYER = "/appeal/equivalency-decision-list-employer";
	public static final String EQUIVALENCY_APPEALS_LIST_ADMIN = "/appeal/equivalency-appeals-list-admin";
	public static final String EQUIVALENCY_APPEALS_LIST_COMMITTE = "/edit-appeal/equivalency-appeals-list-vehpc-committee";
	public static final String APPEAL_REQUEST_SAVE_URL = "/o/c/equivalencyappeals/scopes/";
	public static final String DOCUMENT_INFO_APPEAL_REQUEST_SAVE_URL = "/o/c/documentinfos/scopes/";
	public static final String URL_FOR_CERTIFICATE_VIEW = "/o/c/equivalencycertificates/scopes/";
	public static final String DECISION_CERTIFICATE_URL = "/o/c/documentinfos/";
	public static final String DOCUMENT_INFO_CERTIFICATE_URL = "/o/c/documentinfos/scopes/";
	public static final String GET_EQUIVALENCY_DECISION_URL_VIEW = "/o/c/equivalencydecisions/";
	public static final String DOCUMENT_INFO_URL_VIEW = "http://localhost:8080/o/c/documentinfos/scopes/";
	public static final String APPEAL_REQUEST_STATUS_URL_VIEW = "/o/c/equivalencyappealstatuses/";
	public static final String EQ_APPEAL_URL = "/o/c/equivalencyappeals/";
	public static final String CASE_REPORT_URL = "/o/c/casereports/";
	public static final String EQUIVALENCY_DECISION_URL = "/o/c/equivalencydecisions/";
	public static final String EQUIVALENCY_BY_ID_URL = "/o/c/equivalencyrequests/";
	public static final String EQUIVALENCY_CERTIFICATE = "/o/c/equivalencycertificates/";
	public static final String EQUIVALENCY_REQUESTS_URL = "/o/c/equivalencyrequests/scopes/{scope-id}";
	public static final String PERSON_DETAILS_URL = "/o/c/persons/scopes/{scope-id}";
	public static final String DOCUMENT_INFO_URL_SEARCH = "/o/c/documentinfos/scopes/{scope-id}";
	public static final String EQUIVALENCY_DECISION_URL_SEARCH = "/o/c/equivalencydecisions/scopes/{scope-id}";
	public static final String DECISION_URL = "/o/c/equivalencydecisionlevels/scopes/{scope-id}";
	public static final String EQUIVALENCY_APPEAL = "/o/c/equivalencyappeals/scopes/{scope-id}";
	public static final String OBJECT_ERC = "OB_EQUIVALENCY_APPEAL_ERC";
	public static final String VIEW_APPEAL_PERSON_LIST = "/appeal/appeal_admin_search";
	public static final String VIEW_APPEAL_EMPLOYER_LIST = "/jsps/appeal/equivalency-decision-list-employee.jsp";
	public static final String EMPLOYEE_EMPLOYER_LIST = "/appeal/equivalency-decision-list-employee";
	public static final String ADMIN_COMMITTE_PRESIDENT_LIST = "/appeal/equivalency-appeals-list-admin.jsp";
	public static final String VEHPC_APPEAL_FOLDER_NAME = "VEHPC Appeal Document";
	public static final String REQUEST_URL = "/o/c/equivalencyrequests/";
	public static final String DECISION_LEVEL_URL = "/o/c/equivalencydecisionlevels/";
	public static final String  VIEW_APPEAL_ADMIN_LIST = "/jsps/appeal/equivalency-appeals-list-admin.jsp";
	public static final String  PERSONAL_DETAIL_PK_URL = "/o/c/personaldetails/";
	public static final String PERSONAL_DETAILS_URL = "/o/c/personaldetails/scopes/{scope-id}";
	public static final String CMD_EMPLOYEE = "employee";
	public static final String CMD_EMPLOYER = "employer";
	public static final String NO_DATA = "No Data";
	public static final String EQUIVALENCY_CERT_TEMPLATE_KEY = "47613";
	public static final String PAGE_SIZE =  "&sort=id:desc&pageSize=0";
	public static final String PAGE_SIZE_WITH_QUESTION = "?sort=id:desc&pageSize=0";
	public static final String PAGE_SIZE_FOR_SCOPES = "?pageSize=0&sort=id%3Adesc";
	
	public static final String SAVE_COMMITTEE_COMMENTS = "/edit-appeal/save-committee-comments";	
	
	public static final String TRANSITION_NAME_EVALUATE = "evaluate";
	public static final String TRANSITION_NAME_INSUFFICIENT = "Insufficient";
	public static final String TRANSITION_NAME_COMPLETED = "complete";
	public static final String TRANSITION_NAME_RAISE = "Raise";
	public static final String TRANSITION_NAME_INITIATE = "Initiate";
	public static final String TRANSITION_NAME_REJECT = "Reject";
	public static final String TRANSITION_NAME_CREATED = "created";
	public static final String TRANSITION_NAME_COMMITTEE_REJECT = "Decline";
	
	public static final String PL_EQUIVALENCY_DOCUMENTS_TYPE_ERC = "PL_EQUIVALENCY_DOCUMENTS_TYPE_ERC";
	
	public static final String EQUIVALENCY_APPEAL_DOCUMENTS_URL = "/o/c/equivalencyappealdocuments/";
	

	public static final String CREATED_KEY = "created";
	public static final String RESUBMIT_KEY = "resubmit";
	public static final String RESUBMIT_VALUE = "resubmit";
	public static final String INSUFFICIENT_KEY = "insufficient";
	public static final String INITIATED_KEY = "initiated";
	public static final String INITIATED_VALUE = "initiate";
	public static final String EQUATED_VALUE = "equate";
	public static final String EQUATED_KEY = "equated";
	public static final String COMPLETED_KEY = "completed";
	public static final String COMPLETED_VALUE = "complete";
	public static final String PL_Equivalency_Status = "PL_Equivalency_Status";
	public static final String OB_EQUIVALENCY_APPEAL_DOCUMENT_URL = "/o/c/equivalencyappealdocuments/";
	public static final String OB_DOCUMENT_INFO_URL = "/o/c/documentinfo/";
	public static final String OB_EQUIVALENCY_APPEAL_URL = "/o/c/equivalencyappeals/";
	public static final String APPEAL_ADDITIONAL_COMMENTS_RESOURCE = "/appeal/additional-comments";
	public static final String OB_EQUIVALENCY_REQUEST_STATUSES_URL = "/o/c/equivalencyrequeststatuses/";
	public static final String APPEAL_REQUEST_SAVE_ERC = "OB_EQUIVALENCY_APPEAL_ERC";
	public static final String VIEW_EDIT_APPEAL = "/edit-appeal/edit-appeal";
	public static final String EDIT_APPEAL_JSP = "/jsps/appeal/edit-appeal/edit-appeal.jsp";
	public static final String EDIT_APPEAL_MVC_ACTION_COMMAND = "/edit-appeal/workflow_action";
}
