/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.superset.dashboard.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RoleDashboardConfig service. Represents a row in the &quot;role_dashboard_config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.superset.dashboard.model.impl.RoleDashboardConfigModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.superset.dashboard.model.impl.RoleDashboardConfigImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RoleDashboardConfig
 * @generated
 */
@ProviderType
public interface RoleDashboardConfigModel
	extends BaseModel<RoleDashboardConfig>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a role dashboard config model instance should use the {@link RoleDashboardConfig} interface instead.
	 */

	/**
	 * Returns the primary key of this role dashboard config.
	 *
	 * @return the primary key of this role dashboard config
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this role dashboard config.
	 *
	 * @param primaryKey the primary key of this role dashboard config
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the config ID of this role dashboard config.
	 *
	 * @return the config ID of this role dashboard config
	 */
	public long getConfigId();

	/**
	 * Sets the config ID of this role dashboard config.
	 *
	 * @param configId the config ID of this role dashboard config
	 */
	public void setConfigId(long configId);

	/**
	 * Returns the role ID of this role dashboard config.
	 *
	 * @return the role ID of this role dashboard config
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this role dashboard config.
	 *
	 * @param roleId the role ID of this role dashboard config
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the dashboard ID of this role dashboard config.
	 *
	 * @return the dashboard ID of this role dashboard config
	 */
	@AutoEscape
	public String getDashboardId();

	/**
	 * Sets the dashboard ID of this role dashboard config.
	 *
	 * @param dashboardId the dashboard ID of this role dashboard config
	 */
	public void setDashboardId(String dashboardId);

	/**
	 * Returns the company ID of this role dashboard config.
	 *
	 * @return the company ID of this role dashboard config
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this role dashboard config.
	 *
	 * @param companyId the company ID of this role dashboard config
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this role dashboard config.
	 *
	 * @return the group ID of this role dashboard config
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this role dashboard config.
	 *
	 * @param groupId the group ID of this role dashboard config
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this role dashboard config.
	 *
	 * @return the user ID of this role dashboard config
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this role dashboard config.
	 *
	 * @param userId the user ID of this role dashboard config
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this role dashboard config.
	 *
	 * @return the user uuid of this role dashboard config
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this role dashboard config.
	 *
	 * @param userUuid the user uuid of this role dashboard config
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this role dashboard config.
	 *
	 * @return the created date of this role dashboard config
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this role dashboard config.
	 *
	 * @param createdDate the created date of this role dashboard config
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this role dashboard config.
	 *
	 * @return the modified date of this role dashboard config
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this role dashboard config.
	 *
	 * @param modifiedDate the modified date of this role dashboard config
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this role dashboard config.
	 *
	 * @return the created by of this role dashboard config
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this role dashboard config.
	 *
	 * @param createdBy the created by of this role dashboard config
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this role dashboard config.
	 *
	 * @return the modified by of this role dashboard config
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this role dashboard config.
	 *
	 * @param modifiedBy the modified by of this role dashboard config
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public RoleDashboardConfig cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}