/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BlockWeekMetadataDetailsRel service. Represents a row in the &quot;block_week_metadata_details_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.BlockWeekMetadataDetailsRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.BlockWeekMetadataDetailsRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BlockWeekMetadataDetailsRel
 * @generated
 */
@ProviderType
public interface BlockWeekMetadataDetailsRelModel
	extends BaseModel<BlockWeekMetadataDetailsRel>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a block week metadata details rel model instance should use the {@link BlockWeekMetadataDetailsRel} interface instead.
	 */

	/**
	 * Returns the primary key of this block week metadata details rel.
	 *
	 * @return the primary key of this block week metadata details rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this block week metadata details rel.
	 *
	 * @param primaryKey the primary key of this block week metadata details rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this block week metadata details rel.
	 *
	 * @return the uuid of this block week metadata details rel
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this block week metadata details rel.
	 *
	 * @param uuid the uuid of this block week metadata details rel
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the block week metadata details rel ID of this block week metadata details rel.
	 *
	 * @return the block week metadata details rel ID of this block week metadata details rel
	 */
	public long getBlockWeekMetadataDetailsRelId();

	/**
	 * Sets the block week metadata details rel ID of this block week metadata details rel.
	 *
	 * @param blockWeekMetadataDetailsRelId the block week metadata details rel ID of this block week metadata details rel
	 */
	public void setBlockWeekMetadataDetailsRelId(
		long blockWeekMetadataDetailsRelId);

	/**
	 * Returns the blocks metadata detail rel ID of this block week metadata details rel.
	 *
	 * @return the blocks metadata detail rel ID of this block week metadata details rel
	 */
	public long getBlocksMetadataDetailRelId();

	/**
	 * Sets the blocks metadata detail rel ID of this block week metadata details rel.
	 *
	 * @param blocksMetadataDetailRelId the blocks metadata detail rel ID of this block week metadata details rel
	 */
	public void setBlocksMetadataDetailRelId(long blocksMetadataDetailRelId);

	/**
	 * Returns the week no of this block week metadata details rel.
	 *
	 * @return the week no of this block week metadata details rel
	 */
	@AutoEscape
	public String getWeekNo();

	/**
	 * Sets the week no of this block week metadata details rel.
	 *
	 * @param weekNo the week no of this block week metadata details rel
	 */
	public void setWeekNo(String weekNo);

	/**
	 * Returns the week start date of this block week metadata details rel.
	 *
	 * @return the week start date of this block week metadata details rel
	 */
	public Date getWeekStartDate();

	/**
	 * Sets the week start date of this block week metadata details rel.
	 *
	 * @param weekStartDate the week start date of this block week metadata details rel
	 */
	public void setWeekStartDate(Date weekStartDate);

	/**
	 * Returns the week end date of this block week metadata details rel.
	 *
	 * @return the week end date of this block week metadata details rel
	 */
	public Date getWeekEndDate();

	/**
	 * Sets the week end date of this block week metadata details rel.
	 *
	 * @param weekEndDate the week end date of this block week metadata details rel
	 */
	public void setWeekEndDate(Date weekEndDate);

	/**
	 * Returns the group ID of this block week metadata details rel.
	 *
	 * @return the group ID of this block week metadata details rel
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this block week metadata details rel.
	 *
	 * @param groupId the group ID of this block week metadata details rel
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this block week metadata details rel.
	 *
	 * @return the company ID of this block week metadata details rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this block week metadata details rel.
	 *
	 * @param companyId the company ID of this block week metadata details rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created date of this block week metadata details rel.
	 *
	 * @return the created date of this block week metadata details rel
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this block week metadata details rel.
	 *
	 * @param createdDate the created date of this block week metadata details rel
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this block week metadata details rel.
	 *
	 * @return the created by of this block week metadata details rel
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this block week metadata details rel.
	 *
	 * @param createdBy the created by of this block week metadata details rel
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this block week metadata details rel.
	 *
	 * @return the modified date of this block week metadata details rel
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this block week metadata details rel.
	 *
	 * @param modifiedDate the modified date of this block week metadata details rel
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this block week metadata details rel.
	 *
	 * @return the modified by of this block week metadata details rel
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this block week metadata details rel.
	 *
	 * @param modifiedBy the modified by of this block week metadata details rel
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public BlockWeekMetadataDetailsRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}