/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BlocksMetadataDetailsRel service. Represents a row in the &quot;blocks_metadata_details_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.BlocksMetadataDetailsRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.BlocksMetadataDetailsRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BlocksMetadataDetailsRel
 * @generated
 */
@ProviderType
public interface BlocksMetadataDetailsRelModel
	extends BaseModel<BlocksMetadataDetailsRel>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a blocks metadata details rel model instance should use the {@link BlocksMetadataDetailsRel} interface instead.
	 */

	/**
	 * Returns the primary key of this blocks metadata details rel.
	 *
	 * @return the primary key of this blocks metadata details rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this blocks metadata details rel.
	 *
	 * @param primaryKey the primary key of this blocks metadata details rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this blocks metadata details rel.
	 *
	 * @return the uuid of this blocks metadata details rel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this blocks metadata details rel.
	 *
	 * @param uuid the uuid of this blocks metadata details rel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the blocks metadata details rel ID of this blocks metadata details rel.
	 *
	 * @return the blocks metadata details rel ID of this blocks metadata details rel
	 */
	public long getBlocksMetadataDetailsRelId();

	/**
	 * Sets the blocks metadata details rel ID of this blocks metadata details rel.
	 *
	 * @param blocksMetadataDetailsRelId the blocks metadata details rel ID of this blocks metadata details rel
	 */
	public void setBlocksMetadataDetailsRelId(long blocksMetadataDetailsRelId);

	/**
	 * Returns the group ID of this blocks metadata details rel.
	 *
	 * @return the group ID of this blocks metadata details rel
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this blocks metadata details rel.
	 *
	 * @param groupId the group ID of this blocks metadata details rel
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this blocks metadata details rel.
	 *
	 * @return the company ID of this blocks metadata details rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this blocks metadata details rel.
	 *
	 * @param companyId the company ID of this blocks metadata details rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this blocks metadata details rel.
	 *
	 * @return the create date of this blocks metadata details rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this blocks metadata details rel.
	 *
	 * @param createDate the create date of this blocks metadata details rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this blocks metadata details rel.
	 *
	 * @return the modified date of this blocks metadata details rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this blocks metadata details rel.
	 *
	 * @param modifiedDate the modified date of this blocks metadata details rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this blocks metadata details rel.
	 *
	 * @return the created by of this blocks metadata details rel
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this blocks metadata details rel.
	 *
	 * @param createdBy the created by of this blocks metadata details rel
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this blocks metadata details rel.
	 *
	 * @return the modified by of this blocks metadata details rel
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this blocks metadata details rel.
	 *
	 * @param modifiedBy the modified by of this blocks metadata details rel
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the prog duration tl blocks lt ID of this blocks metadata details rel.
	 *
	 * @return the prog duration tl blocks lt ID of this blocks metadata details rel
	 */
	public long getProgDurationTlBlocksLtId();

	/**
	 * Sets the prog duration tl blocks lt ID of this blocks metadata details rel.
	 *
	 * @param progDurationTlBlocksLtId the prog duration tl blocks lt ID of this blocks metadata details rel
	 */
	public void setProgDurationTlBlocksLtId(long progDurationTlBlocksLtId);

	/**
	 * Returns the block no of this blocks metadata details rel.
	 *
	 * @return the block no of this blocks metadata details rel
	 */
	@AutoEscape
	public String getBlockNo();

	/**
	 * Sets the block no of this blocks metadata details rel.
	 *
	 * @param blockNo the block no of this blocks metadata details rel
	 */
	public void setBlockNo(String blockNo);

	/**
	 * Returns the block start date of this blocks metadata details rel.
	 *
	 * @return the block start date of this blocks metadata details rel
	 */
	public Date getBlockStartDate();

	/**
	 * Sets the block start date of this blocks metadata details rel.
	 *
	 * @param blockStartDate the block start date of this blocks metadata details rel
	 */
	public void setBlockStartDate(Date blockStartDate);

	/**
	 * Returns the block end date of this blocks metadata details rel.
	 *
	 * @return the block end date of this blocks metadata details rel
	 */
	public Date getBlockEndDate();

	/**
	 * Sets the block end date of this blocks metadata details rel.
	 *
	 * @param blockEndDate the block end date of this blocks metadata details rel
	 */
	public void setBlockEndDate(Date blockEndDate);

	@Override
	public BlocksMetadataDetailsRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}