/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CptCodeMaster service. Represents a row in the &quot;cpt_code_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.CptCodeMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.CptCodeMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CptCodeMaster
 * @generated
 */
@ProviderType
public interface CptCodeMasterModel
	extends BaseModel<CptCodeMaster>, LocalizedModel, ShardedModel,
			StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cpt code master model instance should use the {@link CptCodeMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this cpt code master.
	 *
	 * @return the primary key of this cpt code master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cpt code master.
	 *
	 * @param primaryKey the primary key of this cpt code master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cpt code master.
	 *
	 * @return the uuid of this cpt code master
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this cpt code master.
	 *
	 * @param uuid the uuid of this cpt code master
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the cpt code master ID of this cpt code master.
	 *
	 * @return the cpt code master ID of this cpt code master
	 */
	public long getCptCodeMasterId();

	/**
	 * Sets the cpt code master ID of this cpt code master.
	 *
	 * @param cptCodeMasterId the cpt code master ID of this cpt code master
	 */
	public void setCptCodeMasterId(long cptCodeMasterId);

	/**
	 * Returns the group ID of this cpt code master.
	 *
	 * @return the group ID of this cpt code master
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this cpt code master.
	 *
	 * @param groupId the group ID of this cpt code master
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this cpt code master.
	 *
	 * @return the company ID of this cpt code master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cpt code master.
	 *
	 * @param companyId the company ID of this cpt code master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this cpt code master.
	 *
	 * @return the create date of this cpt code master
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cpt code master.
	 *
	 * @param createDate the create date of this cpt code master
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this cpt code master.
	 *
	 * @return the created by of this cpt code master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this cpt code master.
	 *
	 * @param createdBy the created by of this cpt code master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this cpt code master.
	 *
	 * @return the modified date of this cpt code master
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cpt code master.
	 *
	 * @param modifiedDate the modified date of this cpt code master
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this cpt code master.
	 *
	 * @return the modified by of this cpt code master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this cpt code master.
	 *
	 * @param modifiedBy the modified by of this cpt code master
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the cpt code name of this cpt code master.
	 *
	 * @return the cpt code name of this cpt code master
	 */
	public String getCptCodeName();

	/**
	 * Returns the localized cpt code name of this cpt code master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized cpt code name of this cpt code master
	 */
	@AutoEscape
	public String getCptCodeName(Locale locale);

	/**
	 * Returns the localized cpt code name of this cpt code master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized cpt code name of this cpt code master. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getCptCodeName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized cpt code name of this cpt code master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized cpt code name of this cpt code master
	 */
	@AutoEscape
	public String getCptCodeName(String languageId);

	/**
	 * Returns the localized cpt code name of this cpt code master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized cpt code name of this cpt code master
	 */
	@AutoEscape
	public String getCptCodeName(String languageId, boolean useDefault);

	@AutoEscape
	public String getCptCodeNameCurrentLanguageId();

	@AutoEscape
	public String getCptCodeNameCurrentValue();

	/**
	 * Returns a map of the locales and localized cpt code names of this cpt code master.
	 *
	 * @return the locales and localized cpt code names of this cpt code master
	 */
	public Map<Locale, String> getCptCodeNameMap();

	/**
	 * Sets the cpt code name of this cpt code master.
	 *
	 * @param cptCodeName the cpt code name of this cpt code master
	 */
	public void setCptCodeName(String cptCodeName);

	/**
	 * Sets the localized cpt code name of this cpt code master in the language.
	 *
	 * @param cptCodeName the localized cpt code name of this cpt code master
	 * @param locale the locale of the language
	 */
	public void setCptCodeName(String cptCodeName, Locale locale);

	/**
	 * Sets the localized cpt code name of this cpt code master in the language, and sets the default locale.
	 *
	 * @param cptCodeName the localized cpt code name of this cpt code master
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setCptCodeName(
		String cptCodeName, Locale locale, Locale defaultLocale);

	public void setCptCodeNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized cpt code names of this cpt code master from the map of locales and localized cpt code names.
	 *
	 * @param cptCodeNameMap the locales and localized cpt code names of this cpt code master
	 */
	public void setCptCodeNameMap(Map<Locale, String> cptCodeNameMap);

	/**
	 * Sets the localized cpt code names of this cpt code master from the map of locales and localized cpt code names, and sets the default locale.
	 *
	 * @param cptCodeNameMap the locales and localized cpt code names of this cpt code master
	 * @param defaultLocale the default locale
	 */
	public void setCptCodeNameMap(
		Map<Locale, String> cptCodeNameMap, Locale defaultLocale);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public CptCodeMaster cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}