/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DutyLogViolation service. Represents a row in the &quot;duty_log_violation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.DutyLogViolationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.DutyLogViolationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DutyLogViolation
 * @generated
 */
@ProviderType
public interface DutyLogViolationModel
	extends BaseModel<DutyLogViolation>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a duty log violation model instance should use the {@link DutyLogViolation} interface instead.
	 */

	/**
	 * Returns the primary key of this duty log violation.
	 *
	 * @return the primary key of this duty log violation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this duty log violation.
	 *
	 * @param primaryKey the primary key of this duty log violation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this duty log violation.
	 *
	 * @return the uuid of this duty log violation
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this duty log violation.
	 *
	 * @param uuid the uuid of this duty log violation
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the violation ID of this duty log violation.
	 *
	 * @return the violation ID of this duty log violation
	 */
	public long getViolationId();

	/**
	 * Sets the violation ID of this duty log violation.
	 *
	 * @param ViolationId the violation ID of this duty log violation
	 */
	public void setViolationId(long ViolationId);

	/**
	 * Returns the group ID of this duty log violation.
	 *
	 * @return the group ID of this duty log violation
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this duty log violation.
	 *
	 * @param groupId the group ID of this duty log violation
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this duty log violation.
	 *
	 * @return the company ID of this duty log violation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this duty log violation.
	 *
	 * @param companyId the company ID of this duty log violation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this duty log violation.
	 *
	 * @return the create date of this duty log violation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this duty log violation.
	 *
	 * @param createDate the create date of this duty log violation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this duty log violation.
	 *
	 * @return the created by of this duty log violation
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this duty log violation.
	 *
	 * @param createdBy the created by of this duty log violation
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this duty log violation.
	 *
	 * @return the modified date of this duty log violation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this duty log violation.
	 *
	 * @param modifiedDate the modified date of this duty log violation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this duty log violation.
	 *
	 * @return the modified by of this duty log violation
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this duty log violation.
	 *
	 * @param modifiedBy the modified by of this duty log violation
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the trainee ID of this duty log violation.
	 *
	 * @return the trainee ID of this duty log violation
	 */
	public long getTraineeId();

	/**
	 * Sets the trainee ID of this duty log violation.
	 *
	 * @param traineeId the trainee ID of this duty log violation
	 */
	public void setTraineeId(long traineeId);

	/**
	 * Returns the program master ID of this duty log violation.
	 *
	 * @return the program master ID of this duty log violation
	 */
	public long getProgramMasterId();

	/**
	 * Sets the program master ID of this duty log violation.
	 *
	 * @param programMasterId the program master ID of this duty log violation
	 */
	public void setProgramMasterId(long programMasterId);

	/**
	 * Returns the residency level of this duty log violation.
	 *
	 * @return the residency level of this duty log violation
	 */
	public long getResidencyLevel();

	/**
	 * Sets the residency level of this duty log violation.
	 *
	 * @param residencyLevel the residency level of this duty log violation
	 */
	public void setResidencyLevel(long residencyLevel);

	/**
	 * Returns the rotation ID of this duty log violation.
	 *
	 * @return the rotation ID of this duty log violation
	 */
	public long getRotationId();

	/**
	 * Sets the rotation ID of this duty log violation.
	 *
	 * @param rotationId the rotation ID of this duty log violation
	 */
	public void setRotationId(long rotationId);

	/**
	 * Returns the training site ID of this duty log violation.
	 *
	 * @return the training site ID of this duty log violation
	 */
	public long getTrainingSiteId();

	/**
	 * Sets the training site ID of this duty log violation.
	 *
	 * @param trainingSiteId the training site ID of this duty log violation
	 */
	public void setTrainingSiteId(long trainingSiteId);

	/**
	 * Returns the block ID of this duty log violation.
	 *
	 * @return the block ID of this duty log violation
	 */
	public long getBlockId();

	/**
	 * Sets the block ID of this duty log violation.
	 *
	 * @param blockId the block ID of this duty log violation
	 */
	public void setBlockId(long blockId);

	/**
	 * Returns the block week ID of this duty log violation.
	 *
	 * @return the block week ID of this duty log violation
	 */
	public long getBlockWeekId();

	/**
	 * Sets the block week ID of this duty log violation.
	 *
	 * @param blockWeekId the block week ID of this duty log violation
	 */
	public void setBlockWeekId(long blockWeekId);

	/**
	 * Returns the program duty rule ID of this duty log violation.
	 *
	 * @return the program duty rule ID of this duty log violation
	 */
	public long getProgramDutyRuleId();

	/**
	 * Sets the program duty rule ID of this duty log violation.
	 *
	 * @param programDutyRuleId the program duty rule ID of this duty log violation
	 */
	public void setProgramDutyRuleId(long programDutyRuleId);

	/**
	 * Returns the acgme80 hours rule of this duty log violation.
	 *
	 * @return the acgme80 hours rule of this duty log violation
	 */
	public int getAcgme80HoursRule();

	/**
	 * Sets the acgme80 hours rule of this duty log violation.
	 *
	 * @param acgme80HoursRule the acgme80 hours rule of this duty log violation
	 */
	public void setAcgme80HoursRule(int acgme80HoursRule);

	/**
	 * Returns the acgme call rule option1 of this duty log violation.
	 *
	 * @return the acgme call rule option1 of this duty log violation
	 */
	public int getAcgmeCallRuleOption1();

	/**
	 * Sets the acgme call rule option1 of this duty log violation.
	 *
	 * @param acgmeCallRuleOption1 the acgme call rule option1 of this duty log violation
	 */
	public void setAcgmeCallRuleOption1(int acgmeCallRuleOption1);

	/**
	 * Returns the acgme call rule option2 of this duty log violation.
	 *
	 * @return the acgme call rule option2 of this duty log violation
	 */
	public int getAcgmeCallRuleOption2();

	/**
	 * Sets the acgme call rule option2 of this duty log violation.
	 *
	 * @param acgmeCallRuleOption2 the acgme call rule option2 of this duty log violation
	 */
	public void setAcgmeCallRuleOption2(int acgmeCallRuleOption2);

	/**
	 * Returns the acgme short break rule of this duty log violation.
	 *
	 * @return the acgme short break rule of this duty log violation
	 */
	public int getAcgmeShortBreakRule();

	/**
	 * Sets the acgme short break rule of this duty log violation.
	 *
	 * @param acgmeShortBreakRule the acgme short break rule of this duty log violation
	 */
	public void setAcgmeShortBreakRule(int acgmeShortBreakRule);

	/**
	 * Returns the acgme24 hours rule of this duty log violation.
	 *
	 * @return the acgme24 hours rule of this duty log violation
	 */
	public int getAcgme24HoursRule();

	/**
	 * Sets the acgme24 hours rule of this duty log violation.
	 *
	 * @param acgme24HoursRule the acgme24 hours rule of this duty log violation
	 */
	public void setAcgme24HoursRule(int acgme24HoursRule);

	/**
	 * Returns the acgme day off rule of this duty log violation.
	 *
	 * @return the acgme day off rule of this duty log violation
	 */
	public int getAcgmeDayOffRule();

	/**
	 * Sets the acgme day off rule of this duty log violation.
	 *
	 * @param acgmeDayOffRule the acgme day off rule of this duty log violation
	 */
	public void setAcgmeDayOffRule(int acgmeDayOffRule);

	/**
	 * Returns the duty log ID of this duty log violation.
	 *
	 * @return the duty log ID of this duty log violation
	 */
	public long getDutyLogId();

	/**
	 * Sets the duty log ID of this duty log violation.
	 *
	 * @param dutyLogId the duty log ID of this duty log violation
	 */
	public void setDutyLogId(long dutyLogId);

	@Override
	public DutyLogViolation cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}