/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DutyAssignment service. Represents a row in the &quot;duty_assignment_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.DutyAssignmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.DutyAssignmentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DutyAssignment
 * @generated
 */
@ProviderType
public interface DutyAssignmentModel
	extends BaseModel<DutyAssignment>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a duty assignment model instance should use the {@link DutyAssignment} interface instead.
	 */

	/**
	 * Returns the primary key of this duty assignment.
	 *
	 * @return the primary key of this duty assignment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this duty assignment.
	 *
	 * @param primaryKey the primary key of this duty assignment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this duty assignment.
	 *
	 * @return the uuid of this duty assignment
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this duty assignment.
	 *
	 * @param uuid the uuid of this duty assignment
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the duty assignment ID of this duty assignment.
	 *
	 * @return the duty assignment ID of this duty assignment
	 */
	public long getDutyAssignmentId();

	/**
	 * Sets the duty assignment ID of this duty assignment.
	 *
	 * @param dutyAssignmentId the duty assignment ID of this duty assignment
	 */
	public void setDutyAssignmentId(long dutyAssignmentId);

	/**
	 * Returns the group ID of this duty assignment.
	 *
	 * @return the group ID of this duty assignment
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this duty assignment.
	 *
	 * @param groupId the group ID of this duty assignment
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this duty assignment.
	 *
	 * @return the company ID of this duty assignment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this duty assignment.
	 *
	 * @param companyId the company ID of this duty assignment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this duty assignment.
	 *
	 * @return the create date of this duty assignment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this duty assignment.
	 *
	 * @param createDate the create date of this duty assignment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this duty assignment.
	 *
	 * @return the created by of this duty assignment
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this duty assignment.
	 *
	 * @param createdBy the created by of this duty assignment
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this duty assignment.
	 *
	 * @return the modified date of this duty assignment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this duty assignment.
	 *
	 * @param modifiedDate the modified date of this duty assignment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this duty assignment.
	 *
	 * @return the modified by of this duty assignment
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this duty assignment.
	 *
	 * @param modifiedBy the modified by of this duty assignment
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the duty type ID of this duty assignment.
	 *
	 * @return the duty type ID of this duty assignment
	 */
	public long getDutyTypeId();

	/**
	 * Sets the duty type ID of this duty assignment.
	 *
	 * @param dutyTypeId the duty type ID of this duty assignment
	 */
	public void setDutyTypeId(long dutyTypeId);

	/**
	 * Returns the assignment of this duty assignment.
	 *
	 * @return the assignment of this duty assignment
	 */
	@AutoEscape
	public String getAssignment();

	/**
	 * Sets the assignment of this duty assignment.
	 *
	 * @param assignment the assignment of this duty assignment
	 */
	public void setAssignment(String assignment);

	/**
	 * Returns the status of this duty assignment.
	 *
	 * @return the status of this duty assignment
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this duty assignment.
	 *
	 * @param status the status of this duty assignment
	 */
	public void setStatus(String status);

	/**
	 * Returns the color code of this duty assignment.
	 *
	 * @return the color code of this duty assignment
	 */
	@AutoEscape
	public String getColorCode();

	/**
	 * Sets the color code of this duty assignment.
	 *
	 * @param colorCode the color code of this duty assignment
	 */
	public void setColorCode(String colorCode);

	@Override
	public DutyAssignment cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}