/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EcMemberRequestRotations service. Represents a row in the &quot;ec_member_request_rotations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.EcMemberRequestRotationsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.EcMemberRequestRotationsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EcMemberRequestRotations
 * @generated
 */
@ProviderType
public interface EcMemberRequestRotationsModel
	extends BaseModel<EcMemberRequestRotations>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ec member request rotations model instance should use the {@link EcMemberRequestRotations} interface instead.
	 */

	/**
	 * Returns the primary key of this ec member request rotations.
	 *
	 * @return the primary key of this ec member request rotations
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ec member request rotations.
	 *
	 * @param primaryKey the primary key of this ec member request rotations
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ec member request rotations.
	 *
	 * @return the uuid of this ec member request rotations
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ec member request rotations.
	 *
	 * @param uuid the uuid of this ec member request rotations
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ec member request rotations ID of this ec member request rotations.
	 *
	 * @return the ec member request rotations ID of this ec member request rotations
	 */
	public long getEcMemberRequestRotationsId();

	/**
	 * Sets the ec member request rotations ID of this ec member request rotations.
	 *
	 * @param ecMemberRequestRotationsId the ec member request rotations ID of this ec member request rotations
	 */
	public void setEcMemberRequestRotationsId(long ecMemberRequestRotationsId);

	/**
	 * Returns the group ID of this ec member request rotations.
	 *
	 * @return the group ID of this ec member request rotations
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this ec member request rotations.
	 *
	 * @param groupId the group ID of this ec member request rotations
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ec member request rotations.
	 *
	 * @return the company ID of this ec member request rotations
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ec member request rotations.
	 *
	 * @param companyId the company ID of this ec member request rotations
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this ec member request rotations.
	 *
	 * @return the create date of this ec member request rotations
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ec member request rotations.
	 *
	 * @param createDate the create date of this ec member request rotations
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ec member request rotations.
	 *
	 * @return the modified date of this ec member request rotations
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ec member request rotations.
	 *
	 * @param modifiedDate the modified date of this ec member request rotations
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ec member request ID of this ec member request rotations.
	 *
	 * @return the ec member request ID of this ec member request rotations
	 */
	public long getEcMemberRequestId();

	/**
	 * Sets the ec member request ID of this ec member request rotations.
	 *
	 * @param ecMemberRequestId the ec member request ID of this ec member request rotations
	 */
	public void setEcMemberRequestId(long ecMemberRequestId);

	/**
	 * Returns the training site ID of this ec member request rotations.
	 *
	 * @return the training site ID of this ec member request rotations
	 */
	public long getTrainingSiteId();

	/**
	 * Sets the training site ID of this ec member request rotations.
	 *
	 * @param trainingSiteId the training site ID of this ec member request rotations
	 */
	public void setTrainingSiteId(long trainingSiteId);

	/**
	 * Returns the rotation ID of this ec member request rotations.
	 *
	 * @return the rotation ID of this ec member request rotations
	 */
	public long getRotationId();

	/**
	 * Sets the rotation ID of this ec member request rotations.
	 *
	 * @param rotationId the rotation ID of this ec member request rotations
	 */
	public void setRotationId(long rotationId);

	/**
	 * Returns the is active of this ec member request rotations.
	 *
	 * @return the is active of this ec member request rotations
	 */
	public Boolean getIsActive();

	/**
	 * Sets the is active of this ec member request rotations.
	 *
	 * @param isActive the is active of this ec member request rotations
	 */
	public void setIsActive(Boolean isActive);

	@Override
	public EcMemberRequestRotations cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}