/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EcMemberRequestState service. Represents a row in the &quot;ec_member_request_state&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.EcMemberRequestStateModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.EcMemberRequestStateImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EcMemberRequestState
 * @generated
 */
@ProviderType
public interface EcMemberRequestStateModel
	extends BaseModel<EcMemberRequestState>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ec member request state model instance should use the {@link EcMemberRequestState} interface instead.
	 */

	/**
	 * Returns the primary key of this ec member request state.
	 *
	 * @return the primary key of this ec member request state
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ec member request state.
	 *
	 * @param primaryKey the primary key of this ec member request state
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ec member request state.
	 *
	 * @return the uuid of this ec member request state
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ec member request state.
	 *
	 * @param uuid the uuid of this ec member request state
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ec member request state ID of this ec member request state.
	 *
	 * @return the ec member request state ID of this ec member request state
	 */
	public long getEcMemberRequestStateId();

	/**
	 * Sets the ec member request state ID of this ec member request state.
	 *
	 * @param ecMemberRequestStateId the ec member request state ID of this ec member request state
	 */
	public void setEcMemberRequestStateId(long ecMemberRequestStateId);

	/**
	 * Returns the group ID of this ec member request state.
	 *
	 * @return the group ID of this ec member request state
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this ec member request state.
	 *
	 * @param groupId the group ID of this ec member request state
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the created by of this ec member request state.
	 *
	 * @return the created by of this ec member request state
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this ec member request state.
	 *
	 * @param createdBy the created by of this ec member request state
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the company ID of this ec member request state.
	 *
	 * @return the company ID of this ec member request state
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ec member request state.
	 *
	 * @param companyId the company ID of this ec member request state
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this ec member request state.
	 *
	 * @return the create date of this ec member request state
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ec member request state.
	 *
	 * @param createDate the create date of this ec member request state
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ec member request state.
	 *
	 * @return the modified date of this ec member request state
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ec member request state.
	 *
	 * @param modifiedDate the modified date of this ec member request state
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by role ID of this ec member request state.
	 *
	 * @return the created by role ID of this ec member request state
	 */
	public long getCreatedByRoleId();

	/**
	 * Sets the created by role ID of this ec member request state.
	 *
	 * @param createdByRoleId the created by role ID of this ec member request state
	 */
	public void setCreatedByRoleId(long createdByRoleId);

	/**
	 * Returns the ec member request ID of this ec member request state.
	 *
	 * @return the ec member request ID of this ec member request state
	 */
	public long getEcMemberRequestId();

	/**
	 * Sets the ec member request ID of this ec member request state.
	 *
	 * @param ecMemberRequestId the ec member request ID of this ec member request state
	 */
	public void setEcMemberRequestId(long ecMemberRequestId);

	/**
	 * Returns the ec member request status ID of this ec member request state.
	 *
	 * @return the ec member request status ID of this ec member request state
	 */
	public long getEcMemberRequestStatusId();

	/**
	 * Sets the ec member request status ID of this ec member request state.
	 *
	 * @param ecMemberRequestStatusId the ec member request status ID of this ec member request state
	 */
	public void setEcMemberRequestStatusId(long ecMemberRequestStatusId);

	/**
	 * Returns the comments of this ec member request state.
	 *
	 * @return the comments of this ec member request state
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this ec member request state.
	 *
	 * @param comments the comments of this ec member request state
	 */
	public void setComments(String comments);

	/**
	 * Returns the is public of this ec member request state.
	 *
	 * @return the is public of this ec member request state
	 */
	public boolean getIsPublic();

	/**
	 * Returns <code>true</code> if this ec member request state is is public.
	 *
	 * @return <code>true</code> if this ec member request state is is public; <code>false</code> otherwise
	 */
	public boolean isIsPublic();

	/**
	 * Sets whether this ec member request state is is public.
	 *
	 * @param isPublic the is public of this ec member request state
	 */
	public void setIsPublic(boolean isPublic);

	@Override
	public EcMemberRequestState cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}