/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EligibilityDegreeMaster service. Represents a row in the &quot;eligibility_degree_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.EligibilityDegreeMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.EligibilityDegreeMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EligibilityDegreeMaster
 * @generated
 */
@ProviderType
public interface EligibilityDegreeMasterModel
	extends BaseModel<EligibilityDegreeMaster>, LocalizedModel, ShardedModel,
			StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a eligibility degree master model instance should use the {@link EligibilityDegreeMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this eligibility degree master.
	 *
	 * @return the primary key of this eligibility degree master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this eligibility degree master.
	 *
	 * @param primaryKey the primary key of this eligibility degree master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this eligibility degree master.
	 *
	 * @return the uuid of this eligibility degree master
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this eligibility degree master.
	 *
	 * @param uuid the uuid of this eligibility degree master
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the eligibility degree master ID of this eligibility degree master.
	 *
	 * @return the eligibility degree master ID of this eligibility degree master
	 */
	public long getEligibilityDegreeMasterId();

	/**
	 * Sets the eligibility degree master ID of this eligibility degree master.
	 *
	 * @param eligibilityDegreeMasterId the eligibility degree master ID of this eligibility degree master
	 */
	public void setEligibilityDegreeMasterId(long eligibilityDegreeMasterId);

	/**
	 * Returns the group ID of this eligibility degree master.
	 *
	 * @return the group ID of this eligibility degree master
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this eligibility degree master.
	 *
	 * @param groupId the group ID of this eligibility degree master
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this eligibility degree master.
	 *
	 * @return the company ID of this eligibility degree master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this eligibility degree master.
	 *
	 * @param companyId the company ID of this eligibility degree master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this eligibility degree master.
	 *
	 * @return the create date of this eligibility degree master
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this eligibility degree master.
	 *
	 * @param createDate the create date of this eligibility degree master
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this eligibility degree master.
	 *
	 * @return the modified date of this eligibility degree master
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this eligibility degree master.
	 *
	 * @param modifiedDate the modified date of this eligibility degree master
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this eligibility degree master.
	 *
	 * @return the created by of this eligibility degree master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this eligibility degree master.
	 *
	 * @param createdBy the created by of this eligibility degree master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this eligibility degree master.
	 *
	 * @return the modified by of this eligibility degree master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this eligibility degree master.
	 *
	 * @param modifiedBy the modified by of this eligibility degree master
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the eligibility degree of this eligibility degree master.
	 *
	 * @return the eligibility degree of this eligibility degree master
	 */
	public String getEligibilityDegree();

	/**
	 * Returns the localized eligibility degree of this eligibility degree master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized eligibility degree of this eligibility degree master
	 */
	@AutoEscape
	public String getEligibilityDegree(Locale locale);

	/**
	 * Returns the localized eligibility degree of this eligibility degree master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized eligibility degree of this eligibility degree master. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getEligibilityDegree(Locale locale, boolean useDefault);

	/**
	 * Returns the localized eligibility degree of this eligibility degree master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized eligibility degree of this eligibility degree master
	 */
	@AutoEscape
	public String getEligibilityDegree(String languageId);

	/**
	 * Returns the localized eligibility degree of this eligibility degree master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized eligibility degree of this eligibility degree master
	 */
	@AutoEscape
	public String getEligibilityDegree(String languageId, boolean useDefault);

	@AutoEscape
	public String getEligibilityDegreeCurrentLanguageId();

	@AutoEscape
	public String getEligibilityDegreeCurrentValue();

	/**
	 * Returns a map of the locales and localized eligibility degrees of this eligibility degree master.
	 *
	 * @return the locales and localized eligibility degrees of this eligibility degree master
	 */
	public Map<Locale, String> getEligibilityDegreeMap();

	/**
	 * Sets the eligibility degree of this eligibility degree master.
	 *
	 * @param eligibilityDegree the eligibility degree of this eligibility degree master
	 */
	public void setEligibilityDegree(String eligibilityDegree);

	/**
	 * Sets the localized eligibility degree of this eligibility degree master in the language.
	 *
	 * @param eligibilityDegree the localized eligibility degree of this eligibility degree master
	 * @param locale the locale of the language
	 */
	public void setEligibilityDegree(String eligibilityDegree, Locale locale);

	/**
	 * Sets the localized eligibility degree of this eligibility degree master in the language, and sets the default locale.
	 *
	 * @param eligibilityDegree the localized eligibility degree of this eligibility degree master
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setEligibilityDegree(
		String eligibilityDegree, Locale locale, Locale defaultLocale);

	public void setEligibilityDegreeCurrentLanguageId(String languageId);

	/**
	 * Sets the localized eligibility degrees of this eligibility degree master from the map of locales and localized eligibility degrees.
	 *
	 * @param eligibilityDegreeMap the locales and localized eligibility degrees of this eligibility degree master
	 */
	public void setEligibilityDegreeMap(
		Map<Locale, String> eligibilityDegreeMap);

	/**
	 * Sets the localized eligibility degrees of this eligibility degree master from the map of locales and localized eligibility degrees, and sets the default locale.
	 *
	 * @param eligibilityDegreeMap the locales and localized eligibility degrees of this eligibility degree master
	 * @param defaultLocale the default locale
	 */
	public void setEligibilityDegreeMap(
		Map<Locale, String> eligibilityDegreeMap, Locale defaultLocale);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public EligibilityDegreeMaster cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}