/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GenderMaster service. Represents a row in the &quot;gender_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.GenderMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.GenderMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GenderMaster
 * @generated
 */
@ProviderType
public interface GenderMasterModel
	extends BaseModel<GenderMaster>, LocalizedModel, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gender master model instance should use the {@link GenderMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this gender master.
	 *
	 * @return the primary key of this gender master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gender master.
	 *
	 * @param primaryKey the primary key of this gender master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this gender master.
	 *
	 * @return the uuid of this gender master
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this gender master.
	 *
	 * @param uuid the uuid of this gender master
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the gender master ID of this gender master.
	 *
	 * @return the gender master ID of this gender master
	 */
	public long getGenderMasterId();

	/**
	 * Sets the gender master ID of this gender master.
	 *
	 * @param genderMasterId the gender master ID of this gender master
	 */
	public void setGenderMasterId(long genderMasterId);

	/**
	 * Returns the group ID of this gender master.
	 *
	 * @return the group ID of this gender master
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this gender master.
	 *
	 * @param groupId the group ID of this gender master
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this gender master.
	 *
	 * @return the company ID of this gender master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this gender master.
	 *
	 * @param companyId the company ID of this gender master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this gender master.
	 *
	 * @return the create date of this gender master
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this gender master.
	 *
	 * @param createDate the create date of this gender master
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this gender master.
	 *
	 * @return the created by of this gender master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this gender master.
	 *
	 * @param createdBy the created by of this gender master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this gender master.
	 *
	 * @return the modified date of this gender master
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this gender master.
	 *
	 * @param modifiedDate the modified date of this gender master
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this gender master.
	 *
	 * @return the modified by of this gender master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this gender master.
	 *
	 * @param modifiedBy the modified by of this gender master
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the gender name of this gender master.
	 *
	 * @return the gender name of this gender master
	 */
	public String getGenderName();

	/**
	 * Returns the localized gender name of this gender master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized gender name of this gender master
	 */
	@AutoEscape
	public String getGenderName(Locale locale);

	/**
	 * Returns the localized gender name of this gender master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized gender name of this gender master. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getGenderName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized gender name of this gender master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized gender name of this gender master
	 */
	@AutoEscape
	public String getGenderName(String languageId);

	/**
	 * Returns the localized gender name of this gender master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized gender name of this gender master
	 */
	@AutoEscape
	public String getGenderName(String languageId, boolean useDefault);

	@AutoEscape
	public String getGenderNameCurrentLanguageId();

	@AutoEscape
	public String getGenderNameCurrentValue();

	/**
	 * Returns a map of the locales and localized gender names of this gender master.
	 *
	 * @return the locales and localized gender names of this gender master
	 */
	public Map<Locale, String> getGenderNameMap();

	/**
	 * Sets the gender name of this gender master.
	 *
	 * @param genderName the gender name of this gender master
	 */
	public void setGenderName(String genderName);

	/**
	 * Sets the localized gender name of this gender master in the language.
	 *
	 * @param genderName the localized gender name of this gender master
	 * @param locale the locale of the language
	 */
	public void setGenderName(String genderName, Locale locale);

	/**
	 * Sets the localized gender name of this gender master in the language, and sets the default locale.
	 *
	 * @param genderName the localized gender name of this gender master
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setGenderName(
		String genderName, Locale locale, Locale defaultLocale);

	public void setGenderNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized gender names of this gender master from the map of locales and localized gender names.
	 *
	 * @param genderNameMap the locales and localized gender names of this gender master
	 */
	public void setGenderNameMap(Map<Locale, String> genderNameMap);

	/**
	 * Sets the localized gender names of this gender master from the map of locales and localized gender names, and sets the default locale.
	 *
	 * @param genderNameMap the locales and localized gender names of this gender master
	 * @param defaultLocale the default locale
	 */
	public void setGenderNameMap(
		Map<Locale, String> genderNameMap, Locale defaultLocale);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public GenderMaster cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}