/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LeaveTraineeMaster service. Represents a row in the &quot;leave_trainee_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.LeaveTraineeMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.LeaveTraineeMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveTraineeMaster
 * @generated
 */
@ProviderType
public interface LeaveTraineeMasterModel
	extends BaseModel<LeaveTraineeMaster>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave trainee master model instance should use the {@link LeaveTraineeMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this leave trainee master.
	 *
	 * @return the primary key of this leave trainee master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave trainee master.
	 *
	 * @param primaryKey the primary key of this leave trainee master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave trainee master.
	 *
	 * @return the uuid of this leave trainee master
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave trainee master.
	 *
	 * @param uuid the uuid of this leave trainee master
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the leave trainee master ID of this leave trainee master.
	 *
	 * @return the leave trainee master ID of this leave trainee master
	 */
	public long getLeaveTraineeMasterId();

	/**
	 * Sets the leave trainee master ID of this leave trainee master.
	 *
	 * @param leaveTraineeMasterId the leave trainee master ID of this leave trainee master
	 */
	public void setLeaveTraineeMasterId(long leaveTraineeMasterId);

	/**
	 * Returns the leave program master ID of this leave trainee master.
	 *
	 * @return the leave program master ID of this leave trainee master
	 */
	public long getLeaveProgramMasterId();

	/**
	 * Sets the leave program master ID of this leave trainee master.
	 *
	 * @param leaveProgramMasterId the leave program master ID of this leave trainee master
	 */
	public void setLeaveProgramMasterId(long leaveProgramMasterId);

	/**
	 * Returns the trainee ID of this leave trainee master.
	 *
	 * @return the trainee ID of this leave trainee master
	 */
	public long getTraineeId();

	/**
	 * Sets the trainee ID of this leave trainee master.
	 *
	 * @param traineeId the trainee ID of this leave trainee master
	 */
	public void setTraineeId(long traineeId);

	/**
	 * Returns the no of leave taken of this leave trainee master.
	 *
	 * @return the no of leave taken of this leave trainee master
	 */
	public int getNoOfLeaveTaken();

	/**
	 * Sets the no of leave taken of this leave trainee master.
	 *
	 * @param noOfLeaveTaken the no of leave taken of this leave trainee master
	 */
	public void setNoOfLeaveTaken(int noOfLeaveTaken);

	/**
	 * Returns the no of leave remaining of this leave trainee master.
	 *
	 * @return the no of leave remaining of this leave trainee master
	 */
	public int getNoOfLeaveRemaining();

	/**
	 * Sets the no of leave remaining of this leave trainee master.
	 *
	 * @param noOfLeaveRemaining the no of leave remaining of this leave trainee master
	 */
	public void setNoOfLeaveRemaining(int noOfLeaveRemaining);

	/**
	 * Returns the group ID of this leave trainee master.
	 *
	 * @return the group ID of this leave trainee master
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this leave trainee master.
	 *
	 * @param groupId the group ID of this leave trainee master
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leave trainee master.
	 *
	 * @return the company ID of this leave trainee master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave trainee master.
	 *
	 * @param companyId the company ID of this leave trainee master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this leave trainee master.
	 *
	 * @return the create date of this leave trainee master
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave trainee master.
	 *
	 * @param createDate the create date of this leave trainee master
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this leave trainee master.
	 *
	 * @return the created by of this leave trainee master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this leave trainee master.
	 *
	 * @param createdBy the created by of this leave trainee master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this leave trainee master.
	 *
	 * @return the modified date of this leave trainee master
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave trainee master.
	 *
	 * @param modifiedDate the modified date of this leave trainee master
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this leave trainee master.
	 *
	 * @return the modified by of this leave trainee master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this leave trainee master.
	 *
	 * @param modifiedBy the modified by of this leave trainee master
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public LeaveTraineeMaster cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}