/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LeaveTypes service. Represents a row in the &quot;leave_types&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.LeaveTypesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.LeaveTypesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveTypes
 * @generated
 */
@ProviderType
public interface LeaveTypesModel
	extends BaseModel<LeaveTypes>, LocalizedModel, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave types model instance should use the {@link LeaveTypes} interface instead.
	 */

	/**
	 * Returns the primary key of this leave types.
	 *
	 * @return the primary key of this leave types
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave types.
	 *
	 * @param primaryKey the primary key of this leave types
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave types.
	 *
	 * @return the uuid of this leave types
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave types.
	 *
	 * @param uuid the uuid of this leave types
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the leave types ID of this leave types.
	 *
	 * @return the leave types ID of this leave types
	 */
	public long getLeaveTypesId();

	/**
	 * Sets the leave types ID of this leave types.
	 *
	 * @param leaveTypesId the leave types ID of this leave types
	 */
	public void setLeaveTypesId(long leaveTypesId);

	/**
	 * Returns the leave types of this leave types.
	 *
	 * @return the leave types of this leave types
	 */
	public String getLeaveTypes();

	/**
	 * Returns the localized leave types of this leave types in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized leave types of this leave types
	 */
	@AutoEscape
	public String getLeaveTypes(Locale locale);

	/**
	 * Returns the localized leave types of this leave types in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized leave types of this leave types. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getLeaveTypes(Locale locale, boolean useDefault);

	/**
	 * Returns the localized leave types of this leave types in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized leave types of this leave types
	 */
	@AutoEscape
	public String getLeaveTypes(String languageId);

	/**
	 * Returns the localized leave types of this leave types in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized leave types of this leave types
	 */
	@AutoEscape
	public String getLeaveTypes(String languageId, boolean useDefault);

	@AutoEscape
	public String getLeaveTypesCurrentLanguageId();

	@AutoEscape
	public String getLeaveTypesCurrentValue();

	/**
	 * Returns a map of the locales and localized leave typeses of this leave types.
	 *
	 * @return the locales and localized leave typeses of this leave types
	 */
	public Map<Locale, String> getLeaveTypesMap();

	/**
	 * Sets the leave types of this leave types.
	 *
	 * @param leaveTypes the leave types of this leave types
	 */
	public void setLeaveTypes(String leaveTypes);

	/**
	 * Sets the localized leave types of this leave types in the language.
	 *
	 * @param leaveTypes the localized leave types of this leave types
	 * @param locale the locale of the language
	 */
	public void setLeaveTypes(String leaveTypes, Locale locale);

	/**
	 * Sets the localized leave types of this leave types in the language, and sets the default locale.
	 *
	 * @param leaveTypes the localized leave types of this leave types
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setLeaveTypes(
		String leaveTypes, Locale locale, Locale defaultLocale);

	public void setLeaveTypesCurrentLanguageId(String languageId);

	/**
	 * Sets the localized leave typeses of this leave types from the map of locales and localized leave typeses.
	 *
	 * @param leaveTypesMap the locales and localized leave typeses of this leave types
	 */
	public void setLeaveTypesMap(Map<Locale, String> leaveTypesMap);

	/**
	 * Sets the localized leave typeses of this leave types from the map of locales and localized leave typeses, and sets the default locale.
	 *
	 * @param leaveTypesMap the locales and localized leave typeses of this leave types
	 * @param defaultLocale the default locale
	 */
	public void setLeaveTypesMap(
		Map<Locale, String> leaveTypesMap, Locale defaultLocale);

	/**
	 * Returns the leave code of this leave types.
	 *
	 * @return the leave code of this leave types
	 */
	public String getLeaveCode();

	/**
	 * Returns the localized leave code of this leave types in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized leave code of this leave types
	 */
	@AutoEscape
	public String getLeaveCode(Locale locale);

	/**
	 * Returns the localized leave code of this leave types in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized leave code of this leave types. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getLeaveCode(Locale locale, boolean useDefault);

	/**
	 * Returns the localized leave code of this leave types in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized leave code of this leave types
	 */
	@AutoEscape
	public String getLeaveCode(String languageId);

	/**
	 * Returns the localized leave code of this leave types in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized leave code of this leave types
	 */
	@AutoEscape
	public String getLeaveCode(String languageId, boolean useDefault);

	@AutoEscape
	public String getLeaveCodeCurrentLanguageId();

	@AutoEscape
	public String getLeaveCodeCurrentValue();

	/**
	 * Returns a map of the locales and localized leave codes of this leave types.
	 *
	 * @return the locales and localized leave codes of this leave types
	 */
	public Map<Locale, String> getLeaveCodeMap();

	/**
	 * Sets the leave code of this leave types.
	 *
	 * @param leaveCode the leave code of this leave types
	 */
	public void setLeaveCode(String leaveCode);

	/**
	 * Sets the localized leave code of this leave types in the language.
	 *
	 * @param leaveCode the localized leave code of this leave types
	 * @param locale the locale of the language
	 */
	public void setLeaveCode(String leaveCode, Locale locale);

	/**
	 * Sets the localized leave code of this leave types in the language, and sets the default locale.
	 *
	 * @param leaveCode the localized leave code of this leave types
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setLeaveCode(
		String leaveCode, Locale locale, Locale defaultLocale);

	public void setLeaveCodeCurrentLanguageId(String languageId);

	/**
	 * Sets the localized leave codes of this leave types from the map of locales and localized leave codes.
	 *
	 * @param leaveCodeMap the locales and localized leave codes of this leave types
	 */
	public void setLeaveCodeMap(Map<Locale, String> leaveCodeMap);

	/**
	 * Sets the localized leave codes of this leave types from the map of locales and localized leave codes, and sets the default locale.
	 *
	 * @param leaveCodeMap the locales and localized leave codes of this leave types
	 * @param defaultLocale the default locale
	 */
	public void setLeaveCodeMap(
		Map<Locale, String> leaveCodeMap, Locale defaultLocale);

	/**
	 * Returns the group ID of this leave types.
	 *
	 * @return the group ID of this leave types
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this leave types.
	 *
	 * @param groupId the group ID of this leave types
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leave types.
	 *
	 * @return the company ID of this leave types
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave types.
	 *
	 * @param companyId the company ID of this leave types
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this leave types.
	 *
	 * @return the create date of this leave types
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave types.
	 *
	 * @param createDate the create date of this leave types
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this leave types.
	 *
	 * @return the created by of this leave types
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this leave types.
	 *
	 * @param createdBy the created by of this leave types
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this leave types.
	 *
	 * @return the modified date of this leave types
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave types.
	 *
	 * @param modifiedDate the modified date of this leave types
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this leave types.
	 *
	 * @return the modified by of this leave types
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this leave types.
	 *
	 * @param modifiedBy the modified by of this leave types
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public LeaveTypes cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}