/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LeaveAnnualMaxTrainee service. Represents a row in the &quot;leave_annual_max_trainee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.LeaveAnnualMaxTraineeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.LeaveAnnualMaxTraineeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveAnnualMaxTrainee
 * @generated
 */
@ProviderType
public interface LeaveAnnualMaxTraineeModel
	extends BaseModel<LeaveAnnualMaxTrainee>, LocalizedModel, ShardedModel,
			StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave annual max trainee model instance should use the {@link LeaveAnnualMaxTrainee} interface instead.
	 */

	/**
	 * Returns the primary key of this leave annual max trainee.
	 *
	 * @return the primary key of this leave annual max trainee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave annual max trainee.
	 *
	 * @param primaryKey the primary key of this leave annual max trainee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave annual max trainee.
	 *
	 * @return the uuid of this leave annual max trainee
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave annual max trainee.
	 *
	 * @param uuid the uuid of this leave annual max trainee
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the leave annual max trainee ID of this leave annual max trainee.
	 *
	 * @return the leave annual max trainee ID of this leave annual max trainee
	 */
	public long getLeaveAnnualMaxTraineeId();

	/**
	 * Sets the leave annual max trainee ID of this leave annual max trainee.
	 *
	 * @param leaveAnnualMaxTraineeId the leave annual max trainee ID of this leave annual max trainee
	 */
	public void setLeaveAnnualMaxTraineeId(long leaveAnnualMaxTraineeId);

	/**
	 * Returns the leave annual rule ID of this leave annual max trainee.
	 *
	 * @return the leave annual rule ID of this leave annual max trainee
	 */
	public long getLeaveAnnualRuleId();

	/**
	 * Sets the leave annual rule ID of this leave annual max trainee.
	 *
	 * @param leaveAnnualRuleId the leave annual rule ID of this leave annual max trainee
	 */
	public void setLeaveAnnualRuleId(long leaveAnnualRuleId);

	/**
	 * Returns the training level of this leave annual max trainee.
	 *
	 * @return the training level of this leave annual max trainee
	 */
	public String getTrainingLevel();

	/**
	 * Returns the localized training level of this leave annual max trainee in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized training level of this leave annual max trainee
	 */
	@AutoEscape
	public String getTrainingLevel(Locale locale);

	/**
	 * Returns the localized training level of this leave annual max trainee in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized training level of this leave annual max trainee. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTrainingLevel(Locale locale, boolean useDefault);

	/**
	 * Returns the localized training level of this leave annual max trainee in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized training level of this leave annual max trainee
	 */
	@AutoEscape
	public String getTrainingLevel(String languageId);

	/**
	 * Returns the localized training level of this leave annual max trainee in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized training level of this leave annual max trainee
	 */
	@AutoEscape
	public String getTrainingLevel(String languageId, boolean useDefault);

	@AutoEscape
	public String getTrainingLevelCurrentLanguageId();

	@AutoEscape
	public String getTrainingLevelCurrentValue();

	/**
	 * Returns a map of the locales and localized training levels of this leave annual max trainee.
	 *
	 * @return the locales and localized training levels of this leave annual max trainee
	 */
	public Map<Locale, String> getTrainingLevelMap();

	/**
	 * Sets the training level of this leave annual max trainee.
	 *
	 * @param trainingLevel the training level of this leave annual max trainee
	 */
	public void setTrainingLevel(String trainingLevel);

	/**
	 * Sets the localized training level of this leave annual max trainee in the language.
	 *
	 * @param trainingLevel the localized training level of this leave annual max trainee
	 * @param locale the locale of the language
	 */
	public void setTrainingLevel(String trainingLevel, Locale locale);

	/**
	 * Sets the localized training level of this leave annual max trainee in the language, and sets the default locale.
	 *
	 * @param trainingLevel the localized training level of this leave annual max trainee
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTrainingLevel(
		String trainingLevel, Locale locale, Locale defaultLocale);

	public void setTrainingLevelCurrentLanguageId(String languageId);

	/**
	 * Sets the localized training levels of this leave annual max trainee from the map of locales and localized training levels.
	 *
	 * @param trainingLevelMap the locales and localized training levels of this leave annual max trainee
	 */
	public void setTrainingLevelMap(Map<Locale, String> trainingLevelMap);

	/**
	 * Sets the localized training levels of this leave annual max trainee from the map of locales and localized training levels, and sets the default locale.
	 *
	 * @param trainingLevelMap the locales and localized training levels of this leave annual max trainee
	 * @param defaultLocale the default locale
	 */
	public void setTrainingLevelMap(
		Map<Locale, String> trainingLevelMap, Locale defaultLocale);

	/**
	 * Returns the block of this leave annual max trainee.
	 *
	 * @return the block of this leave annual max trainee
	 */
	public int getBlock();

	/**
	 * Sets the block of this leave annual max trainee.
	 *
	 * @param block the block of this leave annual max trainee
	 */
	public void setBlock(int block);

	/**
	 * Returns the week of this leave annual max trainee.
	 *
	 * @return the week of this leave annual max trainee
	 */
	public int getWeek();

	/**
	 * Sets the week of this leave annual max trainee.
	 *
	 * @param week the week of this leave annual max trainee
	 */
	public void setWeek(int week);

	/**
	 * Returns the max trainee apply leave of this leave annual max trainee.
	 *
	 * @return the max trainee apply leave of this leave annual max trainee
	 */
	public int getMaxTraineeApplyLeave();

	/**
	 * Sets the max trainee apply leave of this leave annual max trainee.
	 *
	 * @param maxTraineeApplyLeave the max trainee apply leave of this leave annual max trainee
	 */
	public void setMaxTraineeApplyLeave(int maxTraineeApplyLeave);

	/**
	 * Returns the no of trainee taken leave of this leave annual max trainee.
	 *
	 * @return the no of trainee taken leave of this leave annual max trainee
	 */
	public int getNoOfTraineeTakenLeave();

	/**
	 * Sets the no of trainee taken leave of this leave annual max trainee.
	 *
	 * @param noOfTraineeTakenLeave the no of trainee taken leave of this leave annual max trainee
	 */
	public void setNoOfTraineeTakenLeave(int noOfTraineeTakenLeave);

	/**
	 * Returns the group ID of this leave annual max trainee.
	 *
	 * @return the group ID of this leave annual max trainee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this leave annual max trainee.
	 *
	 * @param groupId the group ID of this leave annual max trainee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leave annual max trainee.
	 *
	 * @return the company ID of this leave annual max trainee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave annual max trainee.
	 *
	 * @param companyId the company ID of this leave annual max trainee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this leave annual max trainee.
	 *
	 * @return the create date of this leave annual max trainee
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave annual max trainee.
	 *
	 * @param createDate the create date of this leave annual max trainee
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this leave annual max trainee.
	 *
	 * @return the created by of this leave annual max trainee
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this leave annual max trainee.
	 *
	 * @param createdBy the created by of this leave annual max trainee
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this leave annual max trainee.
	 *
	 * @return the modified date of this leave annual max trainee
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave annual max trainee.
	 *
	 * @param modifiedDate the modified date of this leave annual max trainee
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this leave annual max trainee.
	 *
	 * @return the modified by of this leave annual max trainee
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this leave annual max trainee.
	 *
	 * @param modifiedBy the modified by of this leave annual max trainee
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public LeaveAnnualMaxTrainee cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}