/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ParticipationTypeMaster service. Represents a row in the &quot;participation_type_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.ParticipationTypeMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.ParticipationTypeMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParticipationTypeMaster
 * @generated
 */
@ProviderType
public interface ParticipationTypeMasterModel
	extends BaseModel<ParticipationTypeMaster>, LocalizedModel, ShardedModel,
			StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a participation type master model instance should use the {@link ParticipationTypeMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this participation type master.
	 *
	 * @return the primary key of this participation type master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this participation type master.
	 *
	 * @param primaryKey the primary key of this participation type master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this participation type master.
	 *
	 * @return the uuid of this participation type master
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this participation type master.
	 *
	 * @param uuid the uuid of this participation type master
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the participation type master ID of this participation type master.
	 *
	 * @return the participation type master ID of this participation type master
	 */
	public long getParticipationTypeMasterId();

	/**
	 * Sets the participation type master ID of this participation type master.
	 *
	 * @param participationTypeMasterId the participation type master ID of this participation type master
	 */
	public void setParticipationTypeMasterId(long participationTypeMasterId);

	/**
	 * Returns the program duration ID of this participation type master.
	 *
	 * @return the program duration ID of this participation type master
	 */
	public long getProgramDurationId();

	/**
	 * Sets the program duration ID of this participation type master.
	 *
	 * @param programDurationId the program duration ID of this participation type master
	 */
	public void setProgramDurationId(long programDurationId);

	/**
	 * Returns the group ID of this participation type master.
	 *
	 * @return the group ID of this participation type master
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this participation type master.
	 *
	 * @param groupId the group ID of this participation type master
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this participation type master.
	 *
	 * @return the company ID of this participation type master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this participation type master.
	 *
	 * @param companyId the company ID of this participation type master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this participation type master.
	 *
	 * @return the create date of this participation type master
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this participation type master.
	 *
	 * @param createDate the create date of this participation type master
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this participation type master.
	 *
	 * @return the created by of this participation type master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this participation type master.
	 *
	 * @param createdBy the created by of this participation type master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this participation type master.
	 *
	 * @return the modified date of this participation type master
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this participation type master.
	 *
	 * @param modifiedDate the modified date of this participation type master
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this participation type master.
	 *
	 * @return the modified by of this participation type master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this participation type master.
	 *
	 * @param modifiedBy the modified by of this participation type master
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the participation type name of this participation type master.
	 *
	 * @return the participation type name of this participation type master
	 */
	public String getParticipationTypeName();

	/**
	 * Returns the localized participation type name of this participation type master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized participation type name of this participation type master
	 */
	@AutoEscape
	public String getParticipationTypeName(Locale locale);

	/**
	 * Returns the localized participation type name of this participation type master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized participation type name of this participation type master. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getParticipationTypeName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized participation type name of this participation type master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized participation type name of this participation type master
	 */
	@AutoEscape
	public String getParticipationTypeName(String languageId);

	/**
	 * Returns the localized participation type name of this participation type master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized participation type name of this participation type master
	 */
	@AutoEscape
	public String getParticipationTypeName(
		String languageId, boolean useDefault);

	@AutoEscape
	public String getParticipationTypeNameCurrentLanguageId();

	@AutoEscape
	public String getParticipationTypeNameCurrentValue();

	/**
	 * Returns a map of the locales and localized participation type names of this participation type master.
	 *
	 * @return the locales and localized participation type names of this participation type master
	 */
	public Map<Locale, String> getParticipationTypeNameMap();

	/**
	 * Sets the participation type name of this participation type master.
	 *
	 * @param participationTypeName the participation type name of this participation type master
	 */
	public void setParticipationTypeName(String participationTypeName);

	/**
	 * Sets the localized participation type name of this participation type master in the language.
	 *
	 * @param participationTypeName the localized participation type name of this participation type master
	 * @param locale the locale of the language
	 */
	public void setParticipationTypeName(
		String participationTypeName, Locale locale);

	/**
	 * Sets the localized participation type name of this participation type master in the language, and sets the default locale.
	 *
	 * @param participationTypeName the localized participation type name of this participation type master
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setParticipationTypeName(
		String participationTypeName, Locale locale, Locale defaultLocale);

	public void setParticipationTypeNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized participation type names of this participation type master from the map of locales and localized participation type names.
	 *
	 * @param participationTypeNameMap the locales and localized participation type names of this participation type master
	 */
	public void setParticipationTypeNameMap(
		Map<Locale, String> participationTypeNameMap);

	/**
	 * Sets the localized participation type names of this participation type master from the map of locales and localized participation type names, and sets the default locale.
	 *
	 * @param participationTypeNameMap the locales and localized participation type names of this participation type master
	 * @param defaultLocale the default locale
	 */
	public void setParticipationTypeNameMap(
		Map<Locale, String> participationTypeNameMap, Locale defaultLocale);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public ParticipationTypeMaster cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}