/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProcedureGroupProceduresCPTCodeRel service. Represents a row in the &quot;proceduregroup_procedures_cptcode_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.ProcedureGroupProceduresCPTCodeRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.ProcedureGroupProceduresCPTCodeRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProcedureGroupProceduresCPTCodeRel
 * @generated
 */
@ProviderType
public interface ProcedureGroupProceduresCPTCodeRelModel
	extends BaseModel<ProcedureGroupProceduresCPTCodeRel>, ShardedModel,
			StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a procedure group procedures cpt code rel model instance should use the {@link ProcedureGroupProceduresCPTCodeRel} interface instead.
	 */

	/**
	 * Returns the primary key of this procedure group procedures cpt code rel.
	 *
	 * @return the primary key of this procedure group procedures cpt code rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this procedure group procedures cpt code rel.
	 *
	 * @param primaryKey the primary key of this procedure group procedures cpt code rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this procedure group procedures cpt code rel.
	 *
	 * @return the uuid of this procedure group procedures cpt code rel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this procedure group procedures cpt code rel.
	 *
	 * @param uuid the uuid of this procedure group procedures cpt code rel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the pg procedure cpt code rel ID of this procedure group procedures cpt code rel.
	 *
	 * @return the pg procedure cpt code rel ID of this procedure group procedures cpt code rel
	 */
	public long getPgProcedureCptCodeRelId();

	/**
	 * Sets the pg procedure cpt code rel ID of this procedure group procedures cpt code rel.
	 *
	 * @param pgProcedureCptCodeRelId the pg procedure cpt code rel ID of this procedure group procedures cpt code rel
	 */
	public void setPgProcedureCptCodeRelId(long pgProcedureCptCodeRelId);

	/**
	 * Returns the group ID of this procedure group procedures cpt code rel.
	 *
	 * @return the group ID of this procedure group procedures cpt code rel
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this procedure group procedures cpt code rel.
	 *
	 * @param groupId the group ID of this procedure group procedures cpt code rel
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this procedure group procedures cpt code rel.
	 *
	 * @return the company ID of this procedure group procedures cpt code rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this procedure group procedures cpt code rel.
	 *
	 * @param companyId the company ID of this procedure group procedures cpt code rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this procedure group procedures cpt code rel.
	 *
	 * @return the create date of this procedure group procedures cpt code rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this procedure group procedures cpt code rel.
	 *
	 * @param createDate the create date of this procedure group procedures cpt code rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this procedure group procedures cpt code rel.
	 *
	 * @return the created by of this procedure group procedures cpt code rel
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this procedure group procedures cpt code rel.
	 *
	 * @param createdBy the created by of this procedure group procedures cpt code rel
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this procedure group procedures cpt code rel.
	 *
	 * @return the modified date of this procedure group procedures cpt code rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this procedure group procedures cpt code rel.
	 *
	 * @param modifiedDate the modified date of this procedure group procedures cpt code rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this procedure group procedures cpt code rel.
	 *
	 * @return the modified by of this procedure group procedures cpt code rel
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this procedure group procedures cpt code rel.
	 *
	 * @param modifiedBy the modified by of this procedure group procedures cpt code rel
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the procedure group ID of this procedure group procedures cpt code rel.
	 *
	 * @return the procedure group ID of this procedure group procedures cpt code rel
	 */
	public long getProcedureGroupId();

	/**
	 * Sets the procedure group ID of this procedure group procedures cpt code rel.
	 *
	 * @param procedureGroupId the procedure group ID of this procedure group procedures cpt code rel
	 */
	public void setProcedureGroupId(long procedureGroupId);

	/**
	 * Returns the procedure ID of this procedure group procedures cpt code rel.
	 *
	 * @return the procedure ID of this procedure group procedures cpt code rel
	 */
	public long getProcedureId();

	/**
	 * Sets the procedure ID of this procedure group procedures cpt code rel.
	 *
	 * @param procedureId the procedure ID of this procedure group procedures cpt code rel
	 */
	public void setProcedureId(long procedureId);

	/**
	 * Returns the cpt code ID of this procedure group procedures cpt code rel.
	 *
	 * @return the cpt code ID of this procedure group procedures cpt code rel
	 */
	public long getCptCodeId();

	/**
	 * Sets the cpt code ID of this procedure group procedures cpt code rel.
	 *
	 * @param cptCodeId the cpt code ID of this procedure group procedures cpt code rel
	 */
	public void setCptCodeId(long cptCodeId);

	@Override
	public ProcedureGroupProceduresCPTCodeRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}