/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProcedureGroupMaster service. Represents a row in the &quot;procedure_group_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.ProcedureGroupMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.ProcedureGroupMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProcedureGroupMaster
 * @generated
 */
@ProviderType
public interface ProcedureGroupMasterModel
	extends BaseModel<ProcedureGroupMaster>, LocalizedModel, ShardedModel,
			StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a procedure group master model instance should use the {@link ProcedureGroupMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this procedure group master.
	 *
	 * @return the primary key of this procedure group master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this procedure group master.
	 *
	 * @param primaryKey the primary key of this procedure group master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this procedure group master.
	 *
	 * @return the uuid of this procedure group master
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this procedure group master.
	 *
	 * @param uuid the uuid of this procedure group master
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the procedure group master ID of this procedure group master.
	 *
	 * @return the procedure group master ID of this procedure group master
	 */
	public long getProcedureGroupMasterId();

	/**
	 * Sets the procedure group master ID of this procedure group master.
	 *
	 * @param procedureGroupMasterId the procedure group master ID of this procedure group master
	 */
	public void setProcedureGroupMasterId(long procedureGroupMasterId);

	/**
	 * Returns the group ID of this procedure group master.
	 *
	 * @return the group ID of this procedure group master
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this procedure group master.
	 *
	 * @param groupId the group ID of this procedure group master
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this procedure group master.
	 *
	 * @return the company ID of this procedure group master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this procedure group master.
	 *
	 * @param companyId the company ID of this procedure group master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this procedure group master.
	 *
	 * @return the create date of this procedure group master
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this procedure group master.
	 *
	 * @param createDate the create date of this procedure group master
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this procedure group master.
	 *
	 * @return the created by of this procedure group master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this procedure group master.
	 *
	 * @param createdBy the created by of this procedure group master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this procedure group master.
	 *
	 * @return the modified date of this procedure group master
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this procedure group master.
	 *
	 * @param modifiedDate the modified date of this procedure group master
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this procedure group master.
	 *
	 * @return the modified by of this procedure group master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this procedure group master.
	 *
	 * @param modifiedBy the modified by of this procedure group master
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the procedure group name of this procedure group master.
	 *
	 * @return the procedure group name of this procedure group master
	 */
	public String getProcedureGroupName();

	/**
	 * Returns the localized procedure group name of this procedure group master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized procedure group name of this procedure group master
	 */
	@AutoEscape
	public String getProcedureGroupName(Locale locale);

	/**
	 * Returns the localized procedure group name of this procedure group master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized procedure group name of this procedure group master. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getProcedureGroupName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized procedure group name of this procedure group master in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized procedure group name of this procedure group master
	 */
	@AutoEscape
	public String getProcedureGroupName(String languageId);

	/**
	 * Returns the localized procedure group name of this procedure group master in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized procedure group name of this procedure group master
	 */
	@AutoEscape
	public String getProcedureGroupName(String languageId, boolean useDefault);

	@AutoEscape
	public String getProcedureGroupNameCurrentLanguageId();

	@AutoEscape
	public String getProcedureGroupNameCurrentValue();

	/**
	 * Returns a map of the locales and localized procedure group names of this procedure group master.
	 *
	 * @return the locales and localized procedure group names of this procedure group master
	 */
	public Map<Locale, String> getProcedureGroupNameMap();

	/**
	 * Sets the procedure group name of this procedure group master.
	 *
	 * @param procedureGroupName the procedure group name of this procedure group master
	 */
	public void setProcedureGroupName(String procedureGroupName);

	/**
	 * Sets the localized procedure group name of this procedure group master in the language.
	 *
	 * @param procedureGroupName the localized procedure group name of this procedure group master
	 * @param locale the locale of the language
	 */
	public void setProcedureGroupName(String procedureGroupName, Locale locale);

	/**
	 * Sets the localized procedure group name of this procedure group master in the language, and sets the default locale.
	 *
	 * @param procedureGroupName the localized procedure group name of this procedure group master
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setProcedureGroupName(
		String procedureGroupName, Locale locale, Locale defaultLocale);

	public void setProcedureGroupNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized procedure group names of this procedure group master from the map of locales and localized procedure group names.
	 *
	 * @param procedureGroupNameMap the locales and localized procedure group names of this procedure group master
	 */
	public void setProcedureGroupNameMap(
		Map<Locale, String> procedureGroupNameMap);

	/**
	 * Sets the localized procedure group names of this procedure group master from the map of locales and localized procedure group names, and sets the default locale.
	 *
	 * @param procedureGroupNameMap the locales and localized procedure group names of this procedure group master
	 * @param defaultLocale the default locale
	 */
	public void setProcedureGroupNameMap(
		Map<Locale, String> procedureGroupNameMap, Locale defaultLocale);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public ProcedureGroupMaster cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}