/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProceduregroupProgdurationRel service. Represents a row in the &quot;proceduregroup_progduration_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.ProceduregroupProgdurationRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.ProceduregroupProgdurationRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProceduregroupProgdurationRel
 * @generated
 */
@ProviderType
public interface ProceduregroupProgdurationRelModel
	extends BaseModel<ProceduregroupProgdurationRel>, ShardedModel,
			StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a proceduregroup progduration rel model instance should use the {@link ProceduregroupProgdurationRel} interface instead.
	 */

	/**
	 * Returns the primary key of this proceduregroup progduration rel.
	 *
	 * @return the primary key of this proceduregroup progduration rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this proceduregroup progduration rel.
	 *
	 * @param primaryKey the primary key of this proceduregroup progduration rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this proceduregroup progduration rel.
	 *
	 * @return the uuid of this proceduregroup progduration rel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this proceduregroup progduration rel.
	 *
	 * @param uuid the uuid of this proceduregroup progduration rel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the pg pd rel ID of this proceduregroup progduration rel.
	 *
	 * @return the pg pd rel ID of this proceduregroup progduration rel
	 */
	public long getPgPdRelId();

	/**
	 * Sets the pg pd rel ID of this proceduregroup progduration rel.
	 *
	 * @param pgPdRelId the pg pd rel ID of this proceduregroup progduration rel
	 */
	public void setPgPdRelId(long pgPdRelId);

	/**
	 * Returns the procedure group master ID of this proceduregroup progduration rel.
	 *
	 * @return the procedure group master ID of this proceduregroup progduration rel
	 */
	public long getProcedureGroupMasterId();

	/**
	 * Sets the procedure group master ID of this proceduregroup progduration rel.
	 *
	 * @param procedureGroupMasterId the procedure group master ID of this proceduregroup progduration rel
	 */
	public void setProcedureGroupMasterId(long procedureGroupMasterId);

	/**
	 * Returns the program duration ID of this proceduregroup progduration rel.
	 *
	 * @return the program duration ID of this proceduregroup progduration rel
	 */
	public long getProgramDurationId();

	/**
	 * Sets the program duration ID of this proceduregroup progduration rel.
	 *
	 * @param programDurationId the program duration ID of this proceduregroup progduration rel
	 */
	public void setProgramDurationId(long programDurationId);

	/**
	 * Returns the group ID of this proceduregroup progduration rel.
	 *
	 * @return the group ID of this proceduregroup progduration rel
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this proceduregroup progduration rel.
	 *
	 * @param groupId the group ID of this proceduregroup progduration rel
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this proceduregroup progduration rel.
	 *
	 * @return the company ID of this proceduregroup progduration rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this proceduregroup progduration rel.
	 *
	 * @param companyId the company ID of this proceduregroup progduration rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this proceduregroup progduration rel.
	 *
	 * @return the create date of this proceduregroup progduration rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this proceduregroup progduration rel.
	 *
	 * @param createDate the create date of this proceduregroup progduration rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this proceduregroup progduration rel.
	 *
	 * @return the modified date of this proceduregroup progduration rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this proceduregroup progduration rel.
	 *
	 * @param modifiedDate the modified date of this proceduregroup progduration rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created by of this proceduregroup progduration rel.
	 *
	 * @return the created by of this proceduregroup progduration rel
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this proceduregroup progduration rel.
	 *
	 * @param createdBy the created by of this proceduregroup progduration rel
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this proceduregroup progduration rel.
	 *
	 * @return the modified by of this proceduregroup progduration rel
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this proceduregroup progduration rel.
	 *
	 * @param modifiedBy the modified by of this proceduregroup progduration rel
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public ProceduregroupProgdurationRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}