/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProgramEligibilityDegreeRel service. Represents a row in the &quot;program_eligibility_degree_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.ProgramEligibilityDegreeRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.ProgramEligibilityDegreeRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgramEligibilityDegreeRel
 * @generated
 */
@ProviderType
public interface ProgramEligibilityDegreeRelModel
	extends BaseModel<ProgramEligibilityDegreeRel>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a program eligibility degree rel model instance should use the {@link ProgramEligibilityDegreeRel} interface instead.
	 */

	/**
	 * Returns the primary key of this program eligibility degree rel.
	 *
	 * @return the primary key of this program eligibility degree rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this program eligibility degree rel.
	 *
	 * @param primaryKey the primary key of this program eligibility degree rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this program eligibility degree rel.
	 *
	 * @return the uuid of this program eligibility degree rel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this program eligibility degree rel.
	 *
	 * @param uuid the uuid of this program eligibility degree rel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the program ed ID of this program eligibility degree rel.
	 *
	 * @return the program ed ID of this program eligibility degree rel
	 */
	public long getProgramEdId();

	/**
	 * Sets the program ed ID of this program eligibility degree rel.
	 *
	 * @param programEdId the program ed ID of this program eligibility degree rel
	 */
	public void setProgramEdId(long programEdId);

	/**
	 * Returns the program ID of this program eligibility degree rel.
	 *
	 * @return the program ID of this program eligibility degree rel
	 */
	public long getProgramId();

	/**
	 * Sets the program ID of this program eligibility degree rel.
	 *
	 * @param programId the program ID of this program eligibility degree rel
	 */
	public void setProgramId(long programId);

	/**
	 * Returns the eligibility degree master ID of this program eligibility degree rel.
	 *
	 * @return the eligibility degree master ID of this program eligibility degree rel
	 */
	public long getEligibilityDegreeMasterId();

	/**
	 * Sets the eligibility degree master ID of this program eligibility degree rel.
	 *
	 * @param eligibilityDegreeMasterId the eligibility degree master ID of this program eligibility degree rel
	 */
	public void setEligibilityDegreeMasterId(long eligibilityDegreeMasterId);

	/**
	 * Returns the group ID of this program eligibility degree rel.
	 *
	 * @return the group ID of this program eligibility degree rel
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this program eligibility degree rel.
	 *
	 * @param groupId the group ID of this program eligibility degree rel
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this program eligibility degree rel.
	 *
	 * @return the company ID of this program eligibility degree rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this program eligibility degree rel.
	 *
	 * @param companyId the company ID of this program eligibility degree rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this program eligibility degree rel.
	 *
	 * @return the create date of this program eligibility degree rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this program eligibility degree rel.
	 *
	 * @param createDate the create date of this program eligibility degree rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this program eligibility degree rel.
	 *
	 * @return the modified date of this program eligibility degree rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this program eligibility degree rel.
	 *
	 * @param modifiedDate the modified date of this program eligibility degree rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public ProgramEligibilityDegreeRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}