/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProgdurationRotationTlPgProcedurePtRel service. Represents a row in the &quot;progduration_rotation_tl_pg_procedure_pt_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.ProgdurationRotationTlPgProcedurePtRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.ProgdurationRotationTlPgProcedurePtRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgdurationRotationTlPgProcedurePtRel
 * @generated
 */
@ProviderType
public interface ProgdurationRotationTlPgProcedurePtRelModel
	extends BaseModel<ProgdurationRotationTlPgProcedurePtRel>, ShardedModel,
			StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a progduration rotation tl pg procedure pt rel model instance should use the {@link ProgdurationRotationTlPgProcedurePtRel} interface instead.
	 */

	/**
	 * Returns the primary key of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the primary key of this progduration rotation tl pg procedure pt rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param primaryKey the primary key of this progduration rotation tl pg procedure pt rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the uuid of this progduration rotation tl pg procedure pt rel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param uuid the uuid of this progduration rotation tl pg procedure pt rel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the progduration rotation tl pg procedure pt rel ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the progduration rotation tl pg procedure pt rel ID of this progduration rotation tl pg procedure pt rel
	 */
	public long getProgdurationRotationTlPgProcedurePtRelId();

	/**
	 * Sets the progduration rotation tl pg procedure pt rel ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param progdurationRotationTlPgProcedurePtRelId the progduration rotation tl pg procedure pt rel ID of this progduration rotation tl pg procedure pt rel
	 */
	public void setProgdurationRotationTlPgProcedurePtRelId(
		long progdurationRotationTlPgProcedurePtRelId);

	/**
	 * Returns the program duration ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the program duration ID of this progduration rotation tl pg procedure pt rel
	 */
	public long getProgramDurationId();

	/**
	 * Sets the program duration ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param programDurationId the program duration ID of this progduration rotation tl pg procedure pt rel
	 */
	public void setProgramDurationId(long programDurationId);

	/**
	 * Returns the rotation ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the rotation ID of this progduration rotation tl pg procedure pt rel
	 */
	public long getRotationId();

	/**
	 * Sets the rotation ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param rotationId the rotation ID of this progduration rotation tl pg procedure pt rel
	 */
	public void setRotationId(long rotationId);

	/**
	 * Returns the trainee level ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the trainee level ID of this progduration rotation tl pg procedure pt rel
	 */
	public long getTraineeLevelId();

	/**
	 * Sets the trainee level ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param traineeLevelId the trainee level ID of this progduration rotation tl pg procedure pt rel
	 */
	public void setTraineeLevelId(long traineeLevelId);

	/**
	 * Returns the procedure group ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the procedure group ID of this progduration rotation tl pg procedure pt rel
	 */
	public long getProcedureGroupId();

	/**
	 * Sets the procedure group ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param procedureGroupId the procedure group ID of this progduration rotation tl pg procedure pt rel
	 */
	public void setProcedureGroupId(long procedureGroupId);

	/**
	 * Returns the procedure ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the procedure ID of this progduration rotation tl pg procedure pt rel
	 */
	public long getProcedureId();

	/**
	 * Sets the procedure ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param procedureId the procedure ID of this progduration rotation tl pg procedure pt rel
	 */
	public void setProcedureId(long procedureId);

	/**
	 * Returns the group ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the group ID of this progduration rotation tl pg procedure pt rel
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param groupId the group ID of this progduration rotation tl pg procedure pt rel
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the company ID of this progduration rotation tl pg procedure pt rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param companyId the company ID of this progduration rotation tl pg procedure pt rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the create date of this progduration rotation tl pg procedure pt rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param createDate the create date of this progduration rotation tl pg procedure pt rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the created by of this progduration rotation tl pg procedure pt rel
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param createdBy the created by of this progduration rotation tl pg procedure pt rel
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the modified date of this progduration rotation tl pg procedure pt rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param modifiedDate the modified date of this progduration rotation tl pg procedure pt rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the modified by of this progduration rotation tl pg procedure pt rel
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param modifiedBy the modified by of this progduration rotation tl pg procedure pt rel
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the minimum procedures of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the minimum procedures of this progduration rotation tl pg procedure pt rel
	 */
	public int getMinimumProcedures();

	/**
	 * Sets the minimum procedures of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param minimumProcedures the minimum procedures of this progduration rotation tl pg procedure pt rel
	 */
	public void setMinimumProcedures(int minimumProcedures);

	/**
	 * Returns the traineelevel minimum procedures of this progduration rotation tl pg procedure pt rel.
	 *
	 * @return the traineelevel minimum procedures of this progduration rotation tl pg procedure pt rel
	 */
	public int getTraineelevelMinimumProcedures();

	/**
	 * Sets the traineelevel minimum procedures of this progduration rotation tl pg procedure pt rel.
	 *
	 * @param traineelevelMinimumProcedures the traineelevel minimum procedures of this progduration rotation tl pg procedure pt rel
	 */
	public void setTraineelevelMinimumProcedures(
		int traineelevelMinimumProcedures);

	@Override
	public ProgdurationRotationTlPgProcedurePtRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}