/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProgramDutyRule service. Represents a row in the &quot;program_duty_rule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.ProgramDutyRuleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.ProgramDutyRuleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgramDutyRule
 * @generated
 */
@ProviderType
public interface ProgramDutyRuleModel
	extends BaseModel<ProgramDutyRule>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a program duty rule model instance should use the {@link ProgramDutyRule} interface instead.
	 */

	/**
	 * Returns the primary key of this program duty rule.
	 *
	 * @return the primary key of this program duty rule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this program duty rule.
	 *
	 * @param primaryKey the primary key of this program duty rule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this program duty rule.
	 *
	 * @return the uuid of this program duty rule
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this program duty rule.
	 *
	 * @param uuid the uuid of this program duty rule
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the program duty rule ID of this program duty rule.
	 *
	 * @return the program duty rule ID of this program duty rule
	 */
	public long getProgramDutyRuleId();

	/**
	 * Sets the program duty rule ID of this program duty rule.
	 *
	 * @param programDutyRuleId the program duty rule ID of this program duty rule
	 */
	public void setProgramDutyRuleId(long programDutyRuleId);

	/**
	 * Returns the group ID of this program duty rule.
	 *
	 * @return the group ID of this program duty rule
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this program duty rule.
	 *
	 * @param groupId the group ID of this program duty rule
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this program duty rule.
	 *
	 * @return the company ID of this program duty rule
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this program duty rule.
	 *
	 * @param companyId the company ID of this program duty rule
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this program duty rule.
	 *
	 * @return the create date of this program duty rule
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this program duty rule.
	 *
	 * @param createDate the create date of this program duty rule
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this program duty rule.
	 *
	 * @return the created by of this program duty rule
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this program duty rule.
	 *
	 * @param createdBy the created by of this program duty rule
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this program duty rule.
	 *
	 * @return the modified date of this program duty rule
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this program duty rule.
	 *
	 * @param modifiedDate the modified date of this program duty rule
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this program duty rule.
	 *
	 * @return the modified by of this program duty rule
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this program duty rule.
	 *
	 * @param modifiedBy the modified by of this program duty rule
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the program ID of this program duty rule.
	 *
	 * @return the program ID of this program duty rule
	 */
	public long getProgramId();

	/**
	 * Sets the program ID of this program duty rule.
	 *
	 * @param programId the program ID of this program duty rule
	 */
	public void setProgramId(long programId);

	/**
	 * Returns the duty rule ID of this program duty rule.
	 *
	 * @return the duty rule ID of this program duty rule
	 */
	public long getDutyRuleId();

	/**
	 * Sets the duty rule ID of this program duty rule.
	 *
	 * @param dutyRuleId the duty rule ID of this program duty rule
	 */
	public void setDutyRuleId(long dutyRuleId);

	/**
	 * Returns the cohort ID of this program duty rule.
	 *
	 * @return the cohort ID of this program duty rule
	 */
	public long getCohortId();

	/**
	 * Sets the cohort ID of this program duty rule.
	 *
	 * @param cohortId the cohort ID of this program duty rule
	 */
	public void setCohortId(long cohortId);

	/**
	 * Returns the status of this program duty rule.
	 *
	 * @return the status of this program duty rule
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this program duty rule.
	 *
	 * @param status the status of this program duty rule
	 */
	public void setStatus(String status);

	@Override
	public ProgramDutyRule cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}