/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProgramProgramTypeRel service. Represents a row in the &quot;program_programtype_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.ProgramProgramTypeRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.ProgramProgramTypeRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgramProgramTypeRel
 * @generated
 */
@ProviderType
public interface ProgramProgramTypeRelModel
	extends BaseModel<ProgramProgramTypeRel>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a program program type rel model instance should use the {@link ProgramProgramTypeRel} interface instead.
	 */

	/**
	 * Returns the primary key of this program program type rel.
	 *
	 * @return the primary key of this program program type rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this program program type rel.
	 *
	 * @param primaryKey the primary key of this program program type rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this program program type rel.
	 *
	 * @return the uuid of this program program type rel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this program program type rel.
	 *
	 * @param uuid the uuid of this program program type rel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the program pt ID of this program program type rel.
	 *
	 * @return the program pt ID of this program program type rel
	 */
	public long getProgramPtId();

	/**
	 * Sets the program pt ID of this program program type rel.
	 *
	 * @param programPtId the program pt ID of this program program type rel
	 */
	public void setProgramPtId(long programPtId);

	/**
	 * Returns the program ID of this program program type rel.
	 *
	 * @return the program ID of this program program type rel
	 */
	public long getProgramId();

	/**
	 * Sets the program ID of this program program type rel.
	 *
	 * @param programId the program ID of this program program type rel
	 */
	public void setProgramId(long programId);

	/**
	 * Returns the program type ID of this program program type rel.
	 *
	 * @return the program type ID of this program program type rel
	 */
	public long getProgramTypeId();

	/**
	 * Sets the program type ID of this program program type rel.
	 *
	 * @param programTypeId the program type ID of this program program type rel
	 */
	public void setProgramTypeId(long programTypeId);

	/**
	 * Returns the group ID of this program program type rel.
	 *
	 * @return the group ID of this program program type rel
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this program program type rel.
	 *
	 * @param groupId the group ID of this program program type rel
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this program program type rel.
	 *
	 * @return the company ID of this program program type rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this program program type rel.
	 *
	 * @param companyId the company ID of this program program type rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this program program type rel.
	 *
	 * @return the create date of this program program type rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this program program type rel.
	 *
	 * @param createDate the create date of this program program type rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this program program type rel.
	 *
	 * @return the modified date of this program program type rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this program program type rel.
	 *
	 * @param modifiedDate the modified date of this program program type rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public ProgramProgramTypeRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}