/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProgramDurationDetails service. Represents a row in the &quot;program_duration_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.ProgramDurationDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.ProgramDurationDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgramDurationDetails
 * @generated
 */
@ProviderType
public interface ProgramDurationDetailsModel
	extends BaseModel<ProgramDurationDetails>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a program duration details model instance should use the {@link ProgramDurationDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this program duration details.
	 *
	 * @return the primary key of this program duration details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this program duration details.
	 *
	 * @param primaryKey the primary key of this program duration details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this program duration details.
	 *
	 * @return the uuid of this program duration details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this program duration details.
	 *
	 * @param uuid the uuid of this program duration details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the prog duration ID of this program duration details.
	 *
	 * @return the prog duration ID of this program duration details
	 */
	public long getProgDurationId();

	/**
	 * Sets the prog duration ID of this program duration details.
	 *
	 * @param progDurationId the prog duration ID of this program duration details
	 */
	public void setProgDurationId(long progDurationId);

	/**
	 * Returns the program ID of this program duration details.
	 *
	 * @return the program ID of this program duration details
	 */
	public long getProgramId();

	/**
	 * Sets the program ID of this program duration details.
	 *
	 * @param programId the program ID of this program duration details
	 */
	public void setProgramId(long programId);

	/**
	 * Returns the group ID of this program duration details.
	 *
	 * @return the group ID of this program duration details
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this program duration details.
	 *
	 * @param groupId the group ID of this program duration details
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this program duration details.
	 *
	 * @return the company ID of this program duration details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this program duration details.
	 *
	 * @param companyId the company ID of this program duration details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this program duration details.
	 *
	 * @return the create date of this program duration details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this program duration details.
	 *
	 * @param createDate the create date of this program duration details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this program duration details.
	 *
	 * @return the modified date of this program duration details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this program duration details.
	 *
	 * @param modifiedDate the modified date of this program duration details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ay applicable form of this program duration details.
	 *
	 * @return the ay applicable form of this program duration details
	 */
	@AutoEscape
	public String getAyApplicableForm();

	/**
	 * Sets the ay applicable form of this program duration details.
	 *
	 * @param ayApplicableForm the ay applicable form of this program duration details
	 */
	public void setAyApplicableForm(String ayApplicableForm);

	/**
	 * Returns the no of blocks of this program duration details.
	 *
	 * @return the no of blocks of this program duration details
	 */
	public int getNoOfBlocks();

	/**
	 * Sets the no of blocks of this program duration details.
	 *
	 * @param noOfBlocks the no of blocks of this program duration details
	 */
	public void setNoOfBlocks(int noOfBlocks);

	@Override
	public ProgramDurationDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}