/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TraineeProgdurationTraineelevelDetails service. Represents a row in the &quot;trainee_progduration_traineelevel_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.TraineeProgdurationTraineelevelDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.TraineeProgdurationTraineelevelDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TraineeProgdurationTraineelevelDetails
 * @generated
 */
@ProviderType
public interface TraineeProgdurationTraineelevelDetailsModel
	extends BaseModel<TraineeProgdurationTraineelevelDetails>, ShardedModel,
			StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trainee progduration traineelevel details model instance should use the {@link TraineeProgdurationTraineelevelDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this trainee progduration traineelevel details.
	 *
	 * @return the primary key of this trainee progduration traineelevel details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trainee progduration traineelevel details.
	 *
	 * @param primaryKey the primary key of this trainee progduration traineelevel details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this trainee progduration traineelevel details.
	 *
	 * @return the uuid of this trainee progduration traineelevel details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this trainee progduration traineelevel details.
	 *
	 * @param uuid the uuid of this trainee progduration traineelevel details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the trainee pd tl er details ID of this trainee progduration traineelevel details.
	 *
	 * @return the trainee pd tl er details ID of this trainee progduration traineelevel details
	 */
	public long getTraineePdTlErDetailsId();

	/**
	 * Sets the trainee pd tl er details ID of this trainee progduration traineelevel details.
	 *
	 * @param traineePdTlErDetailsId the trainee pd tl er details ID of this trainee progduration traineelevel details
	 */
	public void setTraineePdTlErDetailsId(long traineePdTlErDetailsId);

	/**
	 * Returns the trainee ID of this trainee progduration traineelevel details.
	 *
	 * @return the trainee ID of this trainee progduration traineelevel details
	 */
	public long getTraineeId();

	/**
	 * Sets the trainee ID of this trainee progduration traineelevel details.
	 *
	 * @param traineeId the trainee ID of this trainee progduration traineelevel details
	 */
	public void setTraineeId(long traineeId);

	/**
	 * Returns the program duration ID of this trainee progduration traineelevel details.
	 *
	 * @return the program duration ID of this trainee progduration traineelevel details
	 */
	public long getProgramDurationId();

	/**
	 * Sets the program duration ID of this trainee progduration traineelevel details.
	 *
	 * @param programDurationId the program duration ID of this trainee progduration traineelevel details
	 */
	public void setProgramDurationId(long programDurationId);

	/**
	 * Returns the trainee level ID of this trainee progduration traineelevel details.
	 *
	 * @return the trainee level ID of this trainee progduration traineelevel details
	 */
	public long getTraineeLevelId();

	/**
	 * Sets the trainee level ID of this trainee progduration traineelevel details.
	 *
	 * @param traineeLevelId the trainee level ID of this trainee progduration traineelevel details
	 */
	public void setTraineeLevelId(long traineeLevelId);

	/**
	 * Returns the group ID of this trainee progduration traineelevel details.
	 *
	 * @return the group ID of this trainee progduration traineelevel details
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this trainee progduration traineelevel details.
	 *
	 * @param groupId the group ID of this trainee progduration traineelevel details
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this trainee progduration traineelevel details.
	 *
	 * @return the company ID of this trainee progduration traineelevel details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this trainee progduration traineelevel details.
	 *
	 * @param companyId the company ID of this trainee progduration traineelevel details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this trainee progduration traineelevel details.
	 *
	 * @return the create date of this trainee progduration traineelevel details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this trainee progduration traineelevel details.
	 *
	 * @param createDate the create date of this trainee progduration traineelevel details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this trainee progduration traineelevel details.
	 *
	 * @return the created by of this trainee progduration traineelevel details
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this trainee progduration traineelevel details.
	 *
	 * @param createdBy the created by of this trainee progduration traineelevel details
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this trainee progduration traineelevel details.
	 *
	 * @return the modified date of this trainee progduration traineelevel details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this trainee progduration traineelevel details.
	 *
	 * @param modifiedDate the modified date of this trainee progduration traineelevel details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this trainee progduration traineelevel details.
	 *
	 * @return the modified by of this trainee progduration traineelevel details
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this trainee progduration traineelevel details.
	 *
	 * @param modifiedBy the modified by of this trainee progduration traineelevel details
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public TraineeProgdurationTraineelevelDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}