/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the VisitTypeProgDurationRel service. Represents a row in the &quot;visit_type_prog_duration_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.tms.model.impl.VisitTypeProgDurationRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.tms.model.impl.VisitTypeProgDurationRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VisitTypeProgDurationRel
 * @generated
 */
@ProviderType
public interface VisitTypeProgDurationRelModel
	extends BaseModel<VisitTypeProgDurationRel>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a visit type prog duration rel model instance should use the {@link VisitTypeProgDurationRel} interface instead.
	 */

	/**
	 * Returns the primary key of this visit type prog duration rel.
	 *
	 * @return the primary key of this visit type prog duration rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this visit type prog duration rel.
	 *
	 * @param primaryKey the primary key of this visit type prog duration rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this visit type prog duration rel.
	 *
	 * @return the uuid of this visit type prog duration rel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this visit type prog duration rel.
	 *
	 * @param uuid the uuid of this visit type prog duration rel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the visit type prog duration rel ID of this visit type prog duration rel.
	 *
	 * @return the visit type prog duration rel ID of this visit type prog duration rel
	 */
	public long getVisitTypeProgDurationRelId();

	/**
	 * Sets the visit type prog duration rel ID of this visit type prog duration rel.
	 *
	 * @param VisitTypeProgDurationRelId the visit type prog duration rel ID of this visit type prog duration rel
	 */
	public void setVisitTypeProgDurationRelId(long VisitTypeProgDurationRelId);

	/**
	 * Returns the visit type master ID of this visit type prog duration rel.
	 *
	 * @return the visit type master ID of this visit type prog duration rel
	 */
	public long getVisitTypeMasterId();

	/**
	 * Sets the visit type master ID of this visit type prog duration rel.
	 *
	 * @param visitTypeMasterId the visit type master ID of this visit type prog duration rel
	 */
	public void setVisitTypeMasterId(long visitTypeMasterId);

	/**
	 * Returns the program duration ID of this visit type prog duration rel.
	 *
	 * @return the program duration ID of this visit type prog duration rel
	 */
	public long getProgramDurationId();

	/**
	 * Sets the program duration ID of this visit type prog duration rel.
	 *
	 * @param programDurationId the program duration ID of this visit type prog duration rel
	 */
	public void setProgramDurationId(long programDurationId);

	/**
	 * Returns the group ID of this visit type prog duration rel.
	 *
	 * @return the group ID of this visit type prog duration rel
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this visit type prog duration rel.
	 *
	 * @param groupId the group ID of this visit type prog duration rel
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this visit type prog duration rel.
	 *
	 * @return the company ID of this visit type prog duration rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this visit type prog duration rel.
	 *
	 * @param companyId the company ID of this visit type prog duration rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this visit type prog duration rel.
	 *
	 * @return the create date of this visit type prog duration rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this visit type prog duration rel.
	 *
	 * @param createDate the create date of this visit type prog duration rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this visit type prog duration rel.
	 *
	 * @return the created by of this visit type prog duration rel
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this visit type prog duration rel.
	 *
	 * @param createdBy the created by of this visit type prog duration rel
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this visit type prog duration rel.
	 *
	 * @return the modified date of this visit type prog duration rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this visit type prog duration rel.
	 *
	 * @param modifiedDate the modified date of this visit type prog duration rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this visit type prog duration rel.
	 *
	 * @return the modified by of this visit type prog duration rel
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this visit type prog duration rel.
	 *
	 * @param modifiedBy the modified by of this visit type prog duration rel
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public VisitTypeProgDurationRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}