/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.DutyTypes;
import gov.omsb.tms.model.DutyTypesModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DutyTypes service. Represents a row in the &quot;duty_types_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DutyTypesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DutyTypesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DutyTypesImpl
 * @generated
 */
@JSON(strict = true)
public class DutyTypesModelImpl
	extends BaseModelImpl<DutyTypes> implements DutyTypesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a duty types model instance should use the <code>DutyTypes</code> interface instead.
	 */
	public static final String TABLE_NAME = "duty_types_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"duty_type_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT},
		{"duty_type", Types.VARCHAR}, {"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("duty_type_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("duty_type", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table duty_types_master (uuid_ VARCHAR(75) null,duty_type_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,duty_type VARCHAR(75) null,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table duty_types_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dutyTypes.dutyTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY duty_types_master.duty_type_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DUTYTYPE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DUTYTYPEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DutyTypesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dutyTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDutyTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dutyTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DutyTypes.class;
	}

	@Override
	public String getModelClassName() {
		return DutyTypes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DutyTypes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DutyTypes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DutyTypes, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((DutyTypes)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DutyTypes, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DutyTypes, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DutyTypes)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DutyTypes, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DutyTypes, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<DutyTypes, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DutyTypes, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DutyTypes, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DutyTypes, Object>>();
		Map<String, BiConsumer<DutyTypes, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DutyTypes, ?>>();

		attributeGetterFunctions.put("uuid", DutyTypes::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<DutyTypes, String>)DutyTypes::setUuid);
		attributeGetterFunctions.put("dutyTypeId", DutyTypes::getDutyTypeId);
		attributeSetterBiConsumers.put(
			"dutyTypeId",
			(BiConsumer<DutyTypes, Long>)DutyTypes::setDutyTypeId);
		attributeGetterFunctions.put("groupId", DutyTypes::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<DutyTypes, Long>)DutyTypes::setGroupId);
		attributeGetterFunctions.put("companyId", DutyTypes::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<DutyTypes, Long>)DutyTypes::setCompanyId);
		attributeGetterFunctions.put("createDate", DutyTypes::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DutyTypes, Date>)DutyTypes::setCreateDate);
		attributeGetterFunctions.put("createdBy", DutyTypes::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy", (BiConsumer<DutyTypes, Long>)DutyTypes::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", DutyTypes::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DutyTypes, Date>)DutyTypes::setModifiedDate);
		attributeGetterFunctions.put("modifiedBy", DutyTypes::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<DutyTypes, Long>)DutyTypes::setModifiedBy);
		attributeGetterFunctions.put("dutyType", DutyTypes::getDutyType);
		attributeSetterBiConsumers.put(
			"dutyType", (BiConsumer<DutyTypes, String>)DutyTypes::setDutyType);
		attributeGetterFunctions.put("status", DutyTypes::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<DutyTypes, String>)DutyTypes::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getDutyTypeId() {
		return _dutyTypeId;
	}

	@Override
	public void setDutyTypeId(long dutyTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dutyTypeId = dutyTypeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public String getDutyType() {
		if (_dutyType == null) {
			return "";
		}
		else {
			return _dutyType;
		}
	}

	@Override
	public void setDutyType(String dutyType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dutyType = dutyType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDutyType() {
		return getColumnOriginalValue("duty_type");
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DutyTypes.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DutyTypes.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DutyTypes toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DutyTypes>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DutyTypesImpl dutyTypesImpl = new DutyTypesImpl();

		dutyTypesImpl.setUuid(getUuid());
		dutyTypesImpl.setDutyTypeId(getDutyTypeId());
		dutyTypesImpl.setGroupId(getGroupId());
		dutyTypesImpl.setCompanyId(getCompanyId());
		dutyTypesImpl.setCreateDate(getCreateDate());
		dutyTypesImpl.setCreatedBy(getCreatedBy());
		dutyTypesImpl.setModifiedDate(getModifiedDate());
		dutyTypesImpl.setModifiedBy(getModifiedBy());
		dutyTypesImpl.setDutyType(getDutyType());
		dutyTypesImpl.setStatus(getStatus());

		dutyTypesImpl.resetOriginalValues();

		return dutyTypesImpl;
	}

	@Override
	public DutyTypes cloneWithOriginalValues() {
		DutyTypesImpl dutyTypesImpl = new DutyTypesImpl();

		dutyTypesImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		dutyTypesImpl.setDutyTypeId(
			this.<Long>getColumnOriginalValue("duty_type_id"));
		dutyTypesImpl.setGroupId(this.<Long>getColumnOriginalValue("group_id"));
		dutyTypesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		dutyTypesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		dutyTypesImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		dutyTypesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		dutyTypesImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		dutyTypesImpl.setDutyType(
			this.<String>getColumnOriginalValue("duty_type"));
		dutyTypesImpl.setStatus(this.<String>getColumnOriginalValue("status"));

		return dutyTypesImpl;
	}

	@Override
	public int compareTo(DutyTypes dutyTypes) {
		long primaryKey = dutyTypes.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DutyTypes)) {
			return false;
		}

		DutyTypes dutyTypes = (DutyTypes)object;

		long primaryKey = dutyTypes.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DutyTypes> toCacheModel() {
		DutyTypesCacheModel dutyTypesCacheModel = new DutyTypesCacheModel();

		dutyTypesCacheModel.uuid = getUuid();

		String uuid = dutyTypesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dutyTypesCacheModel.uuid = null;
		}

		dutyTypesCacheModel.dutyTypeId = getDutyTypeId();

		dutyTypesCacheModel.groupId = getGroupId();

		dutyTypesCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			dutyTypesCacheModel.createDate = createDate.getTime();
		}
		else {
			dutyTypesCacheModel.createDate = Long.MIN_VALUE;
		}

		dutyTypesCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dutyTypesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dutyTypesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dutyTypesCacheModel.modifiedBy = getModifiedBy();

		dutyTypesCacheModel.dutyType = getDutyType();

		String dutyType = dutyTypesCacheModel.dutyType;

		if ((dutyType != null) && (dutyType.length() == 0)) {
			dutyTypesCacheModel.dutyType = null;
		}

		dutyTypesCacheModel.status = getStatus();

		String status = dutyTypesCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			dutyTypesCacheModel.status = null;
		}

		return dutyTypesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DutyTypes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DutyTypes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DutyTypes, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DutyTypes)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DutyTypes>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DutyTypes.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _dutyTypeId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private String _dutyType;
	private String _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DutyTypes, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DutyTypes)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("duty_type_id", _dutyTypeId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("duty_type", _dutyType);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("duty_type_id", "dutyTypeId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("duty_type", "dutyType");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("duty_type_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("created_by", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("duty_type", 256L);

		columnBitmasks.put("status", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DutyTypes _escapedModel;

}