/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.EcMemberRequestState;
import gov.omsb.tms.model.EcMemberRequestStateModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EcMemberRequestState service. Represents a row in the &quot;ec_member_request_state&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EcMemberRequestStateModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EcMemberRequestStateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EcMemberRequestStateImpl
 * @generated
 */
@JSON(strict = true)
public class EcMemberRequestStateModelImpl
	extends BaseModelImpl<EcMemberRequestState>
	implements EcMemberRequestStateModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ec member request state model instance should use the <code>EcMemberRequestState</code> interface instead.
	 */
	public static final String TABLE_NAME = "ec_member_request_state";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"ec_member_request_state_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"created_by", Types.BIGINT},
		{"company_id", Types.BIGINT}, {"create_date", Types.TIMESTAMP},
		{"modified_date", Types.TIMESTAMP},
		{"created_by_role_id", Types.BIGINT},
		{"ec_member_request_id", Types.BIGINT},
		{"ec_member_request_status_id", Types.BIGINT},
		{"comments", Types.VARCHAR}, {"is_public", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ec_member_request_state_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by_role_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ec_member_request_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ec_member_request_status_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("comments", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("is_public", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ec_member_request_state (uuid_ VARCHAR(75) null,ec_member_request_state_id LONG not null primary key,group_id LONG,created_by LONG,company_id LONG,create_date DATE null,modified_date DATE null,created_by_role_id LONG,ec_member_request_id LONG,ec_member_request_status_id LONG,comments VARCHAR(75) null,is_public BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ec_member_request_state";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ecMemberRequestState.ecMemberRequestStateId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ec_member_request_state.ec_member_request_state_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ECMEMBERREQUESTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISPUBLIC_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ECMEMBERREQUESTSTATEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EcMemberRequestStateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ecMemberRequestStateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEcMemberRequestStateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ecMemberRequestStateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EcMemberRequestState.class;
	}

	@Override
	public String getModelClassName() {
		return EcMemberRequestState.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EcMemberRequestState, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EcMemberRequestState, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EcMemberRequestState, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EcMemberRequestState)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EcMemberRequestState, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EcMemberRequestState, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EcMemberRequestState)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EcMemberRequestState, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EcMemberRequestState, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EcMemberRequestState, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EcMemberRequestState, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EcMemberRequestState, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EcMemberRequestState, Object>>();
		Map<String, BiConsumer<EcMemberRequestState, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<EcMemberRequestState, ?>>();

		attributeGetterFunctions.put("uuid", EcMemberRequestState::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EcMemberRequestState, String>)
				EcMemberRequestState::setUuid);
		attributeGetterFunctions.put(
			"ecMemberRequestStateId",
			EcMemberRequestState::getEcMemberRequestStateId);
		attributeSetterBiConsumers.put(
			"ecMemberRequestStateId",
			(BiConsumer<EcMemberRequestState, Long>)
				EcMemberRequestState::setEcMemberRequestStateId);
		attributeGetterFunctions.put(
			"groupId", EcMemberRequestState::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EcMemberRequestState, Long>)
				EcMemberRequestState::setGroupId);
		attributeGetterFunctions.put(
			"createdBy", EcMemberRequestState::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<EcMemberRequestState, Long>)
				EcMemberRequestState::setCreatedBy);
		attributeGetterFunctions.put(
			"companyId", EcMemberRequestState::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EcMemberRequestState, Long>)
				EcMemberRequestState::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", EcMemberRequestState::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EcMemberRequestState, Date>)
				EcMemberRequestState::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EcMemberRequestState::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EcMemberRequestState, Date>)
				EcMemberRequestState::setModifiedDate);
		attributeGetterFunctions.put(
			"createdByRoleId", EcMemberRequestState::getCreatedByRoleId);
		attributeSetterBiConsumers.put(
			"createdByRoleId",
			(BiConsumer<EcMemberRequestState, Long>)
				EcMemberRequestState::setCreatedByRoleId);
		attributeGetterFunctions.put(
			"ecMemberRequestId", EcMemberRequestState::getEcMemberRequestId);
		attributeSetterBiConsumers.put(
			"ecMemberRequestId",
			(BiConsumer<EcMemberRequestState, Long>)
				EcMemberRequestState::setEcMemberRequestId);
		attributeGetterFunctions.put(
			"ecMemberRequestStatusId",
			EcMemberRequestState::getEcMemberRequestStatusId);
		attributeSetterBiConsumers.put(
			"ecMemberRequestStatusId",
			(BiConsumer<EcMemberRequestState, Long>)
				EcMemberRequestState::setEcMemberRequestStatusId);
		attributeGetterFunctions.put(
			"comments", EcMemberRequestState::getComments);
		attributeSetterBiConsumers.put(
			"comments",
			(BiConsumer<EcMemberRequestState, String>)
				EcMemberRequestState::setComments);
		attributeGetterFunctions.put(
			"isPublic", EcMemberRequestState::getIsPublic);
		attributeSetterBiConsumers.put(
			"isPublic",
			(BiConsumer<EcMemberRequestState, Boolean>)
				EcMemberRequestState::setIsPublic);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEcMemberRequestStateId() {
		return _ecMemberRequestStateId;
	}

	@Override
	public void setEcMemberRequestStateId(long ecMemberRequestStateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ecMemberRequestStateId = ecMemberRequestStateId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatedByRoleId() {
		return _createdByRoleId;
	}

	@Override
	public void setCreatedByRoleId(long createdByRoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdByRoleId = createdByRoleId;
	}

	@JSON
	@Override
	public long getEcMemberRequestId() {
		return _ecMemberRequestId;
	}

	@Override
	public void setEcMemberRequestId(long ecMemberRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ecMemberRequestId = ecMemberRequestId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEcMemberRequestId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("ec_member_request_id"));
	}

	@JSON
	@Override
	public long getEcMemberRequestStatusId() {
		return _ecMemberRequestStatusId;
	}

	@Override
	public void setEcMemberRequestStatusId(long ecMemberRequestStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ecMemberRequestStatusId = ecMemberRequestStatusId;
	}

	@JSON
	@Override
	public String getComments() {
		if (_comments == null) {
			return "";
		}
		else {
			return _comments;
		}
	}

	@Override
	public void setComments(String comments) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comments = comments;
	}

	@JSON
	@Override
	public boolean getIsPublic() {
		return _isPublic;
	}

	@JSON
	@Override
	public boolean isIsPublic() {
		return _isPublic;
	}

	@Override
	public void setIsPublic(boolean isPublic) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isPublic = isPublic;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsPublic() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("is_public"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EcMemberRequestState.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EcMemberRequestState.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EcMemberRequestState toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EcMemberRequestState>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EcMemberRequestStateImpl ecMemberRequestStateImpl =
			new EcMemberRequestStateImpl();

		ecMemberRequestStateImpl.setUuid(getUuid());
		ecMemberRequestStateImpl.setEcMemberRequestStateId(
			getEcMemberRequestStateId());
		ecMemberRequestStateImpl.setGroupId(getGroupId());
		ecMemberRequestStateImpl.setCreatedBy(getCreatedBy());
		ecMemberRequestStateImpl.setCompanyId(getCompanyId());
		ecMemberRequestStateImpl.setCreateDate(getCreateDate());
		ecMemberRequestStateImpl.setModifiedDate(getModifiedDate());
		ecMemberRequestStateImpl.setCreatedByRoleId(getCreatedByRoleId());
		ecMemberRequestStateImpl.setEcMemberRequestId(getEcMemberRequestId());
		ecMemberRequestStateImpl.setEcMemberRequestStatusId(
			getEcMemberRequestStatusId());
		ecMemberRequestStateImpl.setComments(getComments());
		ecMemberRequestStateImpl.setIsPublic(isIsPublic());

		ecMemberRequestStateImpl.resetOriginalValues();

		return ecMemberRequestStateImpl;
	}

	@Override
	public EcMemberRequestState cloneWithOriginalValues() {
		EcMemberRequestStateImpl ecMemberRequestStateImpl =
			new EcMemberRequestStateImpl();

		ecMemberRequestStateImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		ecMemberRequestStateImpl.setEcMemberRequestStateId(
			this.<Long>getColumnOriginalValue("ec_member_request_state_id"));
		ecMemberRequestStateImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		ecMemberRequestStateImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		ecMemberRequestStateImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		ecMemberRequestStateImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		ecMemberRequestStateImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		ecMemberRequestStateImpl.setCreatedByRoleId(
			this.<Long>getColumnOriginalValue("created_by_role_id"));
		ecMemberRequestStateImpl.setEcMemberRequestId(
			this.<Long>getColumnOriginalValue("ec_member_request_id"));
		ecMemberRequestStateImpl.setEcMemberRequestStatusId(
			this.<Long>getColumnOriginalValue("ec_member_request_status_id"));
		ecMemberRequestStateImpl.setComments(
			this.<String>getColumnOriginalValue("comments"));
		ecMemberRequestStateImpl.setIsPublic(
			this.<Boolean>getColumnOriginalValue("is_public"));

		return ecMemberRequestStateImpl;
	}

	@Override
	public int compareTo(EcMemberRequestState ecMemberRequestState) {
		long primaryKey = ecMemberRequestState.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EcMemberRequestState)) {
			return false;
		}

		EcMemberRequestState ecMemberRequestState =
			(EcMemberRequestState)object;

		long primaryKey = ecMemberRequestState.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EcMemberRequestState> toCacheModel() {
		EcMemberRequestStateCacheModel ecMemberRequestStateCacheModel =
			new EcMemberRequestStateCacheModel();

		ecMemberRequestStateCacheModel.uuid = getUuid();

		String uuid = ecMemberRequestStateCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ecMemberRequestStateCacheModel.uuid = null;
		}

		ecMemberRequestStateCacheModel.ecMemberRequestStateId =
			getEcMemberRequestStateId();

		ecMemberRequestStateCacheModel.groupId = getGroupId();

		ecMemberRequestStateCacheModel.createdBy = getCreatedBy();

		ecMemberRequestStateCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			ecMemberRequestStateCacheModel.createDate = createDate.getTime();
		}
		else {
			ecMemberRequestStateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ecMemberRequestStateCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			ecMemberRequestStateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ecMemberRequestStateCacheModel.createdByRoleId = getCreatedByRoleId();

		ecMemberRequestStateCacheModel.ecMemberRequestId =
			getEcMemberRequestId();

		ecMemberRequestStateCacheModel.ecMemberRequestStatusId =
			getEcMemberRequestStatusId();

		ecMemberRequestStateCacheModel.comments = getComments();

		String comments = ecMemberRequestStateCacheModel.comments;

		if ((comments != null) && (comments.length() == 0)) {
			ecMemberRequestStateCacheModel.comments = null;
		}

		ecMemberRequestStateCacheModel.isPublic = isIsPublic();

		return ecMemberRequestStateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EcMemberRequestState, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EcMemberRequestState, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EcMemberRequestState, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EcMemberRequestState)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EcMemberRequestState>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EcMemberRequestState.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _ecMemberRequestStateId;
	private long _groupId;
	private long _createdBy;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdByRoleId;
	private long _ecMemberRequestId;
	private long _ecMemberRequestStatusId;
	private String _comments;
	private boolean _isPublic;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EcMemberRequestState, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EcMemberRequestState)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"ec_member_request_state_id", _ecMemberRequestStateId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("created_by_role_id", _createdByRoleId);
		_columnOriginalValues.put("ec_member_request_id", _ecMemberRequestId);
		_columnOriginalValues.put(
			"ec_member_request_status_id", _ecMemberRequestStatusId);
		_columnOriginalValues.put("comments", _comments);
		_columnOriginalValues.put("is_public", _isPublic);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"ec_member_request_state_id", "ecMemberRequestStateId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("created_by_role_id", "createdByRoleId");
		attributeNames.put("ec_member_request_id", "ecMemberRequestId");
		attributeNames.put(
			"ec_member_request_status_id", "ecMemberRequestStatusId");
		attributeNames.put("is_public", "isPublic");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("ec_member_request_state_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("created_by", 8L);

		columnBitmasks.put("company_id", 16L);

		columnBitmasks.put("create_date", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("created_by_role_id", 128L);

		columnBitmasks.put("ec_member_request_id", 256L);

		columnBitmasks.put("ec_member_request_status_id", 512L);

		columnBitmasks.put("comments", 1024L);

		columnBitmasks.put("is_public", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EcMemberRequestState _escapedModel;

}