/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.FacultyBankDetails;
import gov.omsb.tms.model.FacultyBankDetailsModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FacultyBankDetails service. Represents a row in the &quot;faculty_bank_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FacultyBankDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacultyBankDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FacultyBankDetailsImpl
 * @generated
 */
@JSON(strict = true)
public class FacultyBankDetailsModelImpl
	extends BaseModelImpl<FacultyBankDetails>
	implements FacultyBankDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faculty bank details model instance should use the <code>FacultyBankDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "faculty_bank_details";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"faculty_bank_details_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"modified_date", Types.TIMESTAMP},
		{"faculty_request_id", Types.BIGINT}, {"bank_name", Types.VARCHAR},
		{"account_no", Types.VARCHAR}, {"bank_branch", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("faculty_bank_details_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("faculty_request_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("bank_name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("account_no", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bank_branch", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table faculty_bank_details (uuid_ VARCHAR(75) null,faculty_bank_details_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,modified_date DATE null,faculty_request_id LONG,bank_name STRING null,account_no STRING null,bank_branch STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table faculty_bank_details";

	public static final String ORDER_BY_JPQL =
		" ORDER BY facultyBankDetails.facultyBankDetailsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY faculty_bank_details.faculty_bank_details_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACULTYREQUESTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACULTYBANKDETAILSID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FacultyBankDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _facultyBankDetailsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFacultyBankDetailsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _facultyBankDetailsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FacultyBankDetails.class;
	}

	@Override
	public String getModelClassName() {
		return FacultyBankDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FacultyBankDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FacultyBankDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FacultyBankDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FacultyBankDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FacultyBankDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FacultyBankDetails, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FacultyBankDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FacultyBankDetails, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FacultyBankDetails, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FacultyBankDetails, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FacultyBankDetails, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FacultyBankDetails, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FacultyBankDetails, Object>>();
		Map<String, BiConsumer<FacultyBankDetails, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FacultyBankDetails, ?>>();

		attributeGetterFunctions.put("uuid", FacultyBankDetails::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<FacultyBankDetails, String>)
				FacultyBankDetails::setUuid);
		attributeGetterFunctions.put(
			"facultyBankDetailsId",
			FacultyBankDetails::getFacultyBankDetailsId);
		attributeSetterBiConsumers.put(
			"facultyBankDetailsId",
			(BiConsumer<FacultyBankDetails, Long>)
				FacultyBankDetails::setFacultyBankDetailsId);
		attributeGetterFunctions.put("groupId", FacultyBankDetails::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FacultyBankDetails, Long>)
				FacultyBankDetails::setGroupId);
		attributeGetterFunctions.put(
			"companyId", FacultyBankDetails::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FacultyBankDetails, Long>)
				FacultyBankDetails::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", FacultyBankDetails::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FacultyBankDetails, Date>)
				FacultyBankDetails::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FacultyBankDetails::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FacultyBankDetails, Date>)
				FacultyBankDetails::setModifiedDate);
		attributeGetterFunctions.put(
			"facultyRequestId", FacultyBankDetails::getFacultyRequestId);
		attributeSetterBiConsumers.put(
			"facultyRequestId",
			(BiConsumer<FacultyBankDetails, Long>)
				FacultyBankDetails::setFacultyRequestId);
		attributeGetterFunctions.put(
			"bankName", FacultyBankDetails::getBankName);
		attributeSetterBiConsumers.put(
			"bankName",
			(BiConsumer<FacultyBankDetails, String>)
				FacultyBankDetails::setBankName);
		attributeGetterFunctions.put(
			"accountNo", FacultyBankDetails::getAccountNo);
		attributeSetterBiConsumers.put(
			"accountNo",
			(BiConsumer<FacultyBankDetails, String>)
				FacultyBankDetails::setAccountNo);
		attributeGetterFunctions.put(
			"bankBranch", FacultyBankDetails::getBankBranch);
		attributeSetterBiConsumers.put(
			"bankBranch",
			(BiConsumer<FacultyBankDetails, String>)
				FacultyBankDetails::setBankBranch);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFacultyBankDetailsId() {
		return _facultyBankDetailsId;
	}

	@Override
	public void setFacultyBankDetailsId(long facultyBankDetailsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facultyBankDetailsId = facultyBankDetailsId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getFacultyRequestId() {
		return _facultyRequestId;
	}

	@Override
	public void setFacultyRequestId(long facultyRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facultyRequestId = facultyRequestId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFacultyRequestId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("faculty_request_id"));
	}

	@JSON
	@Override
	public String getBankName() {
		if (_bankName == null) {
			return "";
		}
		else {
			return _bankName;
		}
	}

	@Override
	public String getBankName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBankName(languageId);
	}

	@Override
	public String getBankName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBankName(languageId, useDefault);
	}

	@Override
	public String getBankName(String languageId) {
		return LocalizationUtil.getLocalization(getBankName(), languageId);
	}

	@Override
	public String getBankName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getBankName(), languageId, useDefault);
	}

	@Override
	public String getBankNameCurrentLanguageId() {
		return _bankNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getBankNameCurrentValue() {
		Locale locale = getLocale(_bankNameCurrentLanguageId);

		return getBankName(locale);
	}

	@Override
	public Map<Locale, String> getBankNameMap() {
		return LocalizationUtil.getLocalizationMap(getBankName());
	}

	@Override
	public void setBankName(String bankName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bankName = bankName;
	}

	@Override
	public void setBankName(String bankName, Locale locale) {
		setBankName(bankName, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setBankName(
		String bankName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(bankName)) {
			setBankName(
				LocalizationUtil.updateLocalization(
					getBankName(), "BankName", bankName, languageId,
					defaultLanguageId));
		}
		else {
			setBankName(
				LocalizationUtil.removeLocalization(
					getBankName(), "BankName", languageId));
		}
	}

	@Override
	public void setBankNameCurrentLanguageId(String languageId) {
		_bankNameCurrentLanguageId = languageId;
	}

	@Override
	public void setBankNameMap(Map<Locale, String> bankNameMap) {
		setBankNameMap(bankNameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setBankNameMap(
		Map<Locale, String> bankNameMap, Locale defaultLocale) {

		if (bankNameMap == null) {
			return;
		}

		setBankName(
			LocalizationUtil.updateLocalization(
				bankNameMap, getBankName(), "BankName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getAccountNo() {
		if (_accountNo == null) {
			return "";
		}
		else {
			return _accountNo;
		}
	}

	@Override
	public String getAccountNo(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getAccountNo(languageId);
	}

	@Override
	public String getAccountNo(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getAccountNo(languageId, useDefault);
	}

	@Override
	public String getAccountNo(String languageId) {
		return LocalizationUtil.getLocalization(getAccountNo(), languageId);
	}

	@Override
	public String getAccountNo(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getAccountNo(), languageId, useDefault);
	}

	@Override
	public String getAccountNoCurrentLanguageId() {
		return _accountNoCurrentLanguageId;
	}

	@JSON
	@Override
	public String getAccountNoCurrentValue() {
		Locale locale = getLocale(_accountNoCurrentLanguageId);

		return getAccountNo(locale);
	}

	@Override
	public Map<Locale, String> getAccountNoMap() {
		return LocalizationUtil.getLocalizationMap(getAccountNo());
	}

	@Override
	public void setAccountNo(String accountNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountNo = accountNo;
	}

	@Override
	public void setAccountNo(String accountNo, Locale locale) {
		setAccountNo(accountNo, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setAccountNo(
		String accountNo, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(accountNo)) {
			setAccountNo(
				LocalizationUtil.updateLocalization(
					getAccountNo(), "AccountNo", accountNo, languageId,
					defaultLanguageId));
		}
		else {
			setAccountNo(
				LocalizationUtil.removeLocalization(
					getAccountNo(), "AccountNo", languageId));
		}
	}

	@Override
	public void setAccountNoCurrentLanguageId(String languageId) {
		_accountNoCurrentLanguageId = languageId;
	}

	@Override
	public void setAccountNoMap(Map<Locale, String> accountNoMap) {
		setAccountNoMap(accountNoMap, LocaleUtil.getDefault());
	}

	@Override
	public void setAccountNoMap(
		Map<Locale, String> accountNoMap, Locale defaultLocale) {

		if (accountNoMap == null) {
			return;
		}

		setAccountNo(
			LocalizationUtil.updateLocalization(
				accountNoMap, getAccountNo(), "AccountNo",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getBankBranch() {
		if (_bankBranch == null) {
			return "";
		}
		else {
			return _bankBranch;
		}
	}

	@Override
	public String getBankBranch(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBankBranch(languageId);
	}

	@Override
	public String getBankBranch(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBankBranch(languageId, useDefault);
	}

	@Override
	public String getBankBranch(String languageId) {
		return LocalizationUtil.getLocalization(getBankBranch(), languageId);
	}

	@Override
	public String getBankBranch(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getBankBranch(), languageId, useDefault);
	}

	@Override
	public String getBankBranchCurrentLanguageId() {
		return _bankBranchCurrentLanguageId;
	}

	@JSON
	@Override
	public String getBankBranchCurrentValue() {
		Locale locale = getLocale(_bankBranchCurrentLanguageId);

		return getBankBranch(locale);
	}

	@Override
	public Map<Locale, String> getBankBranchMap() {
		return LocalizationUtil.getLocalizationMap(getBankBranch());
	}

	@Override
	public void setBankBranch(String bankBranch) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bankBranch = bankBranch;
	}

	@Override
	public void setBankBranch(String bankBranch, Locale locale) {
		setBankBranch(bankBranch, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setBankBranch(
		String bankBranch, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(bankBranch)) {
			setBankBranch(
				LocalizationUtil.updateLocalization(
					getBankBranch(), "BankBranch", bankBranch, languageId,
					defaultLanguageId));
		}
		else {
			setBankBranch(
				LocalizationUtil.removeLocalization(
					getBankBranch(), "BankBranch", languageId));
		}
	}

	@Override
	public void setBankBranchCurrentLanguageId(String languageId) {
		_bankBranchCurrentLanguageId = languageId;
	}

	@Override
	public void setBankBranchMap(Map<Locale, String> bankBranchMap) {
		setBankBranchMap(bankBranchMap, LocaleUtil.getDefault());
	}

	@Override
	public void setBankBranchMap(
		Map<Locale, String> bankBranchMap, Locale defaultLocale) {

		if (bankBranchMap == null) {
			return;
		}

		setBankBranch(
			LocalizationUtil.updateLocalization(
				bankBranchMap, getBankBranch(), "BankBranch",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FacultyBankDetails.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FacultyBankDetails.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> bankNameMap = getBankNameMap();

		for (Map.Entry<Locale, String> entry : bankNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> accountNoMap = getAccountNoMap();

		for (Map.Entry<Locale, String> entry : accountNoMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> bankBranchMap = getBankBranchMap();

		for (Map.Entry<Locale, String> entry : bankBranchMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getBankName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			FacultyBankDetails.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String bankName = getBankName(defaultLocale);

		if (Validator.isNull(bankName)) {
			setBankName(getBankName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setBankName(
				getBankName(defaultLocale), defaultLocale, defaultLocale);
		}

		String accountNo = getAccountNo(defaultLocale);

		if (Validator.isNull(accountNo)) {
			setAccountNo(getAccountNo(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setAccountNo(
				getAccountNo(defaultLocale), defaultLocale, defaultLocale);
		}

		String bankBranch = getBankBranch(defaultLocale);

		if (Validator.isNull(bankBranch)) {
			setBankBranch(getBankBranch(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setBankBranch(
				getBankBranch(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public FacultyBankDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FacultyBankDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FacultyBankDetailsImpl facultyBankDetailsImpl =
			new FacultyBankDetailsImpl();

		facultyBankDetailsImpl.setUuid(getUuid());
		facultyBankDetailsImpl.setFacultyBankDetailsId(
			getFacultyBankDetailsId());
		facultyBankDetailsImpl.setGroupId(getGroupId());
		facultyBankDetailsImpl.setCompanyId(getCompanyId());
		facultyBankDetailsImpl.setCreateDate(getCreateDate());
		facultyBankDetailsImpl.setModifiedDate(getModifiedDate());
		facultyBankDetailsImpl.setFacultyRequestId(getFacultyRequestId());
		facultyBankDetailsImpl.setBankName(getBankName());
		facultyBankDetailsImpl.setAccountNo(getAccountNo());
		facultyBankDetailsImpl.setBankBranch(getBankBranch());

		facultyBankDetailsImpl.resetOriginalValues();

		return facultyBankDetailsImpl;
	}

	@Override
	public FacultyBankDetails cloneWithOriginalValues() {
		FacultyBankDetailsImpl facultyBankDetailsImpl =
			new FacultyBankDetailsImpl();

		facultyBankDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		facultyBankDetailsImpl.setFacultyBankDetailsId(
			this.<Long>getColumnOriginalValue("faculty_bank_details_id"));
		facultyBankDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		facultyBankDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		facultyBankDetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		facultyBankDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		facultyBankDetailsImpl.setFacultyRequestId(
			this.<Long>getColumnOriginalValue("faculty_request_id"));
		facultyBankDetailsImpl.setBankName(
			this.<String>getColumnOriginalValue("bank_name"));
		facultyBankDetailsImpl.setAccountNo(
			this.<String>getColumnOriginalValue("account_no"));
		facultyBankDetailsImpl.setBankBranch(
			this.<String>getColumnOriginalValue("bank_branch"));

		return facultyBankDetailsImpl;
	}

	@Override
	public int compareTo(FacultyBankDetails facultyBankDetails) {
		long primaryKey = facultyBankDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FacultyBankDetails)) {
			return false;
		}

		FacultyBankDetails facultyBankDetails = (FacultyBankDetails)object;

		long primaryKey = facultyBankDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FacultyBankDetails> toCacheModel() {
		FacultyBankDetailsCacheModel facultyBankDetailsCacheModel =
			new FacultyBankDetailsCacheModel();

		facultyBankDetailsCacheModel.uuid = getUuid();

		String uuid = facultyBankDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			facultyBankDetailsCacheModel.uuid = null;
		}

		facultyBankDetailsCacheModel.facultyBankDetailsId =
			getFacultyBankDetailsId();

		facultyBankDetailsCacheModel.groupId = getGroupId();

		facultyBankDetailsCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			facultyBankDetailsCacheModel.createDate = createDate.getTime();
		}
		else {
			facultyBankDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			facultyBankDetailsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			facultyBankDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		facultyBankDetailsCacheModel.facultyRequestId = getFacultyRequestId();

		facultyBankDetailsCacheModel.bankName = getBankName();

		String bankName = facultyBankDetailsCacheModel.bankName;

		if ((bankName != null) && (bankName.length() == 0)) {
			facultyBankDetailsCacheModel.bankName = null;
		}

		facultyBankDetailsCacheModel.accountNo = getAccountNo();

		String accountNo = facultyBankDetailsCacheModel.accountNo;

		if ((accountNo != null) && (accountNo.length() == 0)) {
			facultyBankDetailsCacheModel.accountNo = null;
		}

		facultyBankDetailsCacheModel.bankBranch = getBankBranch();

		String bankBranch = facultyBankDetailsCacheModel.bankBranch;

		if ((bankBranch != null) && (bankBranch.length() == 0)) {
			facultyBankDetailsCacheModel.bankBranch = null;
		}

		return facultyBankDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FacultyBankDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FacultyBankDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FacultyBankDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FacultyBankDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FacultyBankDetails>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FacultyBankDetails.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _facultyBankDetailsId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _facultyRequestId;
	private String _bankName;
	private String _bankNameCurrentLanguageId;
	private String _accountNo;
	private String _accountNoCurrentLanguageId;
	private String _bankBranch;
	private String _bankBranchCurrentLanguageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FacultyBankDetails, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FacultyBankDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"faculty_bank_details_id", _facultyBankDetailsId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("faculty_request_id", _facultyRequestId);
		_columnOriginalValues.put("bank_name", _bankName);
		_columnOriginalValues.put("account_no", _accountNo);
		_columnOriginalValues.put("bank_branch", _bankBranch);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("faculty_bank_details_id", "facultyBankDetailsId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("faculty_request_id", "facultyRequestId");
		attributeNames.put("bank_name", "bankName");
		attributeNames.put("account_no", "accountNo");
		attributeNames.put("bank_branch", "bankBranch");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("faculty_bank_details_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("modified_date", 32L);

		columnBitmasks.put("faculty_request_id", 64L);

		columnBitmasks.put("bank_name", 128L);

		columnBitmasks.put("account_no", 256L);

		columnBitmasks.put("bank_branch", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FacultyBankDetails _escapedModel;

}