/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.FacultyIncentive;
import gov.omsb.tms.model.FacultyIncentiveModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FacultyIncentive service. Represents a row in the &quot;faculty_incentive&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FacultyIncentiveModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacultyIncentiveImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FacultyIncentiveImpl
 * @generated
 */
@JSON(strict = true)
public class FacultyIncentiveModelImpl
	extends BaseModelImpl<FacultyIncentive> implements FacultyIncentiveModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faculty incentive model instance should use the <code>FacultyIncentive</code> interface instead.
	 */
	public static final String TABLE_NAME = "faculty_incentive";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"faculty_incentive_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"modified_date", Types.TIMESTAMP},
		{"role_id", Types.BIGINT}, {"amount_in_omr", Types.BIGINT},
		{"applicable_form", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("faculty_incentive_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("role_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("amount_in_omr", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("applicable_form", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table faculty_incentive (uuid_ VARCHAR(75) null,faculty_incentive_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,modified_date DATE null,role_id LONG,amount_in_omr LONG,applicable_form DATE null)";

	public static final String TABLE_SQL_DROP = "drop table faculty_incentive";

	public static final String ORDER_BY_JPQL =
		" ORDER BY facultyIncentive.FacultyIncentiveId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY faculty_incentive.faculty_incentive_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROLEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACULTYINCENTIVEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FacultyIncentiveModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _FacultyIncentiveId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFacultyIncentiveId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _FacultyIncentiveId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FacultyIncentive.class;
	}

	@Override
	public String getModelClassName() {
		return FacultyIncentive.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FacultyIncentive, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FacultyIncentive, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FacultyIncentive, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FacultyIncentive)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FacultyIncentive, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FacultyIncentive, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FacultyIncentive)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FacultyIncentive, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FacultyIncentive, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FacultyIncentive, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FacultyIncentive, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FacultyIncentive, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<FacultyIncentive, Object>>();
		Map<String, BiConsumer<FacultyIncentive, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FacultyIncentive, ?>>();

		attributeGetterFunctions.put("uuid", FacultyIncentive::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<FacultyIncentive, String>)FacultyIncentive::setUuid);
		attributeGetterFunctions.put(
			"FacultyIncentiveId", FacultyIncentive::getFacultyIncentiveId);
		attributeSetterBiConsumers.put(
			"FacultyIncentiveId",
			(BiConsumer<FacultyIncentive, Long>)
				FacultyIncentive::setFacultyIncentiveId);
		attributeGetterFunctions.put("groupId", FacultyIncentive::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FacultyIncentive, Long>)FacultyIncentive::setGroupId);
		attributeGetterFunctions.put(
			"companyId", FacultyIncentive::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FacultyIncentive, Long>)FacultyIncentive::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", FacultyIncentive::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FacultyIncentive, Date>)
				FacultyIncentive::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FacultyIncentive::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FacultyIncentive, Date>)
				FacultyIncentive::setModifiedDate);
		attributeGetterFunctions.put("roleId", FacultyIncentive::getRoleId);
		attributeSetterBiConsumers.put(
			"roleId",
			(BiConsumer<FacultyIncentive, Long>)FacultyIncentive::setRoleId);
		attributeGetterFunctions.put(
			"amountInOMR", FacultyIncentive::getAmountInOMR);
		attributeSetterBiConsumers.put(
			"amountInOMR",
			(BiConsumer<FacultyIncentive, Long>)
				FacultyIncentive::setAmountInOMR);
		attributeGetterFunctions.put(
			"applicableForm", FacultyIncentive::getApplicableForm);
		attributeSetterBiConsumers.put(
			"applicableForm",
			(BiConsumer<FacultyIncentive, Date>)
				FacultyIncentive::setApplicableForm);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFacultyIncentiveId() {
		return _FacultyIncentiveId;
	}

	@Override
	public void setFacultyIncentiveId(long FacultyIncentiveId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FacultyIncentiveId = FacultyIncentiveId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getRoleId() {
		return _roleId;
	}

	@Override
	public void setRoleId(long roleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleId = roleId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRoleId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("role_id"));
	}

	@JSON
	@Override
	public long getAmountInOMR() {
		return _amountInOMR;
	}

	@Override
	public void setAmountInOMR(long amountInOMR) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amountInOMR = amountInOMR;
	}

	@JSON
	@Override
	public Date getApplicableForm() {
		return _applicableForm;
	}

	@Override
	public void setApplicableForm(Date applicableForm) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_applicableForm = applicableForm;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FacultyIncentive.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FacultyIncentive.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FacultyIncentive toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FacultyIncentive>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FacultyIncentiveImpl facultyIncentiveImpl = new FacultyIncentiveImpl();

		facultyIncentiveImpl.setUuid(getUuid());
		facultyIncentiveImpl.setFacultyIncentiveId(getFacultyIncentiveId());
		facultyIncentiveImpl.setGroupId(getGroupId());
		facultyIncentiveImpl.setCompanyId(getCompanyId());
		facultyIncentiveImpl.setCreateDate(getCreateDate());
		facultyIncentiveImpl.setModifiedDate(getModifiedDate());
		facultyIncentiveImpl.setRoleId(getRoleId());
		facultyIncentiveImpl.setAmountInOMR(getAmountInOMR());
		facultyIncentiveImpl.setApplicableForm(getApplicableForm());

		facultyIncentiveImpl.resetOriginalValues();

		return facultyIncentiveImpl;
	}

	@Override
	public FacultyIncentive cloneWithOriginalValues() {
		FacultyIncentiveImpl facultyIncentiveImpl = new FacultyIncentiveImpl();

		facultyIncentiveImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		facultyIncentiveImpl.setFacultyIncentiveId(
			this.<Long>getColumnOriginalValue("faculty_incentive_id"));
		facultyIncentiveImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		facultyIncentiveImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		facultyIncentiveImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		facultyIncentiveImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		facultyIncentiveImpl.setRoleId(
			this.<Long>getColumnOriginalValue("role_id"));
		facultyIncentiveImpl.setAmountInOMR(
			this.<Long>getColumnOriginalValue("amount_in_omr"));
		facultyIncentiveImpl.setApplicableForm(
			this.<Date>getColumnOriginalValue("applicable_form"));

		return facultyIncentiveImpl;
	}

	@Override
	public int compareTo(FacultyIncentive facultyIncentive) {
		long primaryKey = facultyIncentive.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FacultyIncentive)) {
			return false;
		}

		FacultyIncentive facultyIncentive = (FacultyIncentive)object;

		long primaryKey = facultyIncentive.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FacultyIncentive> toCacheModel() {
		FacultyIncentiveCacheModel facultyIncentiveCacheModel =
			new FacultyIncentiveCacheModel();

		facultyIncentiveCacheModel.uuid = getUuid();

		String uuid = facultyIncentiveCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			facultyIncentiveCacheModel.uuid = null;
		}

		facultyIncentiveCacheModel.FacultyIncentiveId = getFacultyIncentiveId();

		facultyIncentiveCacheModel.groupId = getGroupId();

		facultyIncentiveCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			facultyIncentiveCacheModel.createDate = createDate.getTime();
		}
		else {
			facultyIncentiveCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			facultyIncentiveCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			facultyIncentiveCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		facultyIncentiveCacheModel.roleId = getRoleId();

		facultyIncentiveCacheModel.amountInOMR = getAmountInOMR();

		Date applicableForm = getApplicableForm();

		if (applicableForm != null) {
			facultyIncentiveCacheModel.applicableForm =
				applicableForm.getTime();
		}
		else {
			facultyIncentiveCacheModel.applicableForm = Long.MIN_VALUE;
		}

		return facultyIncentiveCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FacultyIncentive, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FacultyIncentive, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FacultyIncentive, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FacultyIncentive)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FacultyIncentive>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FacultyIncentive.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _FacultyIncentiveId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _roleId;
	private long _amountInOMR;
	private Date _applicableForm;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FacultyIncentive, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FacultyIncentive)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("faculty_incentive_id", _FacultyIncentiveId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("role_id", _roleId);
		_columnOriginalValues.put("amount_in_omr", _amountInOMR);
		_columnOriginalValues.put("applicable_form", _applicableForm);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("faculty_incentive_id", "FacultyIncentiveId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("role_id", "roleId");
		attributeNames.put("amount_in_omr", "amountInOMR");
		attributeNames.put("applicable_form", "applicableForm");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("faculty_incentive_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("modified_date", 32L);

		columnBitmasks.put("role_id", 64L);

		columnBitmasks.put("amount_in_omr", 128L);

		columnBitmasks.put("applicable_form", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FacultyIncentive _escapedModel;

}