/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.FacultyRequestState;
import gov.omsb.tms.model.FacultyRequestStateModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FacultyRequestState service. Represents a row in the &quot;faculty_request_state&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FacultyRequestStateModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacultyRequestStateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FacultyRequestStateImpl
 * @generated
 */
@JSON(strict = true)
public class FacultyRequestStateModelImpl
	extends BaseModelImpl<FacultyRequestState>
	implements FacultyRequestStateModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faculty request state model instance should use the <code>FacultyRequestState</code> interface instead.
	 */
	public static final String TABLE_NAME = "faculty_request_state";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"faculty_request_state_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"created_by", Types.BIGINT}, {"create_date", Types.TIMESTAMP},
		{"modified_date", Types.TIMESTAMP},
		{"created_by_role_id", Types.BIGINT},
		{"faculty_request_id", Types.BIGINT},
		{"faculty_request_status_id", Types.BIGINT}, {"comments", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("faculty_request_state_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by_role_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("faculty_request_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("faculty_request_status_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("comments", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table faculty_request_state (uuid_ VARCHAR(75) null,faculty_request_state_id LONG not null primary key,group_id LONG,company_id LONG,created_by LONG,create_date DATE null,modified_date DATE null,created_by_role_id LONG,faculty_request_id LONG,faculty_request_status_id LONG,comments VARCHAR(1000) null)";

	public static final String TABLE_SQL_DROP =
		"drop table faculty_request_state";

	public static final String ORDER_BY_JPQL =
		" ORDER BY facultyRequestState.facultyRequestStateId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY faculty_request_state.faculty_request_state_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDBY_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACULTYREQUESTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACULTYREQUESTSTATEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FacultyRequestStateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _facultyRequestStateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFacultyRequestStateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _facultyRequestStateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FacultyRequestState.class;
	}

	@Override
	public String getModelClassName() {
		return FacultyRequestState.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FacultyRequestState, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FacultyRequestState, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FacultyRequestState, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FacultyRequestState)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FacultyRequestState, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FacultyRequestState, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FacultyRequestState)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FacultyRequestState, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FacultyRequestState, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FacultyRequestState, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FacultyRequestState, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FacultyRequestState, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FacultyRequestState, Object>>();
		Map<String, BiConsumer<FacultyRequestState, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FacultyRequestState, ?>>();

		attributeGetterFunctions.put("uuid", FacultyRequestState::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<FacultyRequestState, String>)
				FacultyRequestState::setUuid);
		attributeGetterFunctions.put(
			"facultyRequestStateId",
			FacultyRequestState::getFacultyRequestStateId);
		attributeSetterBiConsumers.put(
			"facultyRequestStateId",
			(BiConsumer<FacultyRequestState, Long>)
				FacultyRequestState::setFacultyRequestStateId);
		attributeGetterFunctions.put(
			"groupId", FacultyRequestState::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FacultyRequestState, Long>)
				FacultyRequestState::setGroupId);
		attributeGetterFunctions.put(
			"companyId", FacultyRequestState::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FacultyRequestState, Long>)
				FacultyRequestState::setCompanyId);
		attributeGetterFunctions.put(
			"createdBy", FacultyRequestState::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<FacultyRequestState, Long>)
				FacultyRequestState::setCreatedBy);
		attributeGetterFunctions.put(
			"createDate", FacultyRequestState::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FacultyRequestState, Date>)
				FacultyRequestState::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FacultyRequestState::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FacultyRequestState, Date>)
				FacultyRequestState::setModifiedDate);
		attributeGetterFunctions.put(
			"createdByRoleId", FacultyRequestState::getCreatedByRoleId);
		attributeSetterBiConsumers.put(
			"createdByRoleId",
			(BiConsumer<FacultyRequestState, Long>)
				FacultyRequestState::setCreatedByRoleId);
		attributeGetterFunctions.put(
			"facultyRequestId", FacultyRequestState::getFacultyRequestId);
		attributeSetterBiConsumers.put(
			"facultyRequestId",
			(BiConsumer<FacultyRequestState, Long>)
				FacultyRequestState::setFacultyRequestId);
		attributeGetterFunctions.put(
			"facultyRequestStatusId",
			FacultyRequestState::getFacultyRequestStatusId);
		attributeSetterBiConsumers.put(
			"facultyRequestStatusId",
			(BiConsumer<FacultyRequestState, Long>)
				FacultyRequestState::setFacultyRequestStatusId);
		attributeGetterFunctions.put(
			"comments", FacultyRequestState::getComments);
		attributeSetterBiConsumers.put(
			"comments",
			(BiConsumer<FacultyRequestState, String>)
				FacultyRequestState::setComments);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFacultyRequestStateId() {
		return _facultyRequestStateId;
	}

	@Override
	public void setFacultyRequestStateId(long facultyRequestStateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facultyRequestStateId = facultyRequestStateId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCreatedBy() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("created_by"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatedByRoleId() {
		return _createdByRoleId;
	}

	@Override
	public void setCreatedByRoleId(long createdByRoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdByRoleId = createdByRoleId;
	}

	@JSON
	@Override
	public long getFacultyRequestId() {
		return _facultyRequestId;
	}

	@Override
	public void setFacultyRequestId(long facultyRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facultyRequestId = facultyRequestId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFacultyRequestId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("faculty_request_id"));
	}

	@JSON
	@Override
	public long getFacultyRequestStatusId() {
		return _facultyRequestStatusId;
	}

	@Override
	public void setFacultyRequestStatusId(long facultyRequestStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facultyRequestStatusId = facultyRequestStatusId;
	}

	@JSON
	@Override
	public String getComments() {
		if (_comments == null) {
			return "";
		}
		else {
			return _comments;
		}
	}

	@Override
	public void setComments(String comments) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comments = comments;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FacultyRequestState.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FacultyRequestState.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FacultyRequestState toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FacultyRequestState>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FacultyRequestStateImpl facultyRequestStateImpl =
			new FacultyRequestStateImpl();

		facultyRequestStateImpl.setUuid(getUuid());
		facultyRequestStateImpl.setFacultyRequestStateId(
			getFacultyRequestStateId());
		facultyRequestStateImpl.setGroupId(getGroupId());
		facultyRequestStateImpl.setCompanyId(getCompanyId());
		facultyRequestStateImpl.setCreatedBy(getCreatedBy());
		facultyRequestStateImpl.setCreateDate(getCreateDate());
		facultyRequestStateImpl.setModifiedDate(getModifiedDate());
		facultyRequestStateImpl.setCreatedByRoleId(getCreatedByRoleId());
		facultyRequestStateImpl.setFacultyRequestId(getFacultyRequestId());
		facultyRequestStateImpl.setFacultyRequestStatusId(
			getFacultyRequestStatusId());
		facultyRequestStateImpl.setComments(getComments());

		facultyRequestStateImpl.resetOriginalValues();

		return facultyRequestStateImpl;
	}

	@Override
	public FacultyRequestState cloneWithOriginalValues() {
		FacultyRequestStateImpl facultyRequestStateImpl =
			new FacultyRequestStateImpl();

		facultyRequestStateImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		facultyRequestStateImpl.setFacultyRequestStateId(
			this.<Long>getColumnOriginalValue("faculty_request_state_id"));
		facultyRequestStateImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		facultyRequestStateImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		facultyRequestStateImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		facultyRequestStateImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		facultyRequestStateImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		facultyRequestStateImpl.setCreatedByRoleId(
			this.<Long>getColumnOriginalValue("created_by_role_id"));
		facultyRequestStateImpl.setFacultyRequestId(
			this.<Long>getColumnOriginalValue("faculty_request_id"));
		facultyRequestStateImpl.setFacultyRequestStatusId(
			this.<Long>getColumnOriginalValue("faculty_request_status_id"));
		facultyRequestStateImpl.setComments(
			this.<String>getColumnOriginalValue("comments"));

		return facultyRequestStateImpl;
	}

	@Override
	public int compareTo(FacultyRequestState facultyRequestState) {
		long primaryKey = facultyRequestState.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FacultyRequestState)) {
			return false;
		}

		FacultyRequestState facultyRequestState = (FacultyRequestState)object;

		long primaryKey = facultyRequestState.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FacultyRequestState> toCacheModel() {
		FacultyRequestStateCacheModel facultyRequestStateCacheModel =
			new FacultyRequestStateCacheModel();

		facultyRequestStateCacheModel.uuid = getUuid();

		String uuid = facultyRequestStateCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			facultyRequestStateCacheModel.uuid = null;
		}

		facultyRequestStateCacheModel.facultyRequestStateId =
			getFacultyRequestStateId();

		facultyRequestStateCacheModel.groupId = getGroupId();

		facultyRequestStateCacheModel.companyId = getCompanyId();

		facultyRequestStateCacheModel.createdBy = getCreatedBy();

		Date createDate = getCreateDate();

		if (createDate != null) {
			facultyRequestStateCacheModel.createDate = createDate.getTime();
		}
		else {
			facultyRequestStateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			facultyRequestStateCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			facultyRequestStateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		facultyRequestStateCacheModel.createdByRoleId = getCreatedByRoleId();

		facultyRequestStateCacheModel.facultyRequestId = getFacultyRequestId();

		facultyRequestStateCacheModel.facultyRequestStatusId =
			getFacultyRequestStatusId();

		facultyRequestStateCacheModel.comments = getComments();

		String comments = facultyRequestStateCacheModel.comments;

		if ((comments != null) && (comments.length() == 0)) {
			facultyRequestStateCacheModel.comments = null;
		}

		return facultyRequestStateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FacultyRequestState, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FacultyRequestState, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FacultyRequestState, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FacultyRequestState)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FacultyRequestState>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FacultyRequestState.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _facultyRequestStateId;
	private long _groupId;
	private long _companyId;
	private long _createdBy;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdByRoleId;
	private long _facultyRequestId;
	private long _facultyRequestStatusId;
	private String _comments;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FacultyRequestState, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FacultyRequestState)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"faculty_request_state_id", _facultyRequestStateId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("created_by_role_id", _createdByRoleId);
		_columnOriginalValues.put("faculty_request_id", _facultyRequestId);
		_columnOriginalValues.put(
			"faculty_request_status_id", _facultyRequestStatusId);
		_columnOriginalValues.put("comments", _comments);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("faculty_request_state_id", "facultyRequestStateId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("created_by_role_id", "createdByRoleId");
		attributeNames.put("faculty_request_id", "facultyRequestId");
		attributeNames.put(
			"faculty_request_status_id", "facultyRequestStatusId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("faculty_request_state_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("created_by", 16L);

		columnBitmasks.put("create_date", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("created_by_role_id", 128L);

		columnBitmasks.put("faculty_request_id", 256L);

		columnBitmasks.put("faculty_request_status_id", 512L);

		columnBitmasks.put("comments", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FacultyRequestState _escapedModel;

}