/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.FacultyType;
import gov.omsb.tms.model.FacultyTypeModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FacultyType service. Represents a row in the &quot;faculty_type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FacultyTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacultyTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FacultyTypeImpl
 * @generated
 */
@JSON(strict = true)
public class FacultyTypeModelImpl
	extends BaseModelImpl<FacultyType> implements FacultyTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faculty type model instance should use the <code>FacultyType</code> interface instead.
	 */
	public static final String TABLE_NAME = "faculty_type";

	public static final Object[][] TABLE_COLUMNS = {
		{"faculty_type_id", Types.BIGINT}, {"group_id", Types.BIGINT},
		{"company_id", Types.BIGINT}, {"create_date", Types.TIMESTAMP},
		{"modified_date", Types.TIMESTAMP}, {"code", Types.VARCHAR},
		{"name_en", Types.VARCHAR}, {"name_ar", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("faculty_type_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name_en", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name_ar", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table faculty_type (faculty_type_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,modified_date DATE null,code VARCHAR(75) null,name_en VARCHAR(75) null,name_ar VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table faculty_type";

	public static final String ORDER_BY_JPQL =
		" ORDER BY facultyType.facultyTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY faculty_type.faculty_type_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACULTYTYPEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FacultyTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _facultyTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFacultyTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _facultyTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FacultyType.class;
	}

	@Override
	public String getModelClassName() {
		return FacultyType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FacultyType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FacultyType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FacultyType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FacultyType)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FacultyType, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FacultyType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FacultyType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FacultyType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FacultyType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FacultyType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FacultyType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FacultyType, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<FacultyType, Object>>();
		Map<String, BiConsumer<FacultyType, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<FacultyType, ?>>();

		attributeGetterFunctions.put(
			"facultyTypeId", FacultyType::getFacultyTypeId);
		attributeSetterBiConsumers.put(
			"facultyTypeId",
			(BiConsumer<FacultyType, Long>)FacultyType::setFacultyTypeId);
		attributeGetterFunctions.put("groupId", FacultyType::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<FacultyType, Long>)FacultyType::setGroupId);
		attributeGetterFunctions.put("companyId", FacultyType::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FacultyType, Long>)FacultyType::setCompanyId);
		attributeGetterFunctions.put("createDate", FacultyType::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FacultyType, Date>)FacultyType::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FacultyType::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FacultyType, Date>)FacultyType::setModifiedDate);
		attributeGetterFunctions.put("code", FacultyType::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<FacultyType, String>)FacultyType::setCode);
		attributeGetterFunctions.put("nameEn", FacultyType::getNameEn);
		attributeSetterBiConsumers.put(
			"nameEn", (BiConsumer<FacultyType, String>)FacultyType::setNameEn);
		attributeGetterFunctions.put("nameAr", FacultyType::getNameAr);
		attributeSetterBiConsumers.put(
			"nameAr", (BiConsumer<FacultyType, String>)FacultyType::setNameAr);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getFacultyTypeId() {
		return _facultyTypeId;
	}

	@Override
	public void setFacultyTypeId(long facultyTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facultyTypeId = facultyTypeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCode() {
		return getColumnOriginalValue("code");
	}

	@JSON
	@Override
	public String getNameEn() {
		if (_nameEn == null) {
			return "";
		}
		else {
			return _nameEn;
		}
	}

	@Override
	public void setNameEn(String nameEn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nameEn = nameEn;
	}

	@JSON
	@Override
	public String getNameAr() {
		if (_nameAr == null) {
			return "";
		}
		else {
			return _nameAr;
		}
	}

	@Override
	public void setNameAr(String nameAr) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nameAr = nameAr;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FacultyType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FacultyType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FacultyType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FacultyTypeImpl facultyTypeImpl = new FacultyTypeImpl();

		facultyTypeImpl.setFacultyTypeId(getFacultyTypeId());
		facultyTypeImpl.setGroupId(getGroupId());
		facultyTypeImpl.setCompanyId(getCompanyId());
		facultyTypeImpl.setCreateDate(getCreateDate());
		facultyTypeImpl.setModifiedDate(getModifiedDate());
		facultyTypeImpl.setCode(getCode());
		facultyTypeImpl.setNameEn(getNameEn());
		facultyTypeImpl.setNameAr(getNameAr());

		facultyTypeImpl.resetOriginalValues();

		return facultyTypeImpl;
	}

	@Override
	public FacultyType cloneWithOriginalValues() {
		FacultyTypeImpl facultyTypeImpl = new FacultyTypeImpl();

		facultyTypeImpl.setFacultyTypeId(
			this.<Long>getColumnOriginalValue("faculty_type_id"));
		facultyTypeImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		facultyTypeImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		facultyTypeImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		facultyTypeImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		facultyTypeImpl.setCode(this.<String>getColumnOriginalValue("code"));
		facultyTypeImpl.setNameEn(
			this.<String>getColumnOriginalValue("name_en"));
		facultyTypeImpl.setNameAr(
			this.<String>getColumnOriginalValue("name_ar"));

		return facultyTypeImpl;
	}

	@Override
	public int compareTo(FacultyType facultyType) {
		long primaryKey = facultyType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FacultyType)) {
			return false;
		}

		FacultyType facultyType = (FacultyType)object;

		long primaryKey = facultyType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FacultyType> toCacheModel() {
		FacultyTypeCacheModel facultyTypeCacheModel =
			new FacultyTypeCacheModel();

		facultyTypeCacheModel.facultyTypeId = getFacultyTypeId();

		facultyTypeCacheModel.groupId = getGroupId();

		facultyTypeCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			facultyTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			facultyTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			facultyTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			facultyTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		facultyTypeCacheModel.code = getCode();

		String code = facultyTypeCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			facultyTypeCacheModel.code = null;
		}

		facultyTypeCacheModel.nameEn = getNameEn();

		String nameEn = facultyTypeCacheModel.nameEn;

		if ((nameEn != null) && (nameEn.length() == 0)) {
			facultyTypeCacheModel.nameEn = null;
		}

		facultyTypeCacheModel.nameAr = getNameAr();

		String nameAr = facultyTypeCacheModel.nameAr;

		if ((nameAr != null) && (nameAr.length() == 0)) {
			facultyTypeCacheModel.nameAr = null;
		}

		return facultyTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FacultyType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FacultyType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FacultyType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FacultyType)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FacultyType>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FacultyType.class, ModelWrapper.class);

	}

	private long _facultyTypeId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _code;
	private String _nameEn;
	private String _nameAr;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FacultyType, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FacultyType)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("faculty_type_id", _facultyTypeId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("code", _code);
		_columnOriginalValues.put("name_en", _nameEn);
		_columnOriginalValues.put("name_ar", _nameAr);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("faculty_type_id", "facultyTypeId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("name_en", "nameEn");
		attributeNames.put("name_ar", "nameAr");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("faculty_type_id", 1L);

		columnBitmasks.put("group_id", 2L);

		columnBitmasks.put("company_id", 4L);

		columnBitmasks.put("create_date", 8L);

		columnBitmasks.put("modified_date", 16L);

		columnBitmasks.put("code", 32L);

		columnBitmasks.put("name_en", 64L);

		columnBitmasks.put("name_ar", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FacultyType _escapedModel;

}