/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.GenderMaster;
import gov.omsb.tms.model.GenderMasterModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GenderMaster service. Represents a row in the &quot;gender_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GenderMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GenderMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GenderMasterImpl
 * @generated
 */
@JSON(strict = true)
public class GenderMasterModelImpl
	extends BaseModelImpl<GenderMaster> implements GenderMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a gender master model instance should use the <code>GenderMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "gender_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"gender_master_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT},
		{"gender_name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gender_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("gender_name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table gender_master (uuid_ VARCHAR(75) null,gender_master_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,gender_name STRING null)";

	public static final String TABLE_SQL_DROP = "drop table gender_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY genderMaster.genderMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY gender_master.gender_master_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GENDERMASTERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public GenderMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _genderMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGenderMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _genderMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GenderMaster.class;
	}

	@Override
	public String getModelClassName() {
		return GenderMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GenderMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GenderMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GenderMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GenderMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GenderMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GenderMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GenderMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GenderMaster, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GenderMaster, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<GenderMaster, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GenderMaster, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GenderMaster, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GenderMaster, Object>>();
		Map<String, BiConsumer<GenderMaster, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GenderMaster, ?>>();

		attributeGetterFunctions.put("uuid", GenderMaster::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<GenderMaster, String>)GenderMaster::setUuid);
		attributeGetterFunctions.put(
			"genderMasterId", GenderMaster::getGenderMasterId);
		attributeSetterBiConsumers.put(
			"genderMasterId",
			(BiConsumer<GenderMaster, Long>)GenderMaster::setGenderMasterId);
		attributeGetterFunctions.put("groupId", GenderMaster::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<GenderMaster, Long>)GenderMaster::setGroupId);
		attributeGetterFunctions.put("companyId", GenderMaster::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<GenderMaster, Long>)GenderMaster::setCompanyId);
		attributeGetterFunctions.put("createDate", GenderMaster::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<GenderMaster, Date>)GenderMaster::setCreateDate);
		attributeGetterFunctions.put("createdBy", GenderMaster::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<GenderMaster, Long>)GenderMaster::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", GenderMaster::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<GenderMaster, Date>)GenderMaster::setModifiedDate);
		attributeGetterFunctions.put("modifiedBy", GenderMaster::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<GenderMaster, Long>)GenderMaster::setModifiedBy);
		attributeGetterFunctions.put("genderName", GenderMaster::getGenderName);
		attributeSetterBiConsumers.put(
			"genderName",
			(BiConsumer<GenderMaster, String>)GenderMaster::setGenderName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getGenderMasterId() {
		return _genderMasterId;
	}

	@Override
	public void setGenderMasterId(long genderMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_genderMasterId = genderMasterId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public String getGenderName() {
		if (_genderName == null) {
			return "";
		}
		else {
			return _genderName;
		}
	}

	@Override
	public String getGenderName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getGenderName(languageId);
	}

	@Override
	public String getGenderName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getGenderName(languageId, useDefault);
	}

	@Override
	public String getGenderName(String languageId) {
		return LocalizationUtil.getLocalization(getGenderName(), languageId);
	}

	@Override
	public String getGenderName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getGenderName(), languageId, useDefault);
	}

	@Override
	public String getGenderNameCurrentLanguageId() {
		return _genderNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getGenderNameCurrentValue() {
		Locale locale = getLocale(_genderNameCurrentLanguageId);

		return getGenderName(locale);
	}

	@Override
	public Map<Locale, String> getGenderNameMap() {
		return LocalizationUtil.getLocalizationMap(getGenderName());
	}

	@Override
	public void setGenderName(String genderName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_genderName = genderName;
	}

	@Override
	public void setGenderName(String genderName, Locale locale) {
		setGenderName(genderName, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setGenderName(
		String genderName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(genderName)) {
			setGenderName(
				LocalizationUtil.updateLocalization(
					getGenderName(), "GenderName", genderName, languageId,
					defaultLanguageId));
		}
		else {
			setGenderName(
				LocalizationUtil.removeLocalization(
					getGenderName(), "GenderName", languageId));
		}
	}

	@Override
	public void setGenderNameCurrentLanguageId(String languageId) {
		_genderNameCurrentLanguageId = languageId;
	}

	@Override
	public void setGenderNameMap(Map<Locale, String> genderNameMap) {
		setGenderNameMap(genderNameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setGenderNameMap(
		Map<Locale, String> genderNameMap, Locale defaultLocale) {

		if (genderNameMap == null) {
			return;
		}

		setGenderName(
			LocalizationUtil.updateLocalization(
				genderNameMap, getGenderName(), "GenderName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(GenderMaster.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GenderMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> genderNameMap = getGenderNameMap();

		for (Map.Entry<Locale, String> entry : genderNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getGenderName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			GenderMaster.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String genderName = getGenderName(defaultLocale);

		if (Validator.isNull(genderName)) {
			setGenderName(getGenderName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setGenderName(
				getGenderName(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public GenderMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GenderMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GenderMasterImpl genderMasterImpl = new GenderMasterImpl();

		genderMasterImpl.setUuid(getUuid());
		genderMasterImpl.setGenderMasterId(getGenderMasterId());
		genderMasterImpl.setGroupId(getGroupId());
		genderMasterImpl.setCompanyId(getCompanyId());
		genderMasterImpl.setCreateDate(getCreateDate());
		genderMasterImpl.setCreatedBy(getCreatedBy());
		genderMasterImpl.setModifiedDate(getModifiedDate());
		genderMasterImpl.setModifiedBy(getModifiedBy());
		genderMasterImpl.setGenderName(getGenderName());

		genderMasterImpl.resetOriginalValues();

		return genderMasterImpl;
	}

	@Override
	public GenderMaster cloneWithOriginalValues() {
		GenderMasterImpl genderMasterImpl = new GenderMasterImpl();

		genderMasterImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		genderMasterImpl.setGenderMasterId(
			this.<Long>getColumnOriginalValue("gender_master_id"));
		genderMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		genderMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		genderMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		genderMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		genderMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		genderMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		genderMasterImpl.setGenderName(
			this.<String>getColumnOriginalValue("gender_name"));

		return genderMasterImpl;
	}

	@Override
	public int compareTo(GenderMaster genderMaster) {
		long primaryKey = genderMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof GenderMaster)) {
			return false;
		}

		GenderMaster genderMaster = (GenderMaster)object;

		long primaryKey = genderMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<GenderMaster> toCacheModel() {
		GenderMasterCacheModel genderMasterCacheModel =
			new GenderMasterCacheModel();

		genderMasterCacheModel.uuid = getUuid();

		String uuid = genderMasterCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			genderMasterCacheModel.uuid = null;
		}

		genderMasterCacheModel.genderMasterId = getGenderMasterId();

		genderMasterCacheModel.groupId = getGroupId();

		genderMasterCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			genderMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			genderMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		genderMasterCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			genderMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			genderMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		genderMasterCacheModel.modifiedBy = getModifiedBy();

		genderMasterCacheModel.genderName = getGenderName();

		String genderName = genderMasterCacheModel.genderName;

		if ((genderName != null) && (genderName.length() == 0)) {
			genderMasterCacheModel.genderName = null;
		}

		return genderMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GenderMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GenderMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GenderMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((GenderMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GenderMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					GenderMaster.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _genderMasterId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private String _genderName;
	private String _genderNameCurrentLanguageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<GenderMaster, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((GenderMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("gender_master_id", _genderMasterId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("gender_name", _genderName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("gender_master_id", "genderMasterId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("gender_name", "genderName");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("gender_master_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("created_by", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("gender_name", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private GenderMaster _escapedModel;

}