/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.LeaveProgramMaster;
import gov.omsb.tms.model.LeaveProgramMasterModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveProgramMaster service. Represents a row in the &quot;leave_program_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveProgramMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveProgramMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveProgramMasterImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveProgramMasterModelImpl
	extends BaseModelImpl<LeaveProgramMaster>
	implements LeaveProgramMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave program master model instance should use the <code>LeaveProgramMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "leave_program_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"leave_program_master_id", Types.BIGINT},
		{"program_master_id", Types.BIGINT}, {"leave_types_id", Types.BIGINT},
		{"no_of_leaves", Types.INTEGER}, {"resident_level_rule", Types.VARCHAR},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leave_program_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leave_types_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("no_of_leaves", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("resident_level_rule", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table leave_program_master (uuid_ VARCHAR(75) null,leave_program_master_id LONG not null primary key,program_master_id LONG,leave_types_id LONG,no_of_leaves INTEGER,resident_level_rule STRING null,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table leave_program_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveProgramMaster.leaveProgramMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY leave_program_master.leave_program_master_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVETYPESID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMMASTERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEPROGRAMMASTERID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveProgramMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveProgramMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveProgramMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveProgramMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveProgramMaster.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveProgramMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveProgramMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveProgramMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveProgramMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveProgramMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveProgramMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveProgramMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveProgramMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveProgramMaster, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveProgramMaster, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LeaveProgramMaster, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LeaveProgramMaster, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LeaveProgramMaster, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<LeaveProgramMaster, Object>>();
		Map<String, BiConsumer<LeaveProgramMaster, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<LeaveProgramMaster, ?>>();

		attributeGetterFunctions.put("uuid", LeaveProgramMaster::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<LeaveProgramMaster, String>)
				LeaveProgramMaster::setUuid);
		attributeGetterFunctions.put(
			"leaveProgramMasterId",
			LeaveProgramMaster::getLeaveProgramMasterId);
		attributeSetterBiConsumers.put(
			"leaveProgramMasterId",
			(BiConsumer<LeaveProgramMaster, Long>)
				LeaveProgramMaster::setLeaveProgramMasterId);
		attributeGetterFunctions.put(
			"programMasterId", LeaveProgramMaster::getProgramMasterId);
		attributeSetterBiConsumers.put(
			"programMasterId",
			(BiConsumer<LeaveProgramMaster, Long>)
				LeaveProgramMaster::setProgramMasterId);
		attributeGetterFunctions.put(
			"leaveTypesId", LeaveProgramMaster::getLeaveTypesId);
		attributeSetterBiConsumers.put(
			"leaveTypesId",
			(BiConsumer<LeaveProgramMaster, Long>)
				LeaveProgramMaster::setLeaveTypesId);
		attributeGetterFunctions.put(
			"noOfLeaves", LeaveProgramMaster::getNoOfLeaves);
		attributeSetterBiConsumers.put(
			"noOfLeaves",
			(BiConsumer<LeaveProgramMaster, Integer>)
				LeaveProgramMaster::setNoOfLeaves);
		attributeGetterFunctions.put(
			"residentLevelRule", LeaveProgramMaster::getResidentLevelRule);
		attributeSetterBiConsumers.put(
			"residentLevelRule",
			(BiConsumer<LeaveProgramMaster, String>)
				LeaveProgramMaster::setResidentLevelRule);
		attributeGetterFunctions.put("groupId", LeaveProgramMaster::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<LeaveProgramMaster, Long>)
				LeaveProgramMaster::setGroupId);
		attributeGetterFunctions.put(
			"companyId", LeaveProgramMaster::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LeaveProgramMaster, Long>)
				LeaveProgramMaster::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", LeaveProgramMaster::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LeaveProgramMaster, Date>)
				LeaveProgramMaster::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", LeaveProgramMaster::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<LeaveProgramMaster, Long>)
				LeaveProgramMaster::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", LeaveProgramMaster::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LeaveProgramMaster, Date>)
				LeaveProgramMaster::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", LeaveProgramMaster::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<LeaveProgramMaster, Long>)
				LeaveProgramMaster::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLeaveProgramMasterId() {
		return _leaveProgramMasterId;
	}

	@Override
	public void setLeaveProgramMasterId(long leaveProgramMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveProgramMasterId = leaveProgramMasterId;
	}

	@JSON
	@Override
	public long getProgramMasterId() {
		return _programMasterId;
	}

	@Override
	public void setProgramMasterId(long programMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programMasterId = programMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgramMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("program_master_id"));
	}

	@JSON
	@Override
	public long getLeaveTypesId() {
		return _leaveTypesId;
	}

	@Override
	public void setLeaveTypesId(long leaveTypesId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypesId = leaveTypesId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeaveTypesId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("leave_types_id"));
	}

	@JSON
	@Override
	public int getNoOfLeaves() {
		return _noOfLeaves;
	}

	@Override
	public void setNoOfLeaves(int noOfLeaves) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noOfLeaves = noOfLeaves;
	}

	@JSON
	@Override
	public String getResidentLevelRule() {
		if (_residentLevelRule == null) {
			return "";
		}
		else {
			return _residentLevelRule;
		}
	}

	@Override
	public String getResidentLevelRule(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getResidentLevelRule(languageId);
	}

	@Override
	public String getResidentLevelRule(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getResidentLevelRule(languageId, useDefault);
	}

	@Override
	public String getResidentLevelRule(String languageId) {
		return LocalizationUtil.getLocalization(
			getResidentLevelRule(), languageId);
	}

	@Override
	public String getResidentLevelRule(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getResidentLevelRule(), languageId, useDefault);
	}

	@Override
	public String getResidentLevelRuleCurrentLanguageId() {
		return _residentLevelRuleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getResidentLevelRuleCurrentValue() {
		Locale locale = getLocale(_residentLevelRuleCurrentLanguageId);

		return getResidentLevelRule(locale);
	}

	@Override
	public Map<Locale, String> getResidentLevelRuleMap() {
		return LocalizationUtil.getLocalizationMap(getResidentLevelRule());
	}

	@Override
	public void setResidentLevelRule(String residentLevelRule) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_residentLevelRule = residentLevelRule;
	}

	@Override
	public void setResidentLevelRule(String residentLevelRule, Locale locale) {
		setResidentLevelRule(
			residentLevelRule, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setResidentLevelRule(
		String residentLevelRule, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(residentLevelRule)) {
			setResidentLevelRule(
				LocalizationUtil.updateLocalization(
					getResidentLevelRule(), "ResidentLevelRule",
					residentLevelRule, languageId, defaultLanguageId));
		}
		else {
			setResidentLevelRule(
				LocalizationUtil.removeLocalization(
					getResidentLevelRule(), "ResidentLevelRule", languageId));
		}
	}

	@Override
	public void setResidentLevelRuleCurrentLanguageId(String languageId) {
		_residentLevelRuleCurrentLanguageId = languageId;
	}

	@Override
	public void setResidentLevelRuleMap(
		Map<Locale, String> residentLevelRuleMap) {

		setResidentLevelRuleMap(residentLevelRuleMap, LocaleUtil.getDefault());
	}

	@Override
	public void setResidentLevelRuleMap(
		Map<Locale, String> residentLevelRuleMap, Locale defaultLocale) {

		if (residentLevelRuleMap == null) {
			return;
		}

		setResidentLevelRule(
			LocalizationUtil.updateLocalization(
				residentLevelRuleMap, getResidentLevelRule(),
				"ResidentLevelRule", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveProgramMaster.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveProgramMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> residentLevelRuleMap = getResidentLevelRuleMap();

		for (Map.Entry<Locale, String> entry :
				residentLevelRuleMap.entrySet()) {

			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getResidentLevelRule();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			LeaveProgramMaster.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String residentLevelRule = getResidentLevelRule(defaultLocale);

		if (Validator.isNull(residentLevelRule)) {
			setResidentLevelRule(
				getResidentLevelRule(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setResidentLevelRule(
				getResidentLevelRule(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public LeaveProgramMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveProgramMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveProgramMasterImpl leaveProgramMasterImpl =
			new LeaveProgramMasterImpl();

		leaveProgramMasterImpl.setUuid(getUuid());
		leaveProgramMasterImpl.setLeaveProgramMasterId(
			getLeaveProgramMasterId());
		leaveProgramMasterImpl.setProgramMasterId(getProgramMasterId());
		leaveProgramMasterImpl.setLeaveTypesId(getLeaveTypesId());
		leaveProgramMasterImpl.setNoOfLeaves(getNoOfLeaves());
		leaveProgramMasterImpl.setResidentLevelRule(getResidentLevelRule());
		leaveProgramMasterImpl.setGroupId(getGroupId());
		leaveProgramMasterImpl.setCompanyId(getCompanyId());
		leaveProgramMasterImpl.setCreateDate(getCreateDate());
		leaveProgramMasterImpl.setCreatedBy(getCreatedBy());
		leaveProgramMasterImpl.setModifiedDate(getModifiedDate());
		leaveProgramMasterImpl.setModifiedBy(getModifiedBy());

		leaveProgramMasterImpl.resetOriginalValues();

		return leaveProgramMasterImpl;
	}

	@Override
	public LeaveProgramMaster cloneWithOriginalValues() {
		LeaveProgramMasterImpl leaveProgramMasterImpl =
			new LeaveProgramMasterImpl();

		leaveProgramMasterImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		leaveProgramMasterImpl.setLeaveProgramMasterId(
			this.<Long>getColumnOriginalValue("leave_program_master_id"));
		leaveProgramMasterImpl.setProgramMasterId(
			this.<Long>getColumnOriginalValue("program_master_id"));
		leaveProgramMasterImpl.setLeaveTypesId(
			this.<Long>getColumnOriginalValue("leave_types_id"));
		leaveProgramMasterImpl.setNoOfLeaves(
			this.<Integer>getColumnOriginalValue("no_of_leaves"));
		leaveProgramMasterImpl.setResidentLevelRule(
			this.<String>getColumnOriginalValue("resident_level_rule"));
		leaveProgramMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		leaveProgramMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		leaveProgramMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		leaveProgramMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		leaveProgramMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		leaveProgramMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));

		return leaveProgramMasterImpl;
	}

	@Override
	public int compareTo(LeaveProgramMaster leaveProgramMaster) {
		long primaryKey = leaveProgramMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveProgramMaster)) {
			return false;
		}

		LeaveProgramMaster leaveProgramMaster = (LeaveProgramMaster)object;

		long primaryKey = leaveProgramMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveProgramMaster> toCacheModel() {
		LeaveProgramMasterCacheModel leaveProgramMasterCacheModel =
			new LeaveProgramMasterCacheModel();

		leaveProgramMasterCacheModel.uuid = getUuid();

		String uuid = leaveProgramMasterCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveProgramMasterCacheModel.uuid = null;
		}

		leaveProgramMasterCacheModel.leaveProgramMasterId =
			getLeaveProgramMasterId();

		leaveProgramMasterCacheModel.programMasterId = getProgramMasterId();

		leaveProgramMasterCacheModel.leaveTypesId = getLeaveTypesId();

		leaveProgramMasterCacheModel.noOfLeaves = getNoOfLeaves();

		leaveProgramMasterCacheModel.residentLevelRule = getResidentLevelRule();

		String residentLevelRule =
			leaveProgramMasterCacheModel.residentLevelRule;

		if ((residentLevelRule != null) && (residentLevelRule.length() == 0)) {
			leaveProgramMasterCacheModel.residentLevelRule = null;
		}

		leaveProgramMasterCacheModel.groupId = getGroupId();

		leaveProgramMasterCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveProgramMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveProgramMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		leaveProgramMasterCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveProgramMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveProgramMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveProgramMasterCacheModel.modifiedBy = getModifiedBy();

		return leaveProgramMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveProgramMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveProgramMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveProgramMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LeaveProgramMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveProgramMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveProgramMaster.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _leaveProgramMasterId;
	private long _programMasterId;
	private long _leaveTypesId;
	private int _noOfLeaves;
	private String _residentLevelRule;
	private String _residentLevelRuleCurrentLanguageId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveProgramMaster, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveProgramMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"leave_program_master_id", _leaveProgramMasterId);
		_columnOriginalValues.put("program_master_id", _programMasterId);
		_columnOriginalValues.put("leave_types_id", _leaveTypesId);
		_columnOriginalValues.put("no_of_leaves", _noOfLeaves);
		_columnOriginalValues.put("resident_level_rule", _residentLevelRule);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("leave_program_master_id", "leaveProgramMasterId");
		attributeNames.put("program_master_id", "programMasterId");
		attributeNames.put("leave_types_id", "leaveTypesId");
		attributeNames.put("no_of_leaves", "noOfLeaves");
		attributeNames.put("resident_level_rule", "residentLevelRule");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("leave_program_master_id", 2L);

		columnBitmasks.put("program_master_id", 4L);

		columnBitmasks.put("leave_types_id", 8L);

		columnBitmasks.put("no_of_leaves", 16L);

		columnBitmasks.put("resident_level_rule", 32L);

		columnBitmasks.put("group_id", 64L);

		columnBitmasks.put("company_id", 128L);

		columnBitmasks.put("create_date", 256L);

		columnBitmasks.put("created_by", 512L);

		columnBitmasks.put("modified_date", 1024L);

		columnBitmasks.put("modified_by", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveProgramMaster _escapedModel;

}