/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.LeaveAnnualMaster;
import gov.omsb.tms.model.LeaveAnnualMasterModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveAnnualMaster service. Represents a row in the &quot;leave_annual_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveAnnualMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveAnnualMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveAnnualMasterImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveAnnualMasterModelImpl
	extends BaseModelImpl<LeaveAnnualMaster> implements LeaveAnnualMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave annual master model instance should use the <code>LeaveAnnualMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "leave_annual_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"leave_annual_master_id", Types.BIGINT},
		{"leave_program_master_id", Types.BIGINT},
		{"leave_types_id", Types.BIGINT}, {"training_level_id", Types.BIGINT},
		{"block_name", Types.VARCHAR},
		{"max_trainee_apply_leave", Types.INTEGER},
		{"no_of_trainee_taken_leave", Types.INTEGER},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leave_annual_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leave_program_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leave_types_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("training_level_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("block_name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("max_trainee_apply_leave", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("no_of_trainee_taken_leave", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table leave_annual_master (uuid_ VARCHAR(75) null,leave_annual_master_id LONG not null primary key,leave_program_master_id LONG,leave_types_id LONG,training_level_id LONG,block_name STRING null,max_trainee_apply_leave INTEGER,no_of_trainee_taken_leave INTEGER,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table leave_annual_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveAnnualMaster.leaveAnnualMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY leave_annual_master.leave_annual_master_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEANNUALMASTERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveAnnualMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveAnnualMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveAnnualMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveAnnualMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveAnnualMaster.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveAnnualMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveAnnualMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveAnnualMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveAnnualMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveAnnualMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveAnnualMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveAnnualMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveAnnualMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveAnnualMaster, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveAnnualMaster, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LeaveAnnualMaster, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LeaveAnnualMaster, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LeaveAnnualMaster, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<LeaveAnnualMaster, Object>>();
		Map<String, BiConsumer<LeaveAnnualMaster, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<LeaveAnnualMaster, ?>>();

		attributeGetterFunctions.put("uuid", LeaveAnnualMaster::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<LeaveAnnualMaster, String>)LeaveAnnualMaster::setUuid);
		attributeGetterFunctions.put(
			"leaveAnnualMasterId", LeaveAnnualMaster::getLeaveAnnualMasterId);
		attributeSetterBiConsumers.put(
			"leaveAnnualMasterId",
			(BiConsumer<LeaveAnnualMaster, Long>)
				LeaveAnnualMaster::setLeaveAnnualMasterId);
		attributeGetterFunctions.put(
			"leaveProgramMasterId", LeaveAnnualMaster::getLeaveProgramMasterId);
		attributeSetterBiConsumers.put(
			"leaveProgramMasterId",
			(BiConsumer<LeaveAnnualMaster, Long>)
				LeaveAnnualMaster::setLeaveProgramMasterId);
		attributeGetterFunctions.put(
			"leaveTypesId", LeaveAnnualMaster::getLeaveTypesId);
		attributeSetterBiConsumers.put(
			"leaveTypesId",
			(BiConsumer<LeaveAnnualMaster, Long>)
				LeaveAnnualMaster::setLeaveTypesId);
		attributeGetterFunctions.put(
			"trainingLevelId", LeaveAnnualMaster::getTrainingLevelId);
		attributeSetterBiConsumers.put(
			"trainingLevelId",
			(BiConsumer<LeaveAnnualMaster, Long>)
				LeaveAnnualMaster::setTrainingLevelId);
		attributeGetterFunctions.put(
			"blockName", LeaveAnnualMaster::getBlockName);
		attributeSetterBiConsumers.put(
			"blockName",
			(BiConsumer<LeaveAnnualMaster, String>)
				LeaveAnnualMaster::setBlockName);
		attributeGetterFunctions.put(
			"maxTraineeApplyLeave", LeaveAnnualMaster::getMaxTraineeApplyLeave);
		attributeSetterBiConsumers.put(
			"maxTraineeApplyLeave",
			(BiConsumer<LeaveAnnualMaster, Integer>)
				LeaveAnnualMaster::setMaxTraineeApplyLeave);
		attributeGetterFunctions.put(
			"noOfTraineeTakenLeave",
			LeaveAnnualMaster::getNoOfTraineeTakenLeave);
		attributeSetterBiConsumers.put(
			"noOfTraineeTakenLeave",
			(BiConsumer<LeaveAnnualMaster, Integer>)
				LeaveAnnualMaster::setNoOfTraineeTakenLeave);
		attributeGetterFunctions.put("groupId", LeaveAnnualMaster::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<LeaveAnnualMaster, Long>)LeaveAnnualMaster::setGroupId);
		attributeGetterFunctions.put(
			"companyId", LeaveAnnualMaster::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LeaveAnnualMaster, Long>)
				LeaveAnnualMaster::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", LeaveAnnualMaster::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LeaveAnnualMaster, Date>)
				LeaveAnnualMaster::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", LeaveAnnualMaster::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<LeaveAnnualMaster, Long>)
				LeaveAnnualMaster::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", LeaveAnnualMaster::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LeaveAnnualMaster, Date>)
				LeaveAnnualMaster::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", LeaveAnnualMaster::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<LeaveAnnualMaster, Long>)
				LeaveAnnualMaster::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLeaveAnnualMasterId() {
		return _leaveAnnualMasterId;
	}

	@Override
	public void setLeaveAnnualMasterId(long leaveAnnualMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveAnnualMasterId = leaveAnnualMasterId;
	}

	@JSON
	@Override
	public long getLeaveProgramMasterId() {
		return _leaveProgramMasterId;
	}

	@Override
	public void setLeaveProgramMasterId(long leaveProgramMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveProgramMasterId = leaveProgramMasterId;
	}

	@JSON
	@Override
	public long getLeaveTypesId() {
		return _leaveTypesId;
	}

	@Override
	public void setLeaveTypesId(long leaveTypesId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypesId = leaveTypesId;
	}

	@JSON
	@Override
	public long getTrainingLevelId() {
		return _trainingLevelId;
	}

	@Override
	public void setTrainingLevelId(long trainingLevelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trainingLevelId = trainingLevelId;
	}

	@JSON
	@Override
	public String getBlockName() {
		if (_blockName == null) {
			return "";
		}
		else {
			return _blockName;
		}
	}

	@Override
	public String getBlockName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBlockName(languageId);
	}

	@Override
	public String getBlockName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBlockName(languageId, useDefault);
	}

	@Override
	public String getBlockName(String languageId) {
		return LocalizationUtil.getLocalization(getBlockName(), languageId);
	}

	@Override
	public String getBlockName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getBlockName(), languageId, useDefault);
	}

	@Override
	public String getBlockNameCurrentLanguageId() {
		return _blockNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getBlockNameCurrentValue() {
		Locale locale = getLocale(_blockNameCurrentLanguageId);

		return getBlockName(locale);
	}

	@Override
	public Map<Locale, String> getBlockNameMap() {
		return LocalizationUtil.getLocalizationMap(getBlockName());
	}

	@Override
	public void setBlockName(String blockName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_blockName = blockName;
	}

	@Override
	public void setBlockName(String blockName, Locale locale) {
		setBlockName(blockName, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setBlockName(
		String blockName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(blockName)) {
			setBlockName(
				LocalizationUtil.updateLocalization(
					getBlockName(), "BlockName", blockName, languageId,
					defaultLanguageId));
		}
		else {
			setBlockName(
				LocalizationUtil.removeLocalization(
					getBlockName(), "BlockName", languageId));
		}
	}

	@Override
	public void setBlockNameCurrentLanguageId(String languageId) {
		_blockNameCurrentLanguageId = languageId;
	}

	@Override
	public void setBlockNameMap(Map<Locale, String> blockNameMap) {
		setBlockNameMap(blockNameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setBlockNameMap(
		Map<Locale, String> blockNameMap, Locale defaultLocale) {

		if (blockNameMap == null) {
			return;
		}

		setBlockName(
			LocalizationUtil.updateLocalization(
				blockNameMap, getBlockName(), "BlockName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public int getMaxTraineeApplyLeave() {
		return _maxTraineeApplyLeave;
	}

	@Override
	public void setMaxTraineeApplyLeave(int maxTraineeApplyLeave) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_maxTraineeApplyLeave = maxTraineeApplyLeave;
	}

	@JSON
	@Override
	public int getNoOfTraineeTakenLeave() {
		return _noOfTraineeTakenLeave;
	}

	@Override
	public void setNoOfTraineeTakenLeave(int noOfTraineeTakenLeave) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noOfTraineeTakenLeave = noOfTraineeTakenLeave;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveAnnualMaster.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveAnnualMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> blockNameMap = getBlockNameMap();

		for (Map.Entry<Locale, String> entry : blockNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getBlockName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			LeaveAnnualMaster.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String blockName = getBlockName(defaultLocale);

		if (Validator.isNull(blockName)) {
			setBlockName(getBlockName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setBlockName(
				getBlockName(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public LeaveAnnualMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveAnnualMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveAnnualMasterImpl leaveAnnualMasterImpl =
			new LeaveAnnualMasterImpl();

		leaveAnnualMasterImpl.setUuid(getUuid());
		leaveAnnualMasterImpl.setLeaveAnnualMasterId(getLeaveAnnualMasterId());
		leaveAnnualMasterImpl.setLeaveProgramMasterId(
			getLeaveProgramMasterId());
		leaveAnnualMasterImpl.setLeaveTypesId(getLeaveTypesId());
		leaveAnnualMasterImpl.setTrainingLevelId(getTrainingLevelId());
		leaveAnnualMasterImpl.setBlockName(getBlockName());
		leaveAnnualMasterImpl.setMaxTraineeApplyLeave(
			getMaxTraineeApplyLeave());
		leaveAnnualMasterImpl.setNoOfTraineeTakenLeave(
			getNoOfTraineeTakenLeave());
		leaveAnnualMasterImpl.setGroupId(getGroupId());
		leaveAnnualMasterImpl.setCompanyId(getCompanyId());
		leaveAnnualMasterImpl.setCreateDate(getCreateDate());
		leaveAnnualMasterImpl.setCreatedBy(getCreatedBy());
		leaveAnnualMasterImpl.setModifiedDate(getModifiedDate());
		leaveAnnualMasterImpl.setModifiedBy(getModifiedBy());

		leaveAnnualMasterImpl.resetOriginalValues();

		return leaveAnnualMasterImpl;
	}

	@Override
	public LeaveAnnualMaster cloneWithOriginalValues() {
		LeaveAnnualMasterImpl leaveAnnualMasterImpl =
			new LeaveAnnualMasterImpl();

		leaveAnnualMasterImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		leaveAnnualMasterImpl.setLeaveAnnualMasterId(
			this.<Long>getColumnOriginalValue("leave_annual_master_id"));
		leaveAnnualMasterImpl.setLeaveProgramMasterId(
			this.<Long>getColumnOriginalValue("leave_program_master_id"));
		leaveAnnualMasterImpl.setLeaveTypesId(
			this.<Long>getColumnOriginalValue("leave_types_id"));
		leaveAnnualMasterImpl.setTrainingLevelId(
			this.<Long>getColumnOriginalValue("training_level_id"));
		leaveAnnualMasterImpl.setBlockName(
			this.<String>getColumnOriginalValue("block_name"));
		leaveAnnualMasterImpl.setMaxTraineeApplyLeave(
			this.<Integer>getColumnOriginalValue("max_trainee_apply_leave"));
		leaveAnnualMasterImpl.setNoOfTraineeTakenLeave(
			this.<Integer>getColumnOriginalValue("no_of_trainee_taken_leave"));
		leaveAnnualMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		leaveAnnualMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		leaveAnnualMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		leaveAnnualMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		leaveAnnualMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		leaveAnnualMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));

		return leaveAnnualMasterImpl;
	}

	@Override
	public int compareTo(LeaveAnnualMaster leaveAnnualMaster) {
		long primaryKey = leaveAnnualMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveAnnualMaster)) {
			return false;
		}

		LeaveAnnualMaster leaveAnnualMaster = (LeaveAnnualMaster)object;

		long primaryKey = leaveAnnualMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveAnnualMaster> toCacheModel() {
		LeaveAnnualMasterCacheModel leaveAnnualMasterCacheModel =
			new LeaveAnnualMasterCacheModel();

		leaveAnnualMasterCacheModel.uuid = getUuid();

		String uuid = leaveAnnualMasterCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveAnnualMasterCacheModel.uuid = null;
		}

		leaveAnnualMasterCacheModel.leaveAnnualMasterId =
			getLeaveAnnualMasterId();

		leaveAnnualMasterCacheModel.leaveProgramMasterId =
			getLeaveProgramMasterId();

		leaveAnnualMasterCacheModel.leaveTypesId = getLeaveTypesId();

		leaveAnnualMasterCacheModel.trainingLevelId = getTrainingLevelId();

		leaveAnnualMasterCacheModel.blockName = getBlockName();

		String blockName = leaveAnnualMasterCacheModel.blockName;

		if ((blockName != null) && (blockName.length() == 0)) {
			leaveAnnualMasterCacheModel.blockName = null;
		}

		leaveAnnualMasterCacheModel.maxTraineeApplyLeave =
			getMaxTraineeApplyLeave();

		leaveAnnualMasterCacheModel.noOfTraineeTakenLeave =
			getNoOfTraineeTakenLeave();

		leaveAnnualMasterCacheModel.groupId = getGroupId();

		leaveAnnualMasterCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveAnnualMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveAnnualMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		leaveAnnualMasterCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveAnnualMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveAnnualMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveAnnualMasterCacheModel.modifiedBy = getModifiedBy();

		return leaveAnnualMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveAnnualMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveAnnualMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveAnnualMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LeaveAnnualMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveAnnualMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveAnnualMaster.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _leaveAnnualMasterId;
	private long _leaveProgramMasterId;
	private long _leaveTypesId;
	private long _trainingLevelId;
	private String _blockName;
	private String _blockNameCurrentLanguageId;
	private int _maxTraineeApplyLeave;
	private int _noOfTraineeTakenLeave;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveAnnualMaster, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveAnnualMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"leave_annual_master_id", _leaveAnnualMasterId);
		_columnOriginalValues.put(
			"leave_program_master_id", _leaveProgramMasterId);
		_columnOriginalValues.put("leave_types_id", _leaveTypesId);
		_columnOriginalValues.put("training_level_id", _trainingLevelId);
		_columnOriginalValues.put("block_name", _blockName);
		_columnOriginalValues.put(
			"max_trainee_apply_leave", _maxTraineeApplyLeave);
		_columnOriginalValues.put(
			"no_of_trainee_taken_leave", _noOfTraineeTakenLeave);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("leave_annual_master_id", "leaveAnnualMasterId");
		attributeNames.put("leave_program_master_id", "leaveProgramMasterId");
		attributeNames.put("leave_types_id", "leaveTypesId");
		attributeNames.put("training_level_id", "trainingLevelId");
		attributeNames.put("block_name", "blockName");
		attributeNames.put("max_trainee_apply_leave", "maxTraineeApplyLeave");
		attributeNames.put(
			"no_of_trainee_taken_leave", "noOfTraineeTakenLeave");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("leave_annual_master_id", 2L);

		columnBitmasks.put("leave_program_master_id", 4L);

		columnBitmasks.put("leave_types_id", 8L);

		columnBitmasks.put("training_level_id", 16L);

		columnBitmasks.put("block_name", 32L);

		columnBitmasks.put("max_trainee_apply_leave", 64L);

		columnBitmasks.put("no_of_trainee_taken_leave", 128L);

		columnBitmasks.put("group_id", 256L);

		columnBitmasks.put("company_id", 512L);

		columnBitmasks.put("create_date", 1024L);

		columnBitmasks.put("created_by", 2048L);

		columnBitmasks.put("modified_date", 4096L);

		columnBitmasks.put("modified_by", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveAnnualMaster _escapedModel;

}