/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.LeaveAnnualMaxTrainee;
import gov.omsb.tms.model.LeaveAnnualMaxTraineeModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveAnnualMaxTrainee service. Represents a row in the &quot;leave_annual_max_trainee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveAnnualMaxTraineeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveAnnualMaxTraineeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveAnnualMaxTraineeImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveAnnualMaxTraineeModelImpl
	extends BaseModelImpl<LeaveAnnualMaxTrainee>
	implements LeaveAnnualMaxTraineeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave annual max trainee model instance should use the <code>LeaveAnnualMaxTrainee</code> interface instead.
	 */
	public static final String TABLE_NAME = "leave_annual_max_trainee";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"leave_annual_max_trainee_id", Types.BIGINT},
		{"leave_annual_rule_id", Types.BIGINT},
		{"training_level", Types.VARCHAR}, {"block", Types.INTEGER},
		{"week", Types.INTEGER}, {"max_trainee_apply_leave", Types.INTEGER},
		{"no_of_trainee_taken_leave", Types.INTEGER},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leave_annual_max_trainee_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leave_annual_rule_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("training_level", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("block", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("week", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("max_trainee_apply_leave", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("no_of_trainee_taken_leave", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table leave_annual_max_trainee (uuid_ VARCHAR(75) null,leave_annual_max_trainee_id LONG not null primary key,leave_annual_rule_id LONG,training_level STRING null,block INTEGER,week INTEGER,max_trainee_apply_leave INTEGER,no_of_trainee_taken_leave INTEGER,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table leave_annual_max_trainee";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveAnnualMaxTrainee.leaveAnnualMaxTraineeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY leave_annual_max_trainee.leave_annual_max_trainee_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEANNUALMAXTRAINEEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveAnnualMaxTraineeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveAnnualMaxTraineeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveAnnualMaxTraineeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveAnnualMaxTraineeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveAnnualMaxTrainee.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveAnnualMaxTrainee.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveAnnualMaxTrainee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveAnnualMaxTrainee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveAnnualMaxTrainee, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveAnnualMaxTrainee)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveAnnualMaxTrainee, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveAnnualMaxTrainee, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveAnnualMaxTrainee)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveAnnualMaxTrainee, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveAnnualMaxTrainee, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LeaveAnnualMaxTrainee, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LeaveAnnualMaxTrainee, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LeaveAnnualMaxTrainee, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<LeaveAnnualMaxTrainee, Object>>();
		Map<String, BiConsumer<LeaveAnnualMaxTrainee, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<LeaveAnnualMaxTrainee, ?>>();

		attributeGetterFunctions.put("uuid", LeaveAnnualMaxTrainee::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<LeaveAnnualMaxTrainee, String>)
				LeaveAnnualMaxTrainee::setUuid);
		attributeGetterFunctions.put(
			"leaveAnnualMaxTraineeId",
			LeaveAnnualMaxTrainee::getLeaveAnnualMaxTraineeId);
		attributeSetterBiConsumers.put(
			"leaveAnnualMaxTraineeId",
			(BiConsumer<LeaveAnnualMaxTrainee, Long>)
				LeaveAnnualMaxTrainee::setLeaveAnnualMaxTraineeId);
		attributeGetterFunctions.put(
			"leaveAnnualRuleId", LeaveAnnualMaxTrainee::getLeaveAnnualRuleId);
		attributeSetterBiConsumers.put(
			"leaveAnnualRuleId",
			(BiConsumer<LeaveAnnualMaxTrainee, Long>)
				LeaveAnnualMaxTrainee::setLeaveAnnualRuleId);
		attributeGetterFunctions.put(
			"trainingLevel", LeaveAnnualMaxTrainee::getTrainingLevel);
		attributeSetterBiConsumers.put(
			"trainingLevel",
			(BiConsumer<LeaveAnnualMaxTrainee, String>)
				LeaveAnnualMaxTrainee::setTrainingLevel);
		attributeGetterFunctions.put("block", LeaveAnnualMaxTrainee::getBlock);
		attributeSetterBiConsumers.put(
			"block",
			(BiConsumer<LeaveAnnualMaxTrainee, Integer>)
				LeaveAnnualMaxTrainee::setBlock);
		attributeGetterFunctions.put("week", LeaveAnnualMaxTrainee::getWeek);
		attributeSetterBiConsumers.put(
			"week",
			(BiConsumer<LeaveAnnualMaxTrainee, Integer>)
				LeaveAnnualMaxTrainee::setWeek);
		attributeGetterFunctions.put(
			"maxTraineeApplyLeave",
			LeaveAnnualMaxTrainee::getMaxTraineeApplyLeave);
		attributeSetterBiConsumers.put(
			"maxTraineeApplyLeave",
			(BiConsumer<LeaveAnnualMaxTrainee, Integer>)
				LeaveAnnualMaxTrainee::setMaxTraineeApplyLeave);
		attributeGetterFunctions.put(
			"noOfTraineeTakenLeave",
			LeaveAnnualMaxTrainee::getNoOfTraineeTakenLeave);
		attributeSetterBiConsumers.put(
			"noOfTraineeTakenLeave",
			(BiConsumer<LeaveAnnualMaxTrainee, Integer>)
				LeaveAnnualMaxTrainee::setNoOfTraineeTakenLeave);
		attributeGetterFunctions.put(
			"groupId", LeaveAnnualMaxTrainee::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<LeaveAnnualMaxTrainee, Long>)
				LeaveAnnualMaxTrainee::setGroupId);
		attributeGetterFunctions.put(
			"companyId", LeaveAnnualMaxTrainee::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LeaveAnnualMaxTrainee, Long>)
				LeaveAnnualMaxTrainee::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", LeaveAnnualMaxTrainee::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LeaveAnnualMaxTrainee, Date>)
				LeaveAnnualMaxTrainee::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", LeaveAnnualMaxTrainee::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<LeaveAnnualMaxTrainee, Long>)
				LeaveAnnualMaxTrainee::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", LeaveAnnualMaxTrainee::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LeaveAnnualMaxTrainee, Date>)
				LeaveAnnualMaxTrainee::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", LeaveAnnualMaxTrainee::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<LeaveAnnualMaxTrainee, Long>)
				LeaveAnnualMaxTrainee::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLeaveAnnualMaxTraineeId() {
		return _leaveAnnualMaxTraineeId;
	}

	@Override
	public void setLeaveAnnualMaxTraineeId(long leaveAnnualMaxTraineeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveAnnualMaxTraineeId = leaveAnnualMaxTraineeId;
	}

	@JSON
	@Override
	public long getLeaveAnnualRuleId() {
		return _leaveAnnualRuleId;
	}

	@Override
	public void setLeaveAnnualRuleId(long leaveAnnualRuleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveAnnualRuleId = leaveAnnualRuleId;
	}

	@JSON
	@Override
	public String getTrainingLevel() {
		if (_trainingLevel == null) {
			return "";
		}
		else {
			return _trainingLevel;
		}
	}

	@Override
	public String getTrainingLevel(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTrainingLevel(languageId);
	}

	@Override
	public String getTrainingLevel(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTrainingLevel(languageId, useDefault);
	}

	@Override
	public String getTrainingLevel(String languageId) {
		return LocalizationUtil.getLocalization(getTrainingLevel(), languageId);
	}

	@Override
	public String getTrainingLevel(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTrainingLevel(), languageId, useDefault);
	}

	@Override
	public String getTrainingLevelCurrentLanguageId() {
		return _trainingLevelCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTrainingLevelCurrentValue() {
		Locale locale = getLocale(_trainingLevelCurrentLanguageId);

		return getTrainingLevel(locale);
	}

	@Override
	public Map<Locale, String> getTrainingLevelMap() {
		return LocalizationUtil.getLocalizationMap(getTrainingLevel());
	}

	@Override
	public void setTrainingLevel(String trainingLevel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trainingLevel = trainingLevel;
	}

	@Override
	public void setTrainingLevel(String trainingLevel, Locale locale) {
		setTrainingLevel(trainingLevel, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setTrainingLevel(
		String trainingLevel, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(trainingLevel)) {
			setTrainingLevel(
				LocalizationUtil.updateLocalization(
					getTrainingLevel(), "TrainingLevel", trainingLevel,
					languageId, defaultLanguageId));
		}
		else {
			setTrainingLevel(
				LocalizationUtil.removeLocalization(
					getTrainingLevel(), "TrainingLevel", languageId));
		}
	}

	@Override
	public void setTrainingLevelCurrentLanguageId(String languageId) {
		_trainingLevelCurrentLanguageId = languageId;
	}

	@Override
	public void setTrainingLevelMap(Map<Locale, String> trainingLevelMap) {
		setTrainingLevelMap(trainingLevelMap, LocaleUtil.getDefault());
	}

	@Override
	public void setTrainingLevelMap(
		Map<Locale, String> trainingLevelMap, Locale defaultLocale) {

		if (trainingLevelMap == null) {
			return;
		}

		setTrainingLevel(
			LocalizationUtil.updateLocalization(
				trainingLevelMap, getTrainingLevel(), "TrainingLevel",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public int getBlock() {
		return _block;
	}

	@Override
	public void setBlock(int block) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_block = block;
	}

	@JSON
	@Override
	public int getWeek() {
		return _week;
	}

	@Override
	public void setWeek(int week) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_week = week;
	}

	@JSON
	@Override
	public int getMaxTraineeApplyLeave() {
		return _maxTraineeApplyLeave;
	}

	@Override
	public void setMaxTraineeApplyLeave(int maxTraineeApplyLeave) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_maxTraineeApplyLeave = maxTraineeApplyLeave;
	}

	@JSON
	@Override
	public int getNoOfTraineeTakenLeave() {
		return _noOfTraineeTakenLeave;
	}

	@Override
	public void setNoOfTraineeTakenLeave(int noOfTraineeTakenLeave) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noOfTraineeTakenLeave = noOfTraineeTakenLeave;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveAnnualMaxTrainee.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveAnnualMaxTrainee.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> trainingLevelMap = getTrainingLevelMap();

		for (Map.Entry<Locale, String> entry : trainingLevelMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTrainingLevel();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			LeaveAnnualMaxTrainee.class.getName(), getPrimaryKey(),
			defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String trainingLevel = getTrainingLevel(defaultLocale);

		if (Validator.isNull(trainingLevel)) {
			setTrainingLevel(
				getTrainingLevel(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTrainingLevel(
				getTrainingLevel(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public LeaveAnnualMaxTrainee toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveAnnualMaxTrainee>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveAnnualMaxTraineeImpl leaveAnnualMaxTraineeImpl =
			new LeaveAnnualMaxTraineeImpl();

		leaveAnnualMaxTraineeImpl.setUuid(getUuid());
		leaveAnnualMaxTraineeImpl.setLeaveAnnualMaxTraineeId(
			getLeaveAnnualMaxTraineeId());
		leaveAnnualMaxTraineeImpl.setLeaveAnnualRuleId(getLeaveAnnualRuleId());
		leaveAnnualMaxTraineeImpl.setTrainingLevel(getTrainingLevel());
		leaveAnnualMaxTraineeImpl.setBlock(getBlock());
		leaveAnnualMaxTraineeImpl.setWeek(getWeek());
		leaveAnnualMaxTraineeImpl.setMaxTraineeApplyLeave(
			getMaxTraineeApplyLeave());
		leaveAnnualMaxTraineeImpl.setNoOfTraineeTakenLeave(
			getNoOfTraineeTakenLeave());
		leaveAnnualMaxTraineeImpl.setGroupId(getGroupId());
		leaveAnnualMaxTraineeImpl.setCompanyId(getCompanyId());
		leaveAnnualMaxTraineeImpl.setCreateDate(getCreateDate());
		leaveAnnualMaxTraineeImpl.setCreatedBy(getCreatedBy());
		leaveAnnualMaxTraineeImpl.setModifiedDate(getModifiedDate());
		leaveAnnualMaxTraineeImpl.setModifiedBy(getModifiedBy());

		leaveAnnualMaxTraineeImpl.resetOriginalValues();

		return leaveAnnualMaxTraineeImpl;
	}

	@Override
	public LeaveAnnualMaxTrainee cloneWithOriginalValues() {
		LeaveAnnualMaxTraineeImpl leaveAnnualMaxTraineeImpl =
			new LeaveAnnualMaxTraineeImpl();

		leaveAnnualMaxTraineeImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		leaveAnnualMaxTraineeImpl.setLeaveAnnualMaxTraineeId(
			this.<Long>getColumnOriginalValue("leave_annual_max_trainee_id"));
		leaveAnnualMaxTraineeImpl.setLeaveAnnualRuleId(
			this.<Long>getColumnOriginalValue("leave_annual_rule_id"));
		leaveAnnualMaxTraineeImpl.setTrainingLevel(
			this.<String>getColumnOriginalValue("training_level"));
		leaveAnnualMaxTraineeImpl.setBlock(
			this.<Integer>getColumnOriginalValue("block"));
		leaveAnnualMaxTraineeImpl.setWeek(
			this.<Integer>getColumnOriginalValue("week"));
		leaveAnnualMaxTraineeImpl.setMaxTraineeApplyLeave(
			this.<Integer>getColumnOriginalValue("max_trainee_apply_leave"));
		leaveAnnualMaxTraineeImpl.setNoOfTraineeTakenLeave(
			this.<Integer>getColumnOriginalValue("no_of_trainee_taken_leave"));
		leaveAnnualMaxTraineeImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		leaveAnnualMaxTraineeImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		leaveAnnualMaxTraineeImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		leaveAnnualMaxTraineeImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		leaveAnnualMaxTraineeImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		leaveAnnualMaxTraineeImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));

		return leaveAnnualMaxTraineeImpl;
	}

	@Override
	public int compareTo(LeaveAnnualMaxTrainee leaveAnnualMaxTrainee) {
		long primaryKey = leaveAnnualMaxTrainee.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveAnnualMaxTrainee)) {
			return false;
		}

		LeaveAnnualMaxTrainee leaveAnnualMaxTrainee =
			(LeaveAnnualMaxTrainee)object;

		long primaryKey = leaveAnnualMaxTrainee.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveAnnualMaxTrainee> toCacheModel() {
		LeaveAnnualMaxTraineeCacheModel leaveAnnualMaxTraineeCacheModel =
			new LeaveAnnualMaxTraineeCacheModel();

		leaveAnnualMaxTraineeCacheModel.uuid = getUuid();

		String uuid = leaveAnnualMaxTraineeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveAnnualMaxTraineeCacheModel.uuid = null;
		}

		leaveAnnualMaxTraineeCacheModel.leaveAnnualMaxTraineeId =
			getLeaveAnnualMaxTraineeId();

		leaveAnnualMaxTraineeCacheModel.leaveAnnualRuleId =
			getLeaveAnnualRuleId();

		leaveAnnualMaxTraineeCacheModel.trainingLevel = getTrainingLevel();

		String trainingLevel = leaveAnnualMaxTraineeCacheModel.trainingLevel;

		if ((trainingLevel != null) && (trainingLevel.length() == 0)) {
			leaveAnnualMaxTraineeCacheModel.trainingLevel = null;
		}

		leaveAnnualMaxTraineeCacheModel.block = getBlock();

		leaveAnnualMaxTraineeCacheModel.week = getWeek();

		leaveAnnualMaxTraineeCacheModel.maxTraineeApplyLeave =
			getMaxTraineeApplyLeave();

		leaveAnnualMaxTraineeCacheModel.noOfTraineeTakenLeave =
			getNoOfTraineeTakenLeave();

		leaveAnnualMaxTraineeCacheModel.groupId = getGroupId();

		leaveAnnualMaxTraineeCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveAnnualMaxTraineeCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveAnnualMaxTraineeCacheModel.createDate = Long.MIN_VALUE;
		}

		leaveAnnualMaxTraineeCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveAnnualMaxTraineeCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			leaveAnnualMaxTraineeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveAnnualMaxTraineeCacheModel.modifiedBy = getModifiedBy();

		return leaveAnnualMaxTraineeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveAnnualMaxTrainee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveAnnualMaxTrainee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveAnnualMaxTrainee, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LeaveAnnualMaxTrainee)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveAnnualMaxTrainee>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveAnnualMaxTrainee.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _leaveAnnualMaxTraineeId;
	private long _leaveAnnualRuleId;
	private String _trainingLevel;
	private String _trainingLevelCurrentLanguageId;
	private int _block;
	private int _week;
	private int _maxTraineeApplyLeave;
	private int _noOfTraineeTakenLeave;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveAnnualMaxTrainee, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveAnnualMaxTrainee)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"leave_annual_max_trainee_id", _leaveAnnualMaxTraineeId);
		_columnOriginalValues.put("leave_annual_rule_id", _leaveAnnualRuleId);
		_columnOriginalValues.put("training_level", _trainingLevel);
		_columnOriginalValues.put("block", _block);
		_columnOriginalValues.put("week", _week);
		_columnOriginalValues.put(
			"max_trainee_apply_leave", _maxTraineeApplyLeave);
		_columnOriginalValues.put(
			"no_of_trainee_taken_leave", _noOfTraineeTakenLeave);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"leave_annual_max_trainee_id", "leaveAnnualMaxTraineeId");
		attributeNames.put("leave_annual_rule_id", "leaveAnnualRuleId");
		attributeNames.put("training_level", "trainingLevel");
		attributeNames.put("max_trainee_apply_leave", "maxTraineeApplyLeave");
		attributeNames.put(
			"no_of_trainee_taken_leave", "noOfTraineeTakenLeave");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("leave_annual_max_trainee_id", 2L);

		columnBitmasks.put("leave_annual_rule_id", 4L);

		columnBitmasks.put("training_level", 8L);

		columnBitmasks.put("block", 16L);

		columnBitmasks.put("week", 32L);

		columnBitmasks.put("max_trainee_apply_leave", 64L);

		columnBitmasks.put("no_of_trainee_taken_leave", 128L);

		columnBitmasks.put("group_id", 256L);

		columnBitmasks.put("company_id", 512L);

		columnBitmasks.put("create_date", 1024L);

		columnBitmasks.put("created_by", 2048L);

		columnBitmasks.put("modified_date", 4096L);

		columnBitmasks.put("modified_by", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveAnnualMaxTrainee _escapedModel;

}