/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.LeaveTypes;
import gov.omsb.tms.model.LeaveTypesModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveTypes service. Represents a row in the &quot;leave_types&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveTypesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveTypesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveTypesImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveTypesModelImpl
	extends BaseModelImpl<LeaveTypes> implements LeaveTypesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave types model instance should use the <code>LeaveTypes</code> interface instead.
	 */
	public static final String TABLE_NAME = "leave_types";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"leave_types_id", Types.BIGINT},
		{"leave_types", Types.VARCHAR}, {"leave_code", Types.VARCHAR},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leave_types_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leave_types", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leave_code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table leave_types (uuid_ VARCHAR(75) null,leave_types_id LONG not null primary key,leave_types STRING null,leave_code STRING null,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG)";

	public static final String TABLE_SQL_DROP = "drop table leave_types";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveTypes.leaveTypesId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY leave_types.leave_types_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVETYPESID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveTypesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveTypesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveTypesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveTypesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveTypes.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveTypes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveTypes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveTypes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveTypes, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LeaveTypes)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveTypes, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveTypes, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveTypes)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveTypes, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveTypes, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LeaveTypes, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LeaveTypes, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LeaveTypes, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LeaveTypes, Object>>();
		Map<String, BiConsumer<LeaveTypes, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LeaveTypes, ?>>();

		attributeGetterFunctions.put("uuid", LeaveTypes::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<LeaveTypes, String>)LeaveTypes::setUuid);
		attributeGetterFunctions.put(
			"leaveTypesId", LeaveTypes::getLeaveTypesId);
		attributeSetterBiConsumers.put(
			"leaveTypesId",
			(BiConsumer<LeaveTypes, Long>)LeaveTypes::setLeaveTypesId);
		attributeGetterFunctions.put("leaveTypes", LeaveTypes::getLeaveTypes);
		attributeSetterBiConsumers.put(
			"leaveTypes",
			(BiConsumer<LeaveTypes, String>)LeaveTypes::setLeaveTypes);
		attributeGetterFunctions.put("leaveCode", LeaveTypes::getLeaveCode);
		attributeSetterBiConsumers.put(
			"leaveCode",
			(BiConsumer<LeaveTypes, String>)LeaveTypes::setLeaveCode);
		attributeGetterFunctions.put("groupId", LeaveTypes::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<LeaveTypes, Long>)LeaveTypes::setGroupId);
		attributeGetterFunctions.put("companyId", LeaveTypes::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LeaveTypes, Long>)LeaveTypes::setCompanyId);
		attributeGetterFunctions.put("createDate", LeaveTypes::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LeaveTypes, Date>)LeaveTypes::setCreateDate);
		attributeGetterFunctions.put("createdBy", LeaveTypes::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<LeaveTypes, Long>)LeaveTypes::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", LeaveTypes::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LeaveTypes, Date>)LeaveTypes::setModifiedDate);
		attributeGetterFunctions.put("modifiedBy", LeaveTypes::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<LeaveTypes, Long>)LeaveTypes::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLeaveTypesId() {
		return _leaveTypesId;
	}

	@Override
	public void setLeaveTypesId(long leaveTypesId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypesId = leaveTypesId;
	}

	@JSON
	@Override
	public String getLeaveTypes() {
		if (_leaveTypes == null) {
			return "";
		}
		else {
			return _leaveTypes;
		}
	}

	@Override
	public String getLeaveTypes(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLeaveTypes(languageId);
	}

	@Override
	public String getLeaveTypes(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLeaveTypes(languageId, useDefault);
	}

	@Override
	public String getLeaveTypes(String languageId) {
		return LocalizationUtil.getLocalization(getLeaveTypes(), languageId);
	}

	@Override
	public String getLeaveTypes(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getLeaveTypes(), languageId, useDefault);
	}

	@Override
	public String getLeaveTypesCurrentLanguageId() {
		return _leaveTypesCurrentLanguageId;
	}

	@JSON
	@Override
	public String getLeaveTypesCurrentValue() {
		Locale locale = getLocale(_leaveTypesCurrentLanguageId);

		return getLeaveTypes(locale);
	}

	@Override
	public Map<Locale, String> getLeaveTypesMap() {
		return LocalizationUtil.getLocalizationMap(getLeaveTypes());
	}

	@Override
	public void setLeaveTypes(String leaveTypes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypes = leaveTypes;
	}

	@Override
	public void setLeaveTypes(String leaveTypes, Locale locale) {
		setLeaveTypes(leaveTypes, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setLeaveTypes(
		String leaveTypes, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(leaveTypes)) {
			setLeaveTypes(
				LocalizationUtil.updateLocalization(
					getLeaveTypes(), "LeaveTypes", leaveTypes, languageId,
					defaultLanguageId));
		}
		else {
			setLeaveTypes(
				LocalizationUtil.removeLocalization(
					getLeaveTypes(), "LeaveTypes", languageId));
		}
	}

	@Override
	public void setLeaveTypesCurrentLanguageId(String languageId) {
		_leaveTypesCurrentLanguageId = languageId;
	}

	@Override
	public void setLeaveTypesMap(Map<Locale, String> leaveTypesMap) {
		setLeaveTypesMap(leaveTypesMap, LocaleUtil.getDefault());
	}

	@Override
	public void setLeaveTypesMap(
		Map<Locale, String> leaveTypesMap, Locale defaultLocale) {

		if (leaveTypesMap == null) {
			return;
		}

		setLeaveTypes(
			LocalizationUtil.updateLocalization(
				leaveTypesMap, getLeaveTypes(), "LeaveTypes",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getLeaveCode() {
		if (_leaveCode == null) {
			return "";
		}
		else {
			return _leaveCode;
		}
	}

	@Override
	public String getLeaveCode(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLeaveCode(languageId);
	}

	@Override
	public String getLeaveCode(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLeaveCode(languageId, useDefault);
	}

	@Override
	public String getLeaveCode(String languageId) {
		return LocalizationUtil.getLocalization(getLeaveCode(), languageId);
	}

	@Override
	public String getLeaveCode(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getLeaveCode(), languageId, useDefault);
	}

	@Override
	public String getLeaveCodeCurrentLanguageId() {
		return _leaveCodeCurrentLanguageId;
	}

	@JSON
	@Override
	public String getLeaveCodeCurrentValue() {
		Locale locale = getLocale(_leaveCodeCurrentLanguageId);

		return getLeaveCode(locale);
	}

	@Override
	public Map<Locale, String> getLeaveCodeMap() {
		return LocalizationUtil.getLocalizationMap(getLeaveCode());
	}

	@Override
	public void setLeaveCode(String leaveCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveCode = leaveCode;
	}

	@Override
	public void setLeaveCode(String leaveCode, Locale locale) {
		setLeaveCode(leaveCode, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setLeaveCode(
		String leaveCode, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(leaveCode)) {
			setLeaveCode(
				LocalizationUtil.updateLocalization(
					getLeaveCode(), "LeaveCode", leaveCode, languageId,
					defaultLanguageId));
		}
		else {
			setLeaveCode(
				LocalizationUtil.removeLocalization(
					getLeaveCode(), "LeaveCode", languageId));
		}
	}

	@Override
	public void setLeaveCodeCurrentLanguageId(String languageId) {
		_leaveCodeCurrentLanguageId = languageId;
	}

	@Override
	public void setLeaveCodeMap(Map<Locale, String> leaveCodeMap) {
		setLeaveCodeMap(leaveCodeMap, LocaleUtil.getDefault());
	}

	@Override
	public void setLeaveCodeMap(
		Map<Locale, String> leaveCodeMap, Locale defaultLocale) {

		if (leaveCodeMap == null) {
			return;
		}

		setLeaveCode(
			LocalizationUtil.updateLocalization(
				leaveCodeMap, getLeaveCode(), "LeaveCode",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveTypes.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveTypes.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> leaveTypesMap = getLeaveTypesMap();

		for (Map.Entry<Locale, String> entry : leaveTypesMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> leaveCodeMap = getLeaveCodeMap();

		for (Map.Entry<Locale, String> entry : leaveCodeMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getLeaveTypes();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			LeaveTypes.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String leaveTypes = getLeaveTypes(defaultLocale);

		if (Validator.isNull(leaveTypes)) {
			setLeaveTypes(getLeaveTypes(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setLeaveTypes(
				getLeaveTypes(defaultLocale), defaultLocale, defaultLocale);
		}

		String leaveCode = getLeaveCode(defaultLocale);

		if (Validator.isNull(leaveCode)) {
			setLeaveCode(getLeaveCode(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setLeaveCode(
				getLeaveCode(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public LeaveTypes toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveTypes>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveTypesImpl leaveTypesImpl = new LeaveTypesImpl();

		leaveTypesImpl.setUuid(getUuid());
		leaveTypesImpl.setLeaveTypesId(getLeaveTypesId());
		leaveTypesImpl.setLeaveTypes(getLeaveTypes());
		leaveTypesImpl.setLeaveCode(getLeaveCode());
		leaveTypesImpl.setGroupId(getGroupId());
		leaveTypesImpl.setCompanyId(getCompanyId());
		leaveTypesImpl.setCreateDate(getCreateDate());
		leaveTypesImpl.setCreatedBy(getCreatedBy());
		leaveTypesImpl.setModifiedDate(getModifiedDate());
		leaveTypesImpl.setModifiedBy(getModifiedBy());

		leaveTypesImpl.resetOriginalValues();

		return leaveTypesImpl;
	}

	@Override
	public LeaveTypes cloneWithOriginalValues() {
		LeaveTypesImpl leaveTypesImpl = new LeaveTypesImpl();

		leaveTypesImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		leaveTypesImpl.setLeaveTypesId(
			this.<Long>getColumnOriginalValue("leave_types_id"));
		leaveTypesImpl.setLeaveTypes(
			this.<String>getColumnOriginalValue("leave_types"));
		leaveTypesImpl.setLeaveCode(
			this.<String>getColumnOriginalValue("leave_code"));
		leaveTypesImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		leaveTypesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		leaveTypesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		leaveTypesImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		leaveTypesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		leaveTypesImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));

		return leaveTypesImpl;
	}

	@Override
	public int compareTo(LeaveTypes leaveTypes) {
		long primaryKey = leaveTypes.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveTypes)) {
			return false;
		}

		LeaveTypes leaveTypes = (LeaveTypes)object;

		long primaryKey = leaveTypes.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveTypes> toCacheModel() {
		LeaveTypesCacheModel leaveTypesCacheModel = new LeaveTypesCacheModel();

		leaveTypesCacheModel.uuid = getUuid();

		String uuid = leaveTypesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveTypesCacheModel.uuid = null;
		}

		leaveTypesCacheModel.leaveTypesId = getLeaveTypesId();

		leaveTypesCacheModel.leaveTypes = getLeaveTypes();

		String leaveTypes = leaveTypesCacheModel.leaveTypes;

		if ((leaveTypes != null) && (leaveTypes.length() == 0)) {
			leaveTypesCacheModel.leaveTypes = null;
		}

		leaveTypesCacheModel.leaveCode = getLeaveCode();

		String leaveCode = leaveTypesCacheModel.leaveCode;

		if ((leaveCode != null) && (leaveCode.length() == 0)) {
			leaveTypesCacheModel.leaveCode = null;
		}

		leaveTypesCacheModel.groupId = getGroupId();

		leaveTypesCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveTypesCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveTypesCacheModel.createDate = Long.MIN_VALUE;
		}

		leaveTypesCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveTypesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveTypesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveTypesCacheModel.modifiedBy = getModifiedBy();

		return leaveTypesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveTypes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveTypes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveTypes, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LeaveTypes)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveTypes>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveTypes.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _leaveTypesId;
	private String _leaveTypes;
	private String _leaveTypesCurrentLanguageId;
	private String _leaveCode;
	private String _leaveCodeCurrentLanguageId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveTypes, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveTypes)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("leave_types_id", _leaveTypesId);
		_columnOriginalValues.put("leave_types", _leaveTypes);
		_columnOriginalValues.put("leave_code", _leaveCode);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("leave_types_id", "leaveTypesId");
		attributeNames.put("leave_types", "leaveTypes");
		attributeNames.put("leave_code", "leaveCode");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("leave_types_id", 2L);

		columnBitmasks.put("leave_types", 4L);

		columnBitmasks.put("leave_code", 8L);

		columnBitmasks.put("group_id", 16L);

		columnBitmasks.put("company_id", 32L);

		columnBitmasks.put("create_date", 64L);

		columnBitmasks.put("created_by", 128L);

		columnBitmasks.put("modified_date", 256L);

		columnBitmasks.put("modified_by", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveTypes _escapedModel;

}