/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.ParticipationTypeMaster;
import gov.omsb.tms.model.ParticipationTypeMasterModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ParticipationTypeMaster service. Represents a row in the &quot;participation_type_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ParticipationTypeMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParticipationTypeMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParticipationTypeMasterImpl
 * @generated
 */
@JSON(strict = true)
public class ParticipationTypeMasterModelImpl
	extends BaseModelImpl<ParticipationTypeMaster>
	implements ParticipationTypeMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a participation type master model instance should use the <code>ParticipationTypeMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "participation_type_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR},
		{"participation_type_master_id", Types.BIGINT},
		{"program_duration_id", Types.BIGINT}, {"group_id", Types.BIGINT},
		{"company_id", Types.BIGINT}, {"create_date", Types.TIMESTAMP},
		{"created_by", Types.BIGINT}, {"modified_date", Types.TIMESTAMP},
		{"modified_by", Types.BIGINT},
		{"participation_type_name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("participation_type_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_duration_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("participation_type_name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table participation_type_master (uuid_ VARCHAR(75) null,participation_type_master_id LONG not null primary key,program_duration_id LONG,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,participation_type_name STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table participation_type_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY participationTypeMaster.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY participation_type_master.modified_date DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARTICIPATIONTYPENAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMDURATIONID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ParticipationTypeMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _participationTypeMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setParticipationTypeMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _participationTypeMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ParticipationTypeMaster.class;
	}

	@Override
	public String getModelClassName() {
		return ParticipationTypeMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ParticipationTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ParticipationTypeMaster, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ParticipationTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ParticipationTypeMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ParticipationTypeMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ParticipationTypeMaster, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ParticipationTypeMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ParticipationTypeMaster, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ParticipationTypeMaster, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ParticipationTypeMaster, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<ParticipationTypeMaster, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<ParticipationTypeMaster, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ParticipationTypeMaster, Object>>();
		Map<String, BiConsumer<ParticipationTypeMaster, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ParticipationTypeMaster, ?>>();

		attributeGetterFunctions.put("uuid", ParticipationTypeMaster::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ParticipationTypeMaster, String>)
				ParticipationTypeMaster::setUuid);
		attributeGetterFunctions.put(
			"participationTypeMasterId",
			ParticipationTypeMaster::getParticipationTypeMasterId);
		attributeSetterBiConsumers.put(
			"participationTypeMasterId",
			(BiConsumer<ParticipationTypeMaster, Long>)
				ParticipationTypeMaster::setParticipationTypeMasterId);
		attributeGetterFunctions.put(
			"programDurationId", ParticipationTypeMaster::getProgramDurationId);
		attributeSetterBiConsumers.put(
			"programDurationId",
			(BiConsumer<ParticipationTypeMaster, Long>)
				ParticipationTypeMaster::setProgramDurationId);
		attributeGetterFunctions.put(
			"groupId", ParticipationTypeMaster::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ParticipationTypeMaster, Long>)
				ParticipationTypeMaster::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ParticipationTypeMaster::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ParticipationTypeMaster, Long>)
				ParticipationTypeMaster::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", ParticipationTypeMaster::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ParticipationTypeMaster, Date>)
				ParticipationTypeMaster::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", ParticipationTypeMaster::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ParticipationTypeMaster, Long>)
				ParticipationTypeMaster::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", ParticipationTypeMaster::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ParticipationTypeMaster, Date>)
				ParticipationTypeMaster::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", ParticipationTypeMaster::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ParticipationTypeMaster, Long>)
				ParticipationTypeMaster::setModifiedBy);
		attributeGetterFunctions.put(
			"participationTypeName",
			ParticipationTypeMaster::getParticipationTypeName);
		attributeSetterBiConsumers.put(
			"participationTypeName",
			(BiConsumer<ParticipationTypeMaster, String>)
				ParticipationTypeMaster::setParticipationTypeName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getParticipationTypeMasterId() {
		return _participationTypeMasterId;
	}

	@Override
	public void setParticipationTypeMasterId(long participationTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_participationTypeMasterId = participationTypeMasterId;
	}

	@JSON
	@Override
	public long getProgramDurationId() {
		return _programDurationId;
	}

	@Override
	public void setProgramDurationId(long programDurationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programDurationId = programDurationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgramDurationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("program_duration_id"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public String getParticipationTypeName() {
		if (_participationTypeName == null) {
			return "";
		}
		else {
			return _participationTypeName;
		}
	}

	@Override
	public String getParticipationTypeName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getParticipationTypeName(languageId);
	}

	@Override
	public String getParticipationTypeName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getParticipationTypeName(languageId, useDefault);
	}

	@Override
	public String getParticipationTypeName(String languageId) {
		return LocalizationUtil.getLocalization(
			getParticipationTypeName(), languageId);
	}

	@Override
	public String getParticipationTypeName(
		String languageId, boolean useDefault) {

		return LocalizationUtil.getLocalization(
			getParticipationTypeName(), languageId, useDefault);
	}

	@Override
	public String getParticipationTypeNameCurrentLanguageId() {
		return _participationTypeNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getParticipationTypeNameCurrentValue() {
		Locale locale = getLocale(_participationTypeNameCurrentLanguageId);

		return getParticipationTypeName(locale);
	}

	@Override
	public Map<Locale, String> getParticipationTypeNameMap() {
		return LocalizationUtil.getLocalizationMap(getParticipationTypeName());
	}

	@Override
	public void setParticipationTypeName(String participationTypeName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_participationTypeName = participationTypeName;
	}

	@Override
	public void setParticipationTypeName(
		String participationTypeName, Locale locale) {

		setParticipationTypeName(
			participationTypeName, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setParticipationTypeName(
		String participationTypeName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(participationTypeName)) {
			setParticipationTypeName(
				LocalizationUtil.updateLocalization(
					getParticipationTypeName(), "ParticipationTypeName",
					participationTypeName, languageId, defaultLanguageId));
		}
		else {
			setParticipationTypeName(
				LocalizationUtil.removeLocalization(
					getParticipationTypeName(), "ParticipationTypeName",
					languageId));
		}
	}

	@Override
	public void setParticipationTypeNameCurrentLanguageId(String languageId) {
		_participationTypeNameCurrentLanguageId = languageId;
	}

	@Override
	public void setParticipationTypeNameMap(
		Map<Locale, String> participationTypeNameMap) {

		setParticipationTypeNameMap(
			participationTypeNameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setParticipationTypeNameMap(
		Map<Locale, String> participationTypeNameMap, Locale defaultLocale) {

		if (participationTypeNameMap == null) {
			return;
		}

		setParticipationTypeName(
			LocalizationUtil.updateLocalization(
				participationTypeNameMap, getParticipationTypeName(),
				"ParticipationTypeName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalParticipationTypeName() {
		return getColumnOriginalValue("participation_type_name");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ParticipationTypeMaster.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ParticipationTypeMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> participationTypeNameMap =
			getParticipationTypeNameMap();

		for (Map.Entry<Locale, String> entry :
				participationTypeNameMap.entrySet()) {

			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getParticipationTypeName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			ParticipationTypeMaster.class.getName(), getPrimaryKey(),
			defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String participationTypeName = getParticipationTypeName(defaultLocale);

		if (Validator.isNull(participationTypeName)) {
			setParticipationTypeName(
				getParticipationTypeName(modelDefaultLanguageId),
				defaultLocale);
		}
		else {
			setParticipationTypeName(
				getParticipationTypeName(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public ParticipationTypeMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ParticipationTypeMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParticipationTypeMasterImpl participationTypeMasterImpl =
			new ParticipationTypeMasterImpl();

		participationTypeMasterImpl.setUuid(getUuid());
		participationTypeMasterImpl.setParticipationTypeMasterId(
			getParticipationTypeMasterId());
		participationTypeMasterImpl.setProgramDurationId(
			getProgramDurationId());
		participationTypeMasterImpl.setGroupId(getGroupId());
		participationTypeMasterImpl.setCompanyId(getCompanyId());
		participationTypeMasterImpl.setCreateDate(getCreateDate());
		participationTypeMasterImpl.setCreatedBy(getCreatedBy());
		participationTypeMasterImpl.setModifiedDate(getModifiedDate());
		participationTypeMasterImpl.setModifiedBy(getModifiedBy());
		participationTypeMasterImpl.setParticipationTypeName(
			getParticipationTypeName());

		participationTypeMasterImpl.resetOriginalValues();

		return participationTypeMasterImpl;
	}

	@Override
	public ParticipationTypeMaster cloneWithOriginalValues() {
		ParticipationTypeMasterImpl participationTypeMasterImpl =
			new ParticipationTypeMasterImpl();

		participationTypeMasterImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		participationTypeMasterImpl.setParticipationTypeMasterId(
			this.<Long>getColumnOriginalValue("participation_type_master_id"));
		participationTypeMasterImpl.setProgramDurationId(
			this.<Long>getColumnOriginalValue("program_duration_id"));
		participationTypeMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		participationTypeMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		participationTypeMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		participationTypeMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		participationTypeMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		participationTypeMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		participationTypeMasterImpl.setParticipationTypeName(
			this.<String>getColumnOriginalValue("participation_type_name"));

		return participationTypeMasterImpl;
	}

	@Override
	public int compareTo(ParticipationTypeMaster participationTypeMaster) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), participationTypeMaster.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ParticipationTypeMaster)) {
			return false;
		}

		ParticipationTypeMaster participationTypeMaster =
			(ParticipationTypeMaster)object;

		long primaryKey = participationTypeMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ParticipationTypeMaster> toCacheModel() {
		ParticipationTypeMasterCacheModel participationTypeMasterCacheModel =
			new ParticipationTypeMasterCacheModel();

		participationTypeMasterCacheModel.uuid = getUuid();

		String uuid = participationTypeMasterCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			participationTypeMasterCacheModel.uuid = null;
		}

		participationTypeMasterCacheModel.participationTypeMasterId =
			getParticipationTypeMasterId();

		participationTypeMasterCacheModel.programDurationId =
			getProgramDurationId();

		participationTypeMasterCacheModel.groupId = getGroupId();

		participationTypeMasterCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			participationTypeMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			participationTypeMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		participationTypeMasterCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			participationTypeMasterCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			participationTypeMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		participationTypeMasterCacheModel.modifiedBy = getModifiedBy();

		participationTypeMasterCacheModel.participationTypeName =
			getParticipationTypeName();

		String participationTypeName =
			participationTypeMasterCacheModel.participationTypeName;

		if ((participationTypeName != null) &&
			(participationTypeName.length() == 0)) {

			participationTypeMasterCacheModel.participationTypeName = null;
		}

		return participationTypeMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ParticipationTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ParticipationTypeMaster, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ParticipationTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ParticipationTypeMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ParticipationTypeMaster>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ParticipationTypeMaster.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _participationTypeMasterId;
	private long _programDurationId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private String _participationTypeName;
	private String _participationTypeNameCurrentLanguageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ParticipationTypeMaster, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ParticipationTypeMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"participation_type_master_id", _participationTypeMasterId);
		_columnOriginalValues.put("program_duration_id", _programDurationId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put(
			"participation_type_name", _participationTypeName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"participation_type_master_id", "participationTypeMasterId");
		attributeNames.put("program_duration_id", "programDurationId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("participation_type_name", "participationTypeName");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("participation_type_master_id", 2L);

		columnBitmasks.put("program_duration_id", 4L);

		columnBitmasks.put("group_id", 8L);

		columnBitmasks.put("company_id", 16L);

		columnBitmasks.put("create_date", 32L);

		columnBitmasks.put("created_by", 64L);

		columnBitmasks.put("modified_date", 128L);

		columnBitmasks.put("modified_by", 256L);

		columnBitmasks.put("participation_type_name", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ParticipationTypeMaster _escapedModel;

}