/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.PatientTypeProgDurationRel;
import gov.omsb.tms.model.PatientTypeProgDurationRelModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PatientTypeProgDurationRel service. Represents a row in the &quot;patient_type_prog_duration_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PatientTypeProgDurationRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatientTypeProgDurationRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PatientTypeProgDurationRelImpl
 * @generated
 */
@JSON(strict = true)
public class PatientTypeProgDurationRelModelImpl
	extends BaseModelImpl<PatientTypeProgDurationRel>
	implements PatientTypeProgDurationRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patient type prog duration rel model instance should use the <code>PatientTypeProgDurationRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "patient_type_prog_duration_rel";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR},
		{"patient_type_prog_duration_rel_id", Types.BIGINT},
		{"patient_type_master_id", Types.BIGINT},
		{"program_duration_id", Types.BIGINT}, {"group_id", Types.BIGINT},
		{"company_id", Types.BIGINT}, {"create_date", Types.TIMESTAMP},
		{"created_by", Types.BIGINT}, {"modified_date", Types.TIMESTAMP},
		{"modified_by", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put(
			"patient_type_prog_duration_rel_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("patient_type_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_duration_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table patient_type_prog_duration_rel (uuid_ VARCHAR(75) null,patient_type_prog_duration_rel_id LONG not null primary key,patient_type_master_id LONG,program_duration_id LONG,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table patient_type_prog_duration_rel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY patientTypeProgDurationRel.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY patient_type_prog_duration_rel.modified_date DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PATIENTTYPEMASTERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMDURATIONID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PatientTypeProgDurationRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PatientTypeProgDurationRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPatientTypeProgDurationRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PatientTypeProgDurationRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PatientTypeProgDurationRel.class;
	}

	@Override
	public String getModelClassName() {
		return PatientTypeProgDurationRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PatientTypeProgDurationRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PatientTypeProgDurationRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PatientTypeProgDurationRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(PatientTypeProgDurationRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PatientTypeProgDurationRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PatientTypeProgDurationRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PatientTypeProgDurationRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PatientTypeProgDurationRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PatientTypeProgDurationRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<PatientTypeProgDurationRel, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<PatientTypeProgDurationRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<PatientTypeProgDurationRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<PatientTypeProgDurationRel, Object>>();
		Map<String, BiConsumer<PatientTypeProgDurationRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<PatientTypeProgDurationRel, ?>>();

		attributeGetterFunctions.put(
			"uuid", PatientTypeProgDurationRel::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<PatientTypeProgDurationRel, String>)
				PatientTypeProgDurationRel::setUuid);
		attributeGetterFunctions.put(
			"PatientTypeProgDurationRelId",
			PatientTypeProgDurationRel::getPatientTypeProgDurationRelId);
		attributeSetterBiConsumers.put(
			"PatientTypeProgDurationRelId",
			(BiConsumer<PatientTypeProgDurationRel, Long>)
				PatientTypeProgDurationRel::setPatientTypeProgDurationRelId);
		attributeGetterFunctions.put(
			"patientTypeMasterId",
			PatientTypeProgDurationRel::getPatientTypeMasterId);
		attributeSetterBiConsumers.put(
			"patientTypeMasterId",
			(BiConsumer<PatientTypeProgDurationRel, Long>)
				PatientTypeProgDurationRel::setPatientTypeMasterId);
		attributeGetterFunctions.put(
			"programDurationId",
			PatientTypeProgDurationRel::getProgramDurationId);
		attributeSetterBiConsumers.put(
			"programDurationId",
			(BiConsumer<PatientTypeProgDurationRel, Long>)
				PatientTypeProgDurationRel::setProgramDurationId);
		attributeGetterFunctions.put(
			"groupId", PatientTypeProgDurationRel::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<PatientTypeProgDurationRel, Long>)
				PatientTypeProgDurationRel::setGroupId);
		attributeGetterFunctions.put(
			"companyId", PatientTypeProgDurationRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<PatientTypeProgDurationRel, Long>)
				PatientTypeProgDurationRel::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", PatientTypeProgDurationRel::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<PatientTypeProgDurationRel, Date>)
				PatientTypeProgDurationRel::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", PatientTypeProgDurationRel::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<PatientTypeProgDurationRel, Long>)
				PatientTypeProgDurationRel::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", PatientTypeProgDurationRel::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<PatientTypeProgDurationRel, Date>)
				PatientTypeProgDurationRel::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", PatientTypeProgDurationRel::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<PatientTypeProgDurationRel, Long>)
				PatientTypeProgDurationRel::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPatientTypeProgDurationRelId() {
		return _PatientTypeProgDurationRelId;
	}

	@Override
	public void setPatientTypeProgDurationRelId(
		long PatientTypeProgDurationRelId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PatientTypeProgDurationRelId = PatientTypeProgDurationRelId;
	}

	@JSON
	@Override
	public long getPatientTypeMasterId() {
		return _patientTypeMasterId;
	}

	@Override
	public void setPatientTypeMasterId(long patientTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_patientTypeMasterId = patientTypeMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPatientTypeMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("patient_type_master_id"));
	}

	@JSON
	@Override
	public long getProgramDurationId() {
		return _programDurationId;
	}

	@Override
	public void setProgramDurationId(long programDurationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programDurationId = programDurationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgramDurationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("program_duration_id"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				PatientTypeProgDurationRel.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PatientTypeProgDurationRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PatientTypeProgDurationRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PatientTypeProgDurationRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PatientTypeProgDurationRelImpl patientTypeProgDurationRelImpl =
			new PatientTypeProgDurationRelImpl();

		patientTypeProgDurationRelImpl.setUuid(getUuid());
		patientTypeProgDurationRelImpl.setPatientTypeProgDurationRelId(
			getPatientTypeProgDurationRelId());
		patientTypeProgDurationRelImpl.setPatientTypeMasterId(
			getPatientTypeMasterId());
		patientTypeProgDurationRelImpl.setProgramDurationId(
			getProgramDurationId());
		patientTypeProgDurationRelImpl.setGroupId(getGroupId());
		patientTypeProgDurationRelImpl.setCompanyId(getCompanyId());
		patientTypeProgDurationRelImpl.setCreateDate(getCreateDate());
		patientTypeProgDurationRelImpl.setCreatedBy(getCreatedBy());
		patientTypeProgDurationRelImpl.setModifiedDate(getModifiedDate());
		patientTypeProgDurationRelImpl.setModifiedBy(getModifiedBy());

		patientTypeProgDurationRelImpl.resetOriginalValues();

		return patientTypeProgDurationRelImpl;
	}

	@Override
	public PatientTypeProgDurationRel cloneWithOriginalValues() {
		PatientTypeProgDurationRelImpl patientTypeProgDurationRelImpl =
			new PatientTypeProgDurationRelImpl();

		patientTypeProgDurationRelImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		patientTypeProgDurationRelImpl.setPatientTypeProgDurationRelId(
			this.<Long>getColumnOriginalValue(
				"patient_type_prog_duration_rel_id"));
		patientTypeProgDurationRelImpl.setPatientTypeMasterId(
			this.<Long>getColumnOriginalValue("patient_type_master_id"));
		patientTypeProgDurationRelImpl.setProgramDurationId(
			this.<Long>getColumnOriginalValue("program_duration_id"));
		patientTypeProgDurationRelImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		patientTypeProgDurationRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		patientTypeProgDurationRelImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		patientTypeProgDurationRelImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		patientTypeProgDurationRelImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		patientTypeProgDurationRelImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));

		return patientTypeProgDurationRelImpl;
	}

	@Override
	public int compareTo(
		PatientTypeProgDurationRel patientTypeProgDurationRel) {

		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), patientTypeProgDurationRel.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PatientTypeProgDurationRel)) {
			return false;
		}

		PatientTypeProgDurationRel patientTypeProgDurationRel =
			(PatientTypeProgDurationRel)object;

		long primaryKey = patientTypeProgDurationRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PatientTypeProgDurationRel> toCacheModel() {
		PatientTypeProgDurationRelCacheModel
			patientTypeProgDurationRelCacheModel =
				new PatientTypeProgDurationRelCacheModel();

		patientTypeProgDurationRelCacheModel.uuid = getUuid();

		String uuid = patientTypeProgDurationRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			patientTypeProgDurationRelCacheModel.uuid = null;
		}

		patientTypeProgDurationRelCacheModel.PatientTypeProgDurationRelId =
			getPatientTypeProgDurationRelId();

		patientTypeProgDurationRelCacheModel.patientTypeMasterId =
			getPatientTypeMasterId();

		patientTypeProgDurationRelCacheModel.programDurationId =
			getProgramDurationId();

		patientTypeProgDurationRelCacheModel.groupId = getGroupId();

		patientTypeProgDurationRelCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			patientTypeProgDurationRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			patientTypeProgDurationRelCacheModel.createDate = Long.MIN_VALUE;
		}

		patientTypeProgDurationRelCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			patientTypeProgDurationRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			patientTypeProgDurationRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		patientTypeProgDurationRelCacheModel.modifiedBy = getModifiedBy();

		return patientTypeProgDurationRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PatientTypeProgDurationRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PatientTypeProgDurationRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PatientTypeProgDurationRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PatientTypeProgDurationRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, PatientTypeProgDurationRel>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						PatientTypeProgDurationRel.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _PatientTypeProgDurationRelId;
	private long _patientTypeMasterId;
	private long _programDurationId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PatientTypeProgDurationRel, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PatientTypeProgDurationRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"patient_type_prog_duration_rel_id", _PatientTypeProgDurationRelId);
		_columnOriginalValues.put(
			"patient_type_master_id", _patientTypeMasterId);
		_columnOriginalValues.put("program_duration_id", _programDurationId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"patient_type_prog_duration_rel_id",
			"PatientTypeProgDurationRelId");
		attributeNames.put("patient_type_master_id", "patientTypeMasterId");
		attributeNames.put("program_duration_id", "programDurationId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("patient_type_prog_duration_rel_id", 2L);

		columnBitmasks.put("patient_type_master_id", 4L);

		columnBitmasks.put("program_duration_id", 8L);

		columnBitmasks.put("group_id", 16L);

		columnBitmasks.put("company_id", 32L);

		columnBitmasks.put("create_date", 64L);

		columnBitmasks.put("created_by", 128L);

		columnBitmasks.put("modified_date", 256L);

		columnBitmasks.put("modified_by", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PatientTypeProgDurationRel _escapedModel;

}