/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.ProceduregroupProgdurationRel;
import gov.omsb.tms.model.ProceduregroupProgdurationRelModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProceduregroupProgdurationRel service. Represents a row in the &quot;proceduregroup_progduration_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProceduregroupProgdurationRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProceduregroupProgdurationRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProceduregroupProgdurationRelImpl
 * @generated
 */
@JSON(strict = true)
public class ProceduregroupProgdurationRelModelImpl
	extends BaseModelImpl<ProceduregroupProgdurationRel>
	implements ProceduregroupProgdurationRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a proceduregroup progduration rel model instance should use the <code>ProceduregroupProgdurationRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "proceduregroup_progduration_rel";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"pg_pd_rel_id", Types.BIGINT},
		{"procedure_group_master_id", Types.BIGINT},
		{"program_duration_id", Types.BIGINT}, {"group_id", Types.BIGINT},
		{"company_id", Types.BIGINT}, {"create_date", Types.TIMESTAMP},
		{"modified_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_by", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pg_pd_rel_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("procedure_group_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_duration_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table proceduregroup_progduration_rel (uuid_ VARCHAR(75) null,pg_pd_rel_id LONG not null primary key,procedure_group_master_id LONG,program_duration_id LONG,group_id LONG,company_id LONG,create_date DATE null,modified_date DATE null,created_by LONG,modified_by LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table proceduregroup_progduration_rel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY proceduregroupProgdurationRel.pgPdRelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY proceduregroup_progduration_rel.pg_pd_rel_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROCEDUREGROUPMASTERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMDURATIONID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PGPDRELID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProceduregroupProgdurationRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _pgPdRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPgPdRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _pgPdRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProceduregroupProgdurationRel.class;
	}

	@Override
	public String getModelClassName() {
		return ProceduregroupProgdurationRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProceduregroupProgdurationRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProceduregroupProgdurationRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProceduregroupProgdurationRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(ProceduregroupProgdurationRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProceduregroupProgdurationRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProceduregroupProgdurationRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProceduregroupProgdurationRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProceduregroupProgdurationRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProceduregroupProgdurationRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<ProceduregroupProgdurationRel, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<ProceduregroupProgdurationRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProceduregroupProgdurationRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProceduregroupProgdurationRel, Object>>();
		Map<String, BiConsumer<ProceduregroupProgdurationRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ProceduregroupProgdurationRel, ?>>();

		attributeGetterFunctions.put(
			"uuid", ProceduregroupProgdurationRel::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProceduregroupProgdurationRel, String>)
				ProceduregroupProgdurationRel::setUuid);
		attributeGetterFunctions.put(
			"pgPdRelId", ProceduregroupProgdurationRel::getPgPdRelId);
		attributeSetterBiConsumers.put(
			"pgPdRelId",
			(BiConsumer<ProceduregroupProgdurationRel, Long>)
				ProceduregroupProgdurationRel::setPgPdRelId);
		attributeGetterFunctions.put(
			"procedureGroupMasterId",
			ProceduregroupProgdurationRel::getProcedureGroupMasterId);
		attributeSetterBiConsumers.put(
			"procedureGroupMasterId",
			(BiConsumer<ProceduregroupProgdurationRel, Long>)
				ProceduregroupProgdurationRel::setProcedureGroupMasterId);
		attributeGetterFunctions.put(
			"programDurationId",
			ProceduregroupProgdurationRel::getProgramDurationId);
		attributeSetterBiConsumers.put(
			"programDurationId",
			(BiConsumer<ProceduregroupProgdurationRel, Long>)
				ProceduregroupProgdurationRel::setProgramDurationId);
		attributeGetterFunctions.put(
			"groupId", ProceduregroupProgdurationRel::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProceduregroupProgdurationRel, Long>)
				ProceduregroupProgdurationRel::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ProceduregroupProgdurationRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProceduregroupProgdurationRel, Long>)
				ProceduregroupProgdurationRel::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", ProceduregroupProgdurationRel::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProceduregroupProgdurationRel, Date>)
				ProceduregroupProgdurationRel::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ProceduregroupProgdurationRel::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProceduregroupProgdurationRel, Date>)
				ProceduregroupProgdurationRel::setModifiedDate);
		attributeGetterFunctions.put(
			"createdBy", ProceduregroupProgdurationRel::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ProceduregroupProgdurationRel, Long>)
				ProceduregroupProgdurationRel::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", ProceduregroupProgdurationRel::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ProceduregroupProgdurationRel, Long>)
				ProceduregroupProgdurationRel::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPgPdRelId() {
		return _pgPdRelId;
	}

	@Override
	public void setPgPdRelId(long pgPdRelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pgPdRelId = pgPdRelId;
	}

	@JSON
	@Override
	public long getProcedureGroupMasterId() {
		return _procedureGroupMasterId;
	}

	@Override
	public void setProcedureGroupMasterId(long procedureGroupMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_procedureGroupMasterId = procedureGroupMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProcedureGroupMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("procedure_group_master_id"));
	}

	@JSON
	@Override
	public long getProgramDurationId() {
		return _programDurationId;
	}

	@Override
	public void setProgramDurationId(long programDurationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programDurationId = programDurationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgramDurationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("program_duration_id"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				ProceduregroupProgdurationRel.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProceduregroupProgdurationRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProceduregroupProgdurationRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProceduregroupProgdurationRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProceduregroupProgdurationRelImpl proceduregroupProgdurationRelImpl =
			new ProceduregroupProgdurationRelImpl();

		proceduregroupProgdurationRelImpl.setUuid(getUuid());
		proceduregroupProgdurationRelImpl.setPgPdRelId(getPgPdRelId());
		proceduregroupProgdurationRelImpl.setProcedureGroupMasterId(
			getProcedureGroupMasterId());
		proceduregroupProgdurationRelImpl.setProgramDurationId(
			getProgramDurationId());
		proceduregroupProgdurationRelImpl.setGroupId(getGroupId());
		proceduregroupProgdurationRelImpl.setCompanyId(getCompanyId());
		proceduregroupProgdurationRelImpl.setCreateDate(getCreateDate());
		proceduregroupProgdurationRelImpl.setModifiedDate(getModifiedDate());
		proceduregroupProgdurationRelImpl.setCreatedBy(getCreatedBy());
		proceduregroupProgdurationRelImpl.setModifiedBy(getModifiedBy());

		proceduregroupProgdurationRelImpl.resetOriginalValues();

		return proceduregroupProgdurationRelImpl;
	}

	@Override
	public ProceduregroupProgdurationRel cloneWithOriginalValues() {
		ProceduregroupProgdurationRelImpl proceduregroupProgdurationRelImpl =
			new ProceduregroupProgdurationRelImpl();

		proceduregroupProgdurationRelImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		proceduregroupProgdurationRelImpl.setPgPdRelId(
			this.<Long>getColumnOriginalValue("pg_pd_rel_id"));
		proceduregroupProgdurationRelImpl.setProcedureGroupMasterId(
			this.<Long>getColumnOriginalValue("procedure_group_master_id"));
		proceduregroupProgdurationRelImpl.setProgramDurationId(
			this.<Long>getColumnOriginalValue("program_duration_id"));
		proceduregroupProgdurationRelImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		proceduregroupProgdurationRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		proceduregroupProgdurationRelImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		proceduregroupProgdurationRelImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		proceduregroupProgdurationRelImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		proceduregroupProgdurationRelImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));

		return proceduregroupProgdurationRelImpl;
	}

	@Override
	public int compareTo(
		ProceduregroupProgdurationRel proceduregroupProgdurationRel) {

		long primaryKey = proceduregroupProgdurationRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProceduregroupProgdurationRel)) {
			return false;
		}

		ProceduregroupProgdurationRel proceduregroupProgdurationRel =
			(ProceduregroupProgdurationRel)object;

		long primaryKey = proceduregroupProgdurationRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProceduregroupProgdurationRel> toCacheModel() {
		ProceduregroupProgdurationRelCacheModel
			proceduregroupProgdurationRelCacheModel =
				new ProceduregroupProgdurationRelCacheModel();

		proceduregroupProgdurationRelCacheModel.uuid = getUuid();

		String uuid = proceduregroupProgdurationRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			proceduregroupProgdurationRelCacheModel.uuid = null;
		}

		proceduregroupProgdurationRelCacheModel.pgPdRelId = getPgPdRelId();

		proceduregroupProgdurationRelCacheModel.procedureGroupMasterId =
			getProcedureGroupMasterId();

		proceduregroupProgdurationRelCacheModel.programDurationId =
			getProgramDurationId();

		proceduregroupProgdurationRelCacheModel.groupId = getGroupId();

		proceduregroupProgdurationRelCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			proceduregroupProgdurationRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			proceduregroupProgdurationRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			proceduregroupProgdurationRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			proceduregroupProgdurationRelCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		proceduregroupProgdurationRelCacheModel.createdBy = getCreatedBy();

		proceduregroupProgdurationRelCacheModel.modifiedBy = getModifiedBy();

		return proceduregroupProgdurationRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProceduregroupProgdurationRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProceduregroupProgdurationRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProceduregroupProgdurationRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProceduregroupProgdurationRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ProceduregroupProgdurationRel>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ProceduregroupProgdurationRel.class,
						ModelWrapper.class);

	}

	private String _uuid;
	private long _pgPdRelId;
	private long _procedureGroupMasterId;
	private long _programDurationId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdBy;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProceduregroupProgdurationRel, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProceduregroupProgdurationRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("pg_pd_rel_id", _pgPdRelId);
		_columnOriginalValues.put(
			"procedure_group_master_id", _procedureGroupMasterId);
		_columnOriginalValues.put("program_duration_id", _programDurationId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_by", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("pg_pd_rel_id", "pgPdRelId");
		attributeNames.put(
			"procedure_group_master_id", "procedureGroupMasterId");
		attributeNames.put("program_duration_id", "programDurationId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_by", "modifiedBy");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("pg_pd_rel_id", 2L);

		columnBitmasks.put("procedure_group_master_id", 4L);

		columnBitmasks.put("program_duration_id", 8L);

		columnBitmasks.put("group_id", 16L);

		columnBitmasks.put("company_id", 32L);

		columnBitmasks.put("create_date", 64L);

		columnBitmasks.put("modified_date", 128L);

		columnBitmasks.put("created_by", 256L);

		columnBitmasks.put("modified_by", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProceduregroupProgdurationRel _escapedModel;

}