/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.ProgramProgramTypeRel;
import gov.omsb.tms.model.ProgramProgramTypeRelModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProgramProgramTypeRel service. Represents a row in the &quot;program_programtype_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProgramProgramTypeRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProgramProgramTypeRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgramProgramTypeRelImpl
 * @generated
 */
@JSON(strict = true)
public class ProgramProgramTypeRelModelImpl
	extends BaseModelImpl<ProgramProgramTypeRel>
	implements ProgramProgramTypeRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a program program type rel model instance should use the <code>ProgramProgramTypeRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "program_programtype_rel";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"program_pt_id", Types.BIGINT},
		{"program_id", Types.BIGINT}, {"program_type_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"modified_date", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("program_pt_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_type_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table program_programtype_rel (uuid_ VARCHAR(75) null,program_pt_id LONG not null primary key,program_id LONG,program_type_id LONG,group_id LONG,company_id LONG,create_date DATE null,modified_date DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table program_programtype_rel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY programProgramTypeRel.programPtId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY program_programtype_rel.program_pt_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMTYPEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMPTID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProgramProgramTypeRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _programPtId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProgramPtId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _programPtId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProgramProgramTypeRel.class;
	}

	@Override
	public String getModelClassName() {
		return ProgramProgramTypeRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProgramProgramTypeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProgramProgramTypeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgramProgramTypeRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProgramProgramTypeRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProgramProgramTypeRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProgramProgramTypeRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProgramProgramTypeRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProgramProgramTypeRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProgramProgramTypeRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ProgramProgramTypeRel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProgramProgramTypeRel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProgramProgramTypeRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProgramProgramTypeRel, Object>>();
		Map<String, BiConsumer<ProgramProgramTypeRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ProgramProgramTypeRel, ?>>();

		attributeGetterFunctions.put("uuid", ProgramProgramTypeRel::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProgramProgramTypeRel, String>)
				ProgramProgramTypeRel::setUuid);
		attributeGetterFunctions.put(
			"programPtId", ProgramProgramTypeRel::getProgramPtId);
		attributeSetterBiConsumers.put(
			"programPtId",
			(BiConsumer<ProgramProgramTypeRel, Long>)
				ProgramProgramTypeRel::setProgramPtId);
		attributeGetterFunctions.put(
			"programId", ProgramProgramTypeRel::getProgramId);
		attributeSetterBiConsumers.put(
			"programId",
			(BiConsumer<ProgramProgramTypeRel, Long>)
				ProgramProgramTypeRel::setProgramId);
		attributeGetterFunctions.put(
			"programTypeId", ProgramProgramTypeRel::getProgramTypeId);
		attributeSetterBiConsumers.put(
			"programTypeId",
			(BiConsumer<ProgramProgramTypeRel, Long>)
				ProgramProgramTypeRel::setProgramTypeId);
		attributeGetterFunctions.put(
			"groupId", ProgramProgramTypeRel::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProgramProgramTypeRel, Long>)
				ProgramProgramTypeRel::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ProgramProgramTypeRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProgramProgramTypeRel, Long>)
				ProgramProgramTypeRel::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", ProgramProgramTypeRel::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProgramProgramTypeRel, Date>)
				ProgramProgramTypeRel::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ProgramProgramTypeRel::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProgramProgramTypeRel, Date>)
				ProgramProgramTypeRel::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getProgramPtId() {
		return _programPtId;
	}

	@Override
	public void setProgramPtId(long programPtId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programPtId = programPtId;
	}

	@JSON
	@Override
	public long getProgramId() {
		return _programId;
	}

	@Override
	public void setProgramId(long programId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programId = programId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgramId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("program_id"));
	}

	@JSON
	@Override
	public long getProgramTypeId() {
		return _programTypeId;
	}

	@Override
	public void setProgramTypeId(long programTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programTypeId = programTypeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgramTypeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("program_type_id"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProgramProgramTypeRel.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProgramProgramTypeRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProgramProgramTypeRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProgramProgramTypeRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProgramProgramTypeRelImpl programProgramTypeRelImpl =
			new ProgramProgramTypeRelImpl();

		programProgramTypeRelImpl.setUuid(getUuid());
		programProgramTypeRelImpl.setProgramPtId(getProgramPtId());
		programProgramTypeRelImpl.setProgramId(getProgramId());
		programProgramTypeRelImpl.setProgramTypeId(getProgramTypeId());
		programProgramTypeRelImpl.setGroupId(getGroupId());
		programProgramTypeRelImpl.setCompanyId(getCompanyId());
		programProgramTypeRelImpl.setCreateDate(getCreateDate());
		programProgramTypeRelImpl.setModifiedDate(getModifiedDate());

		programProgramTypeRelImpl.resetOriginalValues();

		return programProgramTypeRelImpl;
	}

	@Override
	public ProgramProgramTypeRel cloneWithOriginalValues() {
		ProgramProgramTypeRelImpl programProgramTypeRelImpl =
			new ProgramProgramTypeRelImpl();

		programProgramTypeRelImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		programProgramTypeRelImpl.setProgramPtId(
			this.<Long>getColumnOriginalValue("program_pt_id"));
		programProgramTypeRelImpl.setProgramId(
			this.<Long>getColumnOriginalValue("program_id"));
		programProgramTypeRelImpl.setProgramTypeId(
			this.<Long>getColumnOriginalValue("program_type_id"));
		programProgramTypeRelImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		programProgramTypeRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		programProgramTypeRelImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		programProgramTypeRelImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));

		return programProgramTypeRelImpl;
	}

	@Override
	public int compareTo(ProgramProgramTypeRel programProgramTypeRel) {
		long primaryKey = programProgramTypeRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProgramProgramTypeRel)) {
			return false;
		}

		ProgramProgramTypeRel programProgramTypeRel =
			(ProgramProgramTypeRel)object;

		long primaryKey = programProgramTypeRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProgramProgramTypeRel> toCacheModel() {
		ProgramProgramTypeRelCacheModel programProgramTypeRelCacheModel =
			new ProgramProgramTypeRelCacheModel();

		programProgramTypeRelCacheModel.uuid = getUuid();

		String uuid = programProgramTypeRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			programProgramTypeRelCacheModel.uuid = null;
		}

		programProgramTypeRelCacheModel.programPtId = getProgramPtId();

		programProgramTypeRelCacheModel.programId = getProgramId();

		programProgramTypeRelCacheModel.programTypeId = getProgramTypeId();

		programProgramTypeRelCacheModel.groupId = getGroupId();

		programProgramTypeRelCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			programProgramTypeRelCacheModel.createDate = createDate.getTime();
		}
		else {
			programProgramTypeRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			programProgramTypeRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			programProgramTypeRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return programProgramTypeRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProgramProgramTypeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProgramProgramTypeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgramProgramTypeRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProgramProgramTypeRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProgramProgramTypeRel>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProgramProgramTypeRel.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _programPtId;
	private long _programId;
	private long _programTypeId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProgramProgramTypeRel, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProgramProgramTypeRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("program_pt_id", _programPtId);
		_columnOriginalValues.put("program_id", _programId);
		_columnOriginalValues.put("program_type_id", _programTypeId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("program_pt_id", "programPtId");
		attributeNames.put("program_id", "programId");
		attributeNames.put("program_type_id", "programTypeId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("program_pt_id", 2L);

		columnBitmasks.put("program_id", 4L);

		columnBitmasks.put("program_type_id", 8L);

		columnBitmasks.put("group_id", 16L);

		columnBitmasks.put("company_id", 32L);

		columnBitmasks.put("create_date", 64L);

		columnBitmasks.put("modified_date", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProgramProgramTypeRel _escapedModel;

}