/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.ProgramWorkflowDetailsRel;
import gov.omsb.tms.model.ProgramWorkflowDetailsRelModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProgramWorkflowDetailsRel service. Represents a row in the &quot;program_workflow_details_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProgramWorkflowDetailsRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProgramWorkflowDetailsRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgramWorkflowDetailsRelImpl
 * @generated
 */
@JSON(strict = true)
public class ProgramWorkflowDetailsRelModelImpl
	extends BaseModelImpl<ProgramWorkflowDetailsRel>
	implements ProgramWorkflowDetailsRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a program workflow details rel model instance should use the <code>ProgramWorkflowDetailsRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "program_workflow_details_rel";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR},
		{"program_workflow_details_rel_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT},
		{"program_id", Types.BIGINT}, {"workflow_approval_order", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("program_workflow_details_rel_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workflow_approval_order", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table program_workflow_details_rel (uuid_ VARCHAR(75) null,program_workflow_details_rel_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,program_id LONG,workflow_approval_order VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table program_workflow_details_rel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY programWorkflowDetailsRel.programWorkflowDetailsRelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY program_workflow_details_rel.program_workflow_details_rel_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMWORKFLOWDETAILSRELID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProgramWorkflowDetailsRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _programWorkflowDetailsRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProgramWorkflowDetailsRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _programWorkflowDetailsRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProgramWorkflowDetailsRel.class;
	}

	@Override
	public String getModelClassName() {
		return ProgramWorkflowDetailsRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProgramWorkflowDetailsRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProgramWorkflowDetailsRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgramWorkflowDetailsRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProgramWorkflowDetailsRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProgramWorkflowDetailsRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProgramWorkflowDetailsRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProgramWorkflowDetailsRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProgramWorkflowDetailsRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProgramWorkflowDetailsRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<ProgramWorkflowDetailsRel, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<ProgramWorkflowDetailsRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProgramWorkflowDetailsRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProgramWorkflowDetailsRel, Object>>();
		Map<String, BiConsumer<ProgramWorkflowDetailsRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ProgramWorkflowDetailsRel, ?>>();

		attributeGetterFunctions.put(
			"uuid", ProgramWorkflowDetailsRel::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProgramWorkflowDetailsRel, String>)
				ProgramWorkflowDetailsRel::setUuid);
		attributeGetterFunctions.put(
			"programWorkflowDetailsRelId",
			ProgramWorkflowDetailsRel::getProgramWorkflowDetailsRelId);
		attributeSetterBiConsumers.put(
			"programWorkflowDetailsRelId",
			(BiConsumer<ProgramWorkflowDetailsRel, Long>)
				ProgramWorkflowDetailsRel::setProgramWorkflowDetailsRelId);
		attributeGetterFunctions.put(
			"groupId", ProgramWorkflowDetailsRel::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProgramWorkflowDetailsRel, Long>)
				ProgramWorkflowDetailsRel::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ProgramWorkflowDetailsRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProgramWorkflowDetailsRel, Long>)
				ProgramWorkflowDetailsRel::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", ProgramWorkflowDetailsRel::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProgramWorkflowDetailsRel, Date>)
				ProgramWorkflowDetailsRel::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", ProgramWorkflowDetailsRel::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ProgramWorkflowDetailsRel, Long>)
				ProgramWorkflowDetailsRel::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", ProgramWorkflowDetailsRel::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProgramWorkflowDetailsRel, Date>)
				ProgramWorkflowDetailsRel::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", ProgramWorkflowDetailsRel::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ProgramWorkflowDetailsRel, Long>)
				ProgramWorkflowDetailsRel::setModifiedBy);
		attributeGetterFunctions.put(
			"programId", ProgramWorkflowDetailsRel::getProgramId);
		attributeSetterBiConsumers.put(
			"programId",
			(BiConsumer<ProgramWorkflowDetailsRel, Long>)
				ProgramWorkflowDetailsRel::setProgramId);
		attributeGetterFunctions.put(
			"workflowApprovalOrder",
			ProgramWorkflowDetailsRel::getWorkflowApprovalOrder);
		attributeSetterBiConsumers.put(
			"workflowApprovalOrder",
			(BiConsumer<ProgramWorkflowDetailsRel, String>)
				ProgramWorkflowDetailsRel::setWorkflowApprovalOrder);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getProgramWorkflowDetailsRelId() {
		return _programWorkflowDetailsRelId;
	}

	@Override
	public void setProgramWorkflowDetailsRelId(
		long programWorkflowDetailsRelId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programWorkflowDetailsRelId = programWorkflowDetailsRelId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getProgramId() {
		return _programId;
	}

	@Override
	public void setProgramId(long programId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programId = programId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgramId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("program_id"));
	}

	@JSON
	@Override
	public String getWorkflowApprovalOrder() {
		if (_workflowApprovalOrder == null) {
			return "";
		}
		else {
			return _workflowApprovalOrder;
		}
	}

	@Override
	public void setWorkflowApprovalOrder(String workflowApprovalOrder) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowApprovalOrder = workflowApprovalOrder;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				ProgramWorkflowDetailsRel.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProgramWorkflowDetailsRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProgramWorkflowDetailsRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProgramWorkflowDetailsRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProgramWorkflowDetailsRelImpl programWorkflowDetailsRelImpl =
			new ProgramWorkflowDetailsRelImpl();

		programWorkflowDetailsRelImpl.setUuid(getUuid());
		programWorkflowDetailsRelImpl.setProgramWorkflowDetailsRelId(
			getProgramWorkflowDetailsRelId());
		programWorkflowDetailsRelImpl.setGroupId(getGroupId());
		programWorkflowDetailsRelImpl.setCompanyId(getCompanyId());
		programWorkflowDetailsRelImpl.setCreateDate(getCreateDate());
		programWorkflowDetailsRelImpl.setCreatedBy(getCreatedBy());
		programWorkflowDetailsRelImpl.setModifiedDate(getModifiedDate());
		programWorkflowDetailsRelImpl.setModifiedBy(getModifiedBy());
		programWorkflowDetailsRelImpl.setProgramId(getProgramId());
		programWorkflowDetailsRelImpl.setWorkflowApprovalOrder(
			getWorkflowApprovalOrder());

		programWorkflowDetailsRelImpl.resetOriginalValues();

		return programWorkflowDetailsRelImpl;
	}

	@Override
	public ProgramWorkflowDetailsRel cloneWithOriginalValues() {
		ProgramWorkflowDetailsRelImpl programWorkflowDetailsRelImpl =
			new ProgramWorkflowDetailsRelImpl();

		programWorkflowDetailsRelImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		programWorkflowDetailsRelImpl.setProgramWorkflowDetailsRelId(
			this.<Long>getColumnOriginalValue(
				"program_workflow_details_rel_id"));
		programWorkflowDetailsRelImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		programWorkflowDetailsRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		programWorkflowDetailsRelImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		programWorkflowDetailsRelImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		programWorkflowDetailsRelImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		programWorkflowDetailsRelImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		programWorkflowDetailsRelImpl.setProgramId(
			this.<Long>getColumnOriginalValue("program_id"));
		programWorkflowDetailsRelImpl.setWorkflowApprovalOrder(
			this.<String>getColumnOriginalValue("workflow_approval_order"));

		return programWorkflowDetailsRelImpl;
	}

	@Override
	public int compareTo(ProgramWorkflowDetailsRel programWorkflowDetailsRel) {
		long primaryKey = programWorkflowDetailsRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProgramWorkflowDetailsRel)) {
			return false;
		}

		ProgramWorkflowDetailsRel programWorkflowDetailsRel =
			(ProgramWorkflowDetailsRel)object;

		long primaryKey = programWorkflowDetailsRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProgramWorkflowDetailsRel> toCacheModel() {
		ProgramWorkflowDetailsRelCacheModel
			programWorkflowDetailsRelCacheModel =
				new ProgramWorkflowDetailsRelCacheModel();

		programWorkflowDetailsRelCacheModel.uuid = getUuid();

		String uuid = programWorkflowDetailsRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			programWorkflowDetailsRelCacheModel.uuid = null;
		}

		programWorkflowDetailsRelCacheModel.programWorkflowDetailsRelId =
			getProgramWorkflowDetailsRelId();

		programWorkflowDetailsRelCacheModel.groupId = getGroupId();

		programWorkflowDetailsRelCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			programWorkflowDetailsRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			programWorkflowDetailsRelCacheModel.createDate = Long.MIN_VALUE;
		}

		programWorkflowDetailsRelCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			programWorkflowDetailsRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			programWorkflowDetailsRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		programWorkflowDetailsRelCacheModel.modifiedBy = getModifiedBy();

		programWorkflowDetailsRelCacheModel.programId = getProgramId();

		programWorkflowDetailsRelCacheModel.workflowApprovalOrder =
			getWorkflowApprovalOrder();

		String workflowApprovalOrder =
			programWorkflowDetailsRelCacheModel.workflowApprovalOrder;

		if ((workflowApprovalOrder != null) &&
			(workflowApprovalOrder.length() == 0)) {

			programWorkflowDetailsRelCacheModel.workflowApprovalOrder = null;
		}

		return programWorkflowDetailsRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProgramWorkflowDetailsRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProgramWorkflowDetailsRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgramWorkflowDetailsRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProgramWorkflowDetailsRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ProgramWorkflowDetailsRel>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ProgramWorkflowDetailsRel.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _programWorkflowDetailsRelId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private long _programId;
	private String _workflowApprovalOrder;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProgramWorkflowDetailsRel, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProgramWorkflowDetailsRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"program_workflow_details_rel_id", _programWorkflowDetailsRelId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("program_id", _programId);
		_columnOriginalValues.put(
			"workflow_approval_order", _workflowApprovalOrder);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"program_workflow_details_rel_id", "programWorkflowDetailsRelId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("program_id", "programId");
		attributeNames.put("workflow_approval_order", "workflowApprovalOrder");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("program_workflow_details_rel_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("created_by", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("program_id", 256L);

		columnBitmasks.put("workflow_approval_order", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProgramWorkflowDetailsRel _escapedModel;

}