/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.ProgramDutyAssignment;
import gov.omsb.tms.model.ProgramDutyAssignmentModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProgramDutyAssignment service. Represents a row in the &quot;program_duty_assignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProgramDutyAssignmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProgramDutyAssignmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgramDutyAssignmentImpl
 * @generated
 */
@JSON(strict = true)
public class ProgramDutyAssignmentModelImpl
	extends BaseModelImpl<ProgramDutyAssignment>
	implements ProgramDutyAssignmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a program duty assignment model instance should use the <code>ProgramDutyAssignment</code> interface instead.
	 */
	public static final String TABLE_NAME = "program_duty_assignment";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"program_duty_assignment_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT},
		{"program_id", Types.BIGINT}, {"duty_assignment_id", Types.BIGINT},
		{"cohort_id", Types.BIGINT}, {"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("program_duty_assignment_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("duty_assignment_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cohort_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table program_duty_assignment (uuid_ VARCHAR(75) null,program_duty_assignment_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,program_id LONG,duty_assignment_id LONG,cohort_id LONG,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table program_duty_assignment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY programDutyAssignment.programDutyAssignmentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY program_duty_assignment.program_duty_assignment_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COHORTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DUTYASSIGNMENTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMDUTYASSIGNMENTID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProgramDutyAssignmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _programDutyAssignmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProgramDutyAssignmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _programDutyAssignmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProgramDutyAssignment.class;
	}

	@Override
	public String getModelClassName() {
		return ProgramDutyAssignment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProgramDutyAssignment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProgramDutyAssignment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgramDutyAssignment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProgramDutyAssignment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProgramDutyAssignment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProgramDutyAssignment, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProgramDutyAssignment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProgramDutyAssignment, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProgramDutyAssignment, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ProgramDutyAssignment, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProgramDutyAssignment, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProgramDutyAssignment, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProgramDutyAssignment, Object>>();
		Map<String, BiConsumer<ProgramDutyAssignment, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ProgramDutyAssignment, ?>>();

		attributeGetterFunctions.put("uuid", ProgramDutyAssignment::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProgramDutyAssignment, String>)
				ProgramDutyAssignment::setUuid);
		attributeGetterFunctions.put(
			"programDutyAssignmentId",
			ProgramDutyAssignment::getProgramDutyAssignmentId);
		attributeSetterBiConsumers.put(
			"programDutyAssignmentId",
			(BiConsumer<ProgramDutyAssignment, Long>)
				ProgramDutyAssignment::setProgramDutyAssignmentId);
		attributeGetterFunctions.put(
			"groupId", ProgramDutyAssignment::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProgramDutyAssignment, Long>)
				ProgramDutyAssignment::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ProgramDutyAssignment::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProgramDutyAssignment, Long>)
				ProgramDutyAssignment::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", ProgramDutyAssignment::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProgramDutyAssignment, Date>)
				ProgramDutyAssignment::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", ProgramDutyAssignment::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ProgramDutyAssignment, Long>)
				ProgramDutyAssignment::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", ProgramDutyAssignment::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProgramDutyAssignment, Date>)
				ProgramDutyAssignment::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", ProgramDutyAssignment::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ProgramDutyAssignment, Long>)
				ProgramDutyAssignment::setModifiedBy);
		attributeGetterFunctions.put(
			"programId", ProgramDutyAssignment::getProgramId);
		attributeSetterBiConsumers.put(
			"programId",
			(BiConsumer<ProgramDutyAssignment, Long>)
				ProgramDutyAssignment::setProgramId);
		attributeGetterFunctions.put(
			"dutyAssignmentId", ProgramDutyAssignment::getDutyAssignmentId);
		attributeSetterBiConsumers.put(
			"dutyAssignmentId",
			(BiConsumer<ProgramDutyAssignment, Long>)
				ProgramDutyAssignment::setDutyAssignmentId);
		attributeGetterFunctions.put(
			"cohortId", ProgramDutyAssignment::getCohortId);
		attributeSetterBiConsumers.put(
			"cohortId",
			(BiConsumer<ProgramDutyAssignment, Long>)
				ProgramDutyAssignment::setCohortId);
		attributeGetterFunctions.put(
			"status", ProgramDutyAssignment::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<ProgramDutyAssignment, String>)
				ProgramDutyAssignment::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getProgramDutyAssignmentId() {
		return _programDutyAssignmentId;
	}

	@Override
	public void setProgramDutyAssignmentId(long programDutyAssignmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programDutyAssignmentId = programDutyAssignmentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getProgramId() {
		return _programId;
	}

	@Override
	public void setProgramId(long programId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programId = programId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgramId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("program_id"));
	}

	@JSON
	@Override
	public long getDutyAssignmentId() {
		return _dutyAssignmentId;
	}

	@Override
	public void setDutyAssignmentId(long dutyAssignmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dutyAssignmentId = dutyAssignmentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDutyAssignmentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("duty_assignment_id"));
	}

	@JSON
	@Override
	public long getCohortId() {
		return _cohortId;
	}

	@Override
	public void setCohortId(long cohortId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cohortId = cohortId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCohortId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("cohort_id"));
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProgramDutyAssignment.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProgramDutyAssignment.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProgramDutyAssignment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProgramDutyAssignment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProgramDutyAssignmentImpl programDutyAssignmentImpl =
			new ProgramDutyAssignmentImpl();

		programDutyAssignmentImpl.setUuid(getUuid());
		programDutyAssignmentImpl.setProgramDutyAssignmentId(
			getProgramDutyAssignmentId());
		programDutyAssignmentImpl.setGroupId(getGroupId());
		programDutyAssignmentImpl.setCompanyId(getCompanyId());
		programDutyAssignmentImpl.setCreateDate(getCreateDate());
		programDutyAssignmentImpl.setCreatedBy(getCreatedBy());
		programDutyAssignmentImpl.setModifiedDate(getModifiedDate());
		programDutyAssignmentImpl.setModifiedBy(getModifiedBy());
		programDutyAssignmentImpl.setProgramId(getProgramId());
		programDutyAssignmentImpl.setDutyAssignmentId(getDutyAssignmentId());
		programDutyAssignmentImpl.setCohortId(getCohortId());
		programDutyAssignmentImpl.setStatus(getStatus());

		programDutyAssignmentImpl.resetOriginalValues();

		return programDutyAssignmentImpl;
	}

	@Override
	public ProgramDutyAssignment cloneWithOriginalValues() {
		ProgramDutyAssignmentImpl programDutyAssignmentImpl =
			new ProgramDutyAssignmentImpl();

		programDutyAssignmentImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		programDutyAssignmentImpl.setProgramDutyAssignmentId(
			this.<Long>getColumnOriginalValue("program_duty_assignment_id"));
		programDutyAssignmentImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		programDutyAssignmentImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		programDutyAssignmentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		programDutyAssignmentImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		programDutyAssignmentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		programDutyAssignmentImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		programDutyAssignmentImpl.setProgramId(
			this.<Long>getColumnOriginalValue("program_id"));
		programDutyAssignmentImpl.setDutyAssignmentId(
			this.<Long>getColumnOriginalValue("duty_assignment_id"));
		programDutyAssignmentImpl.setCohortId(
			this.<Long>getColumnOriginalValue("cohort_id"));
		programDutyAssignmentImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));

		return programDutyAssignmentImpl;
	}

	@Override
	public int compareTo(ProgramDutyAssignment programDutyAssignment) {
		long primaryKey = programDutyAssignment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProgramDutyAssignment)) {
			return false;
		}

		ProgramDutyAssignment programDutyAssignment =
			(ProgramDutyAssignment)object;

		long primaryKey = programDutyAssignment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProgramDutyAssignment> toCacheModel() {
		ProgramDutyAssignmentCacheModel programDutyAssignmentCacheModel =
			new ProgramDutyAssignmentCacheModel();

		programDutyAssignmentCacheModel.uuid = getUuid();

		String uuid = programDutyAssignmentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			programDutyAssignmentCacheModel.uuid = null;
		}

		programDutyAssignmentCacheModel.programDutyAssignmentId =
			getProgramDutyAssignmentId();

		programDutyAssignmentCacheModel.groupId = getGroupId();

		programDutyAssignmentCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			programDutyAssignmentCacheModel.createDate = createDate.getTime();
		}
		else {
			programDutyAssignmentCacheModel.createDate = Long.MIN_VALUE;
		}

		programDutyAssignmentCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			programDutyAssignmentCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			programDutyAssignmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		programDutyAssignmentCacheModel.modifiedBy = getModifiedBy();

		programDutyAssignmentCacheModel.programId = getProgramId();

		programDutyAssignmentCacheModel.dutyAssignmentId =
			getDutyAssignmentId();

		programDutyAssignmentCacheModel.cohortId = getCohortId();

		programDutyAssignmentCacheModel.status = getStatus();

		String status = programDutyAssignmentCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			programDutyAssignmentCacheModel.status = null;
		}

		return programDutyAssignmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProgramDutyAssignment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProgramDutyAssignment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgramDutyAssignment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProgramDutyAssignment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProgramDutyAssignment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProgramDutyAssignment.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _programDutyAssignmentId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private long _programId;
	private long _dutyAssignmentId;
	private long _cohortId;
	private String _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProgramDutyAssignment, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProgramDutyAssignment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"program_duty_assignment_id", _programDutyAssignmentId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("program_id", _programId);
		_columnOriginalValues.put("duty_assignment_id", _dutyAssignmentId);
		_columnOriginalValues.put("cohort_id", _cohortId);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"program_duty_assignment_id", "programDutyAssignmentId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("program_id", "programId");
		attributeNames.put("duty_assignment_id", "dutyAssignmentId");
		attributeNames.put("cohort_id", "cohortId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("program_duty_assignment_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("created_by", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("program_id", 256L);

		columnBitmasks.put("duty_assignment_id", 512L);

		columnBitmasks.put("cohort_id", 1024L);

		columnBitmasks.put("status", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProgramDutyAssignment _escapedModel;

}