/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.ProgdurationObjectivesRel;
import gov.omsb.tms.model.ProgdurationObjectivesRelModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProgdurationObjectivesRel service. Represents a row in the &quot;progduration_objectives_rel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProgdurationObjectivesRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProgdurationObjectivesRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgdurationObjectivesRelImpl
 * @generated
 */
@JSON(strict = true)
public class ProgdurationObjectivesRelModelImpl
	extends BaseModelImpl<ProgdurationObjectivesRel>
	implements ProgdurationObjectivesRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a progduration objectives rel model instance should use the <code>ProgdurationObjectivesRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "progduration_objectives_rel";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"pd_objectives_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"modified_date", Types.TIMESTAMP},
		{"prog_duration_id", Types.BIGINT}, {"objectives", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pd_objectives_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("prog_duration_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("objectives", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table progduration_objectives_rel (uuid_ VARCHAR(75) null,pd_objectives_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,modified_date DATE null,prog_duration_id LONG,objectives STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table progduration_objectives_rel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY progdurationObjectivesRel.PDObjectivesId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY progduration_objectives_rel.pd_objectives_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PDOBJECTIVESID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProgdurationObjectivesRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PDObjectivesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPDObjectivesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PDObjectivesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProgdurationObjectivesRel.class;
	}

	@Override
	public String getModelClassName() {
		return ProgdurationObjectivesRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProgdurationObjectivesRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProgdurationObjectivesRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgdurationObjectivesRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProgdurationObjectivesRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProgdurationObjectivesRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProgdurationObjectivesRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProgdurationObjectivesRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProgdurationObjectivesRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProgdurationObjectivesRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<ProgdurationObjectivesRel, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<ProgdurationObjectivesRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProgdurationObjectivesRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProgdurationObjectivesRel, Object>>();
		Map<String, BiConsumer<ProgdurationObjectivesRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ProgdurationObjectivesRel, ?>>();

		attributeGetterFunctions.put(
			"uuid", ProgdurationObjectivesRel::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProgdurationObjectivesRel, String>)
				ProgdurationObjectivesRel::setUuid);
		attributeGetterFunctions.put(
			"PDObjectivesId", ProgdurationObjectivesRel::getPDObjectivesId);
		attributeSetterBiConsumers.put(
			"PDObjectivesId",
			(BiConsumer<ProgdurationObjectivesRel, Long>)
				ProgdurationObjectivesRel::setPDObjectivesId);
		attributeGetterFunctions.put(
			"groupId", ProgdurationObjectivesRel::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProgdurationObjectivesRel, Long>)
				ProgdurationObjectivesRel::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ProgdurationObjectivesRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProgdurationObjectivesRel, Long>)
				ProgdurationObjectivesRel::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", ProgdurationObjectivesRel::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProgdurationObjectivesRel, Date>)
				ProgdurationObjectivesRel::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ProgdurationObjectivesRel::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProgdurationObjectivesRel, Date>)
				ProgdurationObjectivesRel::setModifiedDate);
		attributeGetterFunctions.put(
			"progDurationId", ProgdurationObjectivesRel::getProgDurationId);
		attributeSetterBiConsumers.put(
			"progDurationId",
			(BiConsumer<ProgdurationObjectivesRel, Long>)
				ProgdurationObjectivesRel::setProgDurationId);
		attributeGetterFunctions.put(
			"objectives", ProgdurationObjectivesRel::getObjectives);
		attributeSetterBiConsumers.put(
			"objectives",
			(BiConsumer<ProgdurationObjectivesRel, String>)
				ProgdurationObjectivesRel::setObjectives);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPDObjectivesId() {
		return _PDObjectivesId;
	}

	@Override
	public void setPDObjectivesId(long PDObjectivesId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PDObjectivesId = PDObjectivesId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProgDurationId() {
		return _progDurationId;
	}

	@Override
	public void setProgDurationId(long progDurationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_progDurationId = progDurationId;
	}

	@JSON
	@Override
	public String getObjectives() {
		if (_objectives == null) {
			return "";
		}
		else {
			return _objectives;
		}
	}

	@Override
	public String getObjectives(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getObjectives(languageId);
	}

	@Override
	public String getObjectives(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getObjectives(languageId, useDefault);
	}

	@Override
	public String getObjectives(String languageId) {
		return LocalizationUtil.getLocalization(getObjectives(), languageId);
	}

	@Override
	public String getObjectives(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getObjectives(), languageId, useDefault);
	}

	@Override
	public String getObjectivesCurrentLanguageId() {
		return _objectivesCurrentLanguageId;
	}

	@JSON
	@Override
	public String getObjectivesCurrentValue() {
		Locale locale = getLocale(_objectivesCurrentLanguageId);

		return getObjectives(locale);
	}

	@Override
	public Map<Locale, String> getObjectivesMap() {
		return LocalizationUtil.getLocalizationMap(getObjectives());
	}

	@Override
	public void setObjectives(String objectives) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_objectives = objectives;
	}

	@Override
	public void setObjectives(String objectives, Locale locale) {
		setObjectives(objectives, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setObjectives(
		String objectives, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(objectives)) {
			setObjectives(
				LocalizationUtil.updateLocalization(
					getObjectives(), "Objectives", objectives, languageId,
					defaultLanguageId));
		}
		else {
			setObjectives(
				LocalizationUtil.removeLocalization(
					getObjectives(), "Objectives", languageId));
		}
	}

	@Override
	public void setObjectivesCurrentLanguageId(String languageId) {
		_objectivesCurrentLanguageId = languageId;
	}

	@Override
	public void setObjectivesMap(Map<Locale, String> objectivesMap) {
		setObjectivesMap(objectivesMap, LocaleUtil.getDefault());
	}

	@Override
	public void setObjectivesMap(
		Map<Locale, String> objectivesMap, Locale defaultLocale) {

		if (objectivesMap == null) {
			return;
		}

		setObjectives(
			LocalizationUtil.updateLocalization(
				objectivesMap, getObjectives(), "Objectives",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				ProgdurationObjectivesRel.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProgdurationObjectivesRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> objectivesMap = getObjectivesMap();

		for (Map.Entry<Locale, String> entry : objectivesMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getObjectives();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			ProgdurationObjectivesRel.class.getName(), getPrimaryKey(),
			defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String objectives = getObjectives(defaultLocale);

		if (Validator.isNull(objectives)) {
			setObjectives(getObjectives(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setObjectives(
				getObjectives(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public ProgdurationObjectivesRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProgdurationObjectivesRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProgdurationObjectivesRelImpl progdurationObjectivesRelImpl =
			new ProgdurationObjectivesRelImpl();

		progdurationObjectivesRelImpl.setUuid(getUuid());
		progdurationObjectivesRelImpl.setPDObjectivesId(getPDObjectivesId());
		progdurationObjectivesRelImpl.setGroupId(getGroupId());
		progdurationObjectivesRelImpl.setCompanyId(getCompanyId());
		progdurationObjectivesRelImpl.setCreateDate(getCreateDate());
		progdurationObjectivesRelImpl.setModifiedDate(getModifiedDate());
		progdurationObjectivesRelImpl.setProgDurationId(getProgDurationId());
		progdurationObjectivesRelImpl.setObjectives(getObjectives());

		progdurationObjectivesRelImpl.resetOriginalValues();

		return progdurationObjectivesRelImpl;
	}

	@Override
	public ProgdurationObjectivesRel cloneWithOriginalValues() {
		ProgdurationObjectivesRelImpl progdurationObjectivesRelImpl =
			new ProgdurationObjectivesRelImpl();

		progdurationObjectivesRelImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		progdurationObjectivesRelImpl.setPDObjectivesId(
			this.<Long>getColumnOriginalValue("pd_objectives_id"));
		progdurationObjectivesRelImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		progdurationObjectivesRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		progdurationObjectivesRelImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		progdurationObjectivesRelImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		progdurationObjectivesRelImpl.setProgDurationId(
			this.<Long>getColumnOriginalValue("prog_duration_id"));
		progdurationObjectivesRelImpl.setObjectives(
			this.<String>getColumnOriginalValue("objectives"));

		return progdurationObjectivesRelImpl;
	}

	@Override
	public int compareTo(ProgdurationObjectivesRel progdurationObjectivesRel) {
		long primaryKey = progdurationObjectivesRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProgdurationObjectivesRel)) {
			return false;
		}

		ProgdurationObjectivesRel progdurationObjectivesRel =
			(ProgdurationObjectivesRel)object;

		long primaryKey = progdurationObjectivesRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProgdurationObjectivesRel> toCacheModel() {
		ProgdurationObjectivesRelCacheModel
			progdurationObjectivesRelCacheModel =
				new ProgdurationObjectivesRelCacheModel();

		progdurationObjectivesRelCacheModel.uuid = getUuid();

		String uuid = progdurationObjectivesRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			progdurationObjectivesRelCacheModel.uuid = null;
		}

		progdurationObjectivesRelCacheModel.PDObjectivesId =
			getPDObjectivesId();

		progdurationObjectivesRelCacheModel.groupId = getGroupId();

		progdurationObjectivesRelCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			progdurationObjectivesRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			progdurationObjectivesRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			progdurationObjectivesRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			progdurationObjectivesRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		progdurationObjectivesRelCacheModel.progDurationId =
			getProgDurationId();

		progdurationObjectivesRelCacheModel.objectives = getObjectives();

		String objectives = progdurationObjectivesRelCacheModel.objectives;

		if ((objectives != null) && (objectives.length() == 0)) {
			progdurationObjectivesRelCacheModel.objectives = null;
		}

		return progdurationObjectivesRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProgdurationObjectivesRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProgdurationObjectivesRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgdurationObjectivesRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProgdurationObjectivesRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ProgdurationObjectivesRel>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ProgdurationObjectivesRel.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _PDObjectivesId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _progDurationId;
	private String _objectives;
	private String _objectivesCurrentLanguageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProgdurationObjectivesRel, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProgdurationObjectivesRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("pd_objectives_id", _PDObjectivesId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("prog_duration_id", _progDurationId);
		_columnOriginalValues.put("objectives", _objectives);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("pd_objectives_id", "PDObjectivesId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("prog_duration_id", "progDurationId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("pd_objectives_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("modified_date", 32L);

		columnBitmasks.put("prog_duration_id", 64L);

		columnBitmasks.put("objectives", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProgdurationObjectivesRel _escapedModel;

}