/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.QararRequest;
import gov.omsb.tms.model.QararRequestModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the QararRequest service. Represents a row in the &quot;qarar_request_info&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>QararRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QararRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QararRequestImpl
 * @generated
 */
@JSON(strict = true)
public class QararRequestModelImpl
	extends BaseModelImpl<QararRequest> implements QararRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qarar request model instance should use the <code>QararRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "qarar_request_info";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"qarar_request_id", Types.BIGINT},
		{"reference_id", Types.BIGINT}, {"reference_class", Types.VARCHAR},
		{"qarar_type", Types.VARCHAR}, {"doc_tree_id", Types.BIGINT},
		{"doc_url", Types.VARCHAR}, {"group_id", Types.BIGINT},
		{"company_id", Types.BIGINT}, {"create_date", Types.TIMESTAMP},
		{"created_by", Types.BIGINT}, {"modified_date", Types.TIMESTAMP},
		{"modified_by", Types.BIGINT}, {"qarar_doc_id", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("qarar_request_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reference_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reference_class", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("qarar_type", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("doc_tree_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("doc_url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("qarar_doc_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table qarar_request_info (uuid_ VARCHAR(75) null,qarar_request_id LONG not null primary key,reference_id LONG,reference_class VARCHAR(75) null,qarar_type VARCHAR(75) null,doc_tree_id LONG,doc_url VARCHAR(75) null,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,qarar_doc_id LONG)";

	public static final String TABLE_SQL_DROP = "drop table qarar_request_info";

	public static final String ORDER_BY_JPQL =
		" ORDER BY qararRequest.qararRequestId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY qarar_request_info.qarar_request_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOCTREEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long QARARREQUESTID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public QararRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _qararRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setQararRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _qararRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QararRequest.class;
	}

	@Override
	public String getModelClassName() {
		return QararRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<QararRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<QararRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QararRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((QararRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<QararRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<QararRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(QararRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<QararRequest, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<QararRequest, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<QararRequest, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<QararRequest, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<QararRequest, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<QararRequest, Object>>();
		Map<String, BiConsumer<QararRequest, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<QararRequest, ?>>();

		attributeGetterFunctions.put("uuid", QararRequest::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<QararRequest, String>)QararRequest::setUuid);
		attributeGetterFunctions.put(
			"qararRequestId", QararRequest::getQararRequestId);
		attributeSetterBiConsumers.put(
			"qararRequestId",
			(BiConsumer<QararRequest, Long>)QararRequest::setQararRequestId);
		attributeGetterFunctions.put(
			"referenceId", QararRequest::getReferenceId);
		attributeSetterBiConsumers.put(
			"referenceId",
			(BiConsumer<QararRequest, Long>)QararRequest::setReferenceId);
		attributeGetterFunctions.put(
			"referenceClass", QararRequest::getReferenceClass);
		attributeSetterBiConsumers.put(
			"referenceClass",
			(BiConsumer<QararRequest, String>)QararRequest::setReferenceClass);
		attributeGetterFunctions.put("qararType", QararRequest::getQararType);
		attributeSetterBiConsumers.put(
			"qararType",
			(BiConsumer<QararRequest, String>)QararRequest::setQararType);
		attributeGetterFunctions.put("docTreeId", QararRequest::getDocTreeId);
		attributeSetterBiConsumers.put(
			"docTreeId",
			(BiConsumer<QararRequest, Long>)QararRequest::setDocTreeId);
		attributeGetterFunctions.put("docURL", QararRequest::getDocURL);
		attributeSetterBiConsumers.put(
			"docURL",
			(BiConsumer<QararRequest, String>)QararRequest::setDocURL);
		attributeGetterFunctions.put("groupId", QararRequest::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<QararRequest, Long>)QararRequest::setGroupId);
		attributeGetterFunctions.put("companyId", QararRequest::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<QararRequest, Long>)QararRequest::setCompanyId);
		attributeGetterFunctions.put("createDate", QararRequest::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<QararRequest, Date>)QararRequest::setCreateDate);
		attributeGetterFunctions.put("createdBy", QararRequest::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<QararRequest, Long>)QararRequest::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", QararRequest::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<QararRequest, Date>)QararRequest::setModifiedDate);
		attributeGetterFunctions.put("modifiedBy", QararRequest::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<QararRequest, Long>)QararRequest::setModifiedBy);
		attributeGetterFunctions.put("qararDocId", QararRequest::getQararDocId);
		attributeSetterBiConsumers.put(
			"qararDocId",
			(BiConsumer<QararRequest, Long>)QararRequest::setQararDocId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getQararRequestId() {
		return _qararRequestId;
	}

	@Override
	public void setQararRequestId(long qararRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qararRequestId = qararRequestId;
	}

	@JSON
	@Override
	public long getReferenceId() {
		return _referenceId;
	}

	@Override
	public void setReferenceId(long referenceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_referenceId = referenceId;
	}

	@JSON
	@Override
	public String getReferenceClass() {
		if (_referenceClass == null) {
			return "";
		}
		else {
			return _referenceClass;
		}
	}

	@Override
	public void setReferenceClass(String referenceClass) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_referenceClass = referenceClass;
	}

	@JSON
	@Override
	public String getQararType() {
		if (_qararType == null) {
			return "";
		}
		else {
			return _qararType;
		}
	}

	@Override
	public void setQararType(String qararType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qararType = qararType;
	}

	@JSON
	@Override
	public long getDocTreeId() {
		return _docTreeId;
	}

	@Override
	public void setDocTreeId(long docTreeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_docTreeId = docTreeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDocTreeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("doc_tree_id"));
	}

	@JSON
	@Override
	public String getDocURL() {
		if (_docURL == null) {
			return "";
		}
		else {
			return _docURL;
		}
	}

	@Override
	public void setDocURL(String docURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_docURL = docURL;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getQararDocId() {
		return _qararDocId;
	}

	@Override
	public void setQararDocId(long qararDocId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qararDocId = qararDocId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(QararRequest.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), QararRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QararRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, QararRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QararRequestImpl qararRequestImpl = new QararRequestImpl();

		qararRequestImpl.setUuid(getUuid());
		qararRequestImpl.setQararRequestId(getQararRequestId());
		qararRequestImpl.setReferenceId(getReferenceId());
		qararRequestImpl.setReferenceClass(getReferenceClass());
		qararRequestImpl.setQararType(getQararType());
		qararRequestImpl.setDocTreeId(getDocTreeId());
		qararRequestImpl.setDocURL(getDocURL());
		qararRequestImpl.setGroupId(getGroupId());
		qararRequestImpl.setCompanyId(getCompanyId());
		qararRequestImpl.setCreateDate(getCreateDate());
		qararRequestImpl.setCreatedBy(getCreatedBy());
		qararRequestImpl.setModifiedDate(getModifiedDate());
		qararRequestImpl.setModifiedBy(getModifiedBy());
		qararRequestImpl.setQararDocId(getQararDocId());

		qararRequestImpl.resetOriginalValues();

		return qararRequestImpl;
	}

	@Override
	public QararRequest cloneWithOriginalValues() {
		QararRequestImpl qararRequestImpl = new QararRequestImpl();

		qararRequestImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		qararRequestImpl.setQararRequestId(
			this.<Long>getColumnOriginalValue("qarar_request_id"));
		qararRequestImpl.setReferenceId(
			this.<Long>getColumnOriginalValue("reference_id"));
		qararRequestImpl.setReferenceClass(
			this.<String>getColumnOriginalValue("reference_class"));
		qararRequestImpl.setQararType(
			this.<String>getColumnOriginalValue("qarar_type"));
		qararRequestImpl.setDocTreeId(
			this.<Long>getColumnOriginalValue("doc_tree_id"));
		qararRequestImpl.setDocURL(
			this.<String>getColumnOriginalValue("doc_url"));
		qararRequestImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		qararRequestImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		qararRequestImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		qararRequestImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		qararRequestImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		qararRequestImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		qararRequestImpl.setQararDocId(
			this.<Long>getColumnOriginalValue("qarar_doc_id"));

		return qararRequestImpl;
	}

	@Override
	public int compareTo(QararRequest qararRequest) {
		long primaryKey = qararRequest.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof QararRequest)) {
			return false;
		}

		QararRequest qararRequest = (QararRequest)object;

		long primaryKey = qararRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<QararRequest> toCacheModel() {
		QararRequestCacheModel qararRequestCacheModel =
			new QararRequestCacheModel();

		qararRequestCacheModel.uuid = getUuid();

		String uuid = qararRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			qararRequestCacheModel.uuid = null;
		}

		qararRequestCacheModel.qararRequestId = getQararRequestId();

		qararRequestCacheModel.referenceId = getReferenceId();

		qararRequestCacheModel.referenceClass = getReferenceClass();

		String referenceClass = qararRequestCacheModel.referenceClass;

		if ((referenceClass != null) && (referenceClass.length() == 0)) {
			qararRequestCacheModel.referenceClass = null;
		}

		qararRequestCacheModel.qararType = getQararType();

		String qararType = qararRequestCacheModel.qararType;

		if ((qararType != null) && (qararType.length() == 0)) {
			qararRequestCacheModel.qararType = null;
		}

		qararRequestCacheModel.docTreeId = getDocTreeId();

		qararRequestCacheModel.docURL = getDocURL();

		String docURL = qararRequestCacheModel.docURL;

		if ((docURL != null) && (docURL.length() == 0)) {
			qararRequestCacheModel.docURL = null;
		}

		qararRequestCacheModel.groupId = getGroupId();

		qararRequestCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			qararRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			qararRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		qararRequestCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			qararRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			qararRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		qararRequestCacheModel.modifiedBy = getModifiedBy();

		qararRequestCacheModel.qararDocId = getQararDocId();

		return qararRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<QararRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<QararRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QararRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((QararRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, QararRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					QararRequest.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _qararRequestId;
	private long _referenceId;
	private String _referenceClass;
	private String _qararType;
	private long _docTreeId;
	private String _docURL;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private long _qararDocId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<QararRequest, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((QararRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("qarar_request_id", _qararRequestId);
		_columnOriginalValues.put("reference_id", _referenceId);
		_columnOriginalValues.put("reference_class", _referenceClass);
		_columnOriginalValues.put("qarar_type", _qararType);
		_columnOriginalValues.put("doc_tree_id", _docTreeId);
		_columnOriginalValues.put("doc_url", _docURL);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("qarar_doc_id", _qararDocId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("qarar_request_id", "qararRequestId");
		attributeNames.put("reference_id", "referenceId");
		attributeNames.put("reference_class", "referenceClass");
		attributeNames.put("qarar_type", "qararType");
		attributeNames.put("doc_tree_id", "docTreeId");
		attributeNames.put("doc_url", "docURL");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("qarar_doc_id", "qararDocId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("qarar_request_id", 2L);

		columnBitmasks.put("reference_id", 4L);

		columnBitmasks.put("reference_class", 8L);

		columnBitmasks.put("qarar_type", 16L);

		columnBitmasks.put("doc_tree_id", 32L);

		columnBitmasks.put("doc_url", 64L);

		columnBitmasks.put("group_id", 128L);

		columnBitmasks.put("company_id", 256L);

		columnBitmasks.put("create_date", 512L);

		columnBitmasks.put("created_by", 1024L);

		columnBitmasks.put("modified_date", 2048L);

		columnBitmasks.put("modified_by", 4096L);

		columnBitmasks.put("qarar_doc_id", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private QararRequest _escapedModel;

}