/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.RoleTypeMaster;
import gov.omsb.tms.model.RoleTypeMasterModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RoleTypeMaster service. Represents a row in the &quot;role_type_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RoleTypeMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RoleTypeMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RoleTypeMasterImpl
 * @generated
 */
@JSON(strict = true)
public class RoleTypeMasterModelImpl
	extends BaseModelImpl<RoleTypeMaster> implements RoleTypeMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a role type master model instance should use the <code>RoleTypeMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "role_type_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"role_type_master_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT},
		{"role_type_name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("role_type_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("role_type_name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table role_type_master (uuid_ VARCHAR(75) null,role_type_master_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,role_type_name STRING null)";

	public static final String TABLE_SQL_DROP = "drop table role_type_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY roleTypeMaster.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY role_type_master.modified_date DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROLETYPENAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RoleTypeMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _roleTypeMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRoleTypeMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _roleTypeMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RoleTypeMaster.class;
	}

	@Override
	public String getModelClassName() {
		return RoleTypeMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RoleTypeMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RoleTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RoleTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RoleTypeMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RoleTypeMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RoleTypeMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RoleTypeMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RoleTypeMaster, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RoleTypeMaster, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<RoleTypeMaster, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RoleTypeMaster, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RoleTypeMaster, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<RoleTypeMaster, Object>>();
		Map<String, BiConsumer<RoleTypeMaster, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<RoleTypeMaster, ?>>();

		attributeGetterFunctions.put("uuid", RoleTypeMaster::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<RoleTypeMaster, String>)RoleTypeMaster::setUuid);
		attributeGetterFunctions.put(
			"roleTypeMasterId", RoleTypeMaster::getRoleTypeMasterId);
		attributeSetterBiConsumers.put(
			"roleTypeMasterId",
			(BiConsumer<RoleTypeMaster, Long>)
				RoleTypeMaster::setRoleTypeMasterId);
		attributeGetterFunctions.put("groupId", RoleTypeMaster::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<RoleTypeMaster, Long>)RoleTypeMaster::setGroupId);
		attributeGetterFunctions.put("companyId", RoleTypeMaster::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<RoleTypeMaster, Long>)RoleTypeMaster::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", RoleTypeMaster::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<RoleTypeMaster, Date>)RoleTypeMaster::setCreateDate);
		attributeGetterFunctions.put("createdBy", RoleTypeMaster::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<RoleTypeMaster, Long>)RoleTypeMaster::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", RoleTypeMaster::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<RoleTypeMaster, Date>)RoleTypeMaster::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", RoleTypeMaster::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<RoleTypeMaster, Long>)RoleTypeMaster::setModifiedBy);
		attributeGetterFunctions.put(
			"roleTypeName", RoleTypeMaster::getRoleTypeName);
		attributeSetterBiConsumers.put(
			"roleTypeName",
			(BiConsumer<RoleTypeMaster, String>)
				RoleTypeMaster::setRoleTypeName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getRoleTypeMasterId() {
		return _roleTypeMasterId;
	}

	@Override
	public void setRoleTypeMasterId(long roleTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleTypeMasterId = roleTypeMasterId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public String getRoleTypeName() {
		if (_roleTypeName == null) {
			return "";
		}
		else {
			return _roleTypeName;
		}
	}

	@Override
	public String getRoleTypeName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getRoleTypeName(languageId);
	}

	@Override
	public String getRoleTypeName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getRoleTypeName(languageId, useDefault);
	}

	@Override
	public String getRoleTypeName(String languageId) {
		return LocalizationUtil.getLocalization(getRoleTypeName(), languageId);
	}

	@Override
	public String getRoleTypeName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getRoleTypeName(), languageId, useDefault);
	}

	@Override
	public String getRoleTypeNameCurrentLanguageId() {
		return _roleTypeNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getRoleTypeNameCurrentValue() {
		Locale locale = getLocale(_roleTypeNameCurrentLanguageId);

		return getRoleTypeName(locale);
	}

	@Override
	public Map<Locale, String> getRoleTypeNameMap() {
		return LocalizationUtil.getLocalizationMap(getRoleTypeName());
	}

	@Override
	public void setRoleTypeName(String roleTypeName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleTypeName = roleTypeName;
	}

	@Override
	public void setRoleTypeName(String roleTypeName, Locale locale) {
		setRoleTypeName(roleTypeName, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setRoleTypeName(
		String roleTypeName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(roleTypeName)) {
			setRoleTypeName(
				LocalizationUtil.updateLocalization(
					getRoleTypeName(), "RoleTypeName", roleTypeName, languageId,
					defaultLanguageId));
		}
		else {
			setRoleTypeName(
				LocalizationUtil.removeLocalization(
					getRoleTypeName(), "RoleTypeName", languageId));
		}
	}

	@Override
	public void setRoleTypeNameCurrentLanguageId(String languageId) {
		_roleTypeNameCurrentLanguageId = languageId;
	}

	@Override
	public void setRoleTypeNameMap(Map<Locale, String> roleTypeNameMap) {
		setRoleTypeNameMap(roleTypeNameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setRoleTypeNameMap(
		Map<Locale, String> roleTypeNameMap, Locale defaultLocale) {

		if (roleTypeNameMap == null) {
			return;
		}

		setRoleTypeName(
			LocalizationUtil.updateLocalization(
				roleTypeNameMap, getRoleTypeName(), "RoleTypeName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalRoleTypeName() {
		return getColumnOriginalValue("role_type_name");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(RoleTypeMaster.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), RoleTypeMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> roleTypeNameMap = getRoleTypeNameMap();

		for (Map.Entry<Locale, String> entry : roleTypeNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getRoleTypeName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			RoleTypeMaster.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String roleTypeName = getRoleTypeName(defaultLocale);

		if (Validator.isNull(roleTypeName)) {
			setRoleTypeName(
				getRoleTypeName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setRoleTypeName(
				getRoleTypeName(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public RoleTypeMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RoleTypeMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RoleTypeMasterImpl roleTypeMasterImpl = new RoleTypeMasterImpl();

		roleTypeMasterImpl.setUuid(getUuid());
		roleTypeMasterImpl.setRoleTypeMasterId(getRoleTypeMasterId());
		roleTypeMasterImpl.setGroupId(getGroupId());
		roleTypeMasterImpl.setCompanyId(getCompanyId());
		roleTypeMasterImpl.setCreateDate(getCreateDate());
		roleTypeMasterImpl.setCreatedBy(getCreatedBy());
		roleTypeMasterImpl.setModifiedDate(getModifiedDate());
		roleTypeMasterImpl.setModifiedBy(getModifiedBy());
		roleTypeMasterImpl.setRoleTypeName(getRoleTypeName());

		roleTypeMasterImpl.resetOriginalValues();

		return roleTypeMasterImpl;
	}

	@Override
	public RoleTypeMaster cloneWithOriginalValues() {
		RoleTypeMasterImpl roleTypeMasterImpl = new RoleTypeMasterImpl();

		roleTypeMasterImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		roleTypeMasterImpl.setRoleTypeMasterId(
			this.<Long>getColumnOriginalValue("role_type_master_id"));
		roleTypeMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		roleTypeMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		roleTypeMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		roleTypeMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		roleTypeMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		roleTypeMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		roleTypeMasterImpl.setRoleTypeName(
			this.<String>getColumnOriginalValue("role_type_name"));

		return roleTypeMasterImpl;
	}

	@Override
	public int compareTo(RoleTypeMaster roleTypeMaster) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), roleTypeMaster.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RoleTypeMaster)) {
			return false;
		}

		RoleTypeMaster roleTypeMaster = (RoleTypeMaster)object;

		long primaryKey = roleTypeMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RoleTypeMaster> toCacheModel() {
		RoleTypeMasterCacheModel roleTypeMasterCacheModel =
			new RoleTypeMasterCacheModel();

		roleTypeMasterCacheModel.uuid = getUuid();

		String uuid = roleTypeMasterCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			roleTypeMasterCacheModel.uuid = null;
		}

		roleTypeMasterCacheModel.roleTypeMasterId = getRoleTypeMasterId();

		roleTypeMasterCacheModel.groupId = getGroupId();

		roleTypeMasterCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			roleTypeMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			roleTypeMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		roleTypeMasterCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			roleTypeMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			roleTypeMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		roleTypeMasterCacheModel.modifiedBy = getModifiedBy();

		roleTypeMasterCacheModel.roleTypeName = getRoleTypeName();

		String roleTypeName = roleTypeMasterCacheModel.roleTypeName;

		if ((roleTypeName != null) && (roleTypeName.length() == 0)) {
			roleTypeMasterCacheModel.roleTypeName = null;
		}

		return roleTypeMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RoleTypeMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RoleTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RoleTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((RoleTypeMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RoleTypeMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RoleTypeMaster.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _roleTypeMasterId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private String _roleTypeName;
	private String _roleTypeNameCurrentLanguageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RoleTypeMaster, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RoleTypeMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("role_type_master_id", _roleTypeMasterId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("role_type_name", _roleTypeName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("role_type_master_id", "roleTypeMasterId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("role_type_name", "roleTypeName");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("role_type_master_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("created_by", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("role_type_name", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RoleTypeMaster _escapedModel;

}