/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.RotationTypeMaster;
import gov.omsb.tms.model.RotationTypeMasterModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RotationTypeMaster service. Represents a row in the &quot;rotation_type_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RotationTypeMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RotationTypeMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RotationTypeMasterImpl
 * @generated
 */
@JSON(strict = true)
public class RotationTypeMasterModelImpl
	extends BaseModelImpl<RotationTypeMaster>
	implements RotationTypeMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rotation type master model instance should use the <code>RotationTypeMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "rotation_type_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"rotation_type_master_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT},
		{"rotation_type_name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rotation_type_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("rotation_type_name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rotation_type_master (uuid_ VARCHAR(75) null,rotation_type_master_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,rotation_type_name STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table rotation_type_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rotationTypeMaster.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rotation_type_master.modified_date DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROTATIONTYPENAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RotationTypeMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _rotationTypeMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRotationTypeMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _rotationTypeMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RotationTypeMaster.class;
	}

	@Override
	public String getModelClassName() {
		return RotationTypeMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RotationTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RotationTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RotationTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RotationTypeMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RotationTypeMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RotationTypeMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RotationTypeMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RotationTypeMaster, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RotationTypeMaster, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<RotationTypeMaster, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RotationTypeMaster, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RotationTypeMaster, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<RotationTypeMaster, Object>>();
		Map<String, BiConsumer<RotationTypeMaster, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<RotationTypeMaster, ?>>();

		attributeGetterFunctions.put("uuid", RotationTypeMaster::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<RotationTypeMaster, String>)
				RotationTypeMaster::setUuid);
		attributeGetterFunctions.put(
			"rotationTypeMasterId",
			RotationTypeMaster::getRotationTypeMasterId);
		attributeSetterBiConsumers.put(
			"rotationTypeMasterId",
			(BiConsumer<RotationTypeMaster, Long>)
				RotationTypeMaster::setRotationTypeMasterId);
		attributeGetterFunctions.put("groupId", RotationTypeMaster::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<RotationTypeMaster, Long>)
				RotationTypeMaster::setGroupId);
		attributeGetterFunctions.put(
			"companyId", RotationTypeMaster::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<RotationTypeMaster, Long>)
				RotationTypeMaster::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", RotationTypeMaster::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<RotationTypeMaster, Date>)
				RotationTypeMaster::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", RotationTypeMaster::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<RotationTypeMaster, Long>)
				RotationTypeMaster::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", RotationTypeMaster::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<RotationTypeMaster, Date>)
				RotationTypeMaster::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", RotationTypeMaster::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<RotationTypeMaster, Long>)
				RotationTypeMaster::setModifiedBy);
		attributeGetterFunctions.put(
			"rotationTypeName", RotationTypeMaster::getRotationTypeName);
		attributeSetterBiConsumers.put(
			"rotationTypeName",
			(BiConsumer<RotationTypeMaster, String>)
				RotationTypeMaster::setRotationTypeName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getRotationTypeMasterId() {
		return _rotationTypeMasterId;
	}

	@Override
	public void setRotationTypeMasterId(long rotationTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rotationTypeMasterId = rotationTypeMasterId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public String getRotationTypeName() {
		if (_rotationTypeName == null) {
			return "";
		}
		else {
			return _rotationTypeName;
		}
	}

	@Override
	public String getRotationTypeName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getRotationTypeName(languageId);
	}

	@Override
	public String getRotationTypeName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getRotationTypeName(languageId, useDefault);
	}

	@Override
	public String getRotationTypeName(String languageId) {
		return LocalizationUtil.getLocalization(
			getRotationTypeName(), languageId);
	}

	@Override
	public String getRotationTypeName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getRotationTypeName(), languageId, useDefault);
	}

	@Override
	public String getRotationTypeNameCurrentLanguageId() {
		return _rotationTypeNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getRotationTypeNameCurrentValue() {
		Locale locale = getLocale(_rotationTypeNameCurrentLanguageId);

		return getRotationTypeName(locale);
	}

	@Override
	public Map<Locale, String> getRotationTypeNameMap() {
		return LocalizationUtil.getLocalizationMap(getRotationTypeName());
	}

	@Override
	public void setRotationTypeName(String rotationTypeName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rotationTypeName = rotationTypeName;
	}

	@Override
	public void setRotationTypeName(String rotationTypeName, Locale locale) {
		setRotationTypeName(rotationTypeName, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setRotationTypeName(
		String rotationTypeName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(rotationTypeName)) {
			setRotationTypeName(
				LocalizationUtil.updateLocalization(
					getRotationTypeName(), "RotationTypeName", rotationTypeName,
					languageId, defaultLanguageId));
		}
		else {
			setRotationTypeName(
				LocalizationUtil.removeLocalization(
					getRotationTypeName(), "RotationTypeName", languageId));
		}
	}

	@Override
	public void setRotationTypeNameCurrentLanguageId(String languageId) {
		_rotationTypeNameCurrentLanguageId = languageId;
	}

	@Override
	public void setRotationTypeNameMap(
		Map<Locale, String> rotationTypeNameMap) {

		setRotationTypeNameMap(rotationTypeNameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setRotationTypeNameMap(
		Map<Locale, String> rotationTypeNameMap, Locale defaultLocale) {

		if (rotationTypeNameMap == null) {
			return;
		}

		setRotationTypeName(
			LocalizationUtil.updateLocalization(
				rotationTypeNameMap, getRotationTypeName(), "RotationTypeName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalRotationTypeName() {
		return getColumnOriginalValue("rotation_type_name");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(RotationTypeMaster.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), RotationTypeMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> rotationTypeNameMap = getRotationTypeNameMap();

		for (Map.Entry<Locale, String> entry : rotationTypeNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getRotationTypeName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			RotationTypeMaster.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String rotationTypeName = getRotationTypeName(defaultLocale);

		if (Validator.isNull(rotationTypeName)) {
			setRotationTypeName(
				getRotationTypeName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setRotationTypeName(
				getRotationTypeName(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public RotationTypeMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RotationTypeMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RotationTypeMasterImpl rotationTypeMasterImpl =
			new RotationTypeMasterImpl();

		rotationTypeMasterImpl.setUuid(getUuid());
		rotationTypeMasterImpl.setRotationTypeMasterId(
			getRotationTypeMasterId());
		rotationTypeMasterImpl.setGroupId(getGroupId());
		rotationTypeMasterImpl.setCompanyId(getCompanyId());
		rotationTypeMasterImpl.setCreateDate(getCreateDate());
		rotationTypeMasterImpl.setCreatedBy(getCreatedBy());
		rotationTypeMasterImpl.setModifiedDate(getModifiedDate());
		rotationTypeMasterImpl.setModifiedBy(getModifiedBy());
		rotationTypeMasterImpl.setRotationTypeName(getRotationTypeName());

		rotationTypeMasterImpl.resetOriginalValues();

		return rotationTypeMasterImpl;
	}

	@Override
	public RotationTypeMaster cloneWithOriginalValues() {
		RotationTypeMasterImpl rotationTypeMasterImpl =
			new RotationTypeMasterImpl();

		rotationTypeMasterImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		rotationTypeMasterImpl.setRotationTypeMasterId(
			this.<Long>getColumnOriginalValue("rotation_type_master_id"));
		rotationTypeMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		rotationTypeMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		rotationTypeMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		rotationTypeMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		rotationTypeMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		rotationTypeMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		rotationTypeMasterImpl.setRotationTypeName(
			this.<String>getColumnOriginalValue("rotation_type_name"));

		return rotationTypeMasterImpl;
	}

	@Override
	public int compareTo(RotationTypeMaster rotationTypeMaster) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), rotationTypeMaster.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RotationTypeMaster)) {
			return false;
		}

		RotationTypeMaster rotationTypeMaster = (RotationTypeMaster)object;

		long primaryKey = rotationTypeMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RotationTypeMaster> toCacheModel() {
		RotationTypeMasterCacheModel rotationTypeMasterCacheModel =
			new RotationTypeMasterCacheModel();

		rotationTypeMasterCacheModel.uuid = getUuid();

		String uuid = rotationTypeMasterCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			rotationTypeMasterCacheModel.uuid = null;
		}

		rotationTypeMasterCacheModel.rotationTypeMasterId =
			getRotationTypeMasterId();

		rotationTypeMasterCacheModel.groupId = getGroupId();

		rotationTypeMasterCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			rotationTypeMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			rotationTypeMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		rotationTypeMasterCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			rotationTypeMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			rotationTypeMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		rotationTypeMasterCacheModel.modifiedBy = getModifiedBy();

		rotationTypeMasterCacheModel.rotationTypeName = getRotationTypeName();

		String rotationTypeName = rotationTypeMasterCacheModel.rotationTypeName;

		if ((rotationTypeName != null) && (rotationTypeName.length() == 0)) {
			rotationTypeMasterCacheModel.rotationTypeName = null;
		}

		return rotationTypeMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RotationTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RotationTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RotationTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RotationTypeMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RotationTypeMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RotationTypeMaster.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _rotationTypeMasterId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private String _rotationTypeName;
	private String _rotationTypeNameCurrentLanguageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RotationTypeMaster, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RotationTypeMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"rotation_type_master_id", _rotationTypeMasterId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("rotation_type_name", _rotationTypeName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("rotation_type_master_id", "rotationTypeMasterId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("rotation_type_name", "rotationTypeName");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("rotation_type_master_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("created_by", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("rotation_type_name", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RotationTypeMaster _escapedModel;

}