/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.TraineeProgdurationTraineelevelDetails;
import gov.omsb.tms.model.TraineeProgdurationTraineelevelDetailsModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TraineeProgdurationTraineelevelDetails service. Represents a row in the &quot;trainee_progduration_traineelevel_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TraineeProgdurationTraineelevelDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TraineeProgdurationTraineelevelDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TraineeProgdurationTraineelevelDetailsImpl
 * @generated
 */
@JSON(strict = true)
public class TraineeProgdurationTraineelevelDetailsModelImpl
	extends BaseModelImpl<TraineeProgdurationTraineelevelDetails>
	implements TraineeProgdurationTraineelevelDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trainee progduration traineelevel details model instance should use the <code>TraineeProgdurationTraineelevelDetails</code> interface instead.
	 */
	public static final String TABLE_NAME =
		"trainee_progduration_traineelevel_details";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"trainee_pd_tl_er_details_id", Types.BIGINT},
		{"trainee_id", Types.BIGINT}, {"program_duration_id", Types.BIGINT},
		{"trainee_level_id", Types.BIGINT}, {"group_id", Types.BIGINT},
		{"company_id", Types.BIGINT}, {"create_date", Types.TIMESTAMP},
		{"created_by", Types.BIGINT}, {"modified_date", Types.TIMESTAMP},
		{"modified_by", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trainee_pd_tl_er_details_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("trainee_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_duration_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("trainee_level_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table trainee_progduration_traineelevel_details (uuid_ VARCHAR(75) null,trainee_pd_tl_er_details_id LONG not null primary key,trainee_id LONG,program_duration_id LONG,trainee_level_id LONG,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table trainee_progduration_traineelevel_details";

	public static final String ORDER_BY_JPQL =
		" ORDER BY traineeProgdurationTraineelevelDetails.traineePdTlErDetailsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY trainee_progduration_traineelevel_details.trainee_pd_tl_er_details_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRAMDURATIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEELEVELID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEEPDTLERDETAILSID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TraineeProgdurationTraineelevelDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _traineePdTlErDetailsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTraineePdTlErDetailsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _traineePdTlErDetailsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TraineeProgdurationTraineelevelDetails.class;
	}

	@Override
	public String getModelClassName() {
		return TraineeProgdurationTraineelevelDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TraineeProgdurationTraineelevelDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String,
				 Function<TraineeProgdurationTraineelevelDetails, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeProgdurationTraineelevelDetails, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(TraineeProgdurationTraineelevelDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TraineeProgdurationTraineelevelDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TraineeProgdurationTraineelevelDetails, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TraineeProgdurationTraineelevelDetails)this,
					entry.getValue());
			}
		}
	}

	public Map<String, Function<TraineeProgdurationTraineelevelDetails, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map
		<String, BiConsumer<TraineeProgdurationTraineelevelDetails, Object>>
			getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<TraineeProgdurationTraineelevelDetails, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<TraineeProgdurationTraineelevelDetails, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<TraineeProgdurationTraineelevelDetails, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String,
					 Function
						 <TraineeProgdurationTraineelevelDetails, Object>>();
		Map<String, BiConsumer<TraineeProgdurationTraineelevelDetails, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String,
					 BiConsumer<TraineeProgdurationTraineelevelDetails, ?>>();

		attributeGetterFunctions.put(
			"uuid", TraineeProgdurationTraineelevelDetails::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, String>)
				TraineeProgdurationTraineelevelDetails::setUuid);
		attributeGetterFunctions.put(
			"traineePdTlErDetailsId",
			TraineeProgdurationTraineelevelDetails::getTraineePdTlErDetailsId);
		attributeSetterBiConsumers.put(
			"traineePdTlErDetailsId",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Long>)
				TraineeProgdurationTraineelevelDetails::
					setTraineePdTlErDetailsId);
		attributeGetterFunctions.put(
			"traineeId", TraineeProgdurationTraineelevelDetails::getTraineeId);
		attributeSetterBiConsumers.put(
			"traineeId",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Long>)
				TraineeProgdurationTraineelevelDetails::setTraineeId);
		attributeGetterFunctions.put(
			"programDurationId",
			TraineeProgdurationTraineelevelDetails::getProgramDurationId);
		attributeSetterBiConsumers.put(
			"programDurationId",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Long>)
				TraineeProgdurationTraineelevelDetails::setProgramDurationId);
		attributeGetterFunctions.put(
			"traineeLevelId",
			TraineeProgdurationTraineelevelDetails::getTraineeLevelId);
		attributeSetterBiConsumers.put(
			"traineeLevelId",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Long>)
				TraineeProgdurationTraineelevelDetails::setTraineeLevelId);
		attributeGetterFunctions.put(
			"groupId", TraineeProgdurationTraineelevelDetails::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Long>)
				TraineeProgdurationTraineelevelDetails::setGroupId);
		attributeGetterFunctions.put(
			"companyId", TraineeProgdurationTraineelevelDetails::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Long>)
				TraineeProgdurationTraineelevelDetails::setCompanyId);
		attributeGetterFunctions.put(
			"createDate",
			TraineeProgdurationTraineelevelDetails::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Date>)
				TraineeProgdurationTraineelevelDetails::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", TraineeProgdurationTraineelevelDetails::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Long>)
				TraineeProgdurationTraineelevelDetails::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate",
			TraineeProgdurationTraineelevelDetails::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Date>)
				TraineeProgdurationTraineelevelDetails::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy",
			TraineeProgdurationTraineelevelDetails::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<TraineeProgdurationTraineelevelDetails, Long>)
				TraineeProgdurationTraineelevelDetails::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getTraineePdTlErDetailsId() {
		return _traineePdTlErDetailsId;
	}

	@Override
	public void setTraineePdTlErDetailsId(long traineePdTlErDetailsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineePdTlErDetailsId = traineePdTlErDetailsId;
	}

	@JSON
	@Override
	public long getTraineeId() {
		return _traineeId;
	}

	@Override
	public void setTraineeId(long traineeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeId = traineeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTraineeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("trainee_id"));
	}

	@JSON
	@Override
	public long getProgramDurationId() {
		return _programDurationId;
	}

	@Override
	public void setProgramDurationId(long programDurationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programDurationId = programDurationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgramDurationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("program_duration_id"));
	}

	@JSON
	@Override
	public long getTraineeLevelId() {
		return _traineeLevelId;
	}

	@Override
	public void setTraineeLevelId(long traineeLevelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeLevelId = traineeLevelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTraineeLevelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("trainee_level_id"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				TraineeProgdurationTraineelevelDetails.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(),
			TraineeProgdurationTraineelevelDetails.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TraineeProgdurationTraineelevelDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TraineeProgdurationTraineelevelDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TraineeProgdurationTraineelevelDetailsImpl
			traineeProgdurationTraineelevelDetailsImpl =
				new TraineeProgdurationTraineelevelDetailsImpl();

		traineeProgdurationTraineelevelDetailsImpl.setUuid(getUuid());
		traineeProgdurationTraineelevelDetailsImpl.setTraineePdTlErDetailsId(
			getTraineePdTlErDetailsId());
		traineeProgdurationTraineelevelDetailsImpl.setTraineeId(getTraineeId());
		traineeProgdurationTraineelevelDetailsImpl.setProgramDurationId(
			getProgramDurationId());
		traineeProgdurationTraineelevelDetailsImpl.setTraineeLevelId(
			getTraineeLevelId());
		traineeProgdurationTraineelevelDetailsImpl.setGroupId(getGroupId());
		traineeProgdurationTraineelevelDetailsImpl.setCompanyId(getCompanyId());
		traineeProgdurationTraineelevelDetailsImpl.setCreateDate(
			getCreateDate());
		traineeProgdurationTraineelevelDetailsImpl.setCreatedBy(getCreatedBy());
		traineeProgdurationTraineelevelDetailsImpl.setModifiedDate(
			getModifiedDate());
		traineeProgdurationTraineelevelDetailsImpl.setModifiedBy(
			getModifiedBy());

		traineeProgdurationTraineelevelDetailsImpl.resetOriginalValues();

		return traineeProgdurationTraineelevelDetailsImpl;
	}

	@Override
	public TraineeProgdurationTraineelevelDetails cloneWithOriginalValues() {
		TraineeProgdurationTraineelevelDetailsImpl
			traineeProgdurationTraineelevelDetailsImpl =
				new TraineeProgdurationTraineelevelDetailsImpl();

		traineeProgdurationTraineelevelDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		traineeProgdurationTraineelevelDetailsImpl.setTraineePdTlErDetailsId(
			this.<Long>getColumnOriginalValue("trainee_pd_tl_er_details_id"));
		traineeProgdurationTraineelevelDetailsImpl.setTraineeId(
			this.<Long>getColumnOriginalValue("trainee_id"));
		traineeProgdurationTraineelevelDetailsImpl.setProgramDurationId(
			this.<Long>getColumnOriginalValue("program_duration_id"));
		traineeProgdurationTraineelevelDetailsImpl.setTraineeLevelId(
			this.<Long>getColumnOriginalValue("trainee_level_id"));
		traineeProgdurationTraineelevelDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		traineeProgdurationTraineelevelDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		traineeProgdurationTraineelevelDetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		traineeProgdurationTraineelevelDetailsImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		traineeProgdurationTraineelevelDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		traineeProgdurationTraineelevelDetailsImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));

		return traineeProgdurationTraineelevelDetailsImpl;
	}

	@Override
	public int compareTo(
		TraineeProgdurationTraineelevelDetails
			traineeProgdurationTraineelevelDetails) {

		long primaryKey =
			traineeProgdurationTraineelevelDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TraineeProgdurationTraineelevelDetails)) {
			return false;
		}

		TraineeProgdurationTraineelevelDetails
			traineeProgdurationTraineelevelDetails =
				(TraineeProgdurationTraineelevelDetails)object;

		long primaryKey =
			traineeProgdurationTraineelevelDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TraineeProgdurationTraineelevelDetails> toCacheModel() {
		TraineeProgdurationTraineelevelDetailsCacheModel
			traineeProgdurationTraineelevelDetailsCacheModel =
				new TraineeProgdurationTraineelevelDetailsCacheModel();

		traineeProgdurationTraineelevelDetailsCacheModel.uuid = getUuid();

		String uuid = traineeProgdurationTraineelevelDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			traineeProgdurationTraineelevelDetailsCacheModel.uuid = null;
		}

		traineeProgdurationTraineelevelDetailsCacheModel.
			traineePdTlErDetailsId = getTraineePdTlErDetailsId();

		traineeProgdurationTraineelevelDetailsCacheModel.traineeId =
			getTraineeId();

		traineeProgdurationTraineelevelDetailsCacheModel.programDurationId =
			getProgramDurationId();

		traineeProgdurationTraineelevelDetailsCacheModel.traineeLevelId =
			getTraineeLevelId();

		traineeProgdurationTraineelevelDetailsCacheModel.groupId = getGroupId();

		traineeProgdurationTraineelevelDetailsCacheModel.companyId =
			getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			traineeProgdurationTraineelevelDetailsCacheModel.createDate =
				createDate.getTime();
		}
		else {
			traineeProgdurationTraineelevelDetailsCacheModel.createDate =
				Long.MIN_VALUE;
		}

		traineeProgdurationTraineelevelDetailsCacheModel.createdBy =
			getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			traineeProgdurationTraineelevelDetailsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			traineeProgdurationTraineelevelDetailsCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		traineeProgdurationTraineelevelDetailsCacheModel.modifiedBy =
			getModifiedBy();

		return traineeProgdurationTraineelevelDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TraineeProgdurationTraineelevelDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry
				<String,
				 Function<TraineeProgdurationTraineelevelDetails, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeProgdurationTraineelevelDetails, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TraineeProgdurationTraineelevelDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, TraineeProgdurationTraineelevelDetails>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						TraineeProgdurationTraineelevelDetails.class,
						ModelWrapper.class);

	}

	private String _uuid;
	private long _traineePdTlErDetailsId;
	private long _traineeId;
	private long _programDurationId;
	private long _traineeLevelId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TraineeProgdurationTraineelevelDetails, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TraineeProgdurationTraineelevelDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"trainee_pd_tl_er_details_id", _traineePdTlErDetailsId);
		_columnOriginalValues.put("trainee_id", _traineeId);
		_columnOriginalValues.put("program_duration_id", _programDurationId);
		_columnOriginalValues.put("trainee_level_id", _traineeLevelId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"trainee_pd_tl_er_details_id", "traineePdTlErDetailsId");
		attributeNames.put("trainee_id", "traineeId");
		attributeNames.put("program_duration_id", "programDurationId");
		attributeNames.put("trainee_level_id", "traineeLevelId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("trainee_pd_tl_er_details_id", 2L);

		columnBitmasks.put("trainee_id", 4L);

		columnBitmasks.put("program_duration_id", 8L);

		columnBitmasks.put("trainee_level_id", 16L);

		columnBitmasks.put("group_id", 32L);

		columnBitmasks.put("company_id", 64L);

		columnBitmasks.put("create_date", 128L);

		columnBitmasks.put("created_by", 256L);

		columnBitmasks.put("modified_date", 512L);

		columnBitmasks.put("modified_by", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TraineeProgdurationTraineelevelDetails _escapedModel;

}