/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.TraineeElectiverotationPriorityDetails;
import gov.omsb.tms.model.TraineeElectiverotationPriorityDetailsModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TraineeElectiverotationPriorityDetails service. Represents a row in the &quot;trainee_electiverotation_priority_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TraineeElectiverotationPriorityDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TraineeElectiverotationPriorityDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TraineeElectiverotationPriorityDetailsImpl
 * @generated
 */
@JSON(strict = true)
public class TraineeElectiverotationPriorityDetailsModelImpl
	extends BaseModelImpl<TraineeElectiverotationPriorityDetails>
	implements TraineeElectiverotationPriorityDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trainee electiverotation priority details model instance should use the <code>TraineeElectiverotationPriorityDetails</code> interface instead.
	 */
	public static final String TABLE_NAME =
		"trainee_electiverotation_priority_details";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR},
		{"trainee_electiverotation_priority_details_id", Types.BIGINT},
		{"trainee_pd_tl_er_details_id", Types.BIGINT},
		{"rotation_id", Types.BIGINT}, {"group_id", Types.BIGINT},
		{"company_id", Types.BIGINT}, {"create_date", Types.TIMESTAMP},
		{"created_by", Types.BIGINT}, {"modified_date", Types.TIMESTAMP},
		{"modified_by", Types.BIGINT}, {"sequence", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put(
			"trainee_electiverotation_priority_details_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("trainee_pd_tl_er_details_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("rotation_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sequence", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table trainee_electiverotation_priority_details (uuid_ VARCHAR(75) null,trainee_electiverotation_priority_details_id LONG not null primary key,trainee_pd_tl_er_details_id LONG,rotation_id LONG,group_id LONG,company_id LONG,create_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,sequence INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table trainee_electiverotation_priority_details";

	public static final String ORDER_BY_JPQL =
		" ORDER BY traineeElectiverotationPriorityDetails.traineeElectiverotationPriorityDetailsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY trainee_electiverotation_priority_details.trainee_electiverotation_priority_details_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEEPDTLERDETAILSID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long
		TRAINEEELECTIVEROTATIONPRIORITYDETAILSID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TraineeElectiverotationPriorityDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _traineeElectiverotationPriorityDetailsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTraineeElectiverotationPriorityDetailsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _traineeElectiverotationPriorityDetailsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TraineeElectiverotationPriorityDetails.class;
	}

	@Override
	public String getModelClassName() {
		return TraineeElectiverotationPriorityDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TraineeElectiverotationPriorityDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String,
				 Function<TraineeElectiverotationPriorityDetails, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeElectiverotationPriorityDetails, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(TraineeElectiverotationPriorityDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TraineeElectiverotationPriorityDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TraineeElectiverotationPriorityDetails, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TraineeElectiverotationPriorityDetails)this,
					entry.getValue());
			}
		}
	}

	public Map<String, Function<TraineeElectiverotationPriorityDetails, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map
		<String, BiConsumer<TraineeElectiverotationPriorityDetails, Object>>
			getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<TraineeElectiverotationPriorityDetails, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<TraineeElectiverotationPriorityDetails, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<TraineeElectiverotationPriorityDetails, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String,
					 Function
						 <TraineeElectiverotationPriorityDetails, Object>>();
		Map<String, BiConsumer<TraineeElectiverotationPriorityDetails, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String,
					 BiConsumer<TraineeElectiverotationPriorityDetails, ?>>();

		attributeGetterFunctions.put(
			"uuid", TraineeElectiverotationPriorityDetails::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<TraineeElectiverotationPriorityDetails, String>)
				TraineeElectiverotationPriorityDetails::setUuid);
		attributeGetterFunctions.put(
			"traineeElectiverotationPriorityDetailsId",
			TraineeElectiverotationPriorityDetails::
				getTraineeElectiverotationPriorityDetailsId);
		attributeSetterBiConsumers.put(
			"traineeElectiverotationPriorityDetailsId",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Long>)
				TraineeElectiverotationPriorityDetails::
					setTraineeElectiverotationPriorityDetailsId);
		attributeGetterFunctions.put(
			"traineePdTlErDetailsId",
			TraineeElectiverotationPriorityDetails::getTraineePdTlErDetailsId);
		attributeSetterBiConsumers.put(
			"traineePdTlErDetailsId",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Long>)
				TraineeElectiverotationPriorityDetails::
					setTraineePdTlErDetailsId);
		attributeGetterFunctions.put(
			"rotationId",
			TraineeElectiverotationPriorityDetails::getRotationId);
		attributeSetterBiConsumers.put(
			"rotationId",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Long>)
				TraineeElectiverotationPriorityDetails::setRotationId);
		attributeGetterFunctions.put(
			"groupId", TraineeElectiverotationPriorityDetails::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Long>)
				TraineeElectiverotationPriorityDetails::setGroupId);
		attributeGetterFunctions.put(
			"companyId", TraineeElectiverotationPriorityDetails::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Long>)
				TraineeElectiverotationPriorityDetails::setCompanyId);
		attributeGetterFunctions.put(
			"createDate",
			TraineeElectiverotationPriorityDetails::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Date>)
				TraineeElectiverotationPriorityDetails::setCreateDate);
		attributeGetterFunctions.put(
			"createdBy", TraineeElectiverotationPriorityDetails::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Long>)
				TraineeElectiverotationPriorityDetails::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate",
			TraineeElectiverotationPriorityDetails::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Date>)
				TraineeElectiverotationPriorityDetails::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy",
			TraineeElectiverotationPriorityDetails::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Long>)
				TraineeElectiverotationPriorityDetails::setModifiedBy);
		attributeGetterFunctions.put(
			"sequence", TraineeElectiverotationPriorityDetails::getSequence);
		attributeSetterBiConsumers.put(
			"sequence",
			(BiConsumer<TraineeElectiverotationPriorityDetails, Integer>)
				TraineeElectiverotationPriorityDetails::setSequence);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getTraineeElectiverotationPriorityDetailsId() {
		return _traineeElectiverotationPriorityDetailsId;
	}

	@Override
	public void setTraineeElectiverotationPriorityDetailsId(
		long traineeElectiverotationPriorityDetailsId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeElectiverotationPriorityDetailsId =
			traineeElectiverotationPriorityDetailsId;
	}

	@JSON
	@Override
	public long getTraineePdTlErDetailsId() {
		return _traineePdTlErDetailsId;
	}

	@Override
	public void setTraineePdTlErDetailsId(long traineePdTlErDetailsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineePdTlErDetailsId = traineePdTlErDetailsId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTraineePdTlErDetailsId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("trainee_pd_tl_er_details_id"));
	}

	@JSON
	@Override
	public long getRotationId() {
		return _rotationId;
	}

	@Override
	public void setRotationId(long rotationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rotationId = rotationId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public int getSequence() {
		return _sequence;
	}

	@Override
	public void setSequence(int sequence) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sequence = sequence;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				TraineeElectiverotationPriorityDetails.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(),
			TraineeElectiverotationPriorityDetails.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TraineeElectiverotationPriorityDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TraineeElectiverotationPriorityDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TraineeElectiverotationPriorityDetailsImpl
			traineeElectiverotationPriorityDetailsImpl =
				new TraineeElectiverotationPriorityDetailsImpl();

		traineeElectiverotationPriorityDetailsImpl.setUuid(getUuid());
		traineeElectiverotationPriorityDetailsImpl.
			setTraineeElectiverotationPriorityDetailsId(
				getTraineeElectiverotationPriorityDetailsId());
		traineeElectiverotationPriorityDetailsImpl.setTraineePdTlErDetailsId(
			getTraineePdTlErDetailsId());
		traineeElectiverotationPriorityDetailsImpl.setRotationId(
			getRotationId());
		traineeElectiverotationPriorityDetailsImpl.setGroupId(getGroupId());
		traineeElectiverotationPriorityDetailsImpl.setCompanyId(getCompanyId());
		traineeElectiverotationPriorityDetailsImpl.setCreateDate(
			getCreateDate());
		traineeElectiverotationPriorityDetailsImpl.setCreatedBy(getCreatedBy());
		traineeElectiverotationPriorityDetailsImpl.setModifiedDate(
			getModifiedDate());
		traineeElectiverotationPriorityDetailsImpl.setModifiedBy(
			getModifiedBy());
		traineeElectiverotationPriorityDetailsImpl.setSequence(getSequence());

		traineeElectiverotationPriorityDetailsImpl.resetOriginalValues();

		return traineeElectiverotationPriorityDetailsImpl;
	}

	@Override
	public TraineeElectiverotationPriorityDetails cloneWithOriginalValues() {
		TraineeElectiverotationPriorityDetailsImpl
			traineeElectiverotationPriorityDetailsImpl =
				new TraineeElectiverotationPriorityDetailsImpl();

		traineeElectiverotationPriorityDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		traineeElectiverotationPriorityDetailsImpl.
			setTraineeElectiverotationPriorityDetailsId(
				this.<Long>getColumnOriginalValue(
					"trainee_electiverotation_priority_details_id"));
		traineeElectiverotationPriorityDetailsImpl.setTraineePdTlErDetailsId(
			this.<Long>getColumnOriginalValue("trainee_pd_tl_er_details_id"));
		traineeElectiverotationPriorityDetailsImpl.setRotationId(
			this.<Long>getColumnOriginalValue("rotation_id"));
		traineeElectiverotationPriorityDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		traineeElectiverotationPriorityDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		traineeElectiverotationPriorityDetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		traineeElectiverotationPriorityDetailsImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		traineeElectiverotationPriorityDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		traineeElectiverotationPriorityDetailsImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		traineeElectiverotationPriorityDetailsImpl.setSequence(
			this.<Integer>getColumnOriginalValue("sequence"));

		return traineeElectiverotationPriorityDetailsImpl;
	}

	@Override
	public int compareTo(
		TraineeElectiverotationPriorityDetails
			traineeElectiverotationPriorityDetails) {

		long primaryKey =
			traineeElectiverotationPriorityDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TraineeElectiverotationPriorityDetails)) {
			return false;
		}

		TraineeElectiverotationPriorityDetails
			traineeElectiverotationPriorityDetails =
				(TraineeElectiverotationPriorityDetails)object;

		long primaryKey =
			traineeElectiverotationPriorityDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TraineeElectiverotationPriorityDetails> toCacheModel() {
		TraineeElectiverotationPriorityDetailsCacheModel
			traineeElectiverotationPriorityDetailsCacheModel =
				new TraineeElectiverotationPriorityDetailsCacheModel();

		traineeElectiverotationPriorityDetailsCacheModel.uuid = getUuid();

		String uuid = traineeElectiverotationPriorityDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			traineeElectiverotationPriorityDetailsCacheModel.uuid = null;
		}

		traineeElectiverotationPriorityDetailsCacheModel.
			traineeElectiverotationPriorityDetailsId =
				getTraineeElectiverotationPriorityDetailsId();

		traineeElectiverotationPriorityDetailsCacheModel.
			traineePdTlErDetailsId = getTraineePdTlErDetailsId();

		traineeElectiverotationPriorityDetailsCacheModel.rotationId =
			getRotationId();

		traineeElectiverotationPriorityDetailsCacheModel.groupId = getGroupId();

		traineeElectiverotationPriorityDetailsCacheModel.companyId =
			getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			traineeElectiverotationPriorityDetailsCacheModel.createDate =
				createDate.getTime();
		}
		else {
			traineeElectiverotationPriorityDetailsCacheModel.createDate =
				Long.MIN_VALUE;
		}

		traineeElectiverotationPriorityDetailsCacheModel.createdBy =
			getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			traineeElectiverotationPriorityDetailsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			traineeElectiverotationPriorityDetailsCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		traineeElectiverotationPriorityDetailsCacheModel.modifiedBy =
			getModifiedBy();

		traineeElectiverotationPriorityDetailsCacheModel.sequence =
			getSequence();

		return traineeElectiverotationPriorityDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TraineeElectiverotationPriorityDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry
				<String,
				 Function<TraineeElectiverotationPriorityDetails, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeElectiverotationPriorityDetails, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TraineeElectiverotationPriorityDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, TraineeElectiverotationPriorityDetails>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						TraineeElectiverotationPriorityDetails.class,
						ModelWrapper.class);

	}

	private String _uuid;
	private long _traineeElectiverotationPriorityDetailsId;
	private long _traineePdTlErDetailsId;
	private long _rotationId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private int _sequence;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TraineeElectiverotationPriorityDetails, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TraineeElectiverotationPriorityDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"trainee_electiverotation_priority_details_id",
			_traineeElectiverotationPriorityDetailsId);
		_columnOriginalValues.put(
			"trainee_pd_tl_er_details_id", _traineePdTlErDetailsId);
		_columnOriginalValues.put("rotation_id", _rotationId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("sequence", _sequence);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"trainee_electiverotation_priority_details_id",
			"traineeElectiverotationPriorityDetailsId");
		attributeNames.put(
			"trainee_pd_tl_er_details_id", "traineePdTlErDetailsId");
		attributeNames.put("rotation_id", "rotationId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("trainee_electiverotation_priority_details_id", 2L);

		columnBitmasks.put("trainee_pd_tl_er_details_id", 4L);

		columnBitmasks.put("rotation_id", 8L);

		columnBitmasks.put("group_id", 16L);

		columnBitmasks.put("company_id", 32L);

		columnBitmasks.put("create_date", 64L);

		columnBitmasks.put("created_by", 128L);

		columnBitmasks.put("modified_date", 256L);

		columnBitmasks.put("modified_by", 512L);

		columnBitmasks.put("sequence", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TraineeElectiverotationPriorityDetails _escapedModel;

}