/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.TraineeCohortDetails;
import gov.omsb.tms.model.TraineeCohortDetailsModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TraineeCohortDetails service. Represents a row in the &quot;trainee_cohort_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TraineeCohortDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TraineeCohortDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TraineeCohortDetailsImpl
 * @generated
 */
@JSON(strict = true)
public class TraineeCohortDetailsModelImpl
	extends BaseModelImpl<TraineeCohortDetails>
	implements TraineeCohortDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trainee cohort details model instance should use the <code>TraineeCohortDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "trainee_cohort_details";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"trainee_cohort_details_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"modified_date", Types.TIMESTAMP},
		{"created_by", Types.BIGINT}, {"modified_by", Types.BIGINT},
		{"trainee_admission_details_rel_id", Types.BIGINT},
		{"cohort_year", Types.VARCHAR}, {"is_current_cohort", Types.BOOLEAN},
		{"trainee_level_id", Types.BIGINT},
		{"is_current_trainee_level", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trainee_cohort_details_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("trainee_admission_details_rel_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cohort_year", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("is_current_cohort", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("trainee_level_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("is_current_trainee_level", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table trainee_cohort_details (uuid_ VARCHAR(75) null,trainee_cohort_details_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,modified_date DATE null,created_by LONG,modified_by LONG,trainee_admission_details_rel_id LONG,cohort_year VARCHAR(75) null,is_current_cohort BOOLEAN,trainee_level_id LONG,is_current_trainee_level BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table trainee_cohort_details";

	public static final String ORDER_BY_JPQL =
		" ORDER BY traineeCohortDetails.traineeCohortDetailsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY trainee_cohort_details.trainee_cohort_details_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COHORTYEAR_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISCURRENTTRAINEELEVEL_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEEADMISSIONDETAILSRELID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEELEVELID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEECOHORTDETAILSID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TraineeCohortDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _traineeCohortDetailsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTraineeCohortDetailsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _traineeCohortDetailsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TraineeCohortDetails.class;
	}

	@Override
	public String getModelClassName() {
		return TraineeCohortDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TraineeCohortDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TraineeCohortDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeCohortDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TraineeCohortDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TraineeCohortDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TraineeCohortDetails, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TraineeCohortDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TraineeCohortDetails, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TraineeCohortDetails, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TraineeCohortDetails, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TraineeCohortDetails, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TraineeCohortDetails, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TraineeCohortDetails, Object>>();
		Map<String, BiConsumer<TraineeCohortDetails, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<TraineeCohortDetails, ?>>();

		attributeGetterFunctions.put("uuid", TraineeCohortDetails::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<TraineeCohortDetails, String>)
				TraineeCohortDetails::setUuid);
		attributeGetterFunctions.put(
			"traineeCohortDetailsId",
			TraineeCohortDetails::getTraineeCohortDetailsId);
		attributeSetterBiConsumers.put(
			"traineeCohortDetailsId",
			(BiConsumer<TraineeCohortDetails, Long>)
				TraineeCohortDetails::setTraineeCohortDetailsId);
		attributeGetterFunctions.put(
			"groupId", TraineeCohortDetails::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TraineeCohortDetails, Long>)
				TraineeCohortDetails::setGroupId);
		attributeGetterFunctions.put(
			"companyId", TraineeCohortDetails::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TraineeCohortDetails, Long>)
				TraineeCohortDetails::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", TraineeCohortDetails::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TraineeCohortDetails, Date>)
				TraineeCohortDetails::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TraineeCohortDetails::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TraineeCohortDetails, Date>)
				TraineeCohortDetails::setModifiedDate);
		attributeGetterFunctions.put(
			"createdBy", TraineeCohortDetails::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<TraineeCohortDetails, Long>)
				TraineeCohortDetails::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", TraineeCohortDetails::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<TraineeCohortDetails, Long>)
				TraineeCohortDetails::setModifiedBy);
		attributeGetterFunctions.put(
			"traineeAdmissionDetailsRelId",
			TraineeCohortDetails::getTraineeAdmissionDetailsRelId);
		attributeSetterBiConsumers.put(
			"traineeAdmissionDetailsRelId",
			(BiConsumer<TraineeCohortDetails, Long>)
				TraineeCohortDetails::setTraineeAdmissionDetailsRelId);
		attributeGetterFunctions.put(
			"cohortYear", TraineeCohortDetails::getCohortYear);
		attributeSetterBiConsumers.put(
			"cohortYear",
			(BiConsumer<TraineeCohortDetails, String>)
				TraineeCohortDetails::setCohortYear);
		attributeGetterFunctions.put(
			"isCurrentCohort", TraineeCohortDetails::getIsCurrentCohort);
		attributeSetterBiConsumers.put(
			"isCurrentCohort",
			(BiConsumer<TraineeCohortDetails, Boolean>)
				TraineeCohortDetails::setIsCurrentCohort);
		attributeGetterFunctions.put(
			"traineeLevelId", TraineeCohortDetails::getTraineeLevelId);
		attributeSetterBiConsumers.put(
			"traineeLevelId",
			(BiConsumer<TraineeCohortDetails, Long>)
				TraineeCohortDetails::setTraineeLevelId);
		attributeGetterFunctions.put(
			"isCurrentTraineeLevel",
			TraineeCohortDetails::getIsCurrentTraineeLevel);
		attributeSetterBiConsumers.put(
			"isCurrentTraineeLevel",
			(BiConsumer<TraineeCohortDetails, Boolean>)
				TraineeCohortDetails::setIsCurrentTraineeLevel);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getTraineeCohortDetailsId() {
		return _traineeCohortDetailsId;
	}

	@Override
	public void setTraineeCohortDetailsId(long traineeCohortDetailsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeCohortDetailsId = traineeCohortDetailsId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getTraineeAdmissionDetailsRelId() {
		return _traineeAdmissionDetailsRelId;
	}

	@Override
	public void setTraineeAdmissionDetailsRelId(
		long traineeAdmissionDetailsRelId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeAdmissionDetailsRelId = traineeAdmissionDetailsRelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTraineeAdmissionDetailsRelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue(
				"trainee_admission_details_rel_id"));
	}

	@JSON
	@Override
	public String getCohortYear() {
		if (_cohortYear == null) {
			return "";
		}
		else {
			return _cohortYear;
		}
	}

	@Override
	public void setCohortYear(String cohortYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cohortYear = cohortYear;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCohortYear() {
		return getColumnOriginalValue("cohort_year");
	}

	@JSON
	@Override
	public Boolean getIsCurrentCohort() {
		return _isCurrentCohort;
	}

	@Override
	public void setIsCurrentCohort(Boolean isCurrentCohort) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isCurrentCohort = isCurrentCohort;
	}

	@JSON
	@Override
	public long getTraineeLevelId() {
		return _traineeLevelId;
	}

	@Override
	public void setTraineeLevelId(long traineeLevelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeLevelId = traineeLevelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTraineeLevelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("trainee_level_id"));
	}

	@JSON
	@Override
	public Boolean getIsCurrentTraineeLevel() {
		return _isCurrentTraineeLevel;
	}

	@Override
	public void setIsCurrentTraineeLevel(Boolean isCurrentTraineeLevel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isCurrentTraineeLevel = isCurrentTraineeLevel;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Boolean getOriginalIsCurrentTraineeLevel() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("is_current_trainee_level"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TraineeCohortDetails.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TraineeCohortDetails.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TraineeCohortDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TraineeCohortDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TraineeCohortDetailsImpl traineeCohortDetailsImpl =
			new TraineeCohortDetailsImpl();

		traineeCohortDetailsImpl.setUuid(getUuid());
		traineeCohortDetailsImpl.setTraineeCohortDetailsId(
			getTraineeCohortDetailsId());
		traineeCohortDetailsImpl.setGroupId(getGroupId());
		traineeCohortDetailsImpl.setCompanyId(getCompanyId());
		traineeCohortDetailsImpl.setCreateDate(getCreateDate());
		traineeCohortDetailsImpl.setModifiedDate(getModifiedDate());
		traineeCohortDetailsImpl.setCreatedBy(getCreatedBy());
		traineeCohortDetailsImpl.setModifiedBy(getModifiedBy());
		traineeCohortDetailsImpl.setTraineeAdmissionDetailsRelId(
			getTraineeAdmissionDetailsRelId());
		traineeCohortDetailsImpl.setCohortYear(getCohortYear());
		traineeCohortDetailsImpl.setIsCurrentCohort(getIsCurrentCohort());
		traineeCohortDetailsImpl.setTraineeLevelId(getTraineeLevelId());
		traineeCohortDetailsImpl.setIsCurrentTraineeLevel(
			getIsCurrentTraineeLevel());

		traineeCohortDetailsImpl.resetOriginalValues();

		return traineeCohortDetailsImpl;
	}

	@Override
	public TraineeCohortDetails cloneWithOriginalValues() {
		TraineeCohortDetailsImpl traineeCohortDetailsImpl =
			new TraineeCohortDetailsImpl();

		traineeCohortDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		traineeCohortDetailsImpl.setTraineeCohortDetailsId(
			this.<Long>getColumnOriginalValue("trainee_cohort_details_id"));
		traineeCohortDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		traineeCohortDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		traineeCohortDetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		traineeCohortDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		traineeCohortDetailsImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		traineeCohortDetailsImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		traineeCohortDetailsImpl.setTraineeAdmissionDetailsRelId(
			this.<Long>getColumnOriginalValue(
				"trainee_admission_details_rel_id"));
		traineeCohortDetailsImpl.setCohortYear(
			this.<String>getColumnOriginalValue("cohort_year"));
		traineeCohortDetailsImpl.setIsCurrentCohort(
			this.<Boolean>getColumnOriginalValue("is_current_cohort"));
		traineeCohortDetailsImpl.setTraineeLevelId(
			this.<Long>getColumnOriginalValue("trainee_level_id"));
		traineeCohortDetailsImpl.setIsCurrentTraineeLevel(
			this.<Boolean>getColumnOriginalValue("is_current_trainee_level"));

		return traineeCohortDetailsImpl;
	}

	@Override
	public int compareTo(TraineeCohortDetails traineeCohortDetails) {
		long primaryKey = traineeCohortDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TraineeCohortDetails)) {
			return false;
		}

		TraineeCohortDetails traineeCohortDetails =
			(TraineeCohortDetails)object;

		long primaryKey = traineeCohortDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TraineeCohortDetails> toCacheModel() {
		TraineeCohortDetailsCacheModel traineeCohortDetailsCacheModel =
			new TraineeCohortDetailsCacheModel();

		traineeCohortDetailsCacheModel.uuid = getUuid();

		String uuid = traineeCohortDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			traineeCohortDetailsCacheModel.uuid = null;
		}

		traineeCohortDetailsCacheModel.traineeCohortDetailsId =
			getTraineeCohortDetailsId();

		traineeCohortDetailsCacheModel.groupId = getGroupId();

		traineeCohortDetailsCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			traineeCohortDetailsCacheModel.createDate = createDate.getTime();
		}
		else {
			traineeCohortDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			traineeCohortDetailsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			traineeCohortDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		traineeCohortDetailsCacheModel.createdBy = getCreatedBy();

		traineeCohortDetailsCacheModel.modifiedBy = getModifiedBy();

		traineeCohortDetailsCacheModel.traineeAdmissionDetailsRelId =
			getTraineeAdmissionDetailsRelId();

		traineeCohortDetailsCacheModel.cohortYear = getCohortYear();

		String cohortYear = traineeCohortDetailsCacheModel.cohortYear;

		if ((cohortYear != null) && (cohortYear.length() == 0)) {
			traineeCohortDetailsCacheModel.cohortYear = null;
		}

		Boolean isCurrentCohort = getIsCurrentCohort();

		if (isCurrentCohort != null) {
			traineeCohortDetailsCacheModel.isCurrentCohort = isCurrentCohort;
		}

		traineeCohortDetailsCacheModel.traineeLevelId = getTraineeLevelId();

		Boolean isCurrentTraineeLevel = getIsCurrentTraineeLevel();

		if (isCurrentTraineeLevel != null) {
			traineeCohortDetailsCacheModel.isCurrentTraineeLevel =
				isCurrentTraineeLevel;
		}

		return traineeCohortDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TraineeCohortDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TraineeCohortDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeCohortDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TraineeCohortDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TraineeCohortDetails>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TraineeCohortDetails.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _traineeCohortDetailsId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdBy;
	private long _modifiedBy;
	private long _traineeAdmissionDetailsRelId;
	private String _cohortYear;
	private Boolean _isCurrentCohort;
	private long _traineeLevelId;
	private Boolean _isCurrentTraineeLevel;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TraineeCohortDetails, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TraineeCohortDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"trainee_cohort_details_id", _traineeCohortDetailsId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put(
			"trainee_admission_details_rel_id", _traineeAdmissionDetailsRelId);
		_columnOriginalValues.put("cohort_year", _cohortYear);
		_columnOriginalValues.put("is_current_cohort", _isCurrentCohort);
		_columnOriginalValues.put("trainee_level_id", _traineeLevelId);
		_columnOriginalValues.put(
			"is_current_trainee_level", _isCurrentTraineeLevel);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"trainee_cohort_details_id", "traineeCohortDetailsId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put(
			"trainee_admission_details_rel_id", "traineeAdmissionDetailsRelId");
		attributeNames.put("cohort_year", "cohortYear");
		attributeNames.put("is_current_cohort", "isCurrentCohort");
		attributeNames.put("trainee_level_id", "traineeLevelId");
		attributeNames.put("is_current_trainee_level", "isCurrentTraineeLevel");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("trainee_cohort_details_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("modified_date", 32L);

		columnBitmasks.put("created_by", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("trainee_admission_details_rel_id", 256L);

		columnBitmasks.put("cohort_year", 512L);

		columnBitmasks.put("is_current_cohort", 1024L);

		columnBitmasks.put("trainee_level_id", 2048L);

		columnBitmasks.put("is_current_trainee_level", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TraineeCohortDetails _escapedModel;

}