/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.TraineeSponsorDetails;
import gov.omsb.tms.model.TraineeSponsorDetailsModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TraineeSponsorDetails service. Represents a row in the &quot;trainee_sponsor_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TraineeSponsorDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TraineeSponsorDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TraineeSponsorDetailsImpl
 * @generated
 */
@JSON(strict = true)
public class TraineeSponsorDetailsModelImpl
	extends BaseModelImpl<TraineeSponsorDetails>
	implements TraineeSponsorDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trainee sponsor details model instance should use the <code>TraineeSponsorDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "trainee_sponsor_details";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"trainee_sponsor_details_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"created_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT},
		{"trainee_id", Types.BIGINT}, {"program_duration_Id", Types.BIGINT},
		{"sponsor", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trainee_sponsor_details_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("created_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("trainee_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("program_duration_Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sponsor", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table trainee_sponsor_details (uuid_ VARCHAR(75) null,trainee_sponsor_details_id LONG not null primary key,group_id LONG,company_id LONG,created_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,trainee_id LONG,program_duration_Id LONG,sponsor STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table trainee_sponsor_details";

	public static final String ORDER_BY_JPQL =
		" ORDER BY traineeSponsorDetails.traineeSponsorDetailsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY trainee_sponsor_details.trainee_sponsor_details_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEESPONSORDETAILSID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TraineeSponsorDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _traineeSponsorDetailsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTraineeSponsorDetailsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _traineeSponsorDetailsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TraineeSponsorDetails.class;
	}

	@Override
	public String getModelClassName() {
		return TraineeSponsorDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TraineeSponsorDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TraineeSponsorDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeSponsorDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TraineeSponsorDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TraineeSponsorDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TraineeSponsorDetails, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TraineeSponsorDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TraineeSponsorDetails, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TraineeSponsorDetails, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TraineeSponsorDetails, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TraineeSponsorDetails, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TraineeSponsorDetails, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TraineeSponsorDetails, Object>>();
		Map<String, BiConsumer<TraineeSponsorDetails, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<TraineeSponsorDetails, ?>>();

		attributeGetterFunctions.put("uuid", TraineeSponsorDetails::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<TraineeSponsorDetails, String>)
				TraineeSponsorDetails::setUuid);
		attributeGetterFunctions.put(
			"traineeSponsorDetailsId",
			TraineeSponsorDetails::getTraineeSponsorDetailsId);
		attributeSetterBiConsumers.put(
			"traineeSponsorDetailsId",
			(BiConsumer<TraineeSponsorDetails, Long>)
				TraineeSponsorDetails::setTraineeSponsorDetailsId);
		attributeGetterFunctions.put(
			"groupId", TraineeSponsorDetails::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TraineeSponsorDetails, Long>)
				TraineeSponsorDetails::setGroupId);
		attributeGetterFunctions.put(
			"companyId", TraineeSponsorDetails::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TraineeSponsorDetails, Long>)
				TraineeSponsorDetails::setCompanyId);
		attributeGetterFunctions.put(
			"createdDate", TraineeSponsorDetails::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<TraineeSponsorDetails, Date>)
				TraineeSponsorDetails::setCreatedDate);
		attributeGetterFunctions.put(
			"createdBy", TraineeSponsorDetails::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<TraineeSponsorDetails, Long>)
				TraineeSponsorDetails::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", TraineeSponsorDetails::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TraineeSponsorDetails, Date>)
				TraineeSponsorDetails::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", TraineeSponsorDetails::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<TraineeSponsorDetails, Long>)
				TraineeSponsorDetails::setModifiedBy);
		attributeGetterFunctions.put(
			"traineeId", TraineeSponsorDetails::getTraineeId);
		attributeSetterBiConsumers.put(
			"traineeId",
			(BiConsumer<TraineeSponsorDetails, Long>)
				TraineeSponsorDetails::setTraineeId);
		attributeGetterFunctions.put(
			"programDurationId", TraineeSponsorDetails::getProgramDurationId);
		attributeSetterBiConsumers.put(
			"programDurationId",
			(BiConsumer<TraineeSponsorDetails, Long>)
				TraineeSponsorDetails::setProgramDurationId);
		attributeGetterFunctions.put(
			"sponsor", TraineeSponsorDetails::getSponsor);
		attributeSetterBiConsumers.put(
			"sponsor",
			(BiConsumer<TraineeSponsorDetails, String>)
				TraineeSponsorDetails::setSponsor);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getTraineeSponsorDetailsId() {
		return _traineeSponsorDetailsId;
	}

	@Override
	public void setTraineeSponsorDetailsId(long traineeSponsorDetailsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeSponsorDetailsId = traineeSponsorDetailsId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getTraineeId() {
		return _traineeId;
	}

	@Override
	public void setTraineeId(long traineeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeId = traineeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTraineeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("trainee_id"));
	}

	@JSON
	@Override
	public long getProgramDurationId() {
		return _programDurationId;
	}

	@Override
	public void setProgramDurationId(long programDurationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_programDurationId = programDurationId;
	}

	@JSON
	@Override
	public String getSponsor() {
		if (_sponsor == null) {
			return "";
		}
		else {
			return _sponsor;
		}
	}

	@Override
	public String getSponsor(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSponsor(languageId);
	}

	@Override
	public String getSponsor(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSponsor(languageId, useDefault);
	}

	@Override
	public String getSponsor(String languageId) {
		return LocalizationUtil.getLocalization(getSponsor(), languageId);
	}

	@Override
	public String getSponsor(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getSponsor(), languageId, useDefault);
	}

	@Override
	public String getSponsorCurrentLanguageId() {
		return _sponsorCurrentLanguageId;
	}

	@JSON
	@Override
	public String getSponsorCurrentValue() {
		Locale locale = getLocale(_sponsorCurrentLanguageId);

		return getSponsor(locale);
	}

	@Override
	public Map<Locale, String> getSponsorMap() {
		return LocalizationUtil.getLocalizationMap(getSponsor());
	}

	@Override
	public void setSponsor(String sponsor) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sponsor = sponsor;
	}

	@Override
	public void setSponsor(String sponsor, Locale locale) {
		setSponsor(sponsor, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setSponsor(
		String sponsor, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(sponsor)) {
			setSponsor(
				LocalizationUtil.updateLocalization(
					getSponsor(), "Sponsor", sponsor, languageId,
					defaultLanguageId));
		}
		else {
			setSponsor(
				LocalizationUtil.removeLocalization(
					getSponsor(), "Sponsor", languageId));
		}
	}

	@Override
	public void setSponsorCurrentLanguageId(String languageId) {
		_sponsorCurrentLanguageId = languageId;
	}

	@Override
	public void setSponsorMap(Map<Locale, String> sponsorMap) {
		setSponsorMap(sponsorMap, LocaleUtil.getDefault());
	}

	@Override
	public void setSponsorMap(
		Map<Locale, String> sponsorMap, Locale defaultLocale) {

		if (sponsorMap == null) {
			return;
		}

		setSponsor(
			LocalizationUtil.updateLocalization(
				sponsorMap, getSponsor(), "Sponsor",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TraineeSponsorDetails.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> sponsorMap = getSponsorMap();

		for (Map.Entry<Locale, String> entry : sponsorMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getSponsor();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			TraineeSponsorDetails.class.getName(), getPrimaryKey(),
			defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String sponsor = getSponsor(defaultLocale);

		if (Validator.isNull(sponsor)) {
			setSponsor(getSponsor(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setSponsor(getSponsor(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public TraineeSponsorDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TraineeSponsorDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TraineeSponsorDetailsImpl traineeSponsorDetailsImpl =
			new TraineeSponsorDetailsImpl();

		traineeSponsorDetailsImpl.setUuid(getUuid());
		traineeSponsorDetailsImpl.setTraineeSponsorDetailsId(
			getTraineeSponsorDetailsId());
		traineeSponsorDetailsImpl.setGroupId(getGroupId());
		traineeSponsorDetailsImpl.setCompanyId(getCompanyId());
		traineeSponsorDetailsImpl.setCreatedDate(getCreatedDate());
		traineeSponsorDetailsImpl.setCreatedBy(getCreatedBy());
		traineeSponsorDetailsImpl.setModifiedDate(getModifiedDate());
		traineeSponsorDetailsImpl.setModifiedBy(getModifiedBy());
		traineeSponsorDetailsImpl.setTraineeId(getTraineeId());
		traineeSponsorDetailsImpl.setProgramDurationId(getProgramDurationId());
		traineeSponsorDetailsImpl.setSponsor(getSponsor());

		traineeSponsorDetailsImpl.resetOriginalValues();

		return traineeSponsorDetailsImpl;
	}

	@Override
	public TraineeSponsorDetails cloneWithOriginalValues() {
		TraineeSponsorDetailsImpl traineeSponsorDetailsImpl =
			new TraineeSponsorDetailsImpl();

		traineeSponsorDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		traineeSponsorDetailsImpl.setTraineeSponsorDetailsId(
			this.<Long>getColumnOriginalValue("trainee_sponsor_details_id"));
		traineeSponsorDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		traineeSponsorDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		traineeSponsorDetailsImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("created_date"));
		traineeSponsorDetailsImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		traineeSponsorDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		traineeSponsorDetailsImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		traineeSponsorDetailsImpl.setTraineeId(
			this.<Long>getColumnOriginalValue("trainee_id"));
		traineeSponsorDetailsImpl.setProgramDurationId(
			this.<Long>getColumnOriginalValue("program_duration_Id"));
		traineeSponsorDetailsImpl.setSponsor(
			this.<String>getColumnOriginalValue("sponsor"));

		return traineeSponsorDetailsImpl;
	}

	@Override
	public int compareTo(TraineeSponsorDetails traineeSponsorDetails) {
		long primaryKey = traineeSponsorDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TraineeSponsorDetails)) {
			return false;
		}

		TraineeSponsorDetails traineeSponsorDetails =
			(TraineeSponsorDetails)object;

		long primaryKey = traineeSponsorDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TraineeSponsorDetails> toCacheModel() {
		TraineeSponsorDetailsCacheModel traineeSponsorDetailsCacheModel =
			new TraineeSponsorDetailsCacheModel();

		traineeSponsorDetailsCacheModel.uuid = getUuid();

		String uuid = traineeSponsorDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			traineeSponsorDetailsCacheModel.uuid = null;
		}

		traineeSponsorDetailsCacheModel.traineeSponsorDetailsId =
			getTraineeSponsorDetailsId();

		traineeSponsorDetailsCacheModel.groupId = getGroupId();

		traineeSponsorDetailsCacheModel.companyId = getCompanyId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			traineeSponsorDetailsCacheModel.createdDate = createdDate.getTime();
		}
		else {
			traineeSponsorDetailsCacheModel.createdDate = Long.MIN_VALUE;
		}

		traineeSponsorDetailsCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			traineeSponsorDetailsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			traineeSponsorDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		traineeSponsorDetailsCacheModel.modifiedBy = getModifiedBy();

		traineeSponsorDetailsCacheModel.traineeId = getTraineeId();

		traineeSponsorDetailsCacheModel.programDurationId =
			getProgramDurationId();

		traineeSponsorDetailsCacheModel.sponsor = getSponsor();

		String sponsor = traineeSponsorDetailsCacheModel.sponsor;

		if ((sponsor != null) && (sponsor.length() == 0)) {
			traineeSponsorDetailsCacheModel.sponsor = null;
		}

		return traineeSponsorDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TraineeSponsorDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TraineeSponsorDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeSponsorDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TraineeSponsorDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TraineeSponsorDetails>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TraineeSponsorDetails.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _traineeSponsorDetailsId;
	private long _groupId;
	private long _companyId;
	private Date _createdDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private long _traineeId;
	private long _programDurationId;
	private String _sponsor;
	private String _sponsorCurrentLanguageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TraineeSponsorDetails, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TraineeSponsorDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"trainee_sponsor_details_id", _traineeSponsorDetailsId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("created_date", _createdDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("trainee_id", _traineeId);
		_columnOriginalValues.put("program_duration_Id", _programDurationId);
		_columnOriginalValues.put("sponsor", _sponsor);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"trainee_sponsor_details_id", "traineeSponsorDetailsId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("created_date", "createdDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("trainee_id", "traineeId");
		attributeNames.put("program_duration_Id", "programDurationId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("trainee_sponsor_details_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("created_date", 16L);

		columnBitmasks.put("created_by", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("trainee_id", 256L);

		columnBitmasks.put("program_duration_Id", 512L);

		columnBitmasks.put("sponsor", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TraineeSponsorDetails _escapedModel;

}