/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import gov.omsb.tms.model.TraineeLevelMaster;
import gov.omsb.tms.model.TraineeLevelMasterModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TraineeLevelMaster service. Represents a row in the &quot;trainee_level_master&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TraineeLevelMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TraineeLevelMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TraineeLevelMasterImpl
 * @generated
 */
@JSON(strict = true)
public class TraineeLevelMasterModelImpl
	extends BaseModelImpl<TraineeLevelMaster>
	implements TraineeLevelMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trainee level master model instance should use the <code>TraineeLevelMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "trainee_level_master";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"trainee_level_master_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"create_date", Types.TIMESTAMP}, {"modified_date", Types.TIMESTAMP},
		{"created_by", Types.BIGINT}, {"modified_by", Types.BIGINT},
		{"trainee_level_name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trainee_level_master_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("create_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("trainee_level_name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table trainee_level_master (uuid_ VARCHAR(75) null,trainee_level_master_id LONG not null primary key,group_id LONG,company_id LONG,create_date DATE null,modified_date DATE null,created_by LONG,modified_by LONG,trainee_level_name STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table trainee_level_master";

	public static final String ORDER_BY_JPQL =
		" ORDER BY traineeLevelMaster.traineeLevelMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY trainee_level_master.trainee_level_master_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEELEVELNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAINEELEVELMASTERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TraineeLevelMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _traineeLevelMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTraineeLevelMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _traineeLevelMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TraineeLevelMaster.class;
	}

	@Override
	public String getModelClassName() {
		return TraineeLevelMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TraineeLevelMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TraineeLevelMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeLevelMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TraineeLevelMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TraineeLevelMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TraineeLevelMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TraineeLevelMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TraineeLevelMaster, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TraineeLevelMaster, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TraineeLevelMaster, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TraineeLevelMaster, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TraineeLevelMaster, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TraineeLevelMaster, Object>>();
		Map<String, BiConsumer<TraineeLevelMaster, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TraineeLevelMaster, ?>>();

		attributeGetterFunctions.put("uuid", TraineeLevelMaster::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<TraineeLevelMaster, String>)
				TraineeLevelMaster::setUuid);
		attributeGetterFunctions.put(
			"traineeLevelMasterId",
			TraineeLevelMaster::getTraineeLevelMasterId);
		attributeSetterBiConsumers.put(
			"traineeLevelMasterId",
			(BiConsumer<TraineeLevelMaster, Long>)
				TraineeLevelMaster::setTraineeLevelMasterId);
		attributeGetterFunctions.put("groupId", TraineeLevelMaster::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TraineeLevelMaster, Long>)
				TraineeLevelMaster::setGroupId);
		attributeGetterFunctions.put(
			"companyId", TraineeLevelMaster::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TraineeLevelMaster, Long>)
				TraineeLevelMaster::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", TraineeLevelMaster::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TraineeLevelMaster, Date>)
				TraineeLevelMaster::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TraineeLevelMaster::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TraineeLevelMaster, Date>)
				TraineeLevelMaster::setModifiedDate);
		attributeGetterFunctions.put(
			"createdBy", TraineeLevelMaster::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<TraineeLevelMaster, Long>)
				TraineeLevelMaster::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", TraineeLevelMaster::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<TraineeLevelMaster, Long>)
				TraineeLevelMaster::setModifiedBy);
		attributeGetterFunctions.put(
			"traineeLevelName", TraineeLevelMaster::getTraineeLevelName);
		attributeSetterBiConsumers.put(
			"traineeLevelName",
			(BiConsumer<TraineeLevelMaster, String>)
				TraineeLevelMaster::setTraineeLevelName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getTraineeLevelMasterId() {
		return _traineeLevelMasterId;
	}

	@Override
	public void setTraineeLevelMasterId(long traineeLevelMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeLevelMasterId = traineeLevelMasterId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public String getTraineeLevelName() {
		if (_traineeLevelName == null) {
			return "";
		}
		else {
			return _traineeLevelName;
		}
	}

	@Override
	public String getTraineeLevelName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTraineeLevelName(languageId);
	}

	@Override
	public String getTraineeLevelName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTraineeLevelName(languageId, useDefault);
	}

	@Override
	public String getTraineeLevelName(String languageId) {
		return LocalizationUtil.getLocalization(
			getTraineeLevelName(), languageId);
	}

	@Override
	public String getTraineeLevelName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTraineeLevelName(), languageId, useDefault);
	}

	@Override
	public String getTraineeLevelNameCurrentLanguageId() {
		return _traineeLevelNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTraineeLevelNameCurrentValue() {
		Locale locale = getLocale(_traineeLevelNameCurrentLanguageId);

		return getTraineeLevelName(locale);
	}

	@Override
	public Map<Locale, String> getTraineeLevelNameMap() {
		return LocalizationUtil.getLocalizationMap(getTraineeLevelName());
	}

	@Override
	public void setTraineeLevelName(String traineeLevelName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_traineeLevelName = traineeLevelName;
	}

	@Override
	public void setTraineeLevelName(String traineeLevelName, Locale locale) {
		setTraineeLevelName(traineeLevelName, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setTraineeLevelName(
		String traineeLevelName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(traineeLevelName)) {
			setTraineeLevelName(
				LocalizationUtil.updateLocalization(
					getTraineeLevelName(), "TraineeLevelName", traineeLevelName,
					languageId, defaultLanguageId));
		}
		else {
			setTraineeLevelName(
				LocalizationUtil.removeLocalization(
					getTraineeLevelName(), "TraineeLevelName", languageId));
		}
	}

	@Override
	public void setTraineeLevelNameCurrentLanguageId(String languageId) {
		_traineeLevelNameCurrentLanguageId = languageId;
	}

	@Override
	public void setTraineeLevelNameMap(
		Map<Locale, String> traineeLevelNameMap) {

		setTraineeLevelNameMap(traineeLevelNameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setTraineeLevelNameMap(
		Map<Locale, String> traineeLevelNameMap, Locale defaultLocale) {

		if (traineeLevelNameMap == null) {
			return;
		}

		setTraineeLevelName(
			LocalizationUtil.updateLocalization(
				traineeLevelNameMap, getTraineeLevelName(), "TraineeLevelName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTraineeLevelName() {
		return getColumnOriginalValue("trainee_level_name");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TraineeLevelMaster.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TraineeLevelMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> traineeLevelNameMap = getTraineeLevelNameMap();

		for (Map.Entry<Locale, String> entry : traineeLevelNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTraineeLevelName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			TraineeLevelMaster.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String traineeLevelName = getTraineeLevelName(defaultLocale);

		if (Validator.isNull(traineeLevelName)) {
			setTraineeLevelName(
				getTraineeLevelName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTraineeLevelName(
				getTraineeLevelName(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public TraineeLevelMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TraineeLevelMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TraineeLevelMasterImpl traineeLevelMasterImpl =
			new TraineeLevelMasterImpl();

		traineeLevelMasterImpl.setUuid(getUuid());
		traineeLevelMasterImpl.setTraineeLevelMasterId(
			getTraineeLevelMasterId());
		traineeLevelMasterImpl.setGroupId(getGroupId());
		traineeLevelMasterImpl.setCompanyId(getCompanyId());
		traineeLevelMasterImpl.setCreateDate(getCreateDate());
		traineeLevelMasterImpl.setModifiedDate(getModifiedDate());
		traineeLevelMasterImpl.setCreatedBy(getCreatedBy());
		traineeLevelMasterImpl.setModifiedBy(getModifiedBy());
		traineeLevelMasterImpl.setTraineeLevelName(getTraineeLevelName());

		traineeLevelMasterImpl.resetOriginalValues();

		return traineeLevelMasterImpl;
	}

	@Override
	public TraineeLevelMaster cloneWithOriginalValues() {
		TraineeLevelMasterImpl traineeLevelMasterImpl =
			new TraineeLevelMasterImpl();

		traineeLevelMasterImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		traineeLevelMasterImpl.setTraineeLevelMasterId(
			this.<Long>getColumnOriginalValue("trainee_level_master_id"));
		traineeLevelMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		traineeLevelMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		traineeLevelMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("create_date"));
		traineeLevelMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		traineeLevelMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		traineeLevelMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		traineeLevelMasterImpl.setTraineeLevelName(
			this.<String>getColumnOriginalValue("trainee_level_name"));

		return traineeLevelMasterImpl;
	}

	@Override
	public int compareTo(TraineeLevelMaster traineeLevelMaster) {
		long primaryKey = traineeLevelMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TraineeLevelMaster)) {
			return false;
		}

		TraineeLevelMaster traineeLevelMaster = (TraineeLevelMaster)object;

		long primaryKey = traineeLevelMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TraineeLevelMaster> toCacheModel() {
		TraineeLevelMasterCacheModel traineeLevelMasterCacheModel =
			new TraineeLevelMasterCacheModel();

		traineeLevelMasterCacheModel.uuid = getUuid();

		String uuid = traineeLevelMasterCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			traineeLevelMasterCacheModel.uuid = null;
		}

		traineeLevelMasterCacheModel.traineeLevelMasterId =
			getTraineeLevelMasterId();

		traineeLevelMasterCacheModel.groupId = getGroupId();

		traineeLevelMasterCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			traineeLevelMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			traineeLevelMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			traineeLevelMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			traineeLevelMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		traineeLevelMasterCacheModel.createdBy = getCreatedBy();

		traineeLevelMasterCacheModel.modifiedBy = getModifiedBy();

		traineeLevelMasterCacheModel.traineeLevelName = getTraineeLevelName();

		String traineeLevelName = traineeLevelMasterCacheModel.traineeLevelName;

		if ((traineeLevelName != null) && (traineeLevelName.length() == 0)) {
			traineeLevelMasterCacheModel.traineeLevelName = null;
		}

		return traineeLevelMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TraineeLevelMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TraineeLevelMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TraineeLevelMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TraineeLevelMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TraineeLevelMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TraineeLevelMaster.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _traineeLevelMasterId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _createdBy;
	private long _modifiedBy;
	private String _traineeLevelName;
	private String _traineeLevelNameCurrentLanguageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TraineeLevelMaster, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TraineeLevelMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"trainee_level_master_id", _traineeLevelMasterId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("create_date", _createDate);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put("trainee_level_name", _traineeLevelName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("trainee_level_master_id", "traineeLevelMasterId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("create_date", "createDate");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put("trainee_level_name", "traineeLevelName");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("trainee_level_master_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("create_date", 16L);

		columnBitmasks.put("modified_date", 32L);

		columnBitmasks.put("created_by", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("trainee_level_name", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TraineeLevelMaster _escapedModel;

}