/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.tms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gov.omsb.tms.model.ViolationUpdateStatus;
import gov.omsb.tms.model.ViolationUpdateStatusModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ViolationUpdateStatus service. Represents a row in the &quot;violation_update_status&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ViolationUpdateStatusModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ViolationUpdateStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ViolationUpdateStatusImpl
 * @generated
 */
@JSON(strict = true)
public class ViolationUpdateStatusModelImpl
	extends BaseModelImpl<ViolationUpdateStatus>
	implements ViolationUpdateStatusModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a violation update status model instance should use the <code>ViolationUpdateStatus</code> interface instead.
	 */
	public static final String TABLE_NAME = "violation_update_status";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"violation_update_status_id", Types.BIGINT},
		{"group_id", Types.BIGINT}, {"company_id", Types.BIGINT},
		{"created_date", Types.TIMESTAMP}, {"created_by", Types.BIGINT},
		{"modified_date", Types.TIMESTAMP}, {"modified_by", Types.BIGINT},
		{"blocks_metadata_details_rel_id", Types.BIGINT},
		{"status", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("violation_update_status_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("group_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("company_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("created_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("created_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modified_date", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modified_by", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("blocks_metadata_details_rel_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table violation_update_status (uuid_ VARCHAR(75) null,violation_update_status_id LONG not null primary key,group_id LONG,company_id LONG,created_date DATE null,created_by LONG,modified_date DATE null,modified_by LONG,blocks_metadata_details_rel_id LONG,status BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table violation_update_status";

	public static final String ORDER_BY_JPQL =
		" ORDER BY violationUpdateStatus.violationUpdateStatusId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY violation_update_status.violation_update_status_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BLOCKSMETADATADETAILRELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VIOLATIONUPDATESTATUSID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ViolationUpdateStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _violationUpdateStatusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setViolationUpdateStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _violationUpdateStatusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ViolationUpdateStatus.class;
	}

	@Override
	public String getModelClassName() {
		return ViolationUpdateStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ViolationUpdateStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ViolationUpdateStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ViolationUpdateStatus, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ViolationUpdateStatus)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ViolationUpdateStatus, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ViolationUpdateStatus, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ViolationUpdateStatus)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ViolationUpdateStatus, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ViolationUpdateStatus, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ViolationUpdateStatus, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ViolationUpdateStatus, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ViolationUpdateStatus, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ViolationUpdateStatus, Object>>();
		Map<String, BiConsumer<ViolationUpdateStatus, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ViolationUpdateStatus, ?>>();

		attributeGetterFunctions.put("uuid", ViolationUpdateStatus::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ViolationUpdateStatus, String>)
				ViolationUpdateStatus::setUuid);
		attributeGetterFunctions.put(
			"violationUpdateStatusId",
			ViolationUpdateStatus::getViolationUpdateStatusId);
		attributeSetterBiConsumers.put(
			"violationUpdateStatusId",
			(BiConsumer<ViolationUpdateStatus, Long>)
				ViolationUpdateStatus::setViolationUpdateStatusId);
		attributeGetterFunctions.put(
			"groupId", ViolationUpdateStatus::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ViolationUpdateStatus, Long>)
				ViolationUpdateStatus::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ViolationUpdateStatus::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ViolationUpdateStatus, Long>)
				ViolationUpdateStatus::setCompanyId);
		attributeGetterFunctions.put(
			"createdDate", ViolationUpdateStatus::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<ViolationUpdateStatus, Date>)
				ViolationUpdateStatus::setCreatedDate);
		attributeGetterFunctions.put(
			"createdBy", ViolationUpdateStatus::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ViolationUpdateStatus, Long>)
				ViolationUpdateStatus::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", ViolationUpdateStatus::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ViolationUpdateStatus, Date>)
				ViolationUpdateStatus::setModifiedDate);
		attributeGetterFunctions.put(
			"modifiedBy", ViolationUpdateStatus::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ViolationUpdateStatus, Long>)
				ViolationUpdateStatus::setModifiedBy);
		attributeGetterFunctions.put(
			"blocksMetadataDetailRelId",
			ViolationUpdateStatus::getBlocksMetadataDetailRelId);
		attributeSetterBiConsumers.put(
			"blocksMetadataDetailRelId",
			(BiConsumer<ViolationUpdateStatus, Long>)
				ViolationUpdateStatus::setBlocksMetadataDetailRelId);
		attributeGetterFunctions.put(
			"status", ViolationUpdateStatus::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<ViolationUpdateStatus, Boolean>)
				ViolationUpdateStatus::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getViolationUpdateStatusId() {
		return _violationUpdateStatusId;
	}

	@Override
	public void setViolationUpdateStatusId(long violationUpdateStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_violationUpdateStatusId = violationUpdateStatusId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("group_id"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("company_id"));
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getBlocksMetadataDetailRelId() {
		return _blocksMetadataDetailRelId;
	}

	@Override
	public void setBlocksMetadataDetailRelId(long blocksMetadataDetailRelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_blocksMetadataDetailRelId = blocksMetadataDetailRelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBlocksMetadataDetailRelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue(
				"blocks_metadata_details_rel_id"));
	}

	@JSON
	@Override
	public Boolean getStatus() {
		return _status;
	}

	@Override
	public void setStatus(Boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ViolationUpdateStatus.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ViolationUpdateStatus toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ViolationUpdateStatus>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ViolationUpdateStatusImpl violationUpdateStatusImpl =
			new ViolationUpdateStatusImpl();

		violationUpdateStatusImpl.setUuid(getUuid());
		violationUpdateStatusImpl.setViolationUpdateStatusId(
			getViolationUpdateStatusId());
		violationUpdateStatusImpl.setGroupId(getGroupId());
		violationUpdateStatusImpl.setCompanyId(getCompanyId());
		violationUpdateStatusImpl.setCreatedDate(getCreatedDate());
		violationUpdateStatusImpl.setCreatedBy(getCreatedBy());
		violationUpdateStatusImpl.setModifiedDate(getModifiedDate());
		violationUpdateStatusImpl.setModifiedBy(getModifiedBy());
		violationUpdateStatusImpl.setBlocksMetadataDetailRelId(
			getBlocksMetadataDetailRelId());
		violationUpdateStatusImpl.setStatus(getStatus());

		violationUpdateStatusImpl.resetOriginalValues();

		return violationUpdateStatusImpl;
	}

	@Override
	public ViolationUpdateStatus cloneWithOriginalValues() {
		ViolationUpdateStatusImpl violationUpdateStatusImpl =
			new ViolationUpdateStatusImpl();

		violationUpdateStatusImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		violationUpdateStatusImpl.setViolationUpdateStatusId(
			this.<Long>getColumnOriginalValue("violation_update_status_id"));
		violationUpdateStatusImpl.setGroupId(
			this.<Long>getColumnOriginalValue("group_id"));
		violationUpdateStatusImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("company_id"));
		violationUpdateStatusImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("created_date"));
		violationUpdateStatusImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("created_by"));
		violationUpdateStatusImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modified_date"));
		violationUpdateStatusImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modified_by"));
		violationUpdateStatusImpl.setBlocksMetadataDetailRelId(
			this.<Long>getColumnOriginalValue(
				"blocks_metadata_details_rel_id"));
		violationUpdateStatusImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));

		return violationUpdateStatusImpl;
	}

	@Override
	public int compareTo(ViolationUpdateStatus violationUpdateStatus) {
		long primaryKey = violationUpdateStatus.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ViolationUpdateStatus)) {
			return false;
		}

		ViolationUpdateStatus violationUpdateStatus =
			(ViolationUpdateStatus)object;

		long primaryKey = violationUpdateStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ViolationUpdateStatus> toCacheModel() {
		ViolationUpdateStatusCacheModel violationUpdateStatusCacheModel =
			new ViolationUpdateStatusCacheModel();

		violationUpdateStatusCacheModel.uuid = getUuid();

		String uuid = violationUpdateStatusCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			violationUpdateStatusCacheModel.uuid = null;
		}

		violationUpdateStatusCacheModel.violationUpdateStatusId =
			getViolationUpdateStatusId();

		violationUpdateStatusCacheModel.groupId = getGroupId();

		violationUpdateStatusCacheModel.companyId = getCompanyId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			violationUpdateStatusCacheModel.createdDate = createdDate.getTime();
		}
		else {
			violationUpdateStatusCacheModel.createdDate = Long.MIN_VALUE;
		}

		violationUpdateStatusCacheModel.createdBy = getCreatedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			violationUpdateStatusCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			violationUpdateStatusCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		violationUpdateStatusCacheModel.modifiedBy = getModifiedBy();

		violationUpdateStatusCacheModel.blocksMetadataDetailRelId =
			getBlocksMetadataDetailRelId();

		Boolean status = getStatus();

		if (status != null) {
			violationUpdateStatusCacheModel.status = status;
		}

		return violationUpdateStatusCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ViolationUpdateStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ViolationUpdateStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ViolationUpdateStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ViolationUpdateStatus)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ViolationUpdateStatus>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ViolationUpdateStatus.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _violationUpdateStatusId;
	private long _groupId;
	private long _companyId;
	private Date _createdDate;
	private long _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _modifiedBy;
	private long _blocksMetadataDetailRelId;
	private Boolean _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ViolationUpdateStatus, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ViolationUpdateStatus)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"violation_update_status_id", _violationUpdateStatusId);
		_columnOriginalValues.put("group_id", _groupId);
		_columnOriginalValues.put("company_id", _companyId);
		_columnOriginalValues.put("created_date", _createdDate);
		_columnOriginalValues.put("created_by", _createdBy);
		_columnOriginalValues.put("modified_date", _modifiedDate);
		_columnOriginalValues.put("modified_by", _modifiedBy);
		_columnOriginalValues.put(
			"blocks_metadata_details_rel_id", _blocksMetadataDetailRelId);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"violation_update_status_id", "violationUpdateStatusId");
		attributeNames.put("group_id", "groupId");
		attributeNames.put("company_id", "companyId");
		attributeNames.put("created_date", "createdDate");
		attributeNames.put("created_by", "createdBy");
		attributeNames.put("modified_date", "modifiedDate");
		attributeNames.put("modified_by", "modifiedBy");
		attributeNames.put(
			"blocks_metadata_details_rel_id", "blocksMetadataDetailRelId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("violation_update_status_id", 2L);

		columnBitmasks.put("group_id", 4L);

		columnBitmasks.put("company_id", 8L);

		columnBitmasks.put("created_date", 16L);

		columnBitmasks.put("created_by", 32L);

		columnBitmasks.put("modified_date", 64L);

		columnBitmasks.put("modified_by", 128L);

		columnBitmasks.put("blocks_metadata_details_rel_id", 256L);

		columnBitmasks.put("status", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ViolationUpdateStatus _escapedModel;

}