components:
   schemas:
       FormDataRequest:
           type: object
           properties:
               formDefinitionIds:
                   description: The formDefinition Ids.
                   type: array
                   items:
                       format: int64
                       type: integer
               recordIds:
                   description: The record Ids.
                   type: array
                   items:
                       format: int64
                       type: integer
                       
       PostFormDataRequest:
           type: object
           properties: 
               firstName:
                   description: First Name.
                   type: string
               lastName:
                   description: Last Name.
                   type: string
                   
       DeleteFormRecordsRequest:
           type: object
           properties: 
               formDefinitionId:
                   description: FormDefinition Id.
                   type: integer
                   format: int64
               recordIds:
                   description: Record Ids.
                   type: array
                   items:
                       type: integer
                       format: int64
           
       FormDataResponse:
           type: object
           properties:
               data:
                   description: The Json response.
                   type: object
               status:
                    type: string
               message:
                    type: string
                    
info:
    description: "FormBuilderHeadless REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "FormBuilderHeadless"
    version: v1.0
openapi: 3.0.1
paths:
   "/get-form-records":
       post:
           description: To Get Form Builder Records
           operationId: getFormData
           tags: ["GetFormData"]
           requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FormDataRequest'
                    application/xml:
                        schema:
                            $ref: '#/components/schemas/FormDataRequest'
           responses:
               '200':
                   description: Ok
                   content:
                       application/json:
                           schema:
                               $ref: "#/components/schemas/FormDataResponse"
                       application/xml:
                           schema:
                               $ref: "#/components/schemas/FormDataResponse"
   "/post-form-data":
       post:
           description: To Post Form data
           operationId: postFormData
           tags: ["PostFormData"]
           requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PostFormDataRequest'
                    application/xml:
                        schema:
                            $ref: '#/components/schemas/PostFormDataRequest'
                   
           responses:
               '200':
                   description: Ok
                   content:
                       application/json:
                           schema:
                               $ref: "#/components/schemas/FormDataResponse"
                       application/xml:
                           schema:
                               $ref: "#/components/schemas/FormDataResponse"
                               
   "/delete-form-records":
       post:
           description: To Delete Form Records
           operationId: deleteFormRecords
           tags: ["DeleteFormRecords"]
           requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteFormRecordsRequest'
                    application/xml:
                        schema:
                            $ref: '#/components/schemas/DeleteFormRecordsRequest'
                   
           responses:
               '200':
                   description: Ok
                   content:
                       application/json:
                           schema:
                               $ref: "#/components/schemas/FormDataResponse"
                       application/xml:
                           schema:
                               $ref: "#/components/schemas/FormDataResponse"
                       
                       