/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.form.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FormDefinition service. Represents a row in the &quot;df_form_definition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gov.omsb.form.builder.model.impl.FormDefinitionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gov.omsb.form.builder.model.impl.FormDefinitionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FormDefinition
 * @generated
 */
@ProviderType
public interface FormDefinitionModel
	extends BaseModel<FormDefinition>, ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form definition model instance should use the {@link FormDefinition} interface instead.
	 */

	/**
	 * Returns the primary key of this form definition.
	 *
	 * @return the primary key of this form definition
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form definition.
	 *
	 * @param primaryKey the primary key of this form definition
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this form definition.
	 *
	 * @return the uuid of this form definition
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this form definition.
	 *
	 * @param uuid the uuid of this form definition
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the form definition ID of this form definition.
	 *
	 * @return the form definition ID of this form definition
	 */
	public long getFormDefinitionId();

	/**
	 * Sets the form definition ID of this form definition.
	 *
	 * @param formDefinitionId the form definition ID of this form definition
	 */
	public void setFormDefinitionId(long formDefinitionId);

	/**
	 * Returns the group ID of this form definition.
	 *
	 * @return the group ID of this form definition
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this form definition.
	 *
	 * @param groupId the group ID of this form definition
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this form definition.
	 *
	 * @return the company ID of this form definition
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this form definition.
	 *
	 * @param companyId the company ID of this form definition
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this form definition.
	 *
	 * @return the created by of this form definition
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this form definition.
	 *
	 * @param createdBy the created by of this form definition
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this form definition.
	 *
	 * @return the modified by of this form definition
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this form definition.
	 *
	 * @param modifiedBy the modified by of this form definition
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the created date of this form definition.
	 *
	 * @return the created date of this form definition
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this form definition.
	 *
	 * @param createdDate the created date of this form definition
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this form definition.
	 *
	 * @return the modified date of this form definition
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this form definition.
	 *
	 * @param modifiedDate the modified date of this form definition
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the form name of this form definition.
	 *
	 * @return the form name of this form definition
	 */
	@AutoEscape
	public String getFormName();

	/**
	 * Sets the form name of this form definition.
	 *
	 * @param formName the form name of this form definition
	 */
	public void setFormName(String formName);

	/**
	 * Returns the form title of this form definition.
	 *
	 * @return the form title of this form definition
	 */
	@AutoEscape
	public String getFormTitle();

	/**
	 * Sets the form title of this form definition.
	 *
	 * @param formTitle the form title of this form definition
	 */
	public void setFormTitle(String formTitle);

	/**
	 * Returns the form description of this form definition.
	 *
	 * @return the form description of this form definition
	 */
	@AutoEscape
	public String getFormDescription();

	/**
	 * Sets the form description of this form definition.
	 *
	 * @param formDescription the form description of this form definition
	 */
	public void setFormDescription(String formDescription);

	/**
	 * Returns the form version of this form definition.
	 *
	 * @return the form version of this form definition
	 */
	@AutoEscape
	public String getFormVersion();

	/**
	 * Sets the form version of this form definition.
	 *
	 * @param formVersion the form version of this form definition
	 */
	public void setFormVersion(String formVersion);

	/**
	 * Returns the form config of this form definition.
	 *
	 * @return the form config of this form definition
	 */
	@AutoEscape
	public String getFormConfig();

	/**
	 * Sets the form config of this form definition.
	 *
	 * @param formConfig the form config of this form definition
	 */
	public void setFormConfig(String formConfig);

	/**
	 * Returns the status of this form definition.
	 *
	 * @return the status of this form definition
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this form definition.
	 *
	 * @param status the status of this form definition
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this form definition.
	 *
	 * @return the status by user ID of this form definition
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this form definition.
	 *
	 * @param statusByUserId the status by user ID of this form definition
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this form definition.
	 *
	 * @return the status by user uuid of this form definition
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this form definition.
	 *
	 * @param statusByUserUuid the status by user uuid of this form definition
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this form definition.
	 *
	 * @return the status by user name of this form definition
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this form definition.
	 *
	 * @param statusByUserName the status by user name of this form definition
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this form definition.
	 *
	 * @return the status date of this form definition
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this form definition.
	 *
	 * @param statusDate the status date of this form definition
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this form definition is approved.
	 *
	 * @return <code>true</code> if this form definition is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this form definition is denied.
	 *
	 * @return <code>true</code> if this form definition is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this form definition is a draft.
	 *
	 * @return <code>true</code> if this form definition is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this form definition is expired.
	 *
	 * @return <code>true</code> if this form definition is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this form definition is inactive.
	 *
	 * @return <code>true</code> if this form definition is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this form definition is incomplete.
	 *
	 * @return <code>true</code> if this form definition is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this form definition is pending.
	 *
	 * @return <code>true</code> if this form definition is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this form definition is scheduled.
	 *
	 * @return <code>true</code> if this form definition is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public FormDefinition cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}