/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gov.omsb.form.builder.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import gov.omsb.form.builder.model.RangeOptionMaster;
import gov.omsb.form.builder.service.RangeOptionMasterLocalService;
import gov.omsb.form.builder.service.RangeOptionMasterLocalServiceUtil;
import gov.omsb.form.builder.service.persistence.FormDefinitionFinder;
import gov.omsb.form.builder.service.persistence.FormDefinitionPersistence;
import gov.omsb.form.builder.service.persistence.FormRecordEntryPersistence;
import gov.omsb.form.builder.service.persistence.RangeOptionMasterPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the range option master local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link gov.omsb.form.builder.service.impl.RangeOptionMasterLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see gov.omsb.form.builder.service.impl.RangeOptionMasterLocalServiceImpl
 * @generated
 */
public abstract class RangeOptionMasterLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   RangeOptionMasterLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RangeOptionMasterLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>RangeOptionMasterLocalServiceUtil</code>.
	 */

	/**
	 * Adds the range option master to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RangeOptionMasterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rangeOptionMaster the range option master
	 * @return the range option master that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RangeOptionMaster addRangeOptionMaster(
		RangeOptionMaster rangeOptionMaster) {

		rangeOptionMaster.setNew(true);

		return rangeOptionMasterPersistence.update(rangeOptionMaster);
	}

	/**
	 * Creates a new range option master with the primary key. Does not add the range option master to the database.
	 *
	 * @param rangeOptionId the primary key for the new range option master
	 * @return the new range option master
	 */
	@Override
	@Transactional(enabled = false)
	public RangeOptionMaster createRangeOptionMaster(long rangeOptionId) {
		return rangeOptionMasterPersistence.create(rangeOptionId);
	}

	/**
	 * Deletes the range option master with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RangeOptionMasterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rangeOptionId the primary key of the range option master
	 * @return the range option master that was removed
	 * @throws PortalException if a range option master with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RangeOptionMaster deleteRangeOptionMaster(long rangeOptionId)
		throws PortalException {

		return rangeOptionMasterPersistence.remove(rangeOptionId);
	}

	/**
	 * Deletes the range option master from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RangeOptionMasterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rangeOptionMaster the range option master
	 * @return the range option master that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RangeOptionMaster deleteRangeOptionMaster(
		RangeOptionMaster rangeOptionMaster) {

		return rangeOptionMasterPersistence.remove(rangeOptionMaster);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return rangeOptionMasterPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			RangeOptionMaster.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return rangeOptionMasterPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>gov.omsb.form.builder.model.impl.RangeOptionMasterModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return rangeOptionMasterPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>gov.omsb.form.builder.model.impl.RangeOptionMasterModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return rangeOptionMasterPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return rangeOptionMasterPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return rangeOptionMasterPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public RangeOptionMaster fetchRangeOptionMaster(long rangeOptionId) {
		return rangeOptionMasterPersistence.fetchByPrimaryKey(rangeOptionId);
	}

	/**
	 * Returns the range option master matching the UUID and group.
	 *
	 * @param uuid the range option master's UUID
	 * @param groupId the primary key of the group
	 * @return the matching range option master, or <code>null</code> if a matching range option master could not be found
	 */
	@Override
	public RangeOptionMaster fetchRangeOptionMasterByUuidAndGroupId(
		String uuid, long groupId) {

		return rangeOptionMasterPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the range option master with the primary key.
	 *
	 * @param rangeOptionId the primary key of the range option master
	 * @return the range option master
	 * @throws PortalException if a range option master with the primary key could not be found
	 */
	@Override
	public RangeOptionMaster getRangeOptionMaster(long rangeOptionId)
		throws PortalException {

		return rangeOptionMasterPersistence.findByPrimaryKey(rangeOptionId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			rangeOptionMasterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RangeOptionMaster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("rangeOptionId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			rangeOptionMasterLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(RangeOptionMaster.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"rangeOptionId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			rangeOptionMasterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RangeOptionMaster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("rangeOptionId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rangeOptionMasterPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement RangeOptionMasterLocalServiceImpl#deleteRangeOptionMaster(RangeOptionMaster) to avoid orphaned data");
		}

		return rangeOptionMasterLocalService.deleteRangeOptionMaster(
			(RangeOptionMaster)persistedModel);
	}

	@Override
	public BasePersistence<RangeOptionMaster> getBasePersistence() {
		return rangeOptionMasterPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rangeOptionMasterPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the range option masters matching the UUID and company.
	 *
	 * @param uuid the UUID of the range option masters
	 * @param companyId the primary key of the company
	 * @return the matching range option masters, or an empty list if no matches were found
	 */
	@Override
	public List<RangeOptionMaster> getRangeOptionMastersByUuidAndCompanyId(
		String uuid, long companyId) {

		return rangeOptionMasterPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of range option masters matching the UUID and company.
	 *
	 * @param uuid the UUID of the range option masters
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of range option masters
	 * @param end the upper bound of the range of range option masters (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching range option masters, or an empty list if no matches were found
	 */
	@Override
	public List<RangeOptionMaster> getRangeOptionMastersByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<RangeOptionMaster> orderByComparator) {

		return rangeOptionMasterPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the range option master matching the UUID and group.
	 *
	 * @param uuid the range option master's UUID
	 * @param groupId the primary key of the group
	 * @return the matching range option master
	 * @throws PortalException if a matching range option master could not be found
	 */
	@Override
	public RangeOptionMaster getRangeOptionMasterByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return rangeOptionMasterPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the range option masters.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>gov.omsb.form.builder.model.impl.RangeOptionMasterModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of range option masters
	 * @param end the upper bound of the range of range option masters (not inclusive)
	 * @return the range of range option masters
	 */
	@Override
	public List<RangeOptionMaster> getRangeOptionMasters(int start, int end) {
		return rangeOptionMasterPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of range option masters.
	 *
	 * @return the number of range option masters
	 */
	@Override
	public int getRangeOptionMastersCount() {
		return rangeOptionMasterPersistence.countAll();
	}

	/**
	 * Updates the range option master in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RangeOptionMasterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rangeOptionMaster the range option master
	 * @return the range option master that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RangeOptionMaster updateRangeOptionMaster(
		RangeOptionMaster rangeOptionMaster) {

		return rangeOptionMasterPersistence.update(rangeOptionMaster);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RangeOptionMasterLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		rangeOptionMasterLocalService = (RangeOptionMasterLocalService)aopProxy;

		_setLocalServiceUtilService(rangeOptionMasterLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RangeOptionMasterLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RangeOptionMaster.class;
	}

	protected String getModelClassName() {
		return RangeOptionMaster.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				rangeOptionMasterPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		RangeOptionMasterLocalService rangeOptionMasterLocalService) {

		try {
			Field field =
				RangeOptionMasterLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, rangeOptionMasterLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected FormDefinitionPersistence formDefinitionPersistence;

	@Reference
	protected FormDefinitionFinder formDefinitionFinder;

	@Reference
	protected FormRecordEntryPersistence formRecordEntryPersistence;

	protected RangeOptionMasterLocalService rangeOptionMasterLocalService;

	@Reference
	protected RangeOptionMasterPersistence rangeOptionMasterPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		RangeOptionMasterLocalServiceBaseImpl.class);

}