components:
   schemas:
       ValidateUserLoginRequest:
           type: object
           properties:
               userName:
                   description: User Name.
                   type: string
               password:
                   description: Password.
                   type: string
                   
       Response:
           type: object
           properties:
               data:
                   description: Response.
                   type: object
               status:
                    type: string
               message:
                    type: string
                    
info:
    description: "OmsbMobileSdkHeadless REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "OmsbMobileSdkHeadless"
    version: v1.0
openapi: 3.0.1

paths:
   "/validate-user-login":
       post:
           description: To validate User Login
           operationId: validateUserLogin
           tags: ["ValidateUserLogin"]
           requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ValidateUserLoginRequest'
                    application/xml:
                        schema:
                            $ref: '#/components/schemas/ValidateUserLoginRequest'
           responses:
               '200':
                   description: Ok
                   content:
                       application/json:
                           schema:
                               $ref: "#/components/schemas/Response"
                       application/xml:
                           schema:
                               $ref: "#/components/schemas/Response"

   